// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhDEeMPbKf1UJ2TL2V-WnXpgL3BAGRC9E',
    appId: '1:594189782744:web:8ef02f55a5581b902951ad',
    messagingSenderId: '594189782744',
    projectId: 'kf-product',
    authDomain: 'kf-product.firebaseapp.com',
    storageBucket: 'kf-product.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1LeQpl0iyorYX7rOPrFq_e9mHSWiLEHQ',
    appId: '1:594189782744:android:37d882a2307babe82951ad',
    messagingSenderId: '594189782744',
    projectId: 'kf-product',
    storageBucket: 'kf-product.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD07kCjx5vEuu8eU1aDJLBu0uc3ak-_YyE',
    appId: '1:594189782744:ios:db366445b69712a32951ad',
    messagingSenderId: '594189782744',
    projectId: 'kf-product',
    storageBucket: 'kf-product.firebasestorage.app',
    iosBundleId: 'com.codemenschen.productdeal',
  );
}
