class ArabicFile {
  static const Map<String, String> arabicTranslations = {
    // ============================================
    // Options Screen Related
    // ============================================
    'options': 'خيارات',
    'account': 'حساب',
    'myOrders': 'طلباتي',
    'myOrdersSubtitle': 'عرض وتتبع طلباتك',
    'statistics': 'إحصائيات',
    'statisticsSubtitle': 'عرض إحصائيات المشاركة في صفقتك',
    'profile': 'حساب تعريفي',
    'profileSubtitle': 'إدارة حسابك',
    'management': 'إدارة',
    'manageCategories': 'إدارة الفئات',
    'manageCategoriesSubtitle': 'إنشاء وإدارة فئات المنتجات',
    'createNewProductSubtitle': 'إنشاء منتج جديد',
    'createNewDealSubtitle': 'إنشاء صفقة جديدة',
    'viewOrdersSubtitle': 'عرض وإدارة الطلبات',
    'inactiveMembersViewSubtitle': 'عرض المحلات التجارية مع عدم وجود طلبات حديثة',
    'manageBannersSubtitle': 'إدارة لافتات التطبيق (المسؤول)',
    'myBannersSubtitle': 'إدارة اللافتات الخاصة بك',
    'unableToLoadOptions': 'غير قادر على تحميل الخيارات',
    'loggingOut': 'تسجيل الخروج...',
    'manageUsers': 'إدارة المستخدمين',
    'manageUsersSubtitle': 'عرض وإدارة حسابات المستخدمين',
    'analytics': 'التحليلات',
    'analyticsSubtitle': 'عرض تحليلات عملك',
    'information': 'معلومة',
    'faq': 'التعليمات',
    'faqSubtitle': 'الأسئلة المتداولة',
    'aboutUs': 'معلومات عنا',
    'aboutUsSubtitle': 'تعرف على المزيد حول منصتنا',
    'helpSupport': 'المساعدة والدعم',
    'helpSupportSubtitle': 'احصل على المساعدة واتصل بالدعم',
    'accountActions': 'إجراءات الحساب',
    'deleteAccount': 'حذف الحساب',
    'deleteAccountSubtitle': 'اطلب حذف حسابك نهائيًا',
    'logout': 'تسجيل الخروج',
    'logoutSubtitle': 'قم بتسجيل الخروج من حسابك',
    'confirmLogout': 'تأكيد الخروج',
    'confirmLogoutMessage': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'cancel': 'يلغي',
    'loginAgain': 'تسجيل الدخول مرة أخرى',
    // ============================================
    // Language Related
    // ============================================
    'language': 'لغة',
    'languageSubtitle': 'تغيير لغة التطبيق',
    'notificationSettings': 'إعدادات الإشعارات',
    'notificationSettingsSubtitle':
        'اختر الإشعارات التي تريد استلامها.',
    'notificationChannels': 'القنوات',
    'pushNotifications': 'إشعارات الدفع',
    'pushNotificationsSubtitle':
        'استلام إشعارات الدفع على جهازك',
    'emailNotifications': 'إشعارات البريد الإلكتروني',
    'emailNotificationsSubtitle': 'استلام الإشعارات عبر البريد الإلكتروني',
    'notificationModules': 'حسب الفئة',
    'notificationSettingsSaved': 'تم حفظ إعدادات الإشعارات',
    'notificationModuleProducts': 'المنتجات',
    'notificationModuleProductOrders': 'طلبات المنتجات',
    'notificationModuleDeals': 'الصفقات',
    'notificationModuleDealOrders': 'طلبات الصفقات',
    'notificationModuleBanners': 'اللافتات',
    'notificationModuleAdmin': 'المسؤول',
    'notificationModuleEngagement': 'التفاعل',
    'notificationModulePayment': 'الدفع',
    'push': 'دفع',
    'currency': 'عملة',
    'currencySubtitle': 'عرض العملة للأسعار (الافتراضي: الجهاز)',
    'systemDefault': 'الافتراضي للنظام',
    'syncFxRates': 'مزامنة أسعار العملات الأجنبية',
    'syncFxRatesSubtitle': 'جلب أحدث أسعار الصرف من البنك المركزي الأوروبي',
    'syncFxRatesSuccess': 'تم تحديث أسعار صرف العملات الأجنبية بنجاح',
    'syncFxRatesFailed': 'لا يمكن تحديث أسعار العملات الأجنبية. باستخدام المعدلات المخزنة مؤقتا.',
    'changingLanguage': 'تغيير اللغة...',
    'languageChangeFailed': 'فشلت مزامنة تفضيلات اللغة. يرجى المحاولة مرة أخرى.',
    'failedToChangeLanguage': 'فشل في تغيير اللغة. يرجى المحاولة مرة أخرى.',
    'english': 'إنجليزي',
    'german': 'الألمانية',
    'turkish': 'تركي',
    'arabic': 'عربي',
    'urdu': 'الأردية',
    'hindi': 'الهندية',
    'russian': 'الروسية',
    'sourceLanguageLabel': 'لغة المحتوى',
    'sourceLanguageHint': 'لغة النص الذي تدخله (سيتم ترجمته إلى لغات أخرى)',
    'selectYourLanguage': 'اختر لغتك',
    'selectYourLanguageSubtitle':
        'اختر لغة التطبيق. يمكنك تغييرها لاحقاً في الإعدادات.',
    'continueButton': 'متابعة',
    // ============================================
    // Common / General
    // ============================================
    'sessionExpired': 'انتهت صلاحية الجلسة',
    'sessionExpiredMessage': 'لقد انتهت صلاحية جلستك. يرجى تسجيل الدخول مرة أخرى لمواصلة استخدام التطبيق.',
    'comingSoon': 'قريباً',
    'retry': 'أعد المحاولة',
    'error': 'خطأ',
    'errorWithDetail': 'خطأ: {detail}',
    'close': 'يغلق',
    'save': 'يحفظ',
    'done': 'منتهي',
    'saving': 'توفير...',
    'update': 'تحديث',
    'edit': 'يحرر',
    'delete': 'يمسح',
    'add': 'يضيف',
    'remove': 'يزيل',
    'select': 'يختار',
    'all': 'الجميع',
    'filter': 'فلتر',
    'type': 'يكتب',
    'status': 'حالة',
    'unknown': 'مجهول',
    // ============================================
    // About Us Related
    // ============================================
    'welcomeToProductDeal': 'مرحبا بكم في صفقة المنتج',
    'trustedMarketplace': 'السوق الموثوق به للمنتجات والصفقات بالجملة',
    'ourMission': 'مهمتنا',
    'ourMissionContent': 'لربط تجار الجملة وتجار التجزئة، مما يجعل عمليات الشراء بالجملة متاحة وفعالة للشركات من جميع الأحجام.',
    'whatWeOffer': 'ما نقدمه',
    'whatWeOfferContent':
        '• الوصول إلى تجار الجملة المعتمدين'
        '• عروض بالجملة وخصومات حصرية'
        '• تتبع المخزون في الوقت الحقيقي'
        '• إدارة النظام الآمن'
        '• اكتشاف المنتج على أساس الموقع',
    'forWholesalers': 'لتجار الجملة',
    'forRetailers': 'لتجار التجزئة',
    'forRetailersContent': 'اكتشف المنتجات من تجار الجملة القريبين، وشارك في الصفقات بالجملة، وقم بإدارة طلباتك بكفاءة.',
    'forWholesalersContent': 'اعرض منتجاتك، وقم بإنشاء صفقات حصرية، وقم بإدارة الطلبات، والوصول إلى شبكة أوسع من تجار التجزئة.',
    // ============================================
    // FAQ Related
    // ============================================
    'frequentlyAskedQuestions': 'الأسئلة المتداولة',
    'commonQuestions': 'الأسئلة الشائعة',
    'faqQuestion1': 'كيف يمكنني تقديم الطلب؟',
    'faqAnswer1': 'تصفح الصفقات أو المنتجات النشطة، وحدد الكمية التي تحتاجها، وانقر على "تقديم الطلب". سيتم مراجعة طلبك من قبل تاجر الجملة.',
    'faqQuestion2': 'ما هي أوامر الصفقة؟',
    'faqAnswer2': 'تمثل طلبات الصفقات فرص شراء بالجملة حيث يقدم تجار الجملة أسعارًا مخفضة عند الوصول إلى الكمية المستهدفة. يمكنك تقديم طلبات متعددة على نفس الصفقة.',
    'faqQuestion3': 'كيف يتم التعامل مع الشحن؟',
    'faqAnswer3': 'يتم ترتيب تفاصيل الشحن مباشرة مع تاجر الجملة بعد تأكيد طلبك. سيتم توفير معلومات الاتصال عند تأكيد الطلب.',
    'faqQuestion4': 'هل يمكنني إلغاء الطلب؟',
    'faqAnswer4': 'يمكنك إلغاء الطلبات المعلقة. بمجرد تأكيد الطلب من قبل تاجر الجملة، يتم تطبيق سياسات الإلغاء وفقًا لشروط تاجر الجملة.',
    'faqQuestion5': 'كيف أصبح تاجر جملة معتمدًا؟',
    'faqAnswer5': 'اتصل بفريق الدعم الخاص بنا للتحقق. ستحتاج إلى تقديم وثائق العمل وإكمال عملية التحقق.',
    'faqQuestion6': 'كيف يتم فرز المنتجات حسب المسافة؟',
    'faqAnswer6': 'يتم فرز المنتجات تلقائيًا حسب قربها من موقعك. تأكد من إضافة موقعك في ملفك الشخصي للحصول على تصنيف دقيق يعتمد على المسافة.',
    'faqQuestion7': 'ما هي طرق الدفع المقبولة؟',
    'faqAnswer7': 'تختلف طرق الدفع حسب تاجر الجملة. تتم مناقشة تفاصيل الدفع بعد تأكيد الطلب.',
    'faqQuestion8': 'كيف أقوم بتحديث ملفي الشخصي؟',
    'faqAnswer8': 'انتقل إلى صفحة ملفك الشخصي من لوحة التحكم، وقم بتحديث معلوماتك، ثم احفظها. يمكنك إضافة عناوين متعددة لمواقع مختلفة.',
    // ============================================
    // Wholesaler Directory Related
    // ============================================
    'couldNotLoadWholesalers': 'لا يمكننا تحميل تجار الجملة الآن.',
    'verifiedPartners': 'شركاء تم التحقق منهم',
    'verifiedPartnersDescription': 'شركاء تم التحقق منهم',
    'noWholesalersNearYou': 'لا يوجد تجار جملة بالقرب منك حتى الآن. قم بتحديث موقعك لفتح المخزون القريب.',
    // ============================================
    // Dashboard Related
    // ============================================
    'dashboard': 'لوحة القيادة',
    'nearbyWholesalers': 'تجار الجملة القريبة',
    'allWholesalers': 'جميع تجار الجملة',
    'noWholesalersFound': 'لم يتم العثور على تجار الجملة',
    'errorLoadingWholesalers': 'حدث خطأ أثناء تحميل تجار الجملة',
    'advertiseWithUs': 'أعلن معنا',
    'boostYourSales': 'عزز مبيعاتك!',
    'promoteYourProducts': 'قم بالترويج لمنتجاتك هنا والوصول إلى المزيد من العملاء.',
    'unableToLoadDashboard': 'غير قادر على تحميل لوحة القيادة',
    'unableToLoadProduct': 'غير قادر على تحميل المنتج',
    'unableToLoadWholesaler': 'غير قادر على تحميل تاجر الجملة',
    'spotlight': 'تسليط الضوء',
    'spotlightWholesalersEmpty': 'سيظهر تجار الجملة البارزون هنا بمجرد ازدحام السوق.',
    // ============================================
    // Orders Related
    // ============================================
    'orderId': 'معرف الطلب',
    'payment': 'قسط',
    'paymentStatus': 'حالة الدفع',
    'placedOn': 'وضعت على',
    'orderItems': 'عناصر الطلب',
    'createShipment': 'إنشاء شحنة',
    'shippingAddress': 'عنوان الشحن',
    'notes': 'ملحوظات',
    'orderNotes': 'ملاحظات الطلب',
    'orderDetails': 'تفاصيل الطلب',
    'unableToLoadOrder': 'غير قادر على تحميل الطلب',
    'updateOrderStatus': 'تحديث حالة الطلب',
    'subtotal': 'المجموع الفرعي',
    'shipping': 'شحن',
    'shippingWithFreeThreshold': 'الشحن: {amount} (مجانًا لوحدات {threshold}+)',
    'freeShippingForThreshold': 'شحن مجاني لوحدات {threshold}+',
    'shippingBaseOnly': 'الشحن: {amount}',
    'shippingWithPerUnit': 'الشحن: {base} + {perUnit} لكل وحدة',
    'total': 'المجموع',
    'reasonOptional': 'السبب (اختياري)',
    'notesOptional': 'ملاحظات (اختياري)',
    'sku': 'رمز التخزين التعريفي',
    'skuN/A': 'رمز المنتج: غير متوفر',
    'trackingAvailable': 'التتبع متاح',
    'shipped': 'تم الشحن',
    'shipments': 'الشحنات',
    'shipmentId': 'شحنة {id}',
    'trackingLabel': 'التتبع: {number}',
    'track': 'مسار',
    'couldNotOpenTrackingUrl': 'تعذر فتح عنوان URL للتتبع',
    'carrierLabel': 'مشغل شبكة الجوال: {name}',
    'estDelivery': 'EST. التسليم: {date}',
    'shippedAt': 'تم الشحن: {date}',
    'deliveredAt': 'تم التسليم: {date}',
    'each': 'كل',
    'unit': 'وحدة',
    'noOrdersYet': 'لا توجد أوامر حتى الآن',
    'noOrdersYetMessage': 'تصفح المنتجات والصفقات لتقديم طلبك الأول.',
    'unableToLoadOrders': 'غير قادر على تحميل طلباتك',
    'orderPlaced': 'تم تقديم الطلب',
    'confirmed': 'مؤكد',
    'delivered': 'تم التوصيل',
    'pendingOrders': 'الأوامر المعلقة',
    'viewOrders': 'عرض الطلبات',
    'allOrders': 'جميع الطلبات',
    'pendingConfirmation': 'في انتظار التأكيد',
    'packing': 'التعبئة',
    'packed': 'معبأة',
    'dispatched': 'مُرسَل',
    'outForDelivery': 'خارج للتسليم',
    'viewDetails': 'عرض التفاصيل',
    'changeOrderStatus': 'تغيير حالة الطلب',
    'orderStatusUpdatedSuccessfully': 'تم تحديث حالة الطلب بنجاح',
    'orderStatusUpdated': 'تم تحديث حالة الطلب بنجاح',
    'itemStatusUpdatedSuccessfully': 'تم تحديث حالة العنصر بنجاح',
    'itemStatusUpdated': 'تم تحديث حالة العنصر بنجاح',
    'ordersCountSuffix': 'طلبات',
    'order': 'طلب',
    'orderLabel': 'طلب',
    'orders': 'طلبات',
    'ordered': 'أمر',
    'dealOrder': 'ترتيب الصفقة',
    'productOrder': 'طلب المنتج',
    'bid': 'مُنَاقَصَة',
    'itemPlusMore': '{item} + {n} المزيد',
    // ============================================
    // Cart Related
    // ============================================
    'yourCart': 'سلة التسوق الخاصة بك',
    'cart': 'عربة',
    'emptyCart': 'سلة التسوق الخاصة بك فارغة',
    'emptyCartMessage': 'أضف المنتجات إلى سلة التسوق الخاصة بك للبدء.',
    'addProductsToSeeThemHere': 'أضف المنتجات لرؤيتها هنا.',
    'placeOrderCashOnDelivery': 'تقديم الطلب (الدفع عند الاستلام)',
    'cashOnDelivery': 'الدفع عند التسليم',
    'paymentMethodCash': 'الدفع عند الاستلام',
    'paymentMethodCashDesc': 'ادفع عند استلام الطلبية.',
    'paymentMethodInvoice': 'الفاتورة',
    'paymentMethodInvoiceDesc':
        'نرسل لك فاتورة؛ الشحن يبدأ بعد تأكيد الطلب.',
    'paymentMethodBankTransfer': 'التحويل البنكي',
    'paymentMethodBankTransferDesc':
        'ادفع أولاً ثم الشحن. إرشادات الدفع ترسل بالبريد.',
    'paymentMode': 'وضع الدفع',
    'paymentModeSubtitle':
        'الافتراضي لصفقاتك. يمكنك تغيير هذا لاحقاً في ملفك الشخصي.',
    'paymentModeSubtitleMulti':
        'حدد طرق الدفع التي تقبلها. يمكنك تغيير هذا لاحقاً في ملفك الشخصي.',
    'paymentSettings': 'إعدادات الدفع',
    'paymentSettingsSubtitle':
        'تفاصيل البنك لطلبات الفاتورة/التحويل البنكي. '
        'يمكنك تحديثها لاحقاً في ملفك الشخصي.',
    'payWithCard': 'الدفع بالبطاقة',
    'placeOrderPayNow': 'تقديم الطلب والدفع',
    'paymentAfterOrderConfirmed': 'سيتم طلب الدفع بعد تأكيد طلبك (مثل التحويل البنكي).',
    'paymentNotAvailable': 'الدفع بالبطاقة غير متوفر. جرب الدفع عند الاستلام.',
    'paymentCancelled': 'تم إلغاء الدفع.',
    'dealSucceededPayNow': 'نجحت الصفقة - ادفع الآن',
    'totalToPay': 'مجموع للدفع',
    'payByInvoice': 'الدفع عن طريق الفاتورة',
    'payByCard': 'الدفع عن طريق البطاقة',
    'invoiceInstructionsSent': 'تم إرسال تعليمات الدفع عبر البريد الإلكتروني.',
    'paymentInstructionsBankOnly': 'تم إرسال تعليمات الدفع عبر البريد الإلكتروني. الدفع عن طريق التحويل البنكي. إذا كنت قد دفعت بالفعل، فسيقوم مالك الصفقة بتأكيد الاستلام.',
    'markAsPaid': 'وضع علامة على أنه مدفوع',
    'paymentNotesOptional': 'إشعارات الدفع (مثل مرجع البنك)',
    'myDealStats': 'إحصائيات صفقتي',
    'dealsJoined': 'انضمت الصفقات',
    'totalOrderedQuantity': 'الكمية الإجمالية المطلوبة',
    'totalOrders': 'إجمالي الطلبات',
    'placeOrder': 'وضع النظام',
    'fxDisclaimer': 'سعر صرف العملات الأجنبية عرضة للتغيير. المبلغ المعروض إرشادي.',
    'placingOrder': 'تقديم الطلب...',
    'orderPlacedSuccessfully': 'تم تقديم الطلب بنجاح!',
    'failedToPlaceOrder': 'فشل في تقديم الطلب',
    'onlyKioskCanOrder': 'يمكن فقط لحسابات Kiosk/Shop تقديم الطلبات.',
    'admins': 'المشرفين',
    'subAdmins': 'المشرفون الفرعيون',
    'wholesalers': 'تجار الجملة',
    'canOnlyViewProducts': 'يمكن فقط عرض المنتجات. يمكن فقط لحسابات Kiosk/Shop تقديم الطلبات.',
    'addToCart': 'أضف إلى السلة',
    'addedToCart': '✅ تم اضافته لسلة التسوق',
    'quantity': 'كمية',
    'unitPrice': 'سعر الوحدة',
    'totalAmount': 'المبلغ الإجمالي',
    'buyer': 'المشتري',
    'items': 'أغراض',
    // ============================================
    // Registration Related
    // ============================================
    'register': 'يسجل',
    'createAccount': 'إنشاء حساب',
    'createAccountTitle': 'إنشاء حساب',
    'createAccountSubtitle': 'أطلق العنان لتجار الجملة المنسقين والصفقات الكبيرة والدعم اللوجستي.',
    'fullName': 'الاسم الكامل',
    'email': 'بريد إلكتروني',
    'workEmail': 'البريد الإلكتروني للعمل',
    'phone': 'هاتف',
    'password': 'كلمة المرور',
    'confirmPassword': 'تأكيد كلمة المرور',
    'confirmPasswordLabel': 'تأكيد كلمة المرور',
    'businessName': 'اسم العمل',
    'country': 'دولة',
    'city': 'مدينة',
    'address': 'عنوان',
    'streetAddress': '.عنوان الشارع',
    'addressWillBeGeocoded': 'سيتم ترميز العنوان جغرافيًا تلقائيًا للحصول على الإحداثيات',
    'addressSearchHint': 'ابحث عن عنوانك',
    'placesLookupFailed':
        'تعذر تحميل تفاصيل العنوان من الخادم. يمكنك كتابة عنوانك أو تعديله يدويًا.',
    'placesNoAddressResults':
        'لم يتم العثور على عناوين. جرّب بحثًا مختلفًا.',
    'placesAddressSearchConfigError':
        'بحث العنوان غير متاح. تحقق من الشبكة وأن التطبيق يشير إلى خادم API '
        'الصحيح (API_BASE_URL).',
    'placesAddressSearchRequestFailed':
        'فشل بحث العنوان. تحقق من الاتصال أو حاول مرة أخرى لاحقًا.',
    'getLocation': 'احصل على الموقع',
    'selectRole': 'حدد الدور',
    'accountType': 'نوع الحساب',
    'alreadyHaveAccount': 'هل لديك حساب بالفعل؟',
    'login': 'تسجيل الدخول',
    'signIn': 'تسجيل الدخول',
    'registrationReceived': 'تم استلام التسجيل! سنقوم بإعلامك بمجرد الموافقة على الحساب.',
    'fullNameRequired': 'الاسم الكامل مطلوب',
    'fullNameMinLength': 'يجب أن يكون الاسم الكامل 3 أحرف على الأقل',
    'emailRequired': 'البريد الإلكتروني مطلوب',
    'provideValidEmail': 'توفير بريد إلكتروني صالح',
    'phoneNumberOptional': 'رقم الهاتف (اختياري)',
    'enterValidPhoneNumber': 'أدخل رقم هاتف صالحًا',
    'kioskShopNameOptional': 'اسم الكشك/المتجر (اختياري)',
    'companyName': 'اسم الشركة',
    'latitudeOptional': 'خط العرض (اختياري)',
    'longitudeOptional': 'خط الطول (اختياري)',
    'locating': 'تحديد موقع...',
    'locatingEllipsis': 'تحديد موقع…',
    'useCurrentLocation': 'استخدام الموقع الحالي',
    'enableLocationServices': 'تمكين خدمات الموقع من الملء التلقائي للإحداثيات.',
    'enableLocationPermissions': 'تمكين أذونات الموقع للملء التلقائي للإحداثيات.',
    'unableToFetchLocation': 'غير قادر على جلب الموقع. يرجى المحاولة مرة أخرى.',
    'unableToFetchLocationShort': 'غير قادر على جلب الموقع.',
    'pleaseEnterValidLatLng': 'الرجاء إدخال خط الطول وخط العرض الصحيح.',
    'createPassword': 'إنشاء كلمة المرور',
    'minimum8CharactersRequired': 'الحد الأدنى 8 أحرف مطلوبة',
    'weVerifyEveryBusiness': 'نحن نتحقق من كل الأعمال يدويًا للحفاظ على ثقة السوق.',
    'submitForReview': 'إرسال للمراجعة',
    'alreadyVerifiedSignIn': 'تم التحقق بالفعل؟ تسجيل الدخول',
    'forgotPassword': 'هل نسيت كلمة السر؟',
    'welcomeBack': 'مرحبًا بعودتك',
    'signInToReach': 'قم بتسجيل الدخول للوصول إلى تجار الجملة المعتمدين بالقرب منك.',
    'createKioskOrWholesalerAccount': 'قم بإنشاء حساب كشك أو تاجر جملة',
    'accountSubmittedForApproval': 'تم تقديم الحساب للموافقة عليه. سيتم فتح لوحة المعلومات بمجرد الموافقة عليها.',
    'dashboardWillUnlock': 'سيتم فتح لوحة المعلومات بمجرد الموافقة عليها.',
    'pleaseLoginToPlaceOrder': 'الرجاء تسجيل الدخول لتقديم الطلب',
    // ============================================
    // Legal / Compliance (T&C + GDPR)
    // ============================================
    'legalComplianceTitle': 'الشؤون القانونية والامتثال',
    'termsAndConditionsFullText': 'من خلال إنشاء حساب، فإنك تدخل في علاقة عمل مع مشغل المنصة وتوافق على شروط وأحكام المنصة (AGB). تحكم هذه الشروط كيفية استخدامك للسوق، وكيفية التعامل مع الصفقات والأوامر، والالتزامات التي تنطبق على المشترين وتجار الجملة. أنت تؤكد أن جميع المعلومات التي تقدمها دقيقة وأنك لن تستخدم المنصة إلا لأغراض تجارية مشروعة. أنت توافق أيضًا على أن الصفقات والطلبات قد تصبح ملزمة بمجرد تأكيدها من قبل تاجر الجملة أو بمجرد الوصول إلى هدف الصفقة. قد يتم تطبيق لوائح إضافية خاصة بكل بلد وفقًا للولاية القضائية الخاصة بك. يرجى مراجعة الشروط والأحكام الكاملة التي شاركها المشغل قبل المتابعة.',
    'scrollToAcceptTerms': 'قم بالتمرير إلى نهاية الشروط والأحكام لفتح مربع اختيار القبول.',
    'scrollToBottom': 'قم بالتمرير إلى الأسفل',
    'acceptTermsLabel': 'لقد قرأت وقبلت الشروط والأحكام (AGB).',
    'termsScrollHint': 'يرجى التمرير خلال الشروط والأحكام قبل الموافقة.',
    'acceptPrivacyLabel': 'لقد قرأت وأوافق على سياسة خصوصية البيانات / اللائحة العامة لحماية البيانات.',
    'privacySummaryText': 'ستتم معالجة بياناتك لإدارة الحساب والأوامر والتحليلات والأمان بما يتماشى مع سياسة الخصوصية الخاصة بنا.',
    'mustAcceptAllLegalDocuments': 'يرجى قبول جميع المستندات القانونية وتأكيد العقد الإطاري.',
    'mustAcceptTermsAndPrivacy': 'يرجى قبول الشروط والأحكام وخصوصية البيانات / اللائحة العامة لحماية البيانات للمتابعة.',
    // ============================================
    // Account Approval / Waiting Screen Related
    // ============================================
    'accountApproval': 'الموافقة على الحساب',
    'accountApproved': 'تمت الموافقة على الحساب!',
    'redirecting': 'إعادة التوجيه...',
    'pendingReview': 'في انتظار المراجعة',
    'needMoreInfo': 'بحاجة الى مزيد من المعلومات',
    'wholesalerVerificationMessage': 'شكرًا! لتفعيل حساب تاجر الجملة الخاص بك، يرجى تقديم مستندات التحقق من عملك. سيقوم مشرفنا بمراجعة حسابك والموافقة عليه.',
    'buyerVerificationMessage': 'شكرًا! لتنشيط حساب المشتري الخاص بك، يرجى تقديم مستندات التحقق من هويتك. سيقوم مشرفنا بمراجعة حسابك والموافقة عليه.',
    'generalVerificationMessage': 'شكرًا! لتفعيل حسابك، يرجى تقديم وثائق التحقق. سيقوم مشرفنا بمراجعة حسابك والموافقة عليه.',
    'adminNote': 'ملاحظة المشرف',
    'uploadVerificationDocument': 'تحميل وثيقة التحقق',
    'acceptedDocumentTypes': 'أنواع المستندات المقبولة',
    'wholesalerDocumentTypes': 'رخصة تجارية، معرف ضريبي، وثائق تسجيل الشركة (PNG، JPG، PDF)',
    'buyerDocumentTypes': 'بطاقة الهوية أو رخصة القيادة أو أي بطاقة هوية صادرة عن الحكومة (PNG، JPG، PDF)',
    'generalDocumentTypes': 'رخصة العمل، رخصة القيادة، بطاقة الهوية (PNG، JPG، PDF)',
    'selectedDocuments': 'المستندات المختارة',
    'addDocuments': 'أضف المستندات',
    'uploading': 'جارٍ التحميل...',
    'uploaded': 'تم الرفع',
    'selectFirst': 'اختر أولاً',
    'documentsUploadedSuccessfully': 'تم تحميل المستند (المستندات) بنجاح. سيقوم مشرفنا بمراجعة حالة حسابك وتحديثها.',
    'documentUploadedSuccessfully': 'تم تحميل المستند بنجاح. سيقوم مشرفنا بمراجعة حالة حسابك وتحديثها.',
    'failedToPickDocuments': 'فشل في اختيار المستندات',
    'passport': 'جواز سفر',
    'passportDescription': 'قم بتحميل جواز سفرك للتحقق من الهوية',
    'passportAlternative': 'إذا لم يكن لديك جواز سفر، يمكنك تحميل بطاقة هوية معتمدة من الحكومة تحتوي على العنوان (على سبيل المثال، Aadhar في الهند، بطاقة الهوية الوطنية، وما إلى ذلك)',
    'gewerbeschein': 'جيويربيشين',
    'idCard': 'بطاقة الهوية',
    'taxId': 'معرف الضريبة',
    'companyRegistration': 'تسجيل الشركة',
    'document': 'وثيقة',
    'gewerbescheinDescription': 'قم بتحميل Gewerbeschein (الرخصة التجارية) الخاصة بك للتحقق من الأعمال',
    'gewerbescheinAlternative': 'قم بتحميل وثيقة الرخصة التجارية الرسمية الخاصة بك الصادرة عن السلطات',
    'businessLicense': 'رخصة تجارية / Gewerbeschein',
    'businessLicenseDescription': 'قم بتحميل رخصة عملك أو Gewerbeschein للتحقق من الأعمال',
    'businessLicenseAlternative': 'إذا لم يكن لديك ترخيص تجاري، يمكنك تحميل مستندات تسجيل الشركة أو المعرف الضريبي أو أي مستند رسمي للتحقق من الأعمال',
    'selectDocument': 'حدد المستند',
    'changeDocument': 'تغيير المستند',
    'pleaseSelectAtLeastOneDocument': 'الرجاء تحديد مستند واحد على الأقل لتحميله.',
    'sendByEmail': 'إرسال عن طريق البريد الإلكتروني',
    'emailOptionDescription': 'وبدلاً من ذلك، يمكنك إرسال مستندات التحقق الخاصة بك مباشرةً عبر البريد الإلكتروني. سيقوم مشرفنا بالتحقق من المستندات وتحديث حالة حسابك وفقًا لذلك.',
    'openEmailToAdmin': 'افتح البريد الإلكتروني للمسؤول',
    'emailDraftOpened': 'تم فتح مسودة البريد الإلكتروني. برجاء إرسالها لإكمال التقديم. سيقوم مشرفنا بالتحقق من مستنداتك وتحديث حالة حسابك.',
    'couldNotOpenEmailApp': 'لا يمكن فتح تطبيق البريد الإلكتروني. يرجى إرسال بريد إلكتروني إلى',
    'manually': 'يدويا',
    'failedToOpenEmail': 'فشل في فتح البريد الإلكتروني',
    'loadingAccountStatus': 'جارٍ تحميل حالة الحساب...',
    'errorLoadingStatus': 'حدث خطأ أثناء تحميل الحالة',
    'pleaseReviewAndResubmit': 'يرجى مراجعة وإعادة تقديم المستندات الخاصة بك.',
    'useDifferentAccount': 'استخدام حساب مختلف',
    'useDifferentAccountConfirm':
        'تسجيل الخروج لتسجيل الدخول أو التسجيل بحساب مختلف؟',
    'failedToUpdateStatus': 'فشل في تحديث الإعدادات القانونية. يرجى المحاولة مرة أخرى.',
    // ============================================
    // Profile Related
    // ============================================
    'editProfile': 'تحرير الملف الشخصي',
    'profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
    'failedToUpdateProfile': 'فشل في تحديث الملف الشخصي',
    'profileImageUpdated': 'تم تحديث صورة الملف الشخصي',
    'failedToUploadImage': 'فشل تحميل الصورة',
    'tagline': 'سطر الوصف',
    'locations': 'المواقع',
    'addLocation': 'أضف الموقع',
    'editLocation': 'تحرير الموقع',
    'deleteLocation': 'حذف الموقع',
    'latitude': 'خط العرض',
    'longitude': 'خط الطول',
    'nameIsRequired': 'الاسم مطلوب',
    'businessNameOptional': 'اسم النشاط التجاري (اختياري)',
    'phoneOptional': 'الهاتف (اختياري)',
    'addresses': 'العناوين',
    'addAddress': 'إضافة عنوان',
    'noAddressesAdded': 'لم تتم إضافة أي عناوين',
    'addYourFirstAddress': 'أضف عنوانك الأول للبدء',
    'editAddress': 'تحرير العنوان',
    'removeAddress': 'إزالة العنوان',
    'editAddressTitle': 'تحرير العنوان',
    'addAddressTitle': 'إضافة عنوان',
    'saveChanges': 'حفظ التغييرات',
    'labelExample': 'الملصق (على سبيل المثال، المنزل، المكتب، المنفذ الرئيسي)',
    'streetAreaOptional': 'الشارع / المنطقة (اختياري)',
    'countryOptional': 'البلد (اختياري)',
    'cityOptional': 'المدينة (اختياري)',
    'locationNotUpdating': 'الموقع لا يتم تحديثه',
    'locationNotUpdatingSolution': 'انتقل إلى الملف الشخصي > العناوين وتأكد من صحة إحداثيات موقعك',
    // ============================================
    // Deals Related
    // ============================================
    'deals': 'العروض',
    'activeDeals': 'الصفقات النشطة',
    'allDeals': 'جميع العروض',
    'myDeals': 'صفقاتي',
    'manageDeals': 'إدارة الصفقات',
    'noDealsFound': 'لم يتم العثور على صفقات',
    'selectDeal': 'حدد الصفقة',
    'unableToLoadDeals': 'غير قادر على تحميل الصفقات',
    'noDealsAvailable': 'لا توجد صفقات متاحة',
    'noDealsYet': 'لا توجد صفقات حتى الآن',
    'checkBackLaterForNewDeals': 'التحقق مرة أخرى في وقت لاحق للحصول على صفقات جديدة',
    'noActiveDeals': 'لا توجد صفقات نشطة',
    'filterDeals': 'عروض التصفية',
    'progress': 'تقدم',
    'dealClosed': 'الصفقة مغلقة',
    'ends': 'ينتهي',
    'variant': 'البديل',
    'min': 'الحد الأدنى:',
    'max': 'الأعلى:',
    'perUnit': '/وحدة',
    'perUnitLabel': 'لكل {unit}',
    'inStock': 'في الأوراق المالية',
    'similarProducts': 'منتجات مماثلة',
    'noActiveDealsForProduct': 'لا توجد صفقات نشطة لهذا المنتج',
    'activeDealsForProduct': 'صفقات نشطة لهذا المنتج',
    'moreFromWholesaler': 'المزيد من {name}',
    'dealsFromWholesaler': 'عروض من {name}',
    'productsFromWholesaler': 'منتجات من {name}',
    'searchProductsFromWholesaler': 'البحث عن منتجات من {name}...',
    'onlyKioskCanPurchase': 'يمكن فقط لحسابات Kiosk/Shop شراء المنتجات',
    'canOnlyReviewFromDelivered': 'يمكنك فقط مراجعة المنتجات من الطلبات التي تم تسليمها',
    'alreadyReviewedThisProduct': 'لقد قمت بالفعل بمراجعة هذا المنتج من هذا الطلب',
    'selectOrderToReview': 'حدد الطلب للمراجعة',
    'orderN': 'الطلب #{id}',
    'viewDeals': 'عرض الصفقات',
    'locationInfoNotAvailable': 'معلومات الموقع غير متوفرة',
    'location': 'موقع',
    'kfProductDealTagline': 'صفقة منتجات KF، تساعدك في العثور على أفضل الصفقات',
    'errorSearchingProducts': 'خطأ في البحث عن المنتجات',
    'myDealOrders': 'أوامر صفقتي',
    'noDealOrdersYet': 'لا توجد أوامر صفقة حتى الآن',
    'browseDealsPlaceFirstOrder': 'تصفح الصفقات النشطة وقم بتقديم طلبك الأول.',
    'statusLabel': 'حالة',
    'noProductsFoundForWholesaler': 'لم يتم العثور على منتجات لتاجر الجملة المحدد',
    'noApprovedWholesalersAvailable': 'لا يوجد تجار جملة معتمدين',
    'searchByNameBusinessEmail': 'البحث حسب الاسم واسم العمل والبريد الإلكتروني ...',
    'selectWholesaler': 'حدد تاجر الجملة',
    'selectProduct': 'حدد المنتج',
    'pageNOfM': 'الصفحة {current} من {total}',
    'priceLabel': 'سعر',
    'pleaseSelectImageOrVideo': 'الرجاء اختيار صورة أو فيديو',
    'onlyWholesalersCreateStories': 'يمكن لتجار الجملة فقط إنشاء القصص',
    'storyCreatedSuccessfully': 'تم إنشاء القصة بنجاح! 🎉',
    'uploadingMedia': 'جارٍ تحميل الوسائط...',
    'creatingStory': 'إنشاء قصة...',
    'storyMedia': 'قصة وسائل الإعلام',
    'videoSelected': 'تم اختيار الفيديو',
    'activeShopsSuffix': 'المحلات التجارية النشطة',
    'storiesCountSuffix': 'قصص',
    'create': 'يخلق',
    'off': 'عن',
    'minOrder': 'الحد الأدنى للطلب',
    'target': 'هدف',
    'units': 'وحدات',
    'dealCreatedSuccessfully': 'تم إنشاء الصفقة بنجاح',
    'createDeal': 'إنشاء صفقة',
    'editDeal': 'تحرير الصفقة',
    'closeDeal': 'إغلاق الصفقة',
    'closeDealConfirmMessage': 'هل أنت متأكد أنك تريد إغلاق هذه الصفقة؟ لا يمكن التراجع عن هذا الإجراء.',
    'closeDealGoalReached': 'تم الوصول للهدف',
    'closeDealGoalReachedHint': 'في حالة تحديده: سيتم تأكيد جميع الطلبات المعلقة تلقائيًا (تم تنفيذ الصفقة بنجاح). إذا لم يتم تحديده: سيتم إغلاق الصفقة ولكن يمكنك تأكيد الطلبات يدويًا لاحقًا.',
    'createYourFirstDeal': 'أنشئ صفقتك الأولى',
    'dealTitle': 'عنوان الصفقة',
    'pleaseEnterDealTitle': 'الرجاء إدخال عنوان الصفقة',
    'dealType': 'نوع الصفقة',
    'dealPrice': 'سعر الصفقة',
    'startDate': 'تاريخ البدء',
    'endDate': 'تاريخ الانتهاء',
    'pleaseEnterDealPrice': 'الرجاء إدخال سعر الصفقة',
    'originalPrice': 'السعر الأصلي',
    'targetQuantity': 'الكمية المستهدفة',
    'pleaseEnterTargetQuantity': 'الرجاء إدخال الكمية المستهدفة',
    'targetQuantityMin': 'يجب أن تكون الكمية المستهدفة 1 على الأقل',
    'minOrderQty': 'الحد الأدنى للطلب الكمية',
    'pleaseEnterMinOrderQty': 'الرجاء إدخال الحد الأدنى لكمية الطلب',
    'minOrderQtyMin': 'الحد الأدنى لكمية الطلب يجب أن لا يقل عن 1',
    'maxOrderQuantityOptional': 'الحد الأقصى لكمية الطلب (اختياري)',
    'endDateMustBeAfterStartDate': 'يجب أن يكون تاريخ الانتهاء بعد تاريخ البدء',
    'pleaseSelectWholesalerFirst': 'الرجاء اختيار تاجر الجملة أولا',
    'auction': 'مزاد',
    'priceDrop': 'انخفاض الأسعار',
    'limitedStock': 'مخزون محدود',
    'scheduled': 'المقرر',
    'live': 'يعيش',
    'highlightedDeal': 'الصفقة المميزة',
    'canOnlyViewDeals': 'يمكن فقط عرض الصفقات. يمكن فقط لحسابات Kiosk/Shop تقديم الطلبات.',
    'dealProgressNotUpdating': 'تقدم الصفقة لا يتم تحديثه',
    'dealProgressNotUpdatingSolution': 'يتم تحديث تقدم الصفقة تلقائيًا. إذا بدت عالقة، قم بتحديث الصفحة',
    'dealProgress': 'تقدم الصفقة',
    'unableToLoadProgress': 'غير قادر على تحميل التقدم: {detail}',
    'noOrdersPlacedYet': 'لم يتم وضع أي أوامر على هذه الصفقة حتى الآن.',
    'orderPlacedSuffix': 'تم تقديم الطلب',
    'ordersPlacedSuffix': 'الطلبات المقدمة',
    'closed': 'مغلق',
    // ============================================
    // Products Related
    // ============================================
    'product': 'منتج',
    'products': 'منتجات',
    'productsSection': 'منتجات',
    'allProducts': 'جميع المنتجات',
    'myProducts': 'منتجاتي',
    'noProductsAvailable': 'لا توجد منتجات متاحة',
    'noProductsYet': 'لا توجد منتجات حتى الآن',
    'addYourFirstProduct': 'أضف منتجك الأول',
    'addFirstProduct': 'أضف منتجك الأول',
    'addProduct': 'أضف منتج',
    'editProduct': 'تحرير المنتج',
    'deleteProduct': 'حذف المنتج',
    'deletingProduct': 'جارٍ حذف المنتج...',
    'deleteProductConfirmGeneric': 'هل أنت متأكد أنك تريد حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.',
    'productUpdatedSuccessfully': 'تم تحديث المنتج بنجاح',
    'productCreatedSuccessfully': 'تم إنشاء المنتج بنجاح',
    'productDeletedSuccessfully': 'تم حذف المنتج بنجاح',
    'changeProductStatus': 'تغيير حالة المنتج',
    'changeStatus': 'تغيير الحالة',
    'updatingStatus': 'جارٍ تحديث الحالة...',
    'statusUpdatedToPending': 'تم تحديث الحالة إلى معلق',
    'statusUpdatedToApproved': 'تم تحديث الحالة إلى "موافق عليه".',
    'statusUpdatedToRejected': 'تم تحديث الحالة إلى مرفوض',
    'productsWillAppearHere': 'ستظهر المنتجات هنا بمجرد إضافتها',
    'noProductsFound': 'لم يتم العثور على منتجات',
    'youveReachedEnd': 'لقد وصلت إلى النهاية',
    'errorLoadingProducts': 'حدث خطأ أثناء تحميل المنتجات',
    'featuredCatalog': 'كتالوج مميز',
    'viewAll': 'عرض الكل',
    'outOfStock': 'إنتهى من المخزن',
    'onlyLeft': 'فقط',
    'left': 'غادر',
    'timeRemainingDay': '{count} يوم متبقي',
    'timeRemainingDays': '{count} أيام متبقية',
    'timeRemainingHour': '{count} ساعة متبقية',
    'timeRemainingHours': '{count} ساعات متبقية',
    'timeRemainingMinute': '{count} دقيقة متبقية',
    'timeRemainingMinutes': '{count} دقائق متبقية',
    'pleaseSelectProduct': 'الرجاء تحديد المنتج',
    'tapToSelectProduct': 'انقر لتحديد منتج',
    'unknownProduct': 'منتج غير معروف',
    'searchProductsHint': 'البحث عن المنتجات بالاسم، SKU...',
    'loadingMoreProducts': 'جارٍ تحميل المزيد من المنتجات...',
    'reachedEnd': 'لقد وصلت إلى النهاية',
    'productsCountSuffix': 'منتجات',
    'price': 'سعر',
    'kilogram': 'كيلوغرام',
    'gram': 'غرام',
    'liter': 'لتر',
    'milliliter': 'ملليلتر',
    'piece': 'قطعة',
    'box': 'صندوق',
    'pack': 'علية',
    'kmAway': 'على بعد كم',
    'viewAllProducts': 'عرض جميع المنتجات',
    // ============================================
    // Product Management Related
    // ============================================
    'productTitle': 'عنوان المنتج',
    'productTitleRequired': 'الرجاء إدخال عنوان المنتج',
    'titleMinLength': 'يجب أن يتكون العنوان من 3 أحرف على الأقل',
    'description': 'وصف',
    'category': 'فئة',
    'wholesaler': 'تاجر الجملة',
    'selectCategory': 'حدد الفئة',
    'selectCategories': 'حدد الفئات',
    'pleaseSelectCategory': 'الرجاء تحديد فئة',
    'tapToSelectCategory': 'انقر لتحديد فئة',
    'pleaseSelectWholesaler': 'الرجاء اختيار تاجر الجملة',
    'tapToSelectWholesaler': 'انقر لتحديد تاجر الجملة',
    'unknownCategory': 'فئة غير معروفة',
    'yourAccount': 'حسابك',
    'currentUser': 'المستخدم الحالي',
    'variants': 'المتغيرات',
    'useVariants': 'استخدم المتغيرات',
    'addVariant': 'إضافة البديل',
    'addAttribute': 'إضافة سمة',
    'variantSkuRequired': 'مطلوب SKU',
    'addAtLeastOneVariant': 'الرجاء إضافة متغير واحد على الأقل',
    'selectVariant': 'حدد البديل',
    'selectVariantHelper': 'حدد البديل لهذه الصفقة',
    'noVariantsMessage': 'هذا المنتج لا يوجد لديه المتغيرات. سيتم إنشاء الصفقة على المنتج مباشرة.',
    'unableToLoadVariantsMessage': 'غير قادر على تحميل المتغيرات. سيتم إنشاء الصفقة على المنتج.',
    'featuredProduct': 'منتج مميز',
    'default': 'تقصير',
    'updateProduct': 'تحديث المنتج',
    'createProduct': 'إنشاء المنتج',
    'globalAttributes': 'السمات العالمية',
    'globalAttributesDescription': 'حدد سمات مثل اللون والحجم لتطبيقها على جميع المتغيرات.',
    'attributeName': 'اسم السمة (على سبيل المثال، اللون)',
    'attributeNameHint': 'اللون والحجم والمواد ...',
    'imageUrl': 'عنوان URL للصورة',
    'productImages': 'صور المنتج',
    'firstImagePrimary': 'الصورة الأولى هي الأولية',
    'addImageUrl': 'أضف عنوان URL',
    'pasteImageUrlHint': 'لصق عنوان URL للصورة',
    'costPrice': 'سعر التكلفة',
    'stock': 'مخزون',
    'stockRequired': 'الرجاء إدخال المخزون',
    'stockNegative': 'لا يمكن أن يكون السهم سلبيا',
    'priceRequired': 'الرجاء إدخال السعر',
    'pricePositive': 'يجب أن يكون السعر أكبر من 0',
    'validationError': 'خطأ في التحقق',
    'checkAllFields': 'يرجى التحقق من كافة الحقول',
    'pending': 'قيد الانتظار',
    'approved': 'موافقة',
    'rejected': 'مرفوض',
    'draft': 'مسودة',
    'failedToCreateDeal': 'فشل في إنشاء الصفقة',
    'invalidDateTimeFormat': 'تنسيق التاريخ/الوقت غير صالح. يرجى التحقق من التواريخ الخاصة بك.',
    // ============================================
    // Categories Related
    // ============================================
    'noCategoriesFound': 'لم يتم العثور على فئات',
    'noCategoriesAvailable': 'لا توجد فئات متاحة',
    'allCategories': 'جميع الفئات',
    'searchCategories': 'فئات البحث...',
    'noCategoriesMatchSearch': 'لا توجد فئات تطابق بحثك',
    'categoriesWillAppearHere': 'ستظهر الفئات هنا بمجرد إضافتها',
    'tryDifferentSearchTerm': 'حاول استخدام مصطلح بحث مختلف',
    'errorLoadingCategories': 'حدث خطأ أثناء تحميل الفئات',
    'unableToLoadCategory': 'غير قادر على تحميل الفئة',
    'productsCount': '{n} المنتجات',
    'categoryName': 'اسم الفئة',
    'categoryDescription': 'وصف',
    'categoryImageUrl': 'عنوان URL للصورة',
    'createCategory': 'إنشاء فئة',
    'editCategory': 'تحرير الفئة',
    'deleteCategory': 'حذف الفئة',
    'deleteCategoryConfirm': 'هل أنت متأكد أنك تريد حذف "{name}"؟ لا يمكن التراجع عن هذا الإجراء.',
    'categoryCreatedSuccessfully': 'تم إنشاء الفئة بنجاح',
    'enterCategoryDescriptionToGenerate': 'أدخل وصف الفئة لإنشاء المحتوى تلقائيًا.',
    'categoryDescriptionHint': 'على سبيل المثال، الخضروات العضوية...',
    'contentGeneratedSuccessfullyEnglish': 'تم إنشاء المحتوى بنجاح! (إنجليزي)',
    'generationFailedWithError': 'فشل الإنشاء: {error}',
    'categoryUpdatedSuccessfully': 'تم تحديث الفئة بنجاح',
    'categoryDeletedSuccessfully': 'تم حذف الفئة بنجاح',
    'categoryCreationImportMessage': 'يتم إنشاء الفئة حاليًا من خلال الاستيراد. يرجى الاتصال بالمسؤول.',
    'pleaseEnterCategoryName': 'الرجاء إدخال اسم الفئة',
    // ============================================
    // Reviews Related
    // ============================================
    'reviewed': 'تمت المراجعة',
    'youHaveAlreadyReviewed': 'لقد قمت بالفعل بمراجعة هذا المنتج من هذا الطلب',
    'reviewUpdatedSuccessfully': 'تم تحديث المراجعة بنجاح',
    'reviewSubmittedSuccessfully': 'تم إرسال المراجعة بنجاح',
    'pleaseSelectRating': 'الرجاء تحديد التقييم',
    'maximum5ImagesAllowed': 'الحد الأقصى المسموح به هو 5 صور',
    'failedToPickImage': 'فشل في اختيار الصورة',
    'failedToUploadImages': 'فشل تحميل الصور',
    'uploadImages': 'تحميل الصور',
    'pickImage': 'اختر الصورة',
    'pickVideo': 'اختر فيديو',
    'uploadFailed': 'فشل التحميل',
    'upload': 'رفع',
    'invalidImageUrl': 'عنوان URL للصورة غير صالح',
    // ============================================
    // Banners Related
    // ============================================
    'viewProduct': 'عرض المنتج',
    'viewDeal': 'عرض الصفقة',
    'openLink': 'افتح الرابط',
    'discoverGreatDealsNearby': 'اكتشاف صفقات كبيرة في مكان قريب',
    'stayTunedForOffers': 'ترقبوا العروض والقصص الجديدة من تجار الجملة المعتمدين.',
    'manageBanners': 'إدارة اللافتات',
    'myBanners': 'لافتاتي',
    'noBannersFound': 'لم يتم العثور على لافتات. إنشاء واحدة!',
    'bannerDetails': 'تفاصيل اللافتة',
    'bannerNotFound': 'لم يتم العثور على اللافتة',
    'views': 'الأعظم',
    'clicks': 'النقرات',
    'bannerRequestSubmitted': 'تم إرسال طلب البانر!',
    'failedToSubmitRequest': 'فشل في تقديم الطلب',
    'deleteBanner': 'حذف الشعار',
    'deleteBannerConfirm': 'هل أنت متأكد أنك تريد حذف هذا الشعار؟',
    'bannerDeleted': 'تم حذف البانر',
    'failedToDeleteBanner': 'فشل في حذف الشعار',
    'targetId': 'معرف الهدف',
    'url': 'عنوان URL',
    'createNewBanner': 'إنشاء شعار جديد',
    'bannerTitle': 'عنوان البانر',
    'enterBannerTitle': 'أدخل عنوان الشعار',
    'bannerImage': 'صورة البانر',
    'webBannerImage': 'صورة الويب',
    'webBannerImageHint': 'وضع أفقي للويب',
    'mobileBannerImage': 'صورة الجوال',
    'mobileBannerImageHint': 'عمودي/مربع للجوال',
    'mobilePreview': 'معاينة الجوال',
    'preview': 'معاينة',
    'previewMobile': 'معاينة الجوال',
    'previewWillAppearHere': 'ستظهر المعاينة هنا',
    'pasteImageUrlHere': 'الصق عنوان URL للصورة هنا',
    'pleaseEnterImageUrlOrSwitch': 'الرجاء إدخال عنوان URL للصورة أو التبديل إلى التحميل واختيار صورة.',
    'pleaseTapChooseImage': 'يرجى النقر على "اختيار صورة" لتحميل صورة بانر، أو التبديل إلى عنوان URL ولصق رابط الصورة.',
    'tapToUploadWebImage': 'انقر لتحميل صورة الويب',
    'tapToUploadMobileImage': 'انقر لتحميل صورة الجوال',
    'chooseImage': 'اختر الصورة',
    'replaceImage': 'استبدال الصورة',
    // ============================================
    // Stories Related
    // ============================================
    'createStory': 'إنشاء قصة',
    'storiesFromVerifiedWholesalers': 'قصص من تجار الجملة المعتمدين',
    'storiesWillAppearHere': 'ستظهر القصص هنا بمجرد إضافتها',
    'selectImageOrVideoForStory': 'اختر صورة أو مقطع فيديو لقصتك',
    'post': 'بريد',
    'expiresAt': 'تنتهي عند',
    // ============================================
    // Shipment / Tracking Related
    // ============================================
    'trackingNumber': 'عدد تتبع',
    'carrier': 'الناقل',
    'trackingUrl': 'عنوان URL للتتبع',
    'openTrackingLink': 'فتح رابط التتبع',
    'statusTimeline': 'الجدول الزمني للحالة',
    // ============================================
    // Account Deletion Related
    // ============================================
    'submitDeletionRequest': 'تقديم طلب الحذف',
    'submitRequest': 'إرسال الطلب',
    'reviewProcess': 'عملية المراجعة',
    'accountDeleted': 'تم حذف الحساب',
    'whatHappensNext': 'ماذا سيحدث بعد ذلك؟',
    'submitRequestDescription': 'أدخل عنوان بريدك الإلكتروني لطلب حذف الحساب',
    'reviewProcessDescription': 'سيقوم فريقنا بمراجعة طلبك خلال 24-48 ساعة. ستتلقى رسالة تأكيد بالبريد الإلكتروني بمجرد معالجة طلبك.',
    'accountDeletedDescription': 'سيتم حذف حسابك وجميع البيانات المرتبطة به نهائيًا. لا يمكن التراجع عن هذا الإجراء.',
    'ourTeamReviewsYourRequest': 'يقوم فريقنا بمراجعة طلبك',
    'reviewDetails': 'تفاصيل المراجعة',
    'reviewDetailsDescription': 'نحن نتحقق من حسابك ونتأكد من اكتمال جميع الطلبات أو المعاملات المعلقة قبل متابعة الحذف.',
    'yourAccountIsPermanentlyRemoved': 'تمت إزالة حسابك نهائيًا',
    'finalStep': 'الخطوة النهائية',
    'finalStepDescription': 'بمجرد الموافقة، سيتم حذف بيانات حسابك نهائيًا من نظامنا. لا يمكن التراجع عن هذا الإجراء.',
    'importantInformation': 'معلومات هامة',
    'accountDeletionIsPermanent': 'يعد حذف الحساب نهائيًا ولا يمكن التراجع عنه',
    'allDataWillBeRemoved': 'ستتم إزالة جميع بياناتك وأوامرك وسجلك نهائيًا',
    'pendingOrdersMustBeCompleted': 'يجب إكمال الطلبات المعلقة قبل متابعة الحذف',
    'youllReceiveEmailConfirmation': 'ستتلقى تأكيدًا بالبريد الإلكتروني بمجرد اكتمال العملية',
    'confirmActionPermanent': 'يرجى التأكد من أنك تفهم أن هذا الإجراء دائم',
    'requestSubmitted': 'تم تقديم الطلب',
    'deletionRequestSubmittedMessage': 'لقد تم إرسال طلب حذف حسابك بنجاح. سيقوم فريقنا بمراجعتها خلال 24-48 ساعة. ستتلقى رسالة تأكيد بالبريد الإلكتروني بمجرد معالجة طلبك.',
    'ok': 'نعم',
    'failedToSubmitDeletionRequest': 'فشل في تقديم طلب الحذف. يرجى المحاولة مرة أخرى.',
    'requestAccountDeletion': 'طلب حذف الحساب',
    'sorryToSeeYouGo': 'نحن نأسف لرؤيتك تذهب',
    'emailAddress': 'عنوان البريد الإلكتروني',
    'enterRegisteredEmail': 'أدخل عنوان بريدك الإلكتروني المسجل',
    'emailAddressRequired': 'عنوان البريد الإلكتروني مطلوب',
    'pleaseEnterValidEmail': 'يرجى إدخال عنوان بريد إلكتروني صالح',
    'reasonForDeletionOptional': 'سبب الحذف (اختياري)',
    'helpUsImproveLeaving': 'ساعدنا على التحسن من خلال مشاركة سبب مغادرتك...',
    'understandActionPermanent': 'أدرك أن هذا الإجراء نهائي ولا يمكن التراجع عنه',
    // ============================================
    // Support / Help Related
    // ============================================
    'emailSupport': 'دعم البريد الإلكتروني',
    'getHelpViaEmail': 'احصل على المساعدة عبر البريد الإلكتروني',
    'phoneSupport': 'الدعم عبر الهاتف',
    'callUsDuringBusinessHours': 'اتصل بنا خلال ساعات العمل',
    'liveChat': 'الدردشة الحية',
    'chatWithUs': 'الدردشة معنا',
    'chatWithSupportTeam': 'الدردشة مع فريق الدعم لدينا',
    'commonIssues': 'القضايا المشتركة',
    'orderNotShowingUp': 'عدم ظهور الطلب',
    'orderNotShowingUpSolution': 'قم بتحديث لوحة التحكم أو تحقق من سجل الطلبات الخاص بك في "طلباتي"',
    'liveChatComingSoon': 'الدردشة الحية قريبا!',
    'needHelpContactSupport': 'بحاجة الى مساعدة؟ اتصل بالدعم',
    'contactSupportAt': 'اتصل بالدعم على',
    'getInTouch': 'تواصل معنا',
    'wereHereToHelp': 'نحن هنا لمساعدتك',
    'businessEmail': 'البريد الإلكتروني للأعمال',
    'contactUsOnWhatsApp': 'تواصل معنا على الواتساب',
    'helloNeedAssistance': 'مرحبًا! انا بحاجة للمساعدة.',
    'myDetails': 'تفاصيلي:',
    'nameLabel': 'اسم:',
    'phoneLabel': 'هاتف:',
    'emailLabel': 'بريد إلكتروني:',
    'businessLabel': 'عمل:',
    'howCanYouHelpMe': 'كيف يمكنك مساعدتي؟',
    'unableToOpenWhatsApp': 'غير قادر على فتح الواتساب. يرجى المحاولة مرة أخرى.',
    'hello': 'مرحبًا',
    // ============================================
    // Common Validation Related
    // ============================================
    'required': 'هذه الخانة مطلوبه',
    'invalidEmail': 'بريد إلكتروني غير صالح',
    'passwordTooShort': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
    // ============================================
    // Manager / Admin Related
    // ============================================
    'admin': 'مسؤل',
    'role': 'دور',
    'created': 'مخلوق',
    'subAdmin': 'المشرف الفرعي',
    'accessDenied': 'تم الرفض',
    'managersSectionOnly': 'هذا القسم متاح فقط للمديرين',
    'totalRevenue': 'إجمالي الإيرادات',
    'myRevenue': 'إيراداتي',
    'activeShops': 'تجار الجملة النشطين',
    'activeMembers': 'المحلات التجارية النشطة / Koisks',
    'inactiveMembers': 'المحلات التجارية غير النشطة',
    'activeShopsSubtitle': 'تجار الجملة الذين تم التحقق منهم على المنصة',
    'activeMembersSubtitle': 'المحلات التجارية التي طلبت مؤخرا',
    'inactiveMembersSubtitle': 'لا يوجد طلب خلال 60+ يومًا',
    'lastOrder': 'الطلب الأخير',
    'lastActive': 'آخر نشاط',
    'lastLogin': 'آخر تسجيل دخول',
    'joined': 'انضم',
    'selectToNotify': 'حدد لإرسال الإخطار',
    'deselect': 'قم بإلغاء التحديد',
    'recipients': 'المستلمون',
    'notificationSent': 'تم إرسال الإشعار',
    'notifyDealParticipantsTitle': 'إشعار المشاركين في الصفقة',
    'notifyDealParticipantsAudienceWarning':
        'سيتم إرسال هذه الرسالة فقط إلى المستخدمين الذين قاموا بإجراء طلب لهذه الصفقة.',
    'notifyDealParticipantsSendUpdateTooltip': 'إرسال التحديث',
    'notifyDealParticipantsSending': 'جارٍ الإرسال...',
    'notifyDealParticipantsNoParticipantsError':
        'تعذر الإرسال: لم ينضم أي مستخدم إلى هذه الصفقة بعد.',
    'notifyDealParticipantsFailedToSend':
        'فشل إرسال الإشعار: {error}',
    'noInactiveMembers': 'لا يوجد أعضاء غير نشطين',
    'selectAll': 'حدد الكل',
    'sendNotification': 'إرسال الإخطار',
    'title': 'عنوان',
    'body': 'رسالة',
    'send': 'يرسل',
    'generateWithAI': 'توليد مع الذكاء الاصطناعي',
    'generateNotificationPrompt': 'قم بوصف الإشعار (على سبيل المثال، إعادة المشاركة، والتخفيضات السريعة، والمنتجات الجديدة) لإنشاء العنوان والرسالة.',
    'weMissYou': 'إننا نفتقدك!',
    'reEngagementDefaultBody': 'لم تقم بتقديم طلب منذ فترة. تصفح أحدث العروض والمنتجات لدينا.',
    'notificationRemindHint': 'على سبيل المثال، تذكير المتاجر غير النشطة بتخفيضاتنا الشتوية',
    'searchByNameEmail': 'البحث بالاسم والبريد الإلكتروني...',
    'generate': 'يولد',
    'page': 'صفحة',
    'never': 'أبداً',
    'quickActions': 'إجراءات سريعة',
    'recentOrders': 'الطلبات الأخيرة',
    'noRecentOrders': 'لا توجد طلبات حديثة',
    'analyticsComingSoon': 'التحليلات - قريبا',
    'importCsv': 'استيراد من CSV',
    'importFromCsv': 'استيراد من CSV',
    'importProductsFromCsv': 'استيراد المنتجات من CSV',
    'importProducts': 'استيراد المنتجات',
    'importing': 'جارٍ الاستيراد...',
    'downloadCsvTemplate': 'تنزيل قالب CSV',
    'getSampleCsvWithColumns': 'احصل على نموذج ملف CSV مع جميع الأعمدة المطلوبة',
    'selectCsvFile': 'حدد ملف CSV',
    'chooseFile': 'اختر ملف',
    'tapToSelectWholesalerForImport': 'انقر لتحديد تاجر جملة للمنتجات المستوردة',
    'importComplete': 'اكتمل الاستيراد',
    'inserted': 'تم إدراجه',
    'updated': 'تم التحديث',
    'skipped': 'تم تخطيه',
    'fileLabel': 'الملف: {name}',
    'wholesalerRequired': 'تاجر الجملة *',
    'wholesalerLabel': 'تاجر الجملة {id}',
    'csvPreviewRows': 'معاينة ملف CSV ({n} صفوف)',
    'multipleRowsSameProductVariant': 'صفوف متعددة بنفس اسم المنتج = متغيرات متعددة',
    'errorsCount': 'الأخطاء ({n})',
    'andMoreErrors': '... و{n} المزيد من الأخطاء',
    'failedToReadFileBytes': 'فشل في قراءة بايت الملف',
    'failedToGetFilePath': 'فشل في الحصول على مسار الملف',
    'errorPickingFile': 'خطأ في اختيار الملف: {error}',
    'csvFileEmpty': 'ملف CSV فارغ',
    'errorParsingCsv': 'خطأ في تحليل ملف CSV: {error}',
    'templateSavedSuccessfully': 'تم حفظ القالب بنجاح',
    'templateDownloadCancelled': 'تم إلغاء تنزيل القالب',
    'errorGeneratingTemplate': 'حدث خطأ أثناء إنشاء القالب',
    'errors': 'أخطاء',
    'viewWholesaler': 'عرض تاجر الجملة',
    'cropImage': 'صورة المحاصيل',
    'change': 'يتغير',
    'navigationError': 'خطأ في التنقل',
    // ============================================
    // Time Related
    // ============================================
    'hours': 'ساعات',
    'minutes': 'دقائق',
    'seconds': 'ثواني',
    'twentyFourHours': '24 ساعة',
    'twelveHours': '12 ساعة',
    'sixHours': '6 ساعات',
    // ============================================
    // Navigation / Route Errors
    // ============================================
    'noStoryDataProvided': 'لم يتم توفير بيانات القصة.',
    'missingWholesalerId': 'معرف تاجر الجملة مفقود.',
    'missingProductId': 'معرف المنتج مفقود.',
    'missingCategorySlug': 'سبيكة فئة مفقودة.',
    'missingDealId': 'معرف الصفقة مفقود.',
    'missingOrderId': 'معرف الطلب مفقود.',
    'featuredProducts': 'المنتجات المميزة',
    // ============================================
    // Order Update / Quantity Change Result
    // ============================================
    'orderUpdate': 'تحديث الطلب',
    'viewMyOrders': 'عرض طلباتي',
    'goToHome': 'اذهب إلى الصفحة الرئيسية',
    'quantityChangeAccepted': 'قبول تغيير الكمية',
    'quantityChangeDeclined': 'تم رفض تغيير الكمية',
    'somethingWentWrong': 'حدث خطأ ما',
    'orderUpdatedMessage': 'لقد تم تحديث طلبك.',
    'orderRevertedMessage': 'لقد تم إرجاع طلبك إلى الكمية السابقة.',
    'pleaseTryAgainLater': 'يرجى المحاولة مرة أخرى في وقت لاحق.',
    // ============================================
    // Deal Detail / Deal Errors
    // ============================================
    'unableToLoadDeal': 'غير قادر على تحميل الصفقة',
    'regularPrice': 'السعر العادي',
    'stockLabel': 'مخزون',
    'dealNotStarted': 'هذه الصفقة لم تبدأ بعد',
    'adminWholesalerManageHint': 'باعتبارك مسؤولًا أو تاجر جملة، يمكنك إدارة هذه الصفقة ولكن لا يمكنك تقديم طلبات. استخدم زر القائمة (⋮) في شريط التطبيق لتعديل هذه الصفقة أو إغلاقها.',
    'adminDealOnlyOwnerCanBid': 'يمكن فقط للمسؤول (مالك الصفقة) إضافة عروض الأسعار على الصفقات الإدارية. لا يمكن لمستخدمي Kiosk تقديم طلبات على هذه الصفقة.',
    'kioskOnlyPlaceOrders': 'يمكن فقط لحسابات Kiosk/Shop تقديم طلبات على هذه الصفقة.',
    'managementView': 'عرض الإدارة',
    'ordering': 'الطلب',
    'failedToLoadDealData': 'فشل في تحميل بيانات الصفقة',
    'dealClosedSuccess': 'تم إغلاق الصفقة بنجاح',
    'failedToCloseDeal': 'فشل في إغلاق الصفقة',
    'onlyAdminCanAddBidsOnAdminDeals': 'يمكن فقط للمسؤول (مالك الصفقة) إضافة عروض الأسعار على الصفقات الإدارية.',
    // ============================================
    // Product Search / Detail
    // ============================================
    'searchProducts': 'البحث عن المنتجات',
    'youCanOnlyReviewFromDeliveredOrders': 'يمكنك فقط مراجعة المنتجات من الطلبات التي تم تسليمها',
    'allImages': 'جميع الصور',
    'contentGeneratedSuccessfully': 'تم إنشاء المحتوى بنجاح! تحقق من الفئة والحقول الأخرى.',
    'generationFailed': 'فشل الجيل',
    'userIdRequired': 'معرف المستخدم مطلوب',
    // ============================================
    // Admin Banner Management
    // ============================================
    'adminBannerManagement': 'إدارة راية المشرف',
    'requests': 'الطلبات',
    'active': 'نشيط',
    'noBannersFoundShort': 'لم يتم العثور على لافتات.',
    'failedToUpdateBanner': 'فشل تحديث الشعار',
    'bannerSubmittedSuccessfully': 'تم إرسال البانر بنجاح',
    'failedToCreateBanner': 'فشل في إنشاء الشعار',
    'failedToSubmitBannerRequest': 'فشل إرسال طلب البانر',
    // ============================================
    // User Management / Admin
    // ============================================
    'administratorsOnlySection': 'هذا القسم متاح فقط للمسؤولين',
    'allRoles': 'جميع الأدوار',
    'allStatuses': 'جميع الحالات',
    'suspended': 'معلق',
    'noUsersFound': 'لم يتم العثور على مستخدمين',
    'pageOf': 'صفحة',
    'ofLabel': 'ل',
    'noDocumentsAvailable': 'لا توجد وثائق متاحة',
    'userUpdatedSuccessfully': 'تم تحديث المستخدم بنجاح',
    'userCreatedSuccessfully': 'تم إنشاء المستخدم بنجاح',
    'userDeletedSuccessfully': 'تم حذف المستخدم بنجاح',
    'deleteUser': 'حذف المستخدم',
    'deleteUserConfirm': 'هل أنت متأكد أنك تريد حذف {name}؟ لا يمكن التراجع عن هذا الإجراء.',
    'verificationDocuments': 'وثائق التحقق',
    'noVerificationDocumentsYet': 'لم يتم تحميل مستندات التحقق حتى الآن.',
    'rejectionReason': 'سبب الرفض:',
    'createUser': 'إنشاء مستخدم',
    'editUser': 'تحرير المستخدم',
    'updateUser': 'تحديث المستخدم',
    'roleRequired': 'الدور مطلوب',
    'statusRequired': 'الحالة مطلوبة',
    'newPasswordLeaveEmpty': 'كلمة المرور الجديدة (اتركها فارغة لتبقى محدثة)',
    'passwordRequired': 'كلمة المرور مطلوبة',
    'passwordMinLength': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    'needInfo': 'بحاجة إلى معلومات',
    'business': 'عمل',
    'searchByNameEmailPhone': 'البحث بالاسم والبريد الإلكتروني والهاتف ...',
    'daysAgo': 'منذ يوم (أيام).',
    'activeDaysLast14': 'الأيام النشطة (آخر 14)',
    'docsCount': '{count} المستند (المستندات)',
    'noPassportDocuments': 'لا توجد وثائق جواز السفر',
    'noGewerbescheinDocuments': 'لا توجد وثائق Gewerbeschein',
    'noBusinessLicenseDocuments': 'لا توجد وثائق رخصة تجارية',
    'documentN': 'المستند {n}',
    'openInBrowser': 'فتح في المتصفح',
    'pdfDocument': 'وثيقة PDF',
    'kiosk': 'كشك',
    // ============================================
    // Order Management (Deal Orders)
    // ============================================
    'errorLoadingOrders': 'حدث خطأ أثناء تحميل الطلبات',
    'errorLoadingDeals': 'حدث خطأ أثناء تحميل الصفقات',
    'orderManagement': 'إدارة الطلبات',
    'orderCountSuffix': 'طلب',
    'confirmOrder': 'تأكيد الطلب',
    'confirmOrderMessage': 'هل أنت متأكد أنك تريد تأكيد هذا الطلب؟',
    'confirm': 'يتأكد',
    'markAsDelivered': 'وضع علامة "تم التسليم".',
    'markDelivered': 'تم تسليم العلامة',
    'cancelOrder': 'إلغاء الطلب',
    'cancelOrderConfirm': 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟',
    'no': 'لا',
    'reduceQuantity': 'تقليل الكمية',
    'orderConfirmedSuccess': 'تم تأكيد الطلب بنجاح',
    'orderMarkedDelivered': 'تم وضع علامة على الطلب بأنه تم التسليم',
    'failedToConfirmOrder': 'فشل في تأكيد الطلب',
    'failedToMarkDelivered': 'تعذّر وضع علامة "تم التسليم".',
    'orderCancelled': 'تم إلغاء الطلب',
    'failedToCancelOrder': 'فشل في إلغاء الطلب',
    'orderMarkedPaid': 'تم وضع علامة على الطلب على أنه مدفوع',
    'failedToMarkOrderPaid': 'فشل في وضع علامة على الطلب على أنه مدفوع',
    'quantityUpdatedSuccess': 'تم تحديث الكمية بنجاح',
    'failedToUpdateQuantity': 'فشل تحديث الكمية',
    'deliveryNotesOptional': 'ملاحظات التسليم (اختياري)',
    'newQuantity': 'كمية جديدة',
    'reduceQuantityHint': 'أدخل الكمية الجديدة. الحد الأدنى هو 1 (أو الحد الأدنى لكمية الطلب الخاصة بالصفقة). استخدم 0 لإلغاء هذا الطلب.',
    'quantityUpdatedTo': 'تم تحديث الكمية إلى',
    // ============================================
    // Deal Order Form
    // ============================================
    'enterQuantity': 'أدخل الكمية',
    'pleaseEnterQuantity': 'الرجاء إدخال الكمية',
    'invalidQuantity': 'كمية غير صالحة',
    'minimumOrderIs': 'الحد الأدنى للطلب هو',
    'maximumOrderIs': 'الحد الأقصى للطلب هو',
    'addSpecialInstructions': 'أضف أية تعليمات خاصة...',
    'minQuantityLabel': 'دقيقة',
    'selectedLabel': 'مختارة',
    'maxQuantityLabel': 'الأعلى',
    // ============================================
    // Shipment / Carrier
    // ============================================
    'pleaseSelectCarrier': 'الرجاء تحديد الناقل',
    'pleaseEnterCarrierNameForOther': 'الرجاء إدخال اسم الناقل لـ "أخرى"',
    'shipmentCreatedSuccess': 'تم إنشاء الشحنة بنجاح',
    'shipmentCreatedAndOrderShipped': 'تم إنشاء الشحنة ووضع علامة على الطلب على أنه تم شحنه',
    'failedToCreateShipment': 'فشل في إنشاء الشحنة',
    // ============================================
    // Stories
    // ============================================
    'failedToPickMedia': 'فشل في اختيار الوسائط',
    'onlyWholesalersCanCreateStories': 'يمكن لتجار الجملة فقط إنشاء القصص',
    'storyCreatedSuccess': 'تم إنشاء القصة بنجاح! 🎉',
    'failedToCreateStory': 'فشل في إنشاء القصة',
    // ============================================
    // Payment
    // ============================================
    'paymentCompletedSuccess': 'اكتمل الدفع بنجاح!',
    'paymentFailed': 'فشل الدفع',
    // ============================================
    // Notifications
    // ============================================
    'notifications': 'إشعارات',
    'markAllAsRead': 'وضع علامة على الكل كمقروءة',
    'deleteAll': 'احذف الكل',
    'filterNotifications': 'تصفية الإخطارات',
    'unread': 'غير مقروءة',
    'read': 'يقرأ',
    'deleteAllNotificationsConfirm': 'هل تريد حذف جميع الإشعارات؟',
    'deleteAllNotificationsMessage': 'هل أنت متأكد أنك تريد حذف كافة الإخطارات؟ لا يمكن التراجع عن هذا الإجراء.',
    // ============================================
    // Deal / Product Modals
    // ============================================
    'paymentEmailTemplateGenerated': 'تم إنشاء قالب البريد الإلكتروني للدفع',
    'aiGenerationFailed': 'فشل جيل الذكاء الاصطناعي',
    'dealUpdatedSuccess': 'تم تحديث الصفقة بنجاح',
    'allowOnlinePayment': 'السماح بالدفع عبر الإنترنت',
    'allowOnlinePaymentSubtitle': 'إذا لم يتم تحديده، فيمكن للعملاء تقديم الطلب فقط؛ يتم طلب الدفع (مثل التحويل البنكي) بعد تأكيد الطلب.',
    'paymentAndEmail': 'الدفع والبريد الإلكتروني',
    'generating': 'جارٍ الإنشاء…',
    'enterDealDescriptionPrompt': 'أدخل وصفًا واضحًا لصفقتك لإنشاء المحتوى تلقائيًا.',
    'dealDescriptionHint': 'على سبيل المثال، تخفيضات سريعة: خصم 50% على جميع السترات الشتوية',
    'enterProductDescriptionPrompt': 'أدخل وصفًا أو تفاصيل المنتج لإنشاء المحتوى تلقائيًا.',
    'productDescriptionHint': 'على سبيل المثال، كرسي مكتب من الجلد الفاخر ذو تصميم مريح...',
    'optionalAutoAssigned': 'اختياري - سيتم تعيينه تلقائيًا إذا كان فارغًا',
    'defaultYourAccount': 'الافتراضي: حسابك (انقر للتغيير)',
    'currentUserYou': 'المستخدم الحالي (أنت)',
    'loadingProductDetails': 'جارٍ تحميل تفاصيل المنتج...',
    'loading': 'تحميل...',
    'ibanBankAccount': 'رقم الحساب المصرفي الدولي / الحساب البنكي',
    'accountOwner': 'صاحب الحساب',
    'referenceTemplate': 'النموذج المرجعي (على سبيل المثال DEAL-{dealCode}-{buyerId})',
    'paymentInstructions': 'تعليمات الدفع (نص مجاني)',
    'paymentEmailSubject': 'موضوع البريد الإلكتروني للدفع',
    'paymentEmailBody': 'نص البريد الإلكتروني للدفع (استخدم {dealTitle}، {amount}، {iban}، {reference}، {accountOwner})',
    'ended': 'انتهى',
    'dealEnded': 'انتهت الصفقة',
    'dealHasEnded': 'انتهت الصفقة',
    'endingSoon': 'تنتهي قريبا!',
    'endsIn1Day': 'ينتهي في 1 يوم',
    'endsInDays': 'ينتهي خلال {n} من الأيام',
    'endsIn1Hour': 'ينتهي في 1 ساعة',
    'endsInHours': 'ينتهي خلال {n} ساعة',
    'endsSoon': 'Ends soon',
    'categories': 'فئات',
    'itemsCount': '{n} العناصر',
    // ============================================
    // Shipment Tracking
    // ============================================
    'pleaseEnterTrackingNumber': 'الرجاء إدخال رقم التتبع',
    'pleaseSelectAtLeastOneItemToShip': 'الرجاء تحديد عنصر واحد على الأقل لشحنه',
    'pleaseEnterTrackingUrlForOther': 'الرجاء إدخال عنوان URL للتتبع الخاص بشركة النقل "الأخرى".',
    'selectItemsToShip': 'حدد العناصر المراد شحنها',
    'noItemsAvailableForShipment': 'لا توجد عناصر متاحة للشحن',
    'selectCarrier': 'حدد الناقل',
    'selectCarrierHint': 'اختر الناقل...',
    'carrierName': 'اسم الناقل',
    'enterCarrierName': 'أدخل اسم الناقل',
    'trackingNumberRequired': 'رقم التتبع مطلوب',
    'enterTrackingNumber': 'أدخل رقم التتبع',
    'trackingUrlAutoGenerated': 'سيتم إنشاء عنوان URL للتتبع تلقائيًا',
    'trackingUrlRequiredForOther': 'عنوان URL للتتبع مطلوب لمشغل شبكة الجوّال "الآخر".',
    'pleaseEnterValidUrl': 'الرجاء إدخال عنوان URL صالح',
    'estimatedDeliveryDate': 'تاريخ التسليم المتوقع',
    'selectDate': 'اختر التاريخ',
    'internalNotesShipment': 'ملاحظات داخلية حول هذه الشحنة',
    'trackingUrlHintAuto': 'يتم إنشاؤه تلقائيًا عند توفير رقم الناقل ورقم التتبع',
    'trackShipment': 'تتبع الشحنة',
    'trackShipmentHint': 'تتبع شحنتك باستخدام رقم التتبع المقدم',
    'trackingDetails': 'تفاصيل التتبع',
    'shipmentNotFound': 'لم يتم العثور على الشحنة',
    'pleaseCheckTrackingNumber': 'يرجى التحقق من رقم التتبع الخاص بك والمحاولة مرة أخرى',
    'noNotifications': 'لا الإخطارات',
    'youreAllCaughtUp': 'أنتم جميعا قد انتهيتم!',
    // ============================================
    // Select Deal / Category
    // ============================================

    // Feature audit – previously hardcoded strings
    'platformMobile': 'الجوال',
    'platformWeb': 'الويب',
    'pleaseWait': 'يرجى الانتظار...',
    'defaultVariant': 'افتراضي',
    'trackOnCarrierWebsite': 'تتبع على موقع شركة الشحن',
    'minOrderQtyRequired': 'الحد الأدنى للطلب *',
    'dealPriceRequired': 'سعر الصفقة *',
    'targetQuantityRequired': 'الكمية المستهدفة *',
    'baseShippingCostEur': 'تكلفة الشحن الأساسية (€)',
    'freeShippingThresholdQuantity': 'الشحن المجاني بعد الكمية',
    'perUnitShippingCostEur': 'تكلفة الشحن للوحدة (€)',
    'descriptionOptional': 'الوصف (اختياري)',
    'enterBannerDescription': 'أدخل وصف البانر',
    'bannerType': 'نوع البانر',
    'targetUrl': 'الرابط المستهدف',
    'skuRequired': 'رمز المنتج *',
    'productToPromoteHint': 'المنتج للترويج',
    'selectDealToPromote': 'اختر صفقة للترويج',
    'titleOptional': 'العنوان (اختياري)',
    'giveReviewTitle': 'أعطِ تقييمك عنواناً',
    'yourReviewOptional': 'تقييمك (اختياري)',
    'shareExperienceWithProduct': 'شارك تجربتك مع هذا المنتج',
    'dealUpdatedSuccessfully': 'تم تحديث الصفقة بنجاح',
    'dealPriceMustBeValidNumber': 'سعر الصفقة يجب أن يكون رقماً صالحاً',
    'pleaseEnterMinOrderQuantity': 'يرجى إدخال الحد الأدنى للطلب',
    'paymentEmailPlaceholdersSubject':
        'المتغيرات: {dealTitle}, {amount}, {reference}',
    'paymentEmailPlaceholdersBody':
        'المتغيرات: {dealTitle}, {amount}, {accountOwner}, {iban}, '
        '{reference}, {additionalInstructions}',
    'failed': 'فشل',

    // ============================================
    // Order status (product orders – display only)
    // ============================================
    'orderStatusPendingConfirmation': 'في انتظار التأكيد',
    'orderStatusConfirmed': 'مؤكد',
    'orderStatusPacking': 'قيد التعبئة',
    'orderStatusDispatched': 'تم الشحن',
    'orderStatusOutForDelivery': 'في الطريق للتسليم',
    'orderStatusDelivered': 'تم التسليم',
    'orderStatusCancelled': 'ملغى',
    'orderStatusReturned': 'مرتجع',
    'orderStatusRefunded': 'مسترد',

    // ============================================
    // Notifications (backend localization keys)
    // ============================================
    'notificationProductApprovalNeededTitle': 'منتج جديد بانتظار الموافقة',
    'notificationProductApprovalNeededBody': '{0} أنشأ منتجًا جديدًا: {1}',
    'notificationProductStatusUpdatedTitle': 'تم تحديث حالة المنتج',
    'notificationProductApprovedBody': 'تمت الموافقة على منتجك "{0}"!',
    'notificationProductRejectedBody': 'تم رفض منتجك "{0}".',
    'notificationProductPendingBody': 'منتجك "{0}" بانتظار الموافقة.',
    'notificationProductStatusChangedBody': 'تم تغيير حالة منتجك "{0}" إلى {1}',
    'notificationNewProductOrderTitle': 'طلب جديد على منتجاتك',
    'notificationNewProductOrderBody': '{0} قدم طلبًا لعدد {1} وحدة من {2}',
    'notificationNewDealOrderTitle': 'طلب جديد على صفقتك',
    'notificationNewDealOrderBody': '{0} قدم طلبًا لعدد {1} وحدة',
    'notificationPaymentReportedTitle': 'المشتري أبلغ عن الدفع',
    'notificationPaymentReportedBody': '{0} أبلغ عن الدفع للطلب. التفاصيل: {1}',
    'notificationDealPaymentReportedBody': '{0} أبلغ عن الدفع لطلب الصفقة. التفاصيل: {1}',
    'notificationDealOrderStatusUpdatedTitle': 'تم تحديث حالة طلب الصفقة',
    'notificationDealOrderConfirmedBody': 'تم تأكيد طلبك على "{0}"!',
    'notificationDealOrderShippedBody': 'تم شحن طلبك على "{0}"!',
    'notificationDealOrderDeliveredBody': 'تم تسليم طلبك على "{0}"!',
    'notificationDealOrderCancelledBody': 'تم إلغاء طلبك على "{0}".',
    'notificationDealOrderRefundedBody': 'تم رد قيمة طلبك على "{0}".',
    'notificationDealOrderPendingBody': 'طلبك على "{0}" بانتظار التأكيد.',
    'notificationDealOrderStatusChangedBody': 'تم تغيير حالة طلبك على "{0}" إلى {1}',
    'notificationOrderQuantityUpdatedTitle': 'تم تحديث كمية الطلب',
    'notificationDealOrderQuantityCancelledBody': 'تم إلغاء طلبك على "{0}" (كان {1} وحدة) بواسطة البائع.',
    'notificationDealOrderQuantityChangedBody': 'تم تحديث طلبك على "{0}": تم تغيير الكمية من {1} إلى {2} وحدة بواسطة البائع.',
    'notificationQuantityChangeDeclinedTitle': 'تم رفض تغيير الكمية',
    'notificationQuantityChangeDeclinedBody': '{0} رفض تغيير الكمية. تم إرجاع الطلب من {1} إلى {2} وحدة.',
    'notificationDealNowLiveTitle': 'صفقة جديدة أصبحت متاحة',
    'notificationDealNowLiveBody': '"{0}" أصبحت متاحة الآن. قدّم طلبك قبل انتهاء الصفقة.',
    'notificationDealTarget70PercentTitle': 'الصفقة قاربت على الاكتمال',
    'notificationDealTarget70PercentBody': '"{0}" ممتلئة بنسبة {1}%! انضم إلى تجار التجزئة الآخرين وساعد صاحب الصفقة على تحقيق الهدف — فهذا يقوّي العلاقة ويُظهر التزامك بالشراكة.',
    'notificationDealEnding24hTitle': 'الصفقة ستنتهي قريبًا',
    'notificationDealEnding24hBody': 'آخر 24 ساعة! "{0}" — بقي {1} طلب فقط لإغلاق هذه الصفقة.',
    'notificationDealEnding7dTitle': 'الصفقة تنتهي خلال 7 أيام',
    'notificationDealEnding7dBody': '"{0}" — بقي {1} طلب فقط لإغلاق هذه الصفقة.',
    'notificationDealSuccessTitle': 'تم إكمال الصفقة بنجاح',
    'notificationDealSuccessBody': 'صفقتك الجماعية "{0}" وصلت إلى الكمية المطلوبة وأصبحت مؤكدة. يرجى الاستعداد للدفع والشحن وفقًا لتعليمات الموزّع.',
    'notificationDealClosedTitle': 'تم إغلاق الصفقة',
    'notificationDealClosedBody': 'تم إغلاق الصفقة "{0}". لن تظهر بعد الآن ضمن الصفقات النشطة.',
    'deal_closed_title': 'تم إغلاق الصفقة!',
    'deal_closed_body':
        'تم إغلاق الصفقة "{0}" رسميًا. شكرًا لمشاركتك!',
    'notificationOrderStatusUpdatedTitle': 'تم تحديث حالة الطلب',
    'notificationOrderConfirmedBody': 'تم تأكيد طلبك لـ "{0}"!',
    'notificationOrderDispatchedBody': 'تم إرسال طلبك لـ "{0}"!',
    'notificationOrderDeliveredBody': 'تم تسليم طلبك لـ "{0}"!',
    'notificationOrderCancelledBody': 'تم إلغاء طلبك لـ "{0}".',
    'notificationOrderPackingBody': 'يتم تجهيز طلبك لـ "{0}"!',
    'notificationOrderOutForDeliveryBody': 'طلبك لـ "{0}" في الطريق للتسليم!',
    'notificationOrderReturnedBody': 'تم إرجاع طلبك لـ "{0}".',
    'notificationOrderRefundedBody': 'تم رد قيمة طلبك لـ "{0}".',
    'notificationOrderStatusChangedBody': 'تم تغيير حالة طلبك لـ "{0}" إلى {1}',
    'notificationOrderItemRemovedBody': 'تمت إزالة عنصر طلبك "{0}" (كان {1} وحدة) بواسطة البائع.',
    'notificationOrderItemQuantityChangedBody': 'تم تحديث عنصر طلبك "{0}": تم تغيير الكمية من {1} إلى {2} وحدة بواسطة البائع.',
    'notificationProductQuantityChangeDeclinedBody': '{0} رفض تغيير الكمية في عنصر الطلب. تم الإرجاع من {1} إلى {2} وحدة.',
    'notificationDailyEngagementTitle': 'اطّلع على عروض اليوم!',
    'notificationDailyEngagementBody': 'اليوم: {0} بانر، {1} صفقات، {2} منتجات مميزة. افتح التطبيق لمشاهدة العروض.',
    'notificationInactiveMembersAlertTitle': 'تنبيه الأعضاء غير النشطين',
    'notificationInactiveMembersAlertBody': '{0} متجرًا لم يقم بطلب خلال {1} يومًا. فكّر في التواصل أو المراجعة.',
    'notificationBulkImportCompletedTitle': 'اكتمل الاستيراد الجماعي',
    'notificationBulkImportCompletedBody': 'تم استيراد {0} منتجًا بنجاح. تم تخطي {1}.',
    'notificationBannerApprovalNeededTitle': 'بانر جديد بانتظار الموافقة',
    'notificationBannerApprovalNeededBody': '{0} طلب الموافقة على البانر: {1}',
    'notificationNewUserRegistrationTitle': 'تسجيل مستخدم جديد',
    'notificationNewUserRegistrationBody': '{0} ({1}) سجل كـ {2}. بانتظار الموافقة.',
    'notificationBannerStatusChangedTitle': 'تغيرت حالة البانر',
    'notificationBannerApprovedBody': 'تمت الموافقة على بانرك "{0}" وهو نشط الآن!',
    'notificationBannerRejectedBody': 'تم رفض بانرك "{0}". يرجى المراجعة وإعادة الإرسال عند الحاجة.',
    'notificationBannerDeactivatedBody': 'تم إلغاء تنشيط بانرك "{0}".',
    'notificationBannerStatusChangedBody': 'تم تغيير حالة بانرك "{0}" إلى {1}',
    'notificationAdminCustomTitle': '{0}',
    'notificationAdminCustomBody': '{0}',
    'kioskShopRole': 'كشك / متجر',
  };
}