class GermanFile {
  static const Map<String, String> germanTranslations = {
    // ============================================
    // Options Screen Related
    // ============================================
    'options': 'Optionen',
    'account': 'Konto',
    'myOrders': 'Meine Bestellungen',
    'myOrdersSubtitle': 'Sehen und verfolgen Sie Ihre Bestellungen',
    'statistics': 'Statistiken',
    'statisticsSubtitle': 'Sehen Sie sich Ihre Statistiken zur Deal-Teilnahme an',
    'profile': 'Profil',
    'profileSubtitle': 'Verwalten Sie Ihr Konto',
    'management': 'Management',
    'manageCategories': 'Kategorien verwalten',
    'manageCategoriesSubtitle': 'Erstellen und verwalten Sie Produktkategorien',
    'createNewProductSubtitle': 'Erstellen Sie ein neues Produkt',
    'createNewDealSubtitle': 'Erstellen Sie einen neuen Deal',
    'viewOrdersSubtitle': 'Bestellungen einsehen und verwalten',
    'inactiveMembersViewSubtitle': 'Shops anzeigen, für die keine aktuellen Bestellungen vorliegen',
    'manageBannersSubtitle': 'App-Banner verwalten (Administrator)',
    'myBannersSubtitle': 'Verwalten Sie Ihre Banner',
    'unableToLoadOptions': 'Optionen können nicht geladen werden',
    'loggingOut': 'Abmelden...',
    'manageUsers': 'Benutzer verwalten',
    'manageUsersSubtitle': 'Benutzerkonten anzeigen und verwalten',
    'analytics': 'Analytik',
    'analyticsSubtitle': 'Sehen Sie sich Ihre Geschäftsanalysen an',
    'information': 'Information',
    'faq': 'FAQ',
    'faqSubtitle': 'Häufig gestellte Fragen',
    'aboutUs': 'Über uns',
    'aboutUsSubtitle': 'Erfahren Sie mehr über unsere Plattform',
    'helpSupport': 'Hilfe und Support',
    'helpSupportSubtitle': 'Holen Sie sich Hilfe und kontaktieren Sie den Support',
    'accountActions': 'Kontoaktionen',
    'deleteAccount': 'Konto löschen',
    'deleteAccountSubtitle': 'Fordern Sie die endgültige Löschung Ihres Kontos an',
    'logout': 'Abmelden',
    'logoutSubtitle': 'Melden Sie sich von Ihrem Konto ab',
    'confirmLogout': 'Bestätigen Sie die Abmeldung',
    'confirmLogoutMessage': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    'cancel': 'Stornieren',
    'loginAgain': 'Melden Sie sich erneut an',
    // ============================================
    // Language Related
    // ============================================
    'language': 'Sprache',
    'languageSubtitle': 'App-Sprache ändern',
    'notificationSettings': 'Benachrichtigungseinstellungen',
    'notificationSettingsSubtitle':
        'Wählen Sie, welche Benachrichtigungen Sie erhalten möchten.',
    'notificationChannels': 'Kanäle',
    'pushNotifications': 'Push-Benachrichtigungen',
    'pushNotificationsSubtitle':
        'Push-Benachrichtigungen auf Ihrem Gerät erhalten',
    'emailNotifications': 'E-Mail-Benachrichtigungen',
    'emailNotificationsSubtitle': 'Benachrichtigungen per E-Mail erhalten',
    'notificationModules': 'Nach Kategorie',
    'notificationSettingsSaved': 'Benachrichtigungseinstellungen gespeichert',
    'notificationModuleProducts': 'Produkte',
    'notificationModuleProductOrders': 'Produktbestellungen',
    'notificationModuleDeals': 'Deals',
    'notificationModuleDealOrders': 'Deal-Bestellungen',
    'notificationModuleBanners': 'Banner',
    'notificationModuleAdmin': 'Admin',
    'notificationModuleEngagement': 'Engagement',
    'notificationModulePayment': 'Zahlung',
    'push': 'Push',
    'currency': 'Währung',
    'currencySubtitle': 'Währung für Preise anzeigen (Standard: Gerät)',
    'systemDefault': 'Systemstandard',
    'syncFxRates': 'FX-Kurse synchronisieren',
    'syncFxRatesSubtitle': 'Holen Sie sich die neuesten Wechselkurse von der EZB',
    'syncFxRatesSuccess': 'Wechselkurse erfolgreich aktualisiert',
    'syncFxRatesFailed': 'Wechselkurse konnten nicht aktualisiert werden. Verwendung zwischengespeicherter Tarife.',
    'changingLanguage': 'Sprache ändern...',
    'languageChangeFailed': 'Spracheinstellung konnte nicht synchronisiert werden. Bitte versuchen Sie es erneut.',
    'failedToChangeLanguage': 'Die Sprache konnte nicht geändert werden. Bitte versuchen Sie es erneut.',
    'english': 'Englisch',
    'german': 'Deutsch',
    'turkish': 'Türkisch',
    'arabic': 'Arabisch',
    'urdu': 'Urdu',
    'hindi': 'Hindi',
    'russian': 'Russisch',
    'sourceLanguageLabel': 'Inhaltssprache',
    'sourceLanguageHint': 'Sprache des eingegebenen Textes (wird in andere Sprachen übersetzt)',
    'selectYourLanguage': 'Wählen Sie Ihre Sprache',
    'selectYourLanguageSubtitle':
        'Wählen Sie die Sprache der App. Sie können sie später in den Einstellungen ändern.',
    'continueButton': 'Weiter',
    // ============================================
    // Common / General
    // ============================================
    'sessionExpired': 'Sitzung abgelaufen',
    'sessionExpiredMessage': 'Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an, um die App weiterhin nutzen zu können.',
    'comingSoon': 'Kommt bald',
    'retry': 'Wiederholen',
    'error': 'Fehler',
    'errorWithDetail': 'Fehler: {detail}',
    'close': 'Schließen',
    'save': 'Speichern',
    'done': 'Erledigt',
    'saving': 'Sparen...',
    'update': 'Aktualisieren',
    'edit': 'Bearbeiten',
    'delete': 'Löschen',
    'add': 'Hinzufügen',
    'remove': 'Entfernen',
    'select': 'Wählen',
    'all': 'Alle',
    'filter': 'Filter',
    'type': 'Typ',
    'status': 'Status',
    'unknown': 'Unbekannt',
    // ============================================
    // About Us Related
    // ============================================
    'welcomeToProductDeal': 'Willkommen bei Product Deal',
    'trustedMarketplace': 'Ihr vertrauenswürdiger Marktplatz für Großhandelsprodukte und -angebote',
    'ourMission': 'Unsere Mission',
    'ourMissionContent': 'Um Groß- und Einzelhändler miteinander zu verbinden und den Großeinkauf für Unternehmen jeder Größe zugänglich und effizient zu machen.',
    'whatWeOffer': 'Was wir anbieten',
    'whatWeOfferContent':
        '• Zugang zu geprüften Großhändlern'
        '• Exklusive Mengenangebote und Rabatte'
        '• Bestandsverfolgung in Echtzeit'
        '• Sichere Auftragsverwaltung'
        '• Standortbasierte Produkterkennung',
    'forWholesalers': 'Für Großhändler',
    'forRetailers': 'Für Einzelhändler',
    'forRetailersContent': 'Entdecken Sie Produkte von Großhändlern in Ihrer Nähe, nehmen Sie an Großangeboten teil und verwalten Sie Ihre Bestellungen effizient.',
    'forWholesalersContent': 'Präsentieren Sie Ihre Produkte, erstellen Sie exklusive Angebote, verwalten Sie Bestellungen und erreichen Sie ein größeres Netzwerk von Einzelhändlern.',
    // ============================================
    // FAQ Related
    // ============================================
    'frequentlyAskedQuestions': 'Häufig gestellte Fragen',
    'commonQuestions': 'Häufige Fragen',
    'faqQuestion1': 'Wie gebe ich eine Bestellung auf?',
    'faqAnswer1': 'Durchsuchen Sie aktive Angebote oder Produkte, wählen Sie die benötigte Menge aus und klicken Sie auf „Bestellung aufgeben“. Ihre Bestellung wird vom Großhändler geprüft.',
    'faqQuestion2': 'Was sind Deal Orders?',
    'faqAnswer2': 'Deal-Orders sind Großkaufmöglichkeiten, bei denen Großhändler ermäßigte Preise anbieten, wenn eine Zielmenge erreicht ist. Sie können mehrere Bestellungen für dasselbe Angebot aufgeben.',
    'faqQuestion3': 'Wie wird der Versand abgewickelt?',
    'faqAnswer3': 'Die Versanddetails werden direkt mit dem Großhändler vereinbart, nachdem Ihre Bestellung bestätigt wurde. Die Kontaktinformationen werden Ihnen bei der Auftragsbestätigung mitgeteilt.',
    'faqQuestion4': 'Kann ich eine Bestellung stornieren?',
    'faqAnswer4': 'Sie können ausstehende Bestellungen stornieren. Sobald eine Bestellung vom Großhändler bestätigt wurde, gelten die Stornierungsbedingungen gemäß den Bedingungen des Großhändlers.',
    'faqQuestion5': 'Wie werde ich ein verifizierter Großhändler?',
    'faqAnswer5': 'Kontaktieren Sie unser Support-Team, um sich verifizieren zu lassen. Sie müssen Geschäftsdokumente vorlegen und den Verifizierungsprozess abschließen.',
    'faqQuestion6': 'Wie werden Produkte nach Entfernung sortiert?',
    'faqAnswer6': 'Die Produkte werden automatisch nach der Nähe zu Ihrem Standort sortiert. Stellen Sie sicher, dass Sie Ihren Standort in Ihrem Profil hinzufügen, um eine genaue, entfernungsbasierte Sortierung zu ermöglichen.',
    'faqQuestion7': 'Welche Zahlungsmethoden werden akzeptiert?',
    'faqAnswer7': 'Die Zahlungsmethoden variieren je nach Großhändler. Zahlungsdetails werden nach Auftragsbestätigung besprochen.',
    'faqQuestion8': 'Wie aktualisiere ich mein Profil?',
    'faqAnswer8': 'Gehen Sie im Dashboard zu Ihrer Profilseite, aktualisieren Sie Ihre Informationen und speichern Sie. Sie können mehrere Adressen für verschiedene Standorte hinzufügen.',
    // ============================================
    // Wholesaler Directory Related
    // ============================================
    'couldNotLoadWholesalers': 'Wir konnten derzeit keine Großhändler laden.',
    'verifiedPartners': 'verifizierte Partner',
    'verifiedPartnersDescription': 'verifizierte Partner',
    'noWholesalersNearYou': 'Noch kein Großhändler in Ihrer Nähe. Aktualisieren Sie Ihren Standort, um Inventar in der Nähe freizuschalten.',
    // ============================================
    // Dashboard Related
    // ============================================
    'dashboard': 'Armaturenbrett',
    'nearbyWholesalers': 'Großhändler in der Nähe',
    'allWholesalers': 'Alle Großhändler',
    'noWholesalersFound': 'Keine Großhändler gefunden',
    'errorLoadingWholesalers': 'Fehler beim Laden der Großhändler',
    'advertiseWithUs': 'Werben Sie bei uns',
    'boostYourSales': 'Steigern Sie Ihren Umsatz!',
    'promoteYourProducts': 'Bewerben Sie hier Ihre Produkte und erreichen Sie mehr Kunden.',
    'unableToLoadDashboard': 'Dashboard kann nicht geladen werden',
    'unableToLoadProduct': 'Produkt kann nicht geladen werden',
    'unableToLoadWholesaler': 'Der Großhändler konnte nicht geladen werden',
    'spotlight': 'Scheinwerfer',
    'spotlightWholesalersEmpty': 'Spotlight-Großhändler werden hier erscheinen, sobald der Markt in Aufruhr ist.',
    // ============================================
    // Orders Related
    // ============================================
    'orderId': 'Bestell-ID',
    'payment': 'Zahlung',
    'paymentStatus': 'Zahlungsstatus',
    'placedOn': 'Aufgelegt',
    'orderItems': 'Artikel bestellen',
    'createShipment': 'Sendung erstellen',
    'shippingAddress': 'Lieferadresse',
    'notes': 'Notizen',
    'orderNotes': 'Bestellhinweise',
    'orderDetails': 'Bestelldetails',
    'unableToLoadOrder': 'Bestellung kann nicht geladen werden',
    'updateOrderStatus': 'Bestellstatus aktualisieren',
    'subtotal': 'Zwischensumme',
    'shipping': 'Versand',
    'shippingWithFreeThreshold': 'Versand: {amount} (Kostenlos für {threshold}+ Einheiten)',
    'freeShippingForThreshold': 'Kostenloser Versand für {threshold}+ Einheiten',
    'shippingBaseOnly': 'Versand: {amount}',
    'shippingWithPerUnit': 'Versand: {base} + {perUnit} pro Einheit',
    'total': 'Gesamt',
    'reasonOptional': 'Grund (optional)',
    'notesOptional': 'Notizen (optional)',
    'sku': 'Artikelnummer',
    'skuN/A': 'Artikelnummer: N/A',
    'trackingAvailable': 'SENDUNGSVERFOLGUNG VERFÜGBAR',
    'shipped': 'Ausgeliefert',
    'shipments': 'Sendungen',
    'shipmentId': 'Sendung {id}',
    'trackingLabel': 'Tracking: {number}',
    'track': 'Schiene',
    'couldNotOpenTrackingUrl': 'Die Tracking-URL konnte nicht geöffnet werden',
    'carrierLabel': 'Träger: {name}',
    'estDelivery': 'Schätzung: Lieferung: {date}',
    'shippedAt': 'Versand: {date}',
    'deliveredAt': 'Geliefert: {date}',
    'each': 'jede',
    'unit': 'Einheit',
    'noOrdersYet': 'Noch keine Bestellungen',
    'noOrdersYetMessage': 'Durchsuchen Sie Produkte und Angebote, um Ihre erste Bestellung aufzugeben.',
    'unableToLoadOrders': 'Ihre Bestellungen können nicht geladen werden',
    'orderPlaced': 'Bestellung aufgegeben',
    'confirmed': 'Bestätigt',
    'delivered': 'Geliefert',
    'pendingOrders': 'Ausstehende Bestellungen',
    'viewOrders': 'Bestellungen anzeigen',
    'allOrders': 'Alle Bestellungen',
    'pendingConfirmation': 'Ausstehende Bestätigung',
    'packing': 'Verpackung',
    'packed': 'Verpackt',
    'dispatched': 'Versendet',
    'outForDelivery': 'Zur Auslieferung bereit',
    'viewDetails': 'Details anzeigen',
    'changeOrderStatus': 'Bestellstatus ändern',
    'orderStatusUpdatedSuccessfully': 'Bestellstatus erfolgreich aktualisiert',
    'orderStatusUpdated': 'Bestellstatus erfolgreich aktualisiert',
    'itemStatusUpdatedSuccessfully': 'Artikelstatus erfolgreich aktualisiert',
    'itemStatusUpdated': 'Artikelstatus erfolgreich aktualisiert',
    'ordersCountSuffix': 'Bestellungen',
    'order': 'Befehl',
    'orderLabel': 'Befehl',
    'orders': 'Bestellungen',
    'ordered': 'bestellt',
    'dealOrder': 'Deal-Reihenfolge',
    'productOrder': 'Produktbestellung',
    'bid': 'Gebot',
    'itemPlusMore': '{item} + {n} mehr',
    // ============================================
    // Cart Related
    // ============================================
    'yourCart': 'Ihr Warenkorb',
    'cart': 'Warenkorb',
    'emptyCart': 'Ihr Warenkorb ist leer',
    'emptyCartMessage': 'Fügen Sie Produkte zu Ihrem Warenkorb hinzu, um loszulegen.',
    'addProductsToSeeThemHere': 'Fügen Sie Produkte hinzu, um sie hier anzuzeigen.',
    'placeOrderCashOnDelivery': 'Bestellung aufgeben (Nachnahme)',
    'cashOnDelivery': 'Nachnahme',
    'paymentMethodCash': 'Bar',
    'paymentMethodCashDesc': 'Bezahlen Sie bei Erhalt der Lieferung.',
    'paymentMethodInvoice': 'Rechnung',
    'paymentMethodInvoiceDesc':
        'Wir senden Ihnen eine Rechnung; der Versand beginnt kurz nach Bestätigung.',
    'paymentMethodBankTransfer': 'Vorkasse',
    'paymentMethodBankTransferDesc':
        'Zuerst zahlen, dann Versand. Zahlungsanweisung per E-Mail.',
    'paymentMode': 'Zahlungsart',
    'paymentModeSubtitle':
        'Standard für Ihre Deals. Sie können dies später in Ihrem Profil ändern.',
    'paymentModeSubtitleMulti':
        'Wählen Sie alle Zahlungsarten, die Sie akzeptieren. '
        'Sie können dies später in Ihrem Profil ändern.',
    'paymentSettings': 'Zahlungseinstellungen',
    'paymentSettingsSubtitle':
        'Bankdaten für Rechnungs-/Überweisungsbestellungen. '
        'Sie können diese später in Ihrem Profil aktualisieren.',
    'payWithCard': 'Bezahlen Sie mit Karte',
    'placeOrderPayNow': 'Bestellung aufgeben und bezahlen',
    'paymentAfterOrderConfirmed': 'Die Zahlungsaufforderung erfolgt nach Bestätigung Ihrer Bestellung (z. B. Banküberweisung).',
    'paymentNotAvailable': 'Kartenzahlung ist nicht möglich. Versuchen Sie es mit Nachnahme.',
    'paymentCancelled': 'Die Zahlung wurde storniert.',
    'dealSucceededPayNow': 'Deal erfolgreich – jetzt bezahlen',
    'totalToPay': 'Gesamtbetrag zu zahlen',
    'payByInvoice': 'Bezahlen Sie per Rechnung',
    'payByCard': 'Bezahlen Sie mit Karte',
    'invoiceInstructionsSent': 'Zahlungsanweisungen wurden per E-Mail gesendet.',
    'paymentInstructionsBankOnly': 'Zahlungsanweisungen wurden per E-Mail gesendet. Bezahlen Sie per Banküberweisung. Wenn Sie bereits bezahlt haben, bestätigt der Deal-Inhaber den Eingang.',
    'markAsPaid': 'Als bezahlt markieren',
    'paymentNotesOptional': 'Zahlungsbelege (z. B. Bankreferenz)',
    'myDealStats': 'Meine Deal-Statistiken',
    'dealsJoined': 'Angebote beigetreten',
    'totalOrderedQuantity': 'Gesamtmenge bestellt',
    'totalOrders': 'Gesamtbestellungen',
    'placeOrder': 'Bestellung aufgeben',
    'fxDisclaimer': 'Der Wechselkurs kann sich ändern. Der angezeigte Betrag ist ein Richtwert.',
    'placingOrder': 'Bestellung aufgeben...',
    'orderPlacedSuccessfully': 'Bestellung erfolgreich aufgegeben!',
    'failedToPlaceOrder': 'Bestellung konnte nicht aufgegeben werden',
    'onlyKioskCanOrder': 'Nur Kiosk-/Shop-Konten können Bestellungen aufgeben.',
    'admins': 'Administratoren',
    'subAdmins': 'Unteradministratoren',
    'wholesalers': 'Großhändler',
    'canOnlyViewProducts': 'kann nur Produkte ansehen. Nur Kiosk-/Shop-Konten können Bestellungen aufgeben.',
    'addToCart': 'In den Warenkorb legen',
    'addedToCart': '✅ Zum Warenkorb hinzugefügt',
    'quantity': 'Menge',
    'unitPrice': 'Stückpreis',
    'totalAmount': 'Gesamtbetrag',
    'buyer': 'Käufer',
    'items': 'Artikel',
    // ============================================
    // Registration Related
    // ============================================
    'register': 'Registrieren',
    'createAccount': 'Benutzerkonto erstellen',
    'createAccountTitle': 'Benutzerkonto erstellen',
    'createAccountSubtitle': 'Schalten Sie kuratierte Großhändler, große Deals und Logistikunterstützung frei.',
    'fullName': 'Vollständiger Name',
    'email': 'E-Mail',
    'workEmail': 'Arbeits-E-Mail',
    'phone': 'Telefon',
    'password': 'Passwort',
    'confirmPassword': 'Passwort bestätigen',
    'confirmPasswordLabel': 'Passwort bestätigen',
    'businessName': 'Firmenname',
    'country': 'Land',
    'city': 'Stadt',
    'address': 'Adresse',
    'streetAddress': 'Straßenadresse',
    'addressWillBeGeocoded': 'Die Adresse wird automatisch geokodiert, um Koordinaten zu erhalten',
    'addressSearchHint': 'Adresse suchen',
    'placesLookupFailed':
        'Adressdetails konnten nicht vom Server geladen werden. Sie können Ihre '
        'Adresse manuell eingeben oder bearbeiten.',
    'placesNoAddressResults':
        'Keine Adressen gefunden. Versuchen Sie eine andere Suche.',
    'placesAddressSearchConfigError':
        'Adresssuche nicht verfügbar. Prüfen Sie Ihre Verbindung und ob die App '
        'den richtigen API-Server verwendet (API_BASE_URL).',
    'placesAddressSearchRequestFailed':
        'Adresssuche fehlgeschlagen. Prüfen Sie Ihre Verbindung oder versuchen '
        'Sie es später erneut.',
    'getLocation': 'Standort abrufen',
    'selectRole': 'Wählen Sie Rolle aus',
    'accountType': 'Kontotyp',
    'alreadyHaveAccount': 'Sie haben bereits ein Konto?',
    'login': 'Login',
    'signIn': 'Anmelden',
    'registrationReceived': 'Anmeldung erhalten! Wir benachrichtigen Sie, sobald das Konto genehmigt wurde.',
    'fullNameRequired': 'Der vollständige Name ist erforderlich',
    'fullNameMinLength': 'Der Name muss mindestens 3 Zeichen lang sein',
    'emailRequired': 'E-Mail ist erforderlich',
    'provideValidEmail': 'Geben Sie eine gültige E-Mail-Adresse an',
    'phoneNumberOptional': 'Telefonnummer (optional)',
    'enterValidPhoneNumber': 'Geben Sie eine gültige Telefonnummer ein',
    'kioskShopNameOptional': 'Kiosk-/Shopname (optional)',
    'companyName': 'Name der Firma',
    'latitudeOptional': 'Breitengrad (optional)',
    'longitudeOptional': 'Längengrad (optional)',
    'locating': 'Lokalisierung...',
    'locatingEllipsis': 'Lokalisieren…',
    'useCurrentLocation': 'Aktuellen Standort verwenden',
    'enableLocationServices': 'Aktivieren Sie Standortdienste, um Koordinaten automatisch auszufüllen.',
    'enableLocationPermissions': 'Aktivieren Sie Standortberechtigungen zum automatischen Ausfüllen von Koordinaten.',
    'unableToFetchLocation': 'Der Standort kann nicht abgerufen werden. Bitte versuchen Sie es erneut.',
    'unableToFetchLocationShort': 'Der Standort kann nicht abgerufen werden.',
    'pleaseEnterValidLatLng': 'Bitte geben Sie einen gültigen Breiten- und Längengrad ein.',
    'createPassword': 'Passwort erstellen',
    'minimum8CharactersRequired': 'Mindestens 8 Zeichen erforderlich',
    'weVerifyEveryBusiness': 'Wir überprüfen jedes Unternehmen manuell, um die Vertrauenswürdigkeit des Marktes zu gewährleisten.',
    'submitForReview': 'Zur Überprüfung einreichen',
    'alreadyVerifiedSignIn': 'Bereits verifiziert? anmelden',
    'forgotPassword': 'Passwort vergessen?',
    'welcomeBack': 'Willkommen zurück',
    'signInToReach': 'Melden Sie sich an, um zugelassene Großhändler in Ihrer Nähe zu erreichen.',
    'createKioskOrWholesalerAccount': 'Erstellen Sie ein Kiosk- oder Großhändlerkonto',
    'accountSubmittedForApproval': 'Konto zur Genehmigung eingereicht. Das Dashboard wird nach der Genehmigung entsperrt.',
    'dashboardWillUnlock': 'Das Dashboard wird nach der Genehmigung entsperrt.',
    'pleaseLoginToPlaceOrder': 'Bitte melden Sie sich an, um eine Bestellung aufzugeben',
    // ============================================
    // Legal / Compliance (T&C + GDPR)
    // ============================================
    'legalComplianceTitle': 'Recht und Compliance',
    'termsAndConditionsFullText': 'Mit der Erstellung eines Kontos gehen Sie eine Geschäftsbeziehung mit dem Plattformbetreiber ein und stimmen den Allgemeinen Geschäftsbedingungen (AGB) der Plattform zu. Diese Bedingungen regeln, wie Sie den Marktplatz nutzen dürfen, wie Geschäfte und Bestellungen abgewickelt werden und welche Pflichten für Käufer und Großhändler gelten. Sie bestätigen, dass alle von Ihnen bereitgestellten Informationen korrekt sind und dass Sie die Plattform nur für legitime Geschäftszwecke nutzen. Sie stimmen außerdem zu, dass Geschäfte und Bestellungen verbindlich werden können, sobald sie vom Großhändler bestätigt wurden oder ein Geschäftsziel erreicht wurde. Abhängig von Ihrer Gerichtsbarkeit können zusätzliche länderspezifische Vorschriften gelten. Bitte lesen Sie die vollständigen Allgemeinen Geschäftsbedingungen des Betreibers, bevor Sie fortfahren.',
    'scrollToAcceptTerms': 'Scrollen Sie zum Ende der Allgemeinen Geschäftsbedingungen, um das Kontrollkästchen „Akzeptanz“ zu entsperren.',
    'scrollToBottom': 'Scrollen Sie nach unten',
    'acceptTermsLabel': 'Ich habe die Allgemeinen Geschäftsbedingungen (AGB) gelesen und akzeptiere sie.',
    'termsScrollHint': 'Bitte scrollen Sie durch die Allgemeinen Geschäftsbedingungen, bevor Sie sie akzeptieren.',
    'acceptPrivacyLabel': 'Ich habe die Datenschutzerklärung/DSGVO gelesen und akzeptiere sie.',
    'privacySummaryText': 'Ihre Daten werden zur Kontoverwaltung, Bestellung, Analyse und Sicherheit gemäß unserer Datenschutzrichtlinie verarbeitet.',
    'mustAcceptAllLegalDocuments': 'Bitte akzeptieren Sie alle rechtlichen Dokumente und bestätigen Sie den Rahmenvertrag.',
    'mustAcceptTermsAndPrivacy': 'Bitte akzeptieren Sie die Allgemeinen Geschäftsbedingungen und den Datenschutz / DSGVO, um fortzufahren.',
    // ============================================
    // Account Approval / Waiting Screen Related
    // ============================================
    'accountApproval': 'Kontogenehmigung',
    'accountApproved': 'Konto genehmigt!',
    'redirecting': 'Weiterleitung...',
    'pendingReview': 'Ausstehende Überprüfung',
    'needMoreInfo': 'Benötigen Sie weitere Informationen',
    'wholesalerVerificationMessage': 'Danke! Um Ihr Großhändlerkonto zu aktivieren, reichen Sie bitte Ihre Unternehmensbestätigungsdokumente ein. Unser Administrator wird Ihr Konto überprüfen und genehmigen.',
    'buyerVerificationMessage': 'Danke! Um Ihr Käuferkonto zu aktivieren, reichen Sie bitte Ihre Identitätsnachweisdokumente ein. Unser Administrator wird Ihr Konto überprüfen und genehmigen.',
    'generalVerificationMessage': 'Danke! Um Ihr Konto zu aktivieren, reichen Sie bitte Verifizierungsdokumente ein. Unser Administrator wird Ihr Konto überprüfen und genehmigen.',
    'adminNote': 'Admin-Hinweis',
    'uploadVerificationDocument': 'Verifizierungsdokument hochladen',
    'acceptedDocumentTypes': 'Akzeptierte Dokumenttypen',
    'wholesalerDocumentTypes': 'Gewerbeschein, Steuer-ID, Firmenregistrierungsunterlagen (PNG, JPG, PDF)',
    'buyerDocumentTypes': 'Personalausweis, Führerschein oder ein anderer amtlicher Ausweis (PNG, JPG, PDF)',
    'generalDocumentTypes': 'Gewerbeschein, Führerschein, Personalausweis (PNG, JPG, PDF)',
    'selectedDocuments': 'Ausgewählte Dokumente',
    'addDocuments': 'Dokumente hinzufügen',
    'uploading': 'Hochladen...',
    'uploaded': 'Hochgeladen',
    'selectFirst': 'Wählen Sie „Zuerst“ aus',
    'documentsUploadedSuccessfully': 'Dokument(e) erfolgreich hochgeladen. Unser Administrator überprüft und aktualisiert Ihren Kontostatus.',
    'documentUploadedSuccessfully': 'Dokument erfolgreich hochgeladen. Unser Administrator überprüft und aktualisiert Ihren Kontostatus.',
    'failedToPickDocuments': 'Dokumente konnten nicht ausgewählt werden',
    'passport': 'Reisepass',
    'passportDescription': 'Laden Sie Ihren Reisepass zur Identitätsprüfung hoch',
    'passportAlternative': 'Wenn Sie keinen Reisepass haben, können Sie einen von der Regierung genehmigten Personalausweis mit Adresse hochladen (z. B. Aadhar in Indien, Personalausweis usw.).',
    'gewerbeschein': 'Gewerbeschein',
    'idCard': 'Ausweis',
    'taxId': 'Steuer-ID',
    'companyRegistration': 'Firmenregistrierung',
    'document': 'Dokumentieren',
    'gewerbescheinDescription': 'Laden Sie Ihren Gewerbeschein zur Gewerbebescheinigung hoch',
    'gewerbescheinAlternative': 'Laden Sie Ihren amtlichen Gewerbeschein hoch, der von den Behörden ausgestellt wurde',
    'businessLicense': 'Gewerbeschein / Gewerbeschein',
    'businessLicenseDescription': 'Laden Sie Ihren Gewerbeschein oder Gewerbeschein zur Gewerbebescheinigung hoch',
    'businessLicenseAlternative': 'Wenn Sie keinen Gewerbeschein besitzen, können Sie Unternehmensregistrierungsdokumente, Steuer-IDs oder andere offizielle Dokumente zur Unternehmensbestätigung hochladen',
    'selectDocument': 'Wählen Sie Dokument aus',
    'changeDocument': 'Dokument ändern',
    'pleaseSelectAtLeastOneDocument': 'Bitte wählen Sie mindestens ein Dokument zum Hochladen aus.',
    'sendByEmail': 'Per E-Mail senden',
    'emailOptionDescription': 'Alternativ können Sie Ihre Verifizierungsunterlagen auch direkt per E-Mail versenden. Unser Administrator überprüft die Dokumente und aktualisiert Ihren Kontostatus entsprechend.',
    'openEmailToAdmin': 'Öffnen Sie „E-Mail an Admin“.',
    'emailDraftOpened': 'E-Mail-Entwurf geöffnet. Bitte senden Sie es, um die Einreichung abzuschließen. Unser Administrator überprüft Ihre Dokumente und aktualisiert Ihren Kontostatus.',
    'couldNotOpenEmailApp': 'Die E-Mail-App konnte nicht geöffnet werden. Bitte senden Sie eine E-Mail an',
    'manually': 'manuell',
    'failedToOpenEmail': 'E-Mail konnte nicht geöffnet werden',
    'loadingAccountStatus': 'Kontostatus wird geladen...',
    'errorLoadingStatus': 'Fehler beim Laden des Status',
    'pleaseReviewAndResubmit': 'Bitte überprüfen Sie Ihre Unterlagen und reichen Sie sie erneut ein.',
    'useDifferentAccount': 'Anderes Konto verwenden',
    'useDifferentAccountConfirm':
        'Abmelden, um sich mit einem anderen Konto anzumelden oder zu registrieren?',
    'failedToUpdateStatus': 'Die rechtlichen Einstellungen konnten nicht aktualisiert werden. Bitte versuchen Sie es erneut.',
    // ============================================
    // Profile Related
    // ============================================
    'editProfile': 'Profil bearbeiten',
    'profileUpdated': 'Profil erfolgreich aktualisiert',
    'failedToUpdateProfile': 'Profil konnte nicht aktualisiert werden',
    'profileImageUpdated': 'Profilbild aktualisiert',
    'failedToUploadImage': 'Bild konnte nicht hochgeladen werden',
    'tagline': 'Slogan',
    'locations': 'Standorte',
    'addLocation': 'Standort hinzufügen',
    'editLocation': 'Standort bearbeiten',
    'deleteLocation': 'Standort löschen',
    'latitude': 'Breite',
    'longitude': 'Länge',
    'nameIsRequired': 'Name ist erforderlich',
    'businessNameOptional': 'Firmenname (optional)',
    'phoneOptional': 'Telefon (optional)',
    'addresses': 'Adressen',
    'addAddress': 'Adresse hinzufügen',
    'noAddressesAdded': 'Keine Adressen hinzugefügt',
    'addYourFirstAddress': 'Fügen Sie Ihre erste Adresse hinzu, um loszulegen',
    'editAddress': 'Adresse bearbeiten',
    'removeAddress': 'Adresse entfernen',
    'editAddressTitle': 'Adresse bearbeiten',
    'addAddressTitle': 'Adresse hinzufügen',
    'saveChanges': 'Änderungen speichern',
    'labelExample': 'Etikett (z. B. Zuhause, Büro, Hauptverkaufsstelle)',
    'streetAreaOptional': 'Straße/Bereich (optional)',
    'countryOptional': 'Land (optional)',
    'cityOptional': 'Stadt (optional)',
    'locationNotUpdating': 'Der Standort wird nicht aktualisiert',
    'locationNotUpdatingSolution': 'Gehen Sie zu Profil > Adressen und stellen Sie sicher, dass Ihre Standortkoordinaten korrekt sind',
    // ============================================
    // Deals Related
    // ============================================
    'deals': 'Angebote',
    'activeDeals': 'Aktive Angebote',
    'allDeals': 'Alle Angebote',
    'myDeals': 'Meine Angebote',
    'manageDeals': 'Angebote verwalten',
    'noDealsFound': 'Keine Angebote gefunden',
    'selectDeal': 'Wählen Sie Deal aus',
    'unableToLoadDeals': 'Angebote können nicht geladen werden',
    'noDealsAvailable': 'Keine Angebote verfügbar',
    'noDealsYet': 'Noch keine Angebote',
    'checkBackLaterForNewDeals': 'Schauen Sie später noch einmal vorbei, um neue Angebote zu erhalten',
    'noActiveDeals': 'Keine aktiven Angebote',
    'filterDeals': 'Angebote filtern',
    'progress': 'Fortschritt',
    'dealClosed': 'Deal abgeschlossen',
    'ends': 'Endet',
    'variant': 'Variante',
    'min': 'Min.:',
    'max': 'Maximal:',
    'perUnit': '/Einheit',
    'perUnitLabel': 'Pro {unit}',
    'inStock': 'auf Lager',
    'similarProducts': 'Ähnliche Produkte',
    'noActiveDealsForProduct': 'Keine aktiven Angebote für dieses Produkt',
    'activeDealsForProduct': 'Aktive Angebote für dieses Produkt',
    'moreFromWholesaler': 'Mehr von {name}',
    'dealsFromWholesaler': 'Angebote von {name}',
    'productsFromWholesaler': 'Produkte von {name}',
    'searchProductsFromWholesaler': 'Suchen Sie nach Produkten von {name}...',
    'onlyKioskCanPurchase': 'Nur Kiosk-/Shop-Konten können Produkte kaufen',
    'canOnlyReviewFromDelivered': 'Sie können nur Produkte aus gelieferten Bestellungen bewerten',
    'alreadyReviewedThisProduct': 'Sie haben dieses Produkt aus dieser Bestellung bereits bewertet',
    'selectOrderToReview': 'Wählen Sie „Bestellung zur Überprüfung“ aus',
    'orderN': 'Bestellung #{id}',
    'viewDeals': 'Angebote ansehen',
    'locationInfoNotAvailable': 'Standortinformationen nicht verfügbar',
    'location': 'Standort',
    'kfProductDealTagline': 'KF Product Deal, hilft Ihnen, die besten Angebote zu finden',
    'errorSearchingProducts': 'Fehler bei der Produktsuche',
    'myDealOrders': 'Meine Deal-Bestellungen',
    'noDealOrdersYet': 'Noch keine Deal-Bestellungen',
    'browseDealsPlaceFirstOrder': 'Durchsuchen Sie aktive Angebote und geben Sie Ihre erste Bestellung auf.',
    'statusLabel': 'Status',
    'noProductsFoundForWholesaler': 'Für den ausgewählten Großhändler wurden keine Produkte gefunden',
    'noApprovedWholesalersAvailable': 'Keine zugelassenen Großhändler verfügbar',
    'searchByNameBusinessEmail': 'Suche nach Name, Firmenname, E-Mail...',
    'selectWholesaler': 'Wählen Sie Großhändler',
    'selectProduct': 'Wählen Sie Produkt aus',
    'pageNOfM': 'Seite {current} von {total}',
    'priceLabel': 'Preis',
    'pleaseSelectImageOrVideo': 'Bitte wählen Sie ein Bild oder Video aus',
    'onlyWholesalersCreateStories': 'Nur Großhändler können Geschichten erstellen',
    'storyCreatedSuccessfully': 'Story erfolgreich erstellt! 🎉',
    'uploadingMedia': 'Medien werden hochgeladen...',
    'creatingStory': 'Geschichte erschaffen...',
    'storyMedia': 'Story-Medien',
    'videoSelected': 'Video ausgewählt',
    'activeShopsSuffix': 'Aktive Geschäfte',
    'storiesCountSuffix': 'Geschichten',
    'create': 'Erstellen',
    'off': 'AUS',
    'minOrder': 'Mindestbestellmenge',
    'target': 'Ziel',
    'units': 'Einheiten',
    'dealCreatedSuccessfully': 'Deal erfolgreich erstellt',
    'createDeal': 'Angebot erstellen',
    'editDeal': 'Angebot bearbeiten',
    'closeDeal': 'Schließen Sie den Deal ab',
    'closeDealConfirmMessage': 'Sind Sie sicher, dass Sie diesen Deal abschließen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'closeDealGoalReached': 'Ziel erreicht',
    'closeDealGoalReachedHint': 'Wenn aktiviert: Alle ausstehenden Bestellungen werden automatisch bestätigt (Geschäft erfolgreich ausgeführt). Wenn diese Option deaktiviert ist, wird das Geschäft abgeschlossen, Sie können Bestellungen jedoch später manuell bestätigen.',
    'createYourFirstDeal': 'Erstellen Sie Ihr erstes Angebot',
    'dealTitle': 'Deal-Titel',
    'pleaseEnterDealTitle': 'Bitte geben Sie den Dealtitel ein',
    'dealType': 'Deal-Typ',
    'dealPrice': 'Angebotspreis',
    'startDate': 'Startdatum',
    'endDate': 'Enddatum',
    'pleaseEnterDealPrice': 'Bitte geben Sie den Angebotspreis ein',
    'originalPrice': 'Originalpreis',
    'targetQuantity': 'Zielmenge',
    'pleaseEnterTargetQuantity': 'Bitte Zielmenge eingeben',
    'targetQuantityMin': 'Zielmenge muss mindestens 1 sein',
    'minOrderQty': 'Mindestbestellmenge',
    'pleaseEnterMinOrderQty': 'Bitte geben Sie die Mindestbestellmenge ein',
    'minOrderQtyMin': 'Die Mindestbestellmenge muss mindestens 1 betragen',
    'maxOrderQuantityOptional': 'Maximale Bestellmenge (optional)',
    'endDateMustBeAfterStartDate': 'Das Enddatum muss nach dem Startdatum liegen',
    'pleaseSelectWholesalerFirst': 'Bitte wählen Sie zunächst einen Großhändler aus',
    'auction': 'Auktion',
    'priceDrop': 'Preisverfall',
    'limitedStock': 'Begrenzter Bestand',
    'scheduled': 'Geplant',
    'live': 'Live',
    'highlightedDeal': 'Hervorgehobener Deal',
    'canOnlyViewDeals': 'kann nur Angebote ansehen. Nur Kiosk-/Shop-Konten können Bestellungen aufgeben.',
    'dealProgressNotUpdating': 'Der Deal-Fortschritt wird nicht aktualisiert',
    'dealProgressNotUpdatingSolution': 'Der Deal-Fortschritt wird automatisch aktualisiert. Wenn es hängen bleibt, aktualisieren Sie die Seite',
    'dealProgress': 'Deal-Fortschritt',
    'unableToLoadProgress': 'Fortschritt kann nicht geladen werden: {detail}',
    'noOrdersPlacedYet': 'Für diesen Deal liegen noch keine Bestellungen vor.',
    'orderPlacedSuffix': 'Bestellung aufgegeben',
    'ordersPlacedSuffix': 'Bestellungen aufgegeben',
    'closed': 'geschlossen',
    // ============================================
    // Products Related
    // ============================================
    'product': 'Produkt',
    'products': 'Produkte',
    'productsSection': 'Produkte',
    'allProducts': 'Alle Produkte',
    'myProducts': 'Meine Produkte',
    'noProductsAvailable': 'Keine Produkte verfügbar',
    'noProductsYet': 'Noch keine Produkte',
    'addYourFirstProduct': 'Fügen Sie Ihr erstes Produkt hinzu',
    'addFirstProduct': 'Fügen Sie Ihr erstes Produkt hinzu',
    'addProduct': 'Produkt hinzufügen',
    'editProduct': 'Produkt bearbeiten',
    'deleteProduct': 'Produkt löschen',
    'deletingProduct': 'Produkt wird gelöscht...',
    'deleteProductConfirmGeneric': 'Sind Sie sicher, dass Sie dieses Produkt löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'productUpdatedSuccessfully': 'Produkt erfolgreich aktualisiert',
    'productCreatedSuccessfully': 'Produkt erfolgreich erstellt',
    'productDeletedSuccessfully': 'Produkt erfolgreich gelöscht',
    'changeProductStatus': 'Produktstatus ändern',
    'changeStatus': 'Status ändern',
    'updatingStatus': 'Status wird aktualisiert...',
    'statusUpdatedToPending': 'Der Status wurde auf „Ausstehend“ aktualisiert',
    'statusUpdatedToApproved': 'Der Status wurde auf „Genehmigt“ aktualisiert',
    'statusUpdatedToRejected': 'Der Status wurde auf „Abgelehnt“ aktualisiert',
    'productsWillAppearHere': 'Produkte werden hier angezeigt, sobald sie hinzugefügt wurden',
    'noProductsFound': 'Keine Produkte gefunden',
    'youveReachedEnd': 'Sie sind am Ende angekommen',
    'errorLoadingProducts': 'Fehler beim Laden der Produkte',
    'featuredCatalog': 'Ausgewählter Katalog',
    'viewAll': 'Alle anzeigen',
    'outOfStock': 'AUSVERKAUFT',
    'onlyLeft': 'NUR',
    'left': 'LINKS',
    'timeRemainingDay': '{count} Tag noch übrig',
    'timeRemainingDays': '{count} Tage noch übrig',
    'timeRemainingHour': '{count} Stunde noch übrig',
    'timeRemainingHours': '{count} Stunden noch übrig',
    'timeRemainingMinute': '{count} Minute noch übrig',
    'timeRemainingMinutes': '{count} Minuten noch übrig',
    'pleaseSelectProduct': 'Bitte wählen Sie ein Produkt aus',
    'tapToSelectProduct': 'Tippen Sie, um ein Produkt auszuwählen',
    'unknownProduct': 'Unbekanntes Produkt',
    'searchProductsHint': 'Suchen Sie Produkte nach Name, SKU...',
    'loadingMoreProducts': 'Weitere Produkte werden geladen...',
    'reachedEnd': 'Du bist am Ende angekommen',
    'productsCountSuffix': 'Produkte',
    'price': 'Preis',
    'kilogram': 'Kilogramm',
    'gram': 'Gramm',
    'liter': 'Liter',
    'milliliter': 'Milliliter',
    'piece': 'Stück',
    'box': 'Kasten',
    'pack': 'Pack',
    'kmAway': 'km entfernt',
    'viewAllProducts': 'Alle Produkte anzeigen',
    // ============================================
    // Product Management Related
    // ============================================
    'productTitle': 'Produkttitel',
    'productTitleRequired': 'Bitte geben Sie den Produkttitel ein',
    'titleMinLength': 'Der Titel muss mindestens 3 Zeichen lang sein',
    'description': 'Beschreibung',
    'category': 'Kategorie',
    'wholesaler': 'Großhändler',
    'selectCategory': 'Kategorie auswählen',
    'selectCategories': 'Wählen Sie Kategorien aus',
    'pleaseSelectCategory': 'Bitte wählen Sie eine Kategorie aus',
    'tapToSelectCategory': 'Tippen Sie, um eine Kategorie auszuwählen',
    'pleaseSelectWholesaler': 'Bitte wählen Sie einen Großhändler aus',
    'tapToSelectWholesaler': 'Tippen Sie, um einen Großhändler auszuwählen',
    'unknownCategory': 'Unbekannte Kategorie',
    'yourAccount': 'Ihr Konto',
    'currentUser': 'Aktueller Benutzer',
    'variants': 'Varianten',
    'useVariants': 'Verwenden Sie Varianten',
    'addVariant': 'Variante hinzufügen',
    'addAttribute': 'Attribut hinzufügen',
    'variantSkuRequired': 'SKU ist erforderlich',
    'addAtLeastOneVariant': 'Bitte fügen Sie mindestens eine Variante hinzu',
    'selectVariant': 'Variante auswählen',
    'selectVariantHelper': 'Wählen Sie eine Variante für dieses Angebot',
    'noVariantsMessage': 'Für dieses Produkt gibt es keine Varianten. Der Deal wird direkt für das Produkt erstellt.',
    'unableToLoadVariantsMessage': 'Varianten können nicht geladen werden. Der Deal wird für das Produkt erstellt.',
    'featuredProduct': 'Empfohlenes Produkt',
    'default': 'Standard',
    'updateProduct': 'Produkt aktualisieren',
    'createProduct': 'Produkt erstellen',
    'globalAttributes': 'Globale Attribute',
    'globalAttributesDescription': 'Definieren Sie Attribute wie Farbe und Größe, die auf alle Varianten angewendet werden sollen.',
    'attributeName': 'Attributname (z. B. Farbe)',
    'attributeNameHint': 'Farbe, Größe, Material...',
    'imageUrl': 'Bild-URL',
    'productImages': 'Produktbilder',
    'firstImagePrimary': 'Das erste Bild ist primär',
    'addImageUrl': 'URL hinzufügen',
    'pasteImageUrlHint': 'Bild-URL einfügen',
    'costPrice': 'Selbstkostenpreis',
    'stock': 'Aktie',
    'stockRequired': 'Bitte geben Sie den Lagerbestand ein',
    'stockNegative': 'Der Bestand darf nicht negativ sein',
    'priceRequired': 'Bitte geben Sie den Preis ein',
    'pricePositive': 'Der Preis muss größer als 0 sein',
    'validationError': 'Validierungsfehler',
    'checkAllFields': 'Bitte überprüfen Sie alle Felder',
    'pending': 'Ausstehend',
    'approved': 'Genehmigt',
    'rejected': 'Abgelehnt',
    'draft': 'Entwurf',
    'failedToCreateDeal': 'Deal konnte nicht erstellt werden',
    'invalidDateTimeFormat': 'Ungültiges Datums-/Uhrzeitformat. Bitte überprüfen Sie Ihre Daten.',
    // ============================================
    // Categories Related
    // ============================================
    'noCategoriesFound': 'Keine Kategorien gefunden',
    'noCategoriesAvailable': 'Keine Kategorien verfügbar',
    'allCategories': 'Alle Kategorien',
    'searchCategories': 'Kategorien durchsuchen...',
    'noCategoriesMatchSearch': 'Keine Kategorien entsprechen Ihrer Suche',
    'categoriesWillAppearHere': 'Kategorien werden hier angezeigt, sobald sie hinzugefügt wurden',
    'tryDifferentSearchTerm': 'Versuchen Sie es mit einem anderen Suchbegriff',
    'errorLoadingCategories': 'Fehler beim Laden der Kategorien',
    'unableToLoadCategory': 'Kategorie kann nicht geladen werden',
    'productsCount': '{n} Produkte',
    'categoryName': 'Kategoriename',
    'categoryDescription': 'Beschreibung',
    'categoryImageUrl': 'Bild-URL',
    'createCategory': 'Kategorie erstellen',
    'editCategory': 'Kategorie bearbeiten',
    'deleteCategory': 'Kategorie löschen',
    'deleteCategoryConfirm': 'Sind Sie sicher, dass Sie „{name}“ löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'categoryCreatedSuccessfully': 'Kategorie erfolgreich erstellt',
    'enterCategoryDescriptionToGenerate': 'Geben Sie eine Kategoriebeschreibung ein, um Inhalte automatisch zu generieren.',
    'categoryDescriptionHint': 'Z. B. Bio-Gemüse...',
    'contentGeneratedSuccessfullyEnglish': 'Inhalt erfolgreich generiert! (Englisch)',
    'generationFailedWithError': 'Generierung fehlgeschlagen: {error}',
    'categoryUpdatedSuccessfully': 'Kategorie erfolgreich aktualisiert',
    'categoryDeletedSuccessfully': 'Kategorie erfolgreich gelöscht',
    'categoryCreationImportMessage': 'Die Erstellung von Kategorien erfolgt derzeit über den Import. Bitte kontaktieren Sie den Administrator.',
    'pleaseEnterCategoryName': 'Bitte geben Sie einen Kategorienamen ein',
    // ============================================
    // Reviews Related
    // ============================================
    'reviewed': 'Bewertet',
    'youHaveAlreadyReviewed': 'Sie haben dieses Produkt aus dieser Bestellung bereits bewertet',
    'reviewUpdatedSuccessfully': 'Bewertung erfolgreich aktualisiert',
    'reviewSubmittedSuccessfully': 'Bewertung erfolgreich eingereicht',
    'pleaseSelectRating': 'Bitte wählen Sie eine Bewertung aus',
    'maximum5ImagesAllowed': 'Maximal 5 Bilder erlaubt',
    'failedToPickImage': 'Bild konnte nicht ausgewählt werden',
    'failedToUploadImages': 'Bilder konnten nicht hochgeladen werden',
    'uploadImages': 'Bilder hochladen',
    'pickImage': 'Bild auswählen',
    'pickVideo': 'Wählen Sie Video',
    'uploadFailed': 'Der Upload ist fehlgeschlagen',
    'upload': 'Hochladen',
    'invalidImageUrl': 'Ungültige Bild-URL',
    // ============================================
    // Banners Related
    // ============================================
    'viewProduct': 'Produkt anzeigen',
    'viewDeal': 'Angebot ansehen',
    'openLink': 'Link öffnen',
    'discoverGreatDealsNearby': 'Entdecken Sie tolle Angebote in Ihrer Nähe',
    'stayTunedForOffers': 'Bleiben Sie dran für neue Angebote und Geschichten von geprüften Großhändlern.',
    'manageBanners': 'Banner verwalten',
    'myBanners': 'Meine Banner',
    'noBannersFound': 'Keine Banner gefunden. Erstelle eins!',
    'bannerDetails': 'Banner-Details',
    'bannerNotFound': 'Banner nicht gefunden',
    'views': 'Ansichten',
    'clicks': 'Klicks',
    'bannerRequestSubmitted': 'Banneranfrage eingereicht!',
    'failedToSubmitRequest': 'Anfrage konnte nicht gesendet werden',
    'deleteBanner': 'Banner löschen',
    'deleteBannerConfirm': 'Möchten Sie dieses Banner wirklich löschen?',
    'bannerDeleted': 'Banner gelöscht',
    'failedToDeleteBanner': 'Banner konnte nicht gelöscht werden',
    'targetId': 'Ziel-ID',
    'url': 'URL',
    'createNewBanner': 'Neues Banner erstellen',
    'bannerTitle': 'Bannertitel',
    'enterBannerTitle': 'Geben Sie den Bannertitel ein',
    'bannerImage': 'Bannerbild',
    'webBannerImage': 'Web-Bild',
    'webBannerImageHint': 'Querformat für Web',
    'mobileBannerImage': 'Mobilbild',
    'mobileBannerImageHint': 'Hochformat/quadratisch für Mobil',
    'mobilePreview': 'Mobilvorschau',
    'preview': 'Vorschau',
    'previewMobile': 'Mobilvorschau',
    'previewWillAppearHere': 'Vorschau erscheint hier',
    'pasteImageUrlHere': 'Fügen Sie hier die Bild-URL ein',
    'pleaseEnterImageUrlOrSwitch': 'Bitte geben Sie eine Bild-URL ein oder wechseln Sie zu Hochladen und wählen Sie ein Bild aus.',
    'pleaseTapChooseImage': 'Bitte tippen Sie auf „Bild auswählen“, um ein Bannerbild hochzuladen, oder wechseln Sie zur URL und fügen Sie einen Bildlink ein.',
    'tapToUploadWebImage': 'Tippen zum Hochladen des Web-Bildes',
    'tapToUploadMobileImage': 'Tippen zum Hochladen des Mobilbildes',
    'chooseImage': 'Wählen Sie Bild',
    'replaceImage': 'Bild ersetzen',
    // ============================================
    // Stories Related
    // ============================================
    'createStory': 'Geschichte erstellen',
    'storiesFromVerifiedWholesalers': 'Geschichten von geprüften Großhändlern',
    'storiesWillAppearHere': 'Geschichten werden hier angezeigt, sobald sie hinzugefügt wurden',
    'selectImageOrVideoForStory': 'Wählen Sie ein Bild oder Video für Ihre Geschichte aus',
    'post': 'Post',
    'expiresAt': 'Läuft ab um',
    // ============================================
    // Shipment / Tracking Related
    // ============================================
    'trackingNumber': 'Tracking-Nummer',
    'carrier': 'Träger',
    'trackingUrl': 'Tracking-URL',
    'openTrackingLink': 'Tracking-Link öffnen',
    'statusTimeline': 'Statuszeitleiste',
    // ============================================
    // Account Deletion Related
    // ============================================
    'submitDeletionRequest': 'Senden Sie einen Löschantrag',
    'submitRequest': 'Anfrage senden',
    'reviewProcess': 'Überprüfungsprozess',
    'accountDeleted': 'Konto gelöscht',
    'whatHappensNext': 'Was passiert als nächstes?',
    'submitRequestDescription': 'Geben Sie Ihre E-Mail-Adresse ein, um die Löschung Ihres Kontos anzufordern',
    'reviewProcessDescription': 'Unser Team wird Ihre Anfrage innerhalb von 24–48 Stunden prüfen. Sie erhalten eine Bestätigungs-E-Mail, sobald Ihre Anfrage bearbeitet wurde.',
    'accountDeletedDescription': 'Ihr Konto und alle damit verbundenen Daten werden dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    'ourTeamReviewsYourRequest': 'Unser Team prüft Ihre Anfrage',
    'reviewDetails': 'Überprüfen Sie Details',
    'reviewDetailsDescription': 'Wir verifizieren Ihr Konto und stellen sicher, dass alle ausstehenden Bestellungen oder Transaktionen abgeschlossen sind, bevor wir mit der Löschung fortfahren.',
    'yourAccountIsPermanentlyRemoved': 'Ihr Konto wird dauerhaft entfernt',
    'finalStep': 'Letzter Schritt',
    'finalStepDescription': 'Nach der Genehmigung werden Ihre Kontodaten dauerhaft aus unserem System gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    'importantInformation': 'Wichtige Informationen',
    'accountDeletionIsPermanent': 'Die Kontolöschung ist dauerhaft und kann nicht rückgängig gemacht werden',
    'allDataWillBeRemoved': 'Alle Ihre Daten, Bestellungen und Ihr Verlauf werden dauerhaft entfernt',
    'pendingOrdersMustBeCompleted': 'Ausstehende Bestellungen müssen abgeschlossen sein, bevor mit dem Löschen fortgefahren werden kann',
    'youllReceiveEmailConfirmation': 'Sobald der Vorgang abgeschlossen ist, erhalten Sie eine E-Mail-Bestätigung',
    'confirmActionPermanent': 'Bitte bestätigen Sie, dass Sie verstehen, dass diese Aktion dauerhaft ist',
    'requestSubmitted': 'Anfrage eingereicht',
    'deletionRequestSubmittedMessage': 'Ihr Antrag auf Kontolöschung wurde erfolgreich übermittelt. Unser Team wird es innerhalb von 24–48 Stunden überprüfen. Sie erhalten eine Bestätigungs-E-Mail, sobald Ihre Anfrage bearbeitet wurde.',
    'ok': 'OK',
    'failedToSubmitDeletionRequest': 'Löschanforderung konnte nicht gesendet werden. Bitte versuchen Sie es erneut.',
    'requestAccountDeletion': 'Fordern Sie die Löschung des Kontos an',
    'sorryToSeeYouGo': 'Es tut uns leid, Sie gehen zu sehen',
    'emailAddress': 'E-Mail-Adresse',
    'enterRegisteredEmail': 'Geben Sie Ihre registrierte E-Mail-Adresse ein',
    'emailAddressRequired': 'E-Mail-Adresse ist erforderlich',
    'pleaseEnterValidEmail': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    'reasonForDeletionOptional': 'Grund für die Löschung (optional)',
    'helpUsImproveLeaving': 'Helfen Sie uns, uns zu verbessern, indem Sie uns mitteilen, warum Sie uns verlassen ...',
    'understandActionPermanent': 'Mir ist bewusst, dass diese Aktion dauerhaft ist und nicht rückgängig gemacht werden kann',
    // ============================================
    // Support / Help Related
    // ============================================
    'emailSupport': 'E-Mail-Support',
    'getHelpViaEmail': 'Erhalten Sie Hilfe per E-Mail',
    'phoneSupport': 'Telefonsupport',
    'callUsDuringBusinessHours': 'Rufen Sie uns während der Geschäftszeiten an',
    'liveChat': 'Live-Chat',
    'chatWithUs': 'Chatten Sie mit uns',
    'chatWithSupportTeam': 'Chatten Sie mit unserem Support-Team',
    'commonIssues': 'Häufige Probleme',
    'orderNotShowingUp': 'Bestellung wird nicht angezeigt',
    'orderNotShowingUpSolution': 'Aktualisieren Sie das Dashboard oder überprüfen Sie Ihren Bestellverlauf unter „Meine Bestellungen“.',
    'liveChatComingSoon': 'Live-Chat folgt bald!',
    'needHelpContactSupport': 'Brauchen Sie Hilfe? Kontaktieren Sie den Support',
    'contactSupportAt': 'Kontaktieren Sie den Support unter',
    'getInTouch': 'Nehmen Sie Kontakt auf',
    'wereHereToHelp': 'Wir sind hier, um Ihnen zu helfen',
    'businessEmail': 'Geschäfts-E-Mail',
    'contactUsOnWhatsApp': 'Kontaktieren Sie uns über WhatsApp',
    'helloNeedAssistance': 'Hallo! Ich brauche Hilfe.',
    'myDetails': 'Meine Daten:',
    'nameLabel': 'Name:',
    'phoneLabel': 'Telefon:',
    'emailLabel': 'E-Mail:',
    'businessLabel': 'Geschäft:',
    'howCanYouHelpMe': 'Wie können Sie mir helfen?',
    'unableToOpenWhatsApp': 'WhatsApp kann nicht geöffnet werden. Bitte versuchen Sie es erneut.',
    'hello': 'Hallo',
    // ============================================
    // Common Validation Related
    // ============================================
    'required': 'Dieses Feld ist erforderlich',
    'invalidEmail': 'Ungültige E-Mail',
    'passwordTooShort': 'Das Passwort muss mindestens 6 Zeichen lang sein',
    'passwordsDoNotMatch': 'Passwörter stimmen nicht überein',
    // ============================================
    // Manager / Admin Related
    // ============================================
    'admin': 'Admin',
    'role': 'Rolle',
    'created': 'Erstellt',
    'subAdmin': 'Unteradministrator',
    'accessDenied': 'Zugriff verweigert',
    'managersSectionOnly': 'Dieser Abschnitt ist nur für Manager verfügbar',
    'totalRevenue': 'Gesamtumsatz',
    'myRevenue': 'Meine Einnahmen',
    'revenueDetail': 'Umsatzdetails',
    'myRevenueDetail': 'Meine Umsatzdetails',
    'howCalculated': 'Wie wird der Umsatz berechnet?',
    'productOrdersRevenue': 'Produktbestellungen (geliefert)',
    'dealOrdersRevenue': 'Deal-Bestellungen (geliefert)',
    'totalGrossRevenue': 'Bruttoumsatz gesamt',
    'platformCut': 'Plattformanteil ({percent}%)',
    'platformCutDescription': 'Ihr Anteil als Plattform-Admin (1% Provision)',
    'revenueFromDeliveredOrders': 'Umsatz aus gelieferten Produkt- und Deal-Bestellungen.',
    'revenueDetailAdminInfo':
        'Als Admin erhalten Sie 1% Provision von allen gelieferten Bestellungen (Produkt + Deal). Produktinhaber erhalten die verbleibenden 99%.',
    'revenueDetailOwnerInfo':
        'Ihr voller Umsatz aus gelieferten Produktbestellungen und Deal-Bestellungen, bei denen Sie Deal-Inhaber sind.',
    'errorLoading': 'Fehler beim Laden',
    'activeShops': 'Aktive Großhändler',
    'activeMembers': 'Aktive Geschäfte / Kiosk',
    'inactiveMembers': 'Inaktive Shops',
    'activeShopsSubtitle': 'Verifizierte Großhändler auf der Plattform',
    'activeMembersSubtitle': 'Geschäfte, die kürzlich bestellt haben',
    'inactiveMembersSubtitle': 'Keine Bestellung in mehr als 60 Tagen',
    'lastOrder': 'Letzte Bestellung',
    'lastActive': 'Zuletzt aktiv',
    'lastLogin': 'Letzter Login',
    'joined': 'Beigetreten',
    'selectToNotify': 'Wählen Sie diese Option, um eine Benachrichtigung zu senden',
    'deselect': 'Abwählen',
    'recipients': 'Empfänger',
    'notificationSent': 'Benachrichtigung gesendet',
    'notifyDealParticipantsTitle': 'Deal-Teilnehmer benachrichtigen',
    'notifyDealParticipantsAudienceWarning':
        'Diese Nachricht wird nur an Nutzer gesendet, die eine Bestellung für diesen Deal aufgegeben haben.',
    'notifyDealParticipantsSendUpdateTooltip': 'Update senden',
    'notifyDealParticipantsSending': 'Senden...',
    'notifyDealParticipantsNoParticipantsError':
        'Senden nicht möglich: Bisher hat sich noch kein Nutzer diesem Deal angeschlossen.',
    'notifyDealParticipantsFailedToSend':
        'Benachrichtigung konnte nicht gesendet werden: {error}',
    'noInactiveMembers': 'Keine inaktiven Mitglieder',
    'selectAll': 'Alles auswählen',
    'sendNotification': 'Benachrichtigung senden',
    'title': 'Titel',
    'body': 'Nachricht',
    'send': 'Schicken',
    'generateWithAI': 'Generieren Sie mit KI',
    'generateNotificationPrompt': 'Beschreiben Sie die Benachrichtigung (z. B. erneutes Engagement, Flash-Sale, neue Produkte), um Titel und Nachricht zu generieren.',
    'weMissYou': 'Wir vermissen dich!',
    'reEngagementDefaultBody': 'Sie haben seit einiger Zeit keine Bestellung mehr aufgegeben. Stöbern Sie in unseren neuesten Angeboten und Produkten.',
    'notificationRemindHint': 'Erinnern Sie beispielsweise inaktive Geschäfte an unseren Winterschlussverkauf',
    'searchByNameEmail': 'Suche nach Name, E-Mail...',
    'generate': 'Erzeugen',
    'page': 'Seite',
    'never': 'Niemals',
    'quickActions': 'Schnelle Aktionen',
    'recentOrders': 'Letzte Bestellungen',
    'noRecentOrders': 'Keine aktuellen Bestellungen',
    'analyticsComingSoon': 'Analytics – Demnächst verfügbar',
    'importCsv': 'Aus CSV importieren',
    'importFromCsv': 'Aus CSV importieren',
    'importProductsFromCsv': 'Produkte aus CSV importieren',
    'importProducts': 'Produkte importieren',
    'importing': 'Importieren...',
    'downloadCsvTemplate': 'Laden Sie die CSV-Vorlage herunter',
    'getSampleCsvWithColumns': 'Holen Sie sich eine Beispiel-CSV-Datei mit allen erforderlichen Spalten',
    'selectCsvFile': 'Wählen Sie CSV-Datei',
    'chooseFile': 'Wählen Sie Datei',
    'tapToSelectWholesalerForImport': 'Tippen Sie hier, um einen Großhändler für importierte Produkte auszuwählen',
    'importComplete': 'Import abgeschlossen',
    'inserted': 'Eingefügt',
    'updated': 'Aktualisiert',
    'skipped': 'Übersprungen',
    'fileLabel': 'Datei: {name}',
    'wholesalerRequired': 'Großhändler *',
    'wholesalerLabel': 'Großhändler {id}',
    'csvPreviewRows': 'CSV-Vorschau ({n} Zeilen)',
    'multipleRowsSameProductVariant': 'Mehrere Zeilen mit demselben Produktnamen = mehrere Varianten',
    'errorsCount': 'Fehler ({n})',
    'andMoreErrors': '... und {n} weitere Fehler',
    'failedToReadFileBytes': 'Dateibytes konnten nicht gelesen werden',
    'failedToGetFilePath': 'Dateipfad konnte nicht abgerufen werden',
    'errorPickingFile': 'Fehler beim Auswählen der Datei: {error}',
    'csvFileEmpty': 'CSV-Datei ist leer',
    'errorParsingCsv': 'Fehler beim Parsen der CSV-Datei: {error}',
    'templateSavedSuccessfully': 'Vorlage erfolgreich gespeichert',
    'templateDownloadCancelled': 'Der Download der Vorlage wurde abgebrochen',
    'errorGeneratingTemplate': 'Fehler beim Generieren der Vorlage',
    'errors': 'Fehler',
    'viewWholesaler': 'Großhändler ansehen',
    'cropImage': 'Bild zuschneiden',
    'change': 'Ändern',
    'navigationError': 'Navigationsfehler',
    // ============================================
    // Time Related
    // ============================================
    'hours': 'Std.',
    'minutes': 'Minuten',
    'seconds': 'Sekunden',
    'twentyFourHours': '24 Stunden',
    'twelveHours': '12 Stunden',
    'sixHours': '6 Stunden',
    // ============================================
    // Navigation / Route Errors
    // ============================================
    'noStoryDataProvided': 'Keine Story-Daten bereitgestellt.',
    'missingWholesalerId': 'Fehlende Großhändler-ID.',
    'missingProductId': 'Fehlende Produkt-ID.',
    'missingCategorySlug': 'Fehlender Kategorie-Slug.',
    'missingDealId': 'Fehlende Deal-ID.',
    'missingOrderId': 'Fehlende Bestell-ID.',
    'featuredProducts': 'Ausgewählte Produkte',
    // ============================================
    // Order Update / Quantity Change Result
    // ============================================
    'orderUpdate': 'Bestellaktualisierung',
    'viewMyOrders': 'Meine Bestellungen ansehen',
    'goToHome': 'Gehen Sie zu Startseite',
    'quantityChangeAccepted': 'Mengenänderung akzeptiert',
    'quantityChangeDeclined': 'Mengenänderung abgelehnt',
    'somethingWentWrong': 'Etwas ist schief gelaufen',
    'orderUpdatedMessage': 'Ihre Bestellung wurde aktualisiert.',
    'orderRevertedMessage': 'Ihre Bestellung wurde auf die vorherige Menge zurückgesetzt.',
    'pleaseTryAgainLater': 'Bitte versuchen Sie es später noch einmal.',
    // ============================================
    // Deal Detail / Deal Errors
    // ============================================
    'unableToLoadDeal': 'Das Angebot konnte nicht geladen werden',
    'regularPrice': 'Regulärer Preis',
    'stockLabel': 'Aktie',
    'dealNotStarted': 'Dieser Deal hat noch nicht begonnen',
    'adminWholesalerManageHint': 'Als Administrator oder Großhändler können Sie dieses Angebot verwalten, aber keine Bestellungen aufgeben. Verwenden Sie die Menüschaltfläche (⋮) in der App-Leiste, um dieses Angebot zu bearbeiten oder zu schließen.',
    'adminDealOnlyOwnerCanBid': 'Nur der Administrator (Deal-Inhaber) kann Gebote für Admin-Deals abgeben. Kiosk-Benutzer können für dieses Angebot keine Bestellungen aufgeben.',
    'kioskOnlyPlaceOrders': 'Bei diesem Angebot können nur Kiosk-/Shop-Konten Bestellungen aufgeben.',
    'managementView': 'Managementansicht',
    'ordering': 'Bestellung',
    'failedToLoadDealData': 'Die Deal-Daten konnten nicht geladen werden',
    'dealClosedSuccess': 'Deal erfolgreich abgeschlossen',
    'failedToCloseDeal': 'Der Deal konnte nicht abgeschlossen werden',
    'onlyAdminCanAddBidsOnAdminDeals': 'Nur der Administrator (Deal-Inhaber) kann Gebote für Admin-Deals abgeben.',
    // ============================================
    // Product Search / Detail
    // ============================================
    'searchProducts': 'Produkte suchen',
    'youCanOnlyReviewFromDeliveredOrders': 'Sie können nur Produkte aus gelieferten Bestellungen bewerten',
    'allImages': 'Alle Bilder',
    'contentGeneratedSuccessfully': 'Inhalt erfolgreich generiert! Überprüfen Sie die Kategorie und andere Felder.',
    'generationFailed': 'Die Generierung ist fehlgeschlagen',
    'userIdRequired': 'Benutzer-ID erforderlich',
    // ============================================
    // Admin Banner Management
    // ============================================
    'adminBannerManagement': 'Admin-Banner-Verwaltung',
    'requests': 'Anfragen',
    'active': 'Aktiv',
    'noBannersFoundShort': 'Keine Banner gefunden.',
    'failedToUpdateBanner': 'Banner konnte nicht aktualisiert werden',
    'bannerSubmittedSuccessfully': 'Banner erfolgreich übermittelt',
    'failedToCreateBanner': 'Banner konnte nicht erstellt werden',
    'failedToSubmitBannerRequest': 'Banneranfrage konnte nicht gesendet werden',
    // ============================================
    // User Management / Admin
    // ============================================
    'administratorsOnlySection': 'Dieser Abschnitt ist nur für Administratoren verfügbar',
    'allRoles': 'Alle Rollen',
    'allStatuses': 'Alle Status',
    'suspended': 'Ausgesetzt',
    'noUsersFound': 'Keine Benutzer gefunden',
    'pageOf': 'Seite',
    'ofLabel': 'von',
    'noDocumentsAvailable': 'Keine Dokumente vorhanden',
    'userUpdatedSuccessfully': 'Benutzer erfolgreich aktualisiert',
    'userCreatedSuccessfully': 'Benutzer erfolgreich erstellt',
    'userDeletedSuccessfully': 'Benutzer erfolgreich gelöscht',
    'deleteUser': 'Benutzer löschen',
    'deleteUserConfirm': 'Sind Sie sicher, dass Sie {name} löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'verificationDocuments': 'Verifizierungsdokumente',
    'noVerificationDocumentsYet': 'Es wurden noch keine Verifizierungsdokumente hochgeladen.',
    'rejectionReason': 'Ablehnungsgrund:',
    'createUser': 'Benutzer erstellen',
    'editUser': 'Benutzer bearbeiten',
    'updateUser': 'Benutzer aktualisieren',
    'roleRequired': 'Rolle ist erforderlich',
    'statusRequired': 'Status ist erforderlich',
    'newPasswordLeaveEmpty': 'Neues Passwort (leer lassen, um aktuell zu bleiben)',
    'passwordRequired': 'Passwort ist erforderlich',
    'passwordMinLength': 'Das Passwort muss mindestens 6 Zeichen lang sein',
    'needInfo': 'Brauche Infos',
    'business': 'Geschäft',
    'searchByNameEmailPhone': 'Suche nach Name, E-Mail, Telefon...',
    'daysAgo': 'Tag(e) her',
    'activeDaysLast14': 'Aktive Tage (letzte 14)',
    'docsCount': '{count} Dokument(e)',
    'noPassportDocuments': 'Keine Passdokumente',
    'noGewerbescheinDocuments': 'Keine Gewerbescheinunterlagen',
    'noBusinessLicenseDocuments': 'Keine Gewerbescheindokumente',
    'documentN': 'Dokument {n}',
    'openInBrowser': 'Im Browser öffnen',
    'pdfDocument': 'PDF-Dokument',
    'kiosk': 'Kiosk',
    // ============================================
    // Order Management (Deal Orders)
    // ============================================
    'errorLoadingOrders': 'Fehler beim Laden der Bestellungen',
    'errorLoadingDeals': 'Fehler beim Laden der Angebote',
    'orderManagement': 'Auftragsverwaltung',
    'orderCountSuffix': 'Befehl',
    'confirmOrder': 'Bestellung bestätigen',
    'confirmOrderMessage': 'Möchten Sie diese Bestellung wirklich bestätigen?',
    'confirm': 'Bestätigen',
    'markAsDelivered': 'Als geliefert markieren',
    'markDelivered': 'Markieren Sie „Geliefert“.',
    'cancelOrder': 'Bestellung stornieren',
    'cancelOrderConfirm': 'Sind Sie sicher, dass Sie diese Bestellung stornieren möchten?',
    'no': 'NEIN',
    'reduceQuantity': 'Menge reduzieren',
    'orderConfirmedSuccess': 'Bestellung erfolgreich bestätigt',
    'orderMarkedDelivered': 'Bestellung als geliefert markiert',
    'failedToConfirmOrder': 'Bestellung konnte nicht bestätigt werden',
    'failedToMarkDelivered': 'Markierung als geliefert fehlgeschlagen',
    'orderCancelled': 'Bestellung storniert',
    'failedToCancelOrder': 'Bestellung konnte nicht storniert werden',
    'orderMarkedPaid': 'Bestellung als bezahlt markiert',
    'failedToMarkOrderPaid': 'Die Bestellung konnte nicht als bezahlt markiert werden',
    'quantityUpdatedSuccess': 'Menge erfolgreich aktualisiert',
    'failedToUpdateQuantity': 'Menge konnte nicht aktualisiert werden',
    'deliveryNotesOptional': 'Lieferscheine (optional)',
    'newQuantity': 'Neue Menge',
    'reduceQuantityHint': 'Geben Sie die neue Menge ein. Das Minimum ist 1 (oder die Mindestbestellmenge des Deals). Verwenden Sie 0, um diese Bestellung zu stornieren.',
    'quantityUpdatedTo': 'Menge aktualisiert auf',
    // ============================================
    // Deal Order Form
    // ============================================
    'enterQuantity': 'Geben Sie die Menge ein',
    'pleaseEnterQuantity': 'Bitte Menge eingeben',
    'invalidQuantity': 'Ungültige Menge',
    'minimumOrderIs': 'Mindestbestellmenge ist',
    'maximumOrderIs': 'Maximalbestellmenge ist',
    'addSpecialInstructions': 'Fügen Sie spezielle Anweisungen hinzu ...',
    'minQuantityLabel': 'Min',
    'selectedLabel': 'Ausgewählt',
    'maxQuantityLabel': 'Max',
    // ============================================
    // Shipment / Carrier
    // ============================================
    'pleaseSelectCarrier': 'Bitte wählen Sie einen Spediteur aus',
    'pleaseEnterCarrierNameForOther': 'Bitte geben Sie unter „Andere“ den Namen des Anbieters ein.',
    'shipmentCreatedSuccess': 'Sendung erfolgreich erstellt',
    'shipmentCreatedAndOrderShipped': 'Sendung erstellt und Bestellung als versandt markiert',
    'failedToCreateShipment': 'Die Sendung konnte nicht erstellt werden',
    // ============================================
    // Stories
    // ============================================
    'failedToPickMedia': 'Fehler beim Auswählen des Mediums',
    'onlyWholesalersCanCreateStories': 'Nur Großhändler können Geschichten erstellen',
    'storyCreatedSuccess': 'Story erfolgreich erstellt! 🎉',
    'failedToCreateStory': 'Story konnte nicht erstellt werden',
    // ============================================
    // Payment
    // ============================================
    'paymentCompletedSuccess': 'Zahlung erfolgreich abgeschlossen!',
    'paymentFailed': 'Die Zahlung ist fehlgeschlagen',
    // ============================================
    // Notifications
    // ============================================
    'notifications': 'Benachrichtigungen',
    'markAllAsRead': 'Alle als gelesen markieren',
    'deleteAll': 'Alles löschen',
    'filterNotifications': 'Benachrichtigungen filtern',
    'unread': 'Ungelesen',
    'read': 'Lesen',
    'deleteAllNotificationsConfirm': 'Alle Benachrichtigungen löschen?',
    'deleteAllNotificationsMessage': 'Sind Sie sicher, dass Sie alle Benachrichtigungen löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    // ============================================
    // Deal / Product Modals
    // ============================================
    'paymentEmailTemplateGenerated': 'Zahlungs-E-Mail-Vorlage generiert',
    'aiGenerationFailed': 'Die KI-Generierung ist fehlgeschlagen',
    'dealUpdatedSuccess': 'Deal erfolgreich aktualisiert',
    'allowOnlinePayment': 'Online-Zahlung zulassen',
    'allowOnlinePaymentSubtitle': 'Wenn diese Option deaktiviert ist, können Kunden nur Bestellungen aufgeben. Die Zahlung (z. B. Banküberweisung) wird nach Bestätigung der Bestellung erbeten.',
    'paymentAndEmail': 'Zahlung & E-Mail',
    'generating': 'Generieren…',
    'enterDealDescriptionPrompt': 'Geben Sie eine klare Beschreibung Ihres Deals ein, um automatisch Inhalte zu generieren.',
    'dealDescriptionHint': 'z. B. Flash-Sale: 50 % Rabatt auf alle Winterjacken',
    'enterProductDescriptionPrompt': 'Geben Sie eine Beschreibung oder Produktdetails ein, um Inhalte automatisch zu generieren.',
    'productDescriptionHint': 'Z. B. ein hochwertiger Bürostuhl aus Leder mit ergonomischem Design ...',
    'optionalAutoAssigned': 'Optional – wird automatisch zugewiesen, wenn es leer ist',
    'defaultYourAccount': 'Standard: Ihr Konto (zum Ändern tippen)',
    'currentUserYou': 'Aktueller Benutzer (Sie)',
    'loadingProductDetails': 'Produktdetails werden geladen...',
    'loading': 'Laden...',
    'ibanBankAccount': 'IBAN / Bankkonto',
    'accountOwner': 'Kontoinhaber',
    'referenceTemplate': 'Referenzvorlage (z. B. DEAL-{dealCode}-{buyerId})',
    'paymentInstructions': 'Zahlungsanweisungen (Freitext)',
    'paymentEmailSubject': 'Betreff der Zahlungs-E-Mail',
    'paymentEmailBody': 'E-Mail-Text der Zahlung (verwenden Sie {dealTitle}, {amount}, {iban}, {reference}, {accountOwner})',
    'ended': 'Beendet',
    'dealEnded': 'Deal beendet',
    'dealHasEnded': 'Der Deal ist beendet',
    'endingSoon': 'Bald zu Ende!',
    'endsIn1Day': 'Endet in 1 Tag',
    'endsInDays': 'Endet in {n} Tagen',
    'endsIn1Hour': 'Endet in 1 Stunde',
    'endsInHours': 'Endet in {n} Stunden',
    'endsSoon': 'Endet bald',
    'categories': 'Kategorien',
    'itemsCount': '{n} Artikel',
    // ============================================
    // Shipment Tracking
    // ============================================
    'pleaseEnterTrackingNumber': 'Bitte geben Sie eine Tracking-Nummer ein',
    'pleaseSelectAtLeastOneItemToShip': 'Bitte wählen Sie mindestens einen Artikel zum Versenden aus',
    'pleaseEnterTrackingUrlForOther': 'Bitte geben Sie die Tracking-URL für „Anderer“ Anbieter ein',
    'selectItemsToShip': 'Wählen Sie „Zu versendende Artikel“ aus',
    'noItemsAvailableForShipment': 'Keine Artikel zum Versand verfügbar',
    'selectCarrier': 'Wählen Sie einen Spediteur aus',
    'selectCarrierHint': 'Wählen Sie einen Anbieter aus...',
    'carrierName': 'Name des Trägers',
    'enterCarrierName': 'Geben Sie den Namen des Anbieters ein',
    'trackingNumberRequired': 'Eine Sendungsverfolgungsnummer ist erforderlich',
    'enterTrackingNumber': 'Geben Sie die Sendungsverfolgungsnummer ein',
    'trackingUrlAutoGenerated': 'Die Tracking-URL wird automatisch generiert',
    'trackingUrlRequiredForOther': 'Für „Andere“ Anbieter ist eine Tracking-URL erforderlich',
    'pleaseEnterValidUrl': 'Bitte geben Sie eine gültige URL ein',
    'estimatedDeliveryDate': 'Voraussichtliches Lieferdatum',
    'selectDate': 'Datum auswählen',
    'internalNotesShipment': 'Interne Notizen zu dieser Sendung',
    'trackingUrlHintAuto': 'Wird automatisch generiert, wenn Spediteur und Sendungsverfolgungsnummer angegeben werden',
    'trackShipment': 'Sendung verfolgen',
    'trackShipmentHint': 'Verfolgen Sie Ihre Sendung mit der angegebenen Sendungsverfolgungsnummer',
    'trackingDetails': 'Tracking-Details',
    'shipmentNotFound': 'Sendung nicht gefunden',
    'pleaseCheckTrackingNumber': 'Bitte überprüfen Sie Ihre Sendungsverfolgungsnummer und versuchen Sie es erneut',
    'noNotifications': 'Keine Benachrichtigungen',
    'youreAllCaughtUp': 'Sie sind alles erledigt!',
    // ============================================
    // Select Deal / Category
    // ============================================

    // Feature audit – previously hardcoded strings
    'platformMobile': 'Mobil',
    'platformWeb': 'Web',
    'pleaseWait': 'Bitte warten...',
    'defaultVariant': 'Standard',
    'trackOnCarrierWebsite': 'Auf Website des Versanddienstes verfolgen',
    'minOrderQtyRequired': 'Mindestbestellmenge *',
    'dealPriceRequired': 'Deal-Preis *',
    'targetQuantityRequired': 'Zielmenge *',
    'baseShippingCostEur': 'Grundversandkosten (€)',
    'freeShippingThresholdQuantity': 'Kostenloser Versand ab Menge',
    'perUnitShippingCostEur': 'Versandkosten pro Einheit (€)',
    'descriptionOptional': 'Beschreibung (optional)',
    'enterBannerDescription': 'Banner-Beschreibung eingeben',
    'bannerType': 'Banner-Typ',
    'targetUrl': 'Ziel-URL',
    'skuRequired': 'SKU *',
    'productToPromoteHint': 'Produkt zum Bewerben',
    'selectDealToPromote': 'Deal zum Bewerben auswählen',
    'titleOptional': 'Titel (optional)',
    'giveReviewTitle': 'Geben Sie Ihrer Bewertung einen Titel',
    'yourReviewOptional': 'Ihre Bewertung (optional)',
    'shareExperienceWithProduct':
        'Teilen Sie Ihre Erfahrung mit diesem Produkt',
    'dealUpdatedSuccessfully': 'Deal erfolgreich aktualisiert',
    'dealPriceMustBeValidNumber': 'Deal-Preis muss eine gültige Zahl sein',
    'pleaseEnterMinOrderQuantity': 'Bitte Mindestbestellmenge eingeben',
    'paymentEmailPlaceholdersSubject':
        'Platzhalter: {dealTitle}, {amount}, {reference}',
    'paymentEmailPlaceholdersBody':
        'Platzhalter: {dealTitle}, {amount}, {accountOwner}, {iban}, '
        '{reference}, {additionalInstructions}',
    'failed': 'Fehlgeschlagen',

    // ============================================
    // Order status (product orders – display only)
    // ============================================
    'orderStatusPendingConfirmation': 'Ausstehend',
    'orderStatusConfirmed': 'Bestätigt',
    'orderStatusPacking': 'Wird verpackt',
    'orderStatusDispatched': 'Versandt',
    'orderStatusOutForDelivery': 'In Zustellung',
    'orderStatusDelivered': 'Zugestellt',
    'orderStatusCancelled': 'Storniert',
    'orderStatusReturned': 'Zurückgesendet',
    'orderStatusRefunded': 'Erstattet',

    // ============================================
    // Notifications (backend localization keys)
    // ============================================
    'notificationProductApprovalNeededTitle': 'Neues Produkt zur Freigabe',
    'notificationProductApprovalNeededBody':
        '{0} hat ein neues Produkt erstellt: {1}',
    'notificationProductStatusUpdatedTitle': 'Produktstatus aktualisiert',
    'notificationProductApprovedBody': 'Ihr Produkt "{0}" wurde genehmigt!',
    'notificationProductRejectedBody': 'Ihr Produkt "{0}" wurde abgelehnt.',
    'notificationProductPendingBody':
        'Ihr Produkt "{0}" wartet auf Freigabe.',
    'notificationProductStatusChangedBody':
        'Der Status Ihres Produkts "{0}" wurde zu {1} geändert',
    'notificationNewProductOrderTitle': 'Neue Bestellung für Ihre Produkte',
    'notificationNewProductOrderBody':
        '{0} hat {1} Stück von {2} bestellt',
    'notificationNewDealOrderTitle': 'Neue Bestellung für Ihren Deal',
    'notificationNewDealOrderBody': '{0} hat {1} Einheiten bestellt',
    'notificationPaymentReportedTitle': 'Käufer meldete Zahlung',
    'notificationPaymentReportedBody':
        '{0} hat eine Zahlung für die Bestellung gemeldet. Details: {1}',
    'notificationDealPaymentReportedBody':
        '{0} hat eine Zahlung für die Deal-Bestellung gemeldet. Details: {1}',
    'notificationDealOrderStatusUpdatedTitle': 'Status der Deal-Bestellung',
    'notificationDealOrderConfirmedBody':
        'Ihre Bestellung zu "{0}" wurde bestätigt!',
    'notificationDealOrderShippedBody':
        'Ihre Bestellung zu "{0}" wurde versandt!',
    'notificationDealOrderDeliveredBody':
        'Ihre Bestellung zu "{0}" wurde geliefert!',
    'notificationDealOrderCancelledBody':
        'Ihre Bestellung zu "{0}" wurde storniert.',
    'notificationDealOrderRefundedBody':
        'Ihre Bestellung zu "{0}" wurde erstattet.',
    'notificationDealOrderPendingBody':
        'Ihre Bestellung zu "{0}" wartet auf Bestätigung.',
    'notificationDealOrderStatusChangedBody':
        'Der Status Ihrer Bestellung zu "{0}" wurde zu {1} geändert',
    'notificationOrderQuantityUpdatedTitle': 'Bestellmenge aktualisiert',
    'notificationDealOrderQuantityCancelledBody':
        'Ihre Bestellung zu "{0}" (zuvor {1} Einheiten) wurde vom Verkäufer storniert.',
    'notificationDealOrderQuantityChangedBody':
        'Ihre Bestellung zu "{0}" wurde aktualisiert: Menge von {1} auf {2} Einheiten geändert.',
    'notificationQuantityChangeDeclinedTitle': 'Mengenänderung abgelehnt',
    'notificationQuantityChangeDeclinedBody':
        '{0} hat die Mengenänderung abgelehnt. Die Bestellung wurde von {1} auf {2} Einheiten zurückgesetzt.',
    'notificationDealNowLiveTitle': 'Neuer Deal ist live',
    'notificationDealNowLiveBody':
        '"{0}" ist jetzt live. Bestellen Sie, bevor der Deal endet.',
    'notificationDealTarget70PercentTitle': 'Deal fast erreicht',
    'notificationDealTarget70PercentBody':
        '"{0}" ist zu {1}% gefüllt! Schließen Sie sich anderen Händlern an und helfen Sie dem Deal-Inhaber, sein Ziel zu erreichen – das stärkt Ihre Beziehung und zeigt Ihr Engagement.',
    'notificationDealEnding24hTitle': 'Deal endet bald',
    'notificationDealEnding24hBody':
        'Letzte 24 Stunden! "{0}" – nur noch {1} Bestellungen bis zum Abschluss dieses Deals.',
    'notificationDealEnding7dTitle': 'Deal endet in 7 Tagen',
    'notificationDealEnding7dBody':
        '"{0}" – nur noch {1} Bestellungen bis zum Abschluss dieses Deals.',
    'notificationDealSuccessTitle': 'Deal erfolgreich abgeschlossen',
    'notificationDealSuccessBody':
        'Ihr Gruppendeal "{0}" hat die erforderliche Menge erreicht und ist jetzt bestätigt. Bitte bereiten Sie Zahlung und Versand gemäß den Anweisungen des Großhändlers vor.',
    'notificationDealClosedTitle': 'Deal geschlossen',
    'notificationDealClosedBody':
        'Der Deal "{0}" wurde geschlossen. Er erscheint nicht mehr in den aktiven Deals.',
    'deal_closed_title': 'Deal geschlossen!',
    'deal_closed_body':
        'Der Deal „{0}“ wurde offiziell geschlossen. Vielen Dank für Ihre Teilnahme!',
    'notificationOrderStatusUpdatedTitle': 'Bestellstatus aktualisiert',
    'notificationOrderConfirmedBody':
        'Ihre Bestellung für "{0}" wurde bestätigt!',
    'notificationOrderDispatchedBody':
        'Ihre Bestellung für "{0}" wurde versandt!',
    'notificationOrderDeliveredBody':
        'Ihre Bestellung für "{0}" wurde geliefert!',
    'notificationOrderCancelledBody':
        'Ihre Bestellung für "{0}" wurde storniert.',
    'notificationOrderPackingBody':
        'Ihre Bestellung für "{0}" wird verpackt!',
    'notificationOrderOutForDeliveryBody':
        'Ihre Bestellung für "{0}" ist in Zustellung!',
    'notificationOrderReturnedBody':
        'Ihre Bestellung für "{0}" wurde zurückgesendet.',
    'notificationOrderRefundedBody':
        'Ihre Bestellung für "{0}" wurde erstattet.',
    'notificationOrderStatusChangedBody':
        'Der Status Ihrer Bestellung für "{0}" wurde zu {1} geändert',
    'notificationOrderItemRemovedBody':
        'Ihr Bestellartikel "{0}" (zuvor {1} Einheiten) wurde vom Verkäufer entfernt.',
    'notificationOrderItemQuantityChangedBody':
        'Ihr Bestellartikel "{0}" wurde aktualisiert: Menge von {1} auf {2} Einheiten geändert.',
    'notificationProductQuantityChangeDeclinedBody':
        '{0} hat die Mengenänderung beim Bestellartikel abgelehnt. Zurückgesetzt von {1} auf {2} Einheiten.',
    'notificationDailyEngagementTitle': 'Angebote von heute ansehen!',
    'notificationDailyEngagementBody':
        'Heute: {0} Banner, {1} Deals, {2} hervorgehobene Produkte. Öffnen Sie die App für Angebote.',
    'notificationInactiveMembersAlertTitle': 'Warnung: Inaktive Mitglieder',
    'notificationInactiveMembersAlertBody':
        '{0} Shop(s) haben seit {1} Tagen nicht bestellt. Erwägen Sie, Kontakt aufzunehmen oder zu prüfen.',
    'notificationBulkImportCompletedTitle': 'Bulk-Import abgeschlossen',
    'notificationBulkImportCompletedBody':
        '{0} Produkte erfolgreich importiert. {1} übersprungen.',
    'notificationBannerApprovalNeededTitle': 'Neues Banner zur Freigabe',
    'notificationBannerApprovalNeededBody':
        '{0} hat eine Freigabe für das Banner angefordert: {1}',
    'notificationNewUserRegistrationTitle': 'Neue Benutzerregistrierung',
    'notificationNewUserRegistrationBody':
        '{0} ({1}) hat sich als {2} registriert. Freigabe ausstehend.',
    'notificationBannerStatusChangedTitle': 'Bannerstatus geändert',
    'notificationBannerApprovedBody':
        'Ihr Banner "{0}" wurde genehmigt und ist jetzt aktiv!',
    'notificationBannerRejectedBody':
        'Ihr Banner "{0}" wurde abgelehnt. Bitte prüfen und ggf. erneut einreichen.',
    'notificationBannerDeactivatedBody':
        'Ihr Banner "{0}" wurde deaktiviert.',
    'notificationBannerStatusChangedBody':
        'Der Status Ihres Banners "{0}" wurde zu {1} geändert',
    'notificationAdminCustomTitle': '{0}',
    'notificationAdminCustomBody': '{0}',
  };
}