class HindiFile {
  static const Map<String, String> hindiTranslations = {
    // ============================================
    // Options Screen Related
    // ============================================
    'options': 'विकल्प',
    'account': 'खाता',
    'myOrders': 'मेरे आदेश',
    'myOrdersSubtitle': 'अपने ऑर्डर देखें और ट्रैक करें',
    'statistics': 'आंकड़े',
    'statisticsSubtitle': 'अपने सौदे में भागीदारी के आँकड़े देखें',
    'profile': 'प्रोफ़ाइल',
    'profileSubtitle': 'अपना खाता प्रबंधित करें',
    'management': 'प्रबंध',
    'manageCategories': 'श्रेणी व्यवस्थित करें',
    'manageCategoriesSubtitle': 'उत्पाद श्रेणियां बनाएं और प्रबंधित करें',
    'createNewProductSubtitle': 'एक नया उत्पाद बनाएं',
    'createNewDealSubtitle': 'एक नया सौदा बनाएं',
    'viewOrdersSubtitle': 'ऑर्डर देखें और प्रबंधित करें',
    'inactiveMembersViewSubtitle': 'बिना हाल के ऑर्डर वाली दुकानें देखें',
    'manageBannersSubtitle': 'ऐप बैनर प्रबंधित करें (व्यवस्थापक)',
    'myBannersSubtitle': 'अपने बैनर प्रबंधित करें',
    'unableToLoadOptions': 'विकल्प लोड करने में असमर्थ',
    'loggingOut': 'लॉग आउट हो रहा है...',
    'manageUsers': 'उपयोगकर्ताओं को प्रबंधित करें',
    'manageUsersSubtitle': 'उपयोगकर्ता खाते देखें और प्रबंधित करें',
    'analytics': 'एनालिटिक्स',
    'analyticsSubtitle': 'अपना व्यवसाय विश्लेषण देखें',
    'information': 'जानकारी',
    'faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'faqSubtitle': 'अक्सर पूछे जाने वाले प्रश्नों',
    'aboutUs': 'हमारे बारे में',
    'aboutUsSubtitle': 'हमारे प्लेटफ़ॉर्म के बारे में और जानें',
    'helpSupport': 'सहायता एवं सहायता',
    'helpSupportSubtitle': 'सहायता प्राप्त करें और सहायता से संपर्क करें',
    'accountActions': 'खाता क्रियाएँ',
    'deleteAccount': 'खाता हटा दो',
    'deleteAccountSubtitle': 'अपना खाता स्थायी रूप से हटाने का अनुरोध करें',
    'logout': 'लॉग आउट',
    'logoutSubtitle': 'अपने खाते से साइन आउट करें',
    'confirmLogout': 'लॉगआउट की पुष्टि करें',
    'confirmLogoutMessage': 'क्या आप लॉग आउट करना चाहते हैं?',
    'cancel': 'रद्द करना',
    'loginAgain': 'फिर से लॉगिन करें',
    // ============================================
    // Language Related
    // ============================================
    'language': 'भाषा',
    'languageSubtitle': 'ऐप की भाषा बदलें',
    'notificationSettings': 'सूचना सेटिंग्स',
    'notificationSettingsSubtitle':
        'चुनें कि आप कौन सी सूचनाएं प्राप्त करना चाहते हैं।',
    'notificationChannels': 'चैनल',
    'pushNotifications': 'पुश सूचनाएं',
    'pushNotificationsSubtitle':
        'अपने डिवाइस पर पुश सूचनाएं प्राप्त करें',
    'emailNotifications': 'ईमेल सूचनाएं',
    'emailNotificationsSubtitle': 'ईमेल के माध्यम से सूचनाएं प्राप्त करें',
    'notificationModules': 'श्रेणी के अनुसार',
    'notificationSettingsSaved': 'सूचना सेटिंग्स सहेजी गईं',
    'notificationModuleProducts': 'उत्पाद',
    'notificationModuleProductOrders': 'उत्पाद ऑर्डर',
    'notificationModuleDeals': 'सौदे',
    'notificationModuleDealOrders': 'सौदा ऑर्डर',
    'notificationModuleBanners': 'बैनर',
    'notificationModuleAdmin': 'व्यवस्थापक',
    'notificationModuleEngagement': 'जुड़ाव',
    'notificationModulePayment': 'भुगतान',
    'push': 'पुश',
    'currency': 'मुद्रा',
    'currencySubtitle': 'कीमतों के लिए मुद्रा प्रदर्शित करें (डिफ़ॉल्ट: डिवाइस)',
    'systemDefault': 'प्रणालीगत चूक',
    'syncFxRates': 'एफएक्स दरों को सिंक करें',
    'syncFxRatesSubtitle': 'ईसीबी से नवीनतम विनिमय दरें प्राप्त करें',
    'syncFxRatesSuccess': 'एफएक्स दरें सफलतापूर्वक अपडेट की गईं',
    'syncFxRatesFailed': 'एफएक्स दरों को अपडेट नहीं किया जा सका. कैश्ड दरों का उपयोग करना.',
    'changingLanguage': 'भाषा बदल रही है...',
    'languageChangeFailed': 'भाषा प्राथमिकता समन्वयित करने में विफल. कृपया पुन: प्रयास करें।',
    'failedToChangeLanguage': 'भाषा बदलने में विफल. कृपया पुन: प्रयास करें।',
    'english': 'अंग्रेज़ी',
    'german': 'जर्मन',
    'turkish': 'तुर्की',
    'arabic': 'अरबी',
    'urdu': 'उर्दू',
    'hindi': 'हिंदी',
    'russian': 'रूसी',
    'sourceLanguageLabel': 'सामग्री की भाषा',
    'sourceLanguageHint': 'आपके द्वारा दर्ज किए गए पाठ की भाषा (अन्य भाषाओं में अनुवाद की जाएगी)',
    'selectYourLanguage': 'अपनी भाषा चुनें',
    'selectYourLanguageSubtitle':
        'ऐप के लिए भाषा चुनें। आप इसे बाद में सेटिंग्स में बदल सकते हैं।',
    'continueButton': 'जारी रखें',
    // ============================================
    // Common / General
    // ============================================
    'sessionExpired': 'सत्र समाप्त हुआ',
    'sessionExpiredMessage': 'आपका सत्र समाप्त हो गया है। ऐप का उपयोग जारी रखने के लिए कृपया दोबारा लॉग इन करें।',
    'comingSoon': 'जल्द आ रहा है',
    'retry': 'पुन: प्रयास करें',
    'error': 'गलती',
    'errorWithDetail': 'त्रुटि: {detail}',
    'close': 'बंद करना',
    'save': 'बचाना',
    'done': 'हो गया',
    'saving': 'सहेजा जा रहा है...',
    'update': 'अद्यतन',
    'edit': 'संपादन करना',
    'delete': 'मिटाना',
    'add': 'जोड़ना',
    'remove': 'निकालना',
    'select': 'चुनना',
    'all': 'सभी',
    'filter': 'फ़िल्टर',
    'type': 'प्रकार',
    'status': 'स्थिति',
    'unknown': 'अज्ञात',
    // ============================================
    // About Us Related
    // ============================================
    'welcomeToProductDeal': 'प्रोडक्ट डील में आपका स्वागत है',
    'trustedMarketplace': 'थोक उत्पादों और सौदों के लिए आपका विश्वसनीय बाज़ार',
    'ourMission': 'हमारा विशेष कार्य',
    'ourMissionContent': 'थोक विक्रेताओं और खुदरा विक्रेताओं को जोड़ने के लिए, सभी आकार के व्यवसायों के लिए थोक खरीदारी को सुलभ और कुशल बनाना।',
    'whatWeOffer': 'हमारी पेशकश',
    'whatWeOfferContent':
        '• सत्यापित थोक विक्रेताओं तक पहुंच'
        '• विशेष थोक सौदे और छूट'
        '• वास्तविक समय सूची ट्रैकिंग'
        '• सुरक्षित ऑर्डर प्रबंधन'
        '• स्थान-आधारित उत्पाद खोज',
    'forWholesalers': 'थोक विक्रेताओं के लिए',
    'forRetailers': 'खुदरा विक्रेताओं के लिए',
    'forRetailersContent': 'आस-पास के थोक विक्रेताओं के उत्पादों की खोज करें, थोक सौदों में भाग लें और अपने ऑर्डर को कुशलतापूर्वक प्रबंधित करें।',
    'forWholesalersContent': 'अपने उत्पादों का प्रदर्शन करें, विशेष सौदे बनाएं, ऑर्डर प्रबंधित करें और खुदरा विक्रेताओं के व्यापक नेटवर्क तक पहुंचें।',
    // ============================================
    // FAQ Related
    // ============================================
    'frequentlyAskedQuestions': 'अक्सर पूछे जाने वाले प्रश्नों',
    'commonQuestions': 'सामान्य प्रश्न',
    'faqQuestion1': 'मैं ऑर्डर कैसे दे सकता हूं?',
    'faqAnswer1': 'सक्रिय सौदे या उत्पाद ब्राउज़ करें, अपनी ज़रूरत की मात्रा चुनें और "ऑर्डर दें" पर क्लिक करें। थोक विक्रेता द्वारा आपके ऑर्डर की समीक्षा की जाएगी.',
    'faqQuestion2': 'डील ऑर्डर क्या हैं?',
    'faqAnswer2': 'डील ऑर्डर थोक खरीदारी के अवसर हैं जहां थोक विक्रेता लक्ष्य मात्रा तक पहुंचने पर रियायती कीमतों की पेशकश करते हैं। आप एक ही डील पर कई ऑर्डर दे सकते हैं।',
    'faqQuestion3': 'शिपिंग कैसे प्रबंधित की जाती है?',
    'faqAnswer3': 'आपके ऑर्डर की पुष्टि होने के बाद शिपिंग विवरण सीधे थोक विक्रेता के साथ व्यवस्थित किया जाता है। ऑर्डर की पुष्टि होने पर संपर्क जानकारी प्रदान की जाएगी।',
    'faqQuestion4': 'क्या मैं कोई ऑर्डर रद्द कर सकता हूँ?',
    'faqAnswer4': 'आप लंबित ऑर्डर रद्द कर सकते हैं. एक बार थोक विक्रेता द्वारा ऑर्डर की पुष्टि हो जाने पर, थोक विक्रेता की शर्तों के अनुसार रद्दीकरण नीतियां लागू होती हैं।',
    'faqQuestion5': 'मैं एक सत्यापित थोक व्यापारी कैसे बनूँ?',
    'faqAnswer5': 'सत्यापित होने के लिए हमारी सहायता टीम से संपर्क करें। आपको व्यावसायिक दस्तावेज़ प्रदान करने और सत्यापन प्रक्रिया पूरी करने की आवश्यकता होगी।',
    'faqQuestion6': 'उत्पादों को दूरी के आधार पर कैसे क्रमबद्ध किया जाता है?',
    'faqAnswer6': 'उत्पाद आपके स्थान से निकटता के आधार पर स्वचालित रूप से क्रमबद्ध होते हैं। सटीक दूरी-आधारित छँटाई के लिए अपनी प्रोफ़ाइल में अपना स्थान जोड़ना सुनिश्चित करें।',
    'faqQuestion7': 'कौन सी भुगतान विधियाँ स्वीकार की जाती हैं?',
    'faqAnswer7': 'भुगतान के तरीके थोक विक्रेता के अनुसार अलग-अलग होते हैं। ऑर्डर की पुष्टि के बाद भुगतान विवरण पर चर्चा की जाती है।',
    'faqQuestion8': 'मैं अपनी प्रोफाइल को कैसे अपडेट करूँ?',
    'faqAnswer8': 'डैशबोर्ड से अपने प्रोफ़ाइल पृष्ठ पर जाएं, अपनी जानकारी अपडेट करें और सहेजें। आप विभिन्न स्थानों के लिए अनेक पते जोड़ सकते हैं.',
    // ============================================
    // Wholesaler Directory Related
    // ============================================
    'couldNotLoadWholesalers': 'हम अभी थोक विक्रेताओं को लोड नहीं कर सके।',
    'verifiedPartners': 'सत्यापित भागीदार',
    'verifiedPartnersDescription': 'सत्यापित भागीदार',
    'noWholesalersNearYou': 'अभी तक आपके आस-पास कोई थोक विक्रेता नहीं है. आस-पास की इन्वेंट्री को अनलॉक करने के लिए अपना स्थान अपडेट करें।',
    // ============================================
    // Dashboard Related
    // ============================================
    'dashboard': 'डैशबोर्ड',
    'nearbyWholesalers': 'आसपास के थोक विक्रेता',
    'allWholesalers': 'सभी थोक विक्रेता',
    'noWholesalersFound': 'कोई थोक विक्रेता नहीं मिला',
    'errorLoadingWholesalers': 'थोक विक्रेताओं को लोड करने में त्रुटि',
    'advertiseWithUs': 'हमारे साथ विज्ञापन करें',
    'boostYourSales': 'अपनी बिक्री बढ़ाएँ!',
    'promoteYourProducts': 'यहां अपने उत्पादों का प्रचार करें और अधिक ग्राहकों तक पहुंचें।',
    'unableToLoadDashboard': 'डैशबोर्ड लोड करने में असमर्थ',
    'unableToLoadProduct': 'उत्पाद लोड करने में असमर्थ',
    'unableToLoadWholesaler': 'थोक विक्रेता लोड करने में असमर्थ',
    'spotlight': 'सुर्खियों',
    'spotlightWholesalersEmpty': 'बाज़ार में हलचल होने पर स्पॉटलाइट थोक विक्रेता यहां दिखाई देंगे।',
    // ============================================
    // Orders Related
    // ============================================
    'orderId': 'आदेश कामतत्व',
    'payment': 'भुगतान',
    'paymentStatus': 'भुगतान की स्थिति',
    'placedOn': 'पर रखा',
    'orderItems': 'आदेश आइटम',
    'createShipment': 'शिपमेंट बनाएं',
    'shippingAddress': 'शिपिंग पता',
    'notes': 'टिप्पणियाँ',
    'orderNotes': 'ऑर्डर नोट',
    'orderDetails': 'ऑर्डर का विवरण',
    'unableToLoadOrder': 'ऑर्डर लोड करने में असमर्थ',
    'updateOrderStatus': 'ऑर्डर स्थिति अपडेट करें',
    'subtotal': 'उप-योग',
    'shipping': 'शिपिंग',
    'shippingWithFreeThreshold': 'शिपिंग: {amount} ({threshold}+ इकाइयों के लिए निःशुल्क)',
    'freeShippingForThreshold': '{threshold}+ इकाइयों के लिए मुफ़्त शिपिंग',
    'shippingBaseOnly': 'शिपिंग: {amount}',
    'shippingWithPerUnit': 'शिपिंग: {base} + {perUnit} प्रति यूनिट',
    'total': 'कुल',
    'reasonOptional': 'कारण (वैकल्पिक)',
    'notesOptional': 'नोट्स (वैकल्पिक)',
    'sku': 'एसकेयू',
    'skuN/A': 'एसकेयू: एन/ए',
    'trackingAvailable': 'ट्रैकिंग उपलब्ध है',
    'shipped': 'लादा गया',
    'shipments': 'लदान',
    'shipmentId': 'शिपमेंट {id}',
    'trackingLabel': 'ट्रैकिंग: {number}',
    'track': 'रास्ता',
    'couldNotOpenTrackingUrl': 'ट्रैकिंग यूआरएल नहीं खुल सका',
    'carrierLabel': 'वाहक: {name}',
    'estDelivery': 'ईएसटी। डिलिवरी: {date}',
    'shippedAt': 'भेज दिया गया: {date}',
    'deliveredAt': 'वितरित: {date}',
    'each': 'प्रत्येक',
    'unit': 'इकाई',
    'noOrdersYet': 'अभी तक कोई आदेश नहीं',
    'noOrdersYetMessage': 'अपना पहला ऑर्डर देने के लिए उत्पाद और सौदे ब्राउज़ करें।',
    'unableToLoadOrders': 'आपके ऑर्डर लोड करने में असमर्थ',
    'orderPlaced': 'आदेश रखा',
    'confirmed': 'की पुष्टि',
    'delivered': 'पहुंचा दिया',
    'pendingOrders': 'लंबित ऑर्डर',
    'viewOrders': 'आदेश देखें',
    'allOrders': 'सभी आदेश',
    'pendingConfirmation': 'पुष्टिकरण लंबित है',
    'packing': 'पैकिंग',
    'packed': 'पैक्ड',
    'dispatched': 'भेजा गया',
    'outForDelivery': 'डिलीवरी के लिए निकले हैं',
    'viewDetails': 'विवरण देखें',
    'changeOrderStatus': 'ऑर्डर स्थिति बदलें',
    'orderStatusUpdatedSuccessfully': 'ऑर्डर स्थिति सफलतापूर्वक अपडेट की गई',
    'orderStatusUpdated': 'ऑर्डर स्थिति सफलतापूर्वक अपडेट की गई',
    'itemStatusUpdatedSuccessfully': 'आइटम स्थिति सफलतापूर्वक अपडेट की गई',
    'itemStatusUpdated': 'आइटम स्थिति सफलतापूर्वक अपडेट की गई',
    'ordersCountSuffix': 'आदेश',
    'order': 'आदेश',
    'orderLabel': 'आदेश',
    'orders': 'आदेश',
    'ordered': 'आदेश दिया',
    'dealOrder': 'डील ऑर्डर',
    'productOrder': 'उत्पाद क्रम',
    'bid': 'बोली',
    'itemPlusMore': '{item} + {n} और अधिक',
    // ============================================
    // Cart Related
    // ============================================
    'yourCart': 'आपकी गाड़ी',
    'cart': 'कार्ट',
    'emptyCart': 'आपकी गाड़ी खाली है',
    'emptyCartMessage': 'आरंभ करने के लिए अपने कार्ट में उत्पाद जोड़ें।',
    'addProductsToSeeThemHere': 'उत्पादों को यहां देखने के लिए उन्हें जोड़ें.',
    'placeOrderCashOnDelivery': 'ऑर्डर दें (डिलीवरी पर नकद)',
    'cashOnDelivery': 'डिलवरी पर नकदी',
    'paymentMethodCash': 'डिलीवरी पर नकद',
    'paymentMethodCashDesc': 'डिलीवरी मिलने पर भुगतान करें।',
    'paymentMethodInvoice': 'चालान',
    'paymentMethodInvoiceDesc':
        'हम चालान भेजते हैं; ऑर्डर पुष्टि के बाद शिपमेंट शुरू।',
    'paymentMethodBankTransfer': 'बैंक ट्रांसफर',
    'paymentMethodBankTransferDesc':
        'पहले भुगतान, फिर शिपमेंट। भुगतान निर्देश ईमेल से भेजे जाते हैं।',
    'paymentMode': 'भुगतान का तरीका',
    'paymentModeSubtitle':
        'आपके डील्स के लिए डिफ़ॉल्ट। आप इसे बाद में अपने प्रोफ़ाइल में बदल सकते हैं।',
    'paymentModeSubtitleMulti':
        'वे सभी भुगतान विधियाँ चुनें जो आप स्वीकार करते हैं। '
        'आप इसे बाद में अपने प्रोफ़ाइल में बदल सकते हैं।',
    'paymentSettings': 'भुगतान सेटिंग्स',
    'paymentSettingsSubtitle':
        'इनवॉइस/बैंक ट्रांसफर ऑर्डर के लिए बैंक विवरण। '
        'आप इन्हें बाद में अपने प्रोफ़ाइल में अपडेट कर सकते हैं।',
    'payWithCard': 'कार्ड से भुगतान करें',
    'placeOrderPayNow': 'ऑर्डर दें और भुगतान करें',
    'paymentAfterOrderConfirmed': 'आपके ऑर्डर की पुष्टि होने के बाद भुगतान का अनुरोध किया जाएगा (उदाहरण के लिए बैंक हस्तांतरण)।',
    'paymentNotAvailable': 'कार्ड से भुगतान उपलब्ध नहीं है. कैश ऑन डिलीवरी का प्रयास करें।',
    'paymentCancelled': 'भुगतान रद्द कर दिया गया.',
    'dealSucceededPayNow': 'सौदा सफल हुआ - अभी भुगतान करें',
    'totalToPay': 'भुगतान करने के लिए कुल',
    'payByInvoice': 'चालान द्वारा भुगतान करें',
    'payByCard': 'कार्ड से भुगतान करें',
    'invoiceInstructionsSent': 'भुगतान निर्देश ईमेल द्वारा भेजे गए थे.',
    'paymentInstructionsBankOnly': 'भुगतान निर्देश ईमेल द्वारा भेजे गए थे। बैंक हस्तांतरण द्वारा भुगतान करें. यदि आपने पहले ही भुगतान कर दिया है, तो सौदा स्वामी रसीद की पुष्टि करेगा।',
    'markAsPaid': 'भुगतान के रूप में चिह्नित करें',
    'paymentNotesOptional': 'भुगतान नोट (जैसे बैंक संदर्भ)',
    'myDealStats': 'मेरे सौदे के आँकड़े',
    'dealsJoined': 'सौदे जुड़े',
    'totalOrderedQuantity': 'आदेशित कुल मात्रा',
    'totalOrders': 'कुल ऑर्डर',
    'placeOrder': 'आदेश देना',
    'fxDisclaimer': 'एफएक्स दर परिवर्तन के अधीन है। प्रदर्शित राशि सांकेतिक है.',
    'placingOrder': 'ऑर्डर देना...',
    'orderPlacedSuccessfully': 'ऑर्डर सफलतापूर्वक दिया गया!',
    'failedToPlaceOrder': 'ऑर्डर देने में विफल',
    'onlyKioskCanOrder': 'केवल कियोस्क/शॉप खाते ही ऑर्डर दे सकते हैं।',
    'admins': 'व्यवस्थापक',
    'subAdmins': 'उप-व्यवस्थापक',
    'wholesalers': 'थोक',
    'canOnlyViewProducts': 'केवल उत्पाद देख सकते हैं. केवल कियोस्क/शॉप खाते ही ऑर्डर दे सकते हैं।',
    'addToCart': 'कार्ट में जोड़ें',
    'addedToCart': '✅ कार्ट में जोड़ा गया',
    'quantity': 'मात्रा',
    'unitPrice': 'यूनिट मूल्य',
    'totalAmount': 'कुल राशि',
    'buyer': 'क्रेता',
    'items': 'सामान',
    // ============================================
    // Registration Related
    // ============================================
    'register': 'पंजीकरण करवाना',
    'createAccount': 'खाता बनाएं',
    'createAccountTitle': 'खाता बनाएं',
    'createAccountSubtitle': 'क्यूरेटेड थोक विक्रेताओं, बड़े सौदों और लॉजिस्टिक्स सहायता को अनलॉक करें।',
    'fullName': 'पूरा नाम',
    'email': 'ईमेल',
    'workEmail': 'कार्य ईमेल',
    'phone': 'फ़ोन',
    'password': 'पासवर्ड',
    'confirmPassword': 'पासवर्ड की पुष्टि कीजिये',
    'confirmPasswordLabel': 'पासवर्ड की पुष्टि कीजिये',
    'businessName': 'व्यवसाय का नाम',
    'country': 'देश',
    'city': 'शहर',
    'address': 'पता',
    'streetAddress': 'सड़क का पता',
    'addressWillBeGeocoded': 'निर्देशांक प्राप्त करने के लिए पता स्वचालित रूप से जियोकोड हो जाएगा',
    'addressSearchHint': 'अपना पता खोजें',
    'placesLookupFailed':
        'सर्वर से पते का विवरण लोड नहीं हो सका। आप अपना पता मैन्युअल रूप से '
        'टाइप या संपादित कर सकते हैं।',
    'placesNoAddressResults':
        'कोई पता नहीं मिला। कोई अन्य खोज आज़माएँ।',
    'placesAddressSearchConfigError':
        'पता खोज उपलब्ध नहीं है। अपना नेटवर्क जांचें और सुनिश्चित करें कि ऐप '
        'सही API सर्वर (API_BASE_URL) का उपयोग करता है।',
    'placesAddressSearchRequestFailed':
        'पता खोज विफल रही। अपना कनेक्शन जांचें या बाद में पुनः प्रयास करें।',
    'getLocation': 'स्थान प्राप्त करें',
    'selectRole': 'भूमिका चुनें',
    'accountType': 'खाता प्रकार',
    'alreadyHaveAccount': 'क्या आपके पास पहले से एक खाता मौजूद है?',
    'login': 'लॉग इन करें',
    'signIn': 'दाखिल करना',
    'registrationReceived': 'पंजीकरण प्राप्त हुआ! खाता स्वीकृत होने पर हम आपको सूचित करेंगे।',
    'fullNameRequired': 'पूरा नाम आवश्यक है',
    'fullNameMinLength': 'पूरा नाम कम से कम 3 अक्षर का होना चाहिए',
    'emailRequired': 'ईमेल की जरूरत है',
    'provideValidEmail': 'एक वैध ईमेल प्रदान करें',
    'phoneNumberOptional': 'दूरभाष क्रमांक (वैकल्पिक)',
    'enterValidPhoneNumber': 'एक वैध फ़ोन नंबर दर्ज करें',
    'kioskShopNameOptional': 'कियॉस्क/दुकान का नाम (वैकल्पिक)',
    'companyName': 'कंपनी का नाम',
    'latitudeOptional': 'अक्षांश (वैकल्पिक)',
    'longitudeOptional': 'देशांतर (वैकल्पिक)',
    'locating': 'पता लगाया जा रहा है...',
    'locatingEllipsis': 'पता लगाया जा रहा है...',
    'useCurrentLocation': 'वर्तमान स्थान का उपयोग करें',
    'enableLocationServices': 'स्वचालित रूप से निर्देशांक भरने के लिए स्थान सेवाएँ सक्षम करें।',
    'enableLocationPermissions': 'स्वचालित रूप से निर्देशांक भरने के लिए स्थान अनुमतियाँ सक्षम करें।',
    'unableToFetchLocation': 'स्थान लाने में असमर्थ. कृपया पुन: प्रयास करें।',
    'unableToFetchLocationShort': 'स्थान लाने में असमर्थ.',
    'pleaseEnterValidLatLng': 'कृपया मान्य अक्षांश और देशांतर दर्ज करें.',
    'createPassword': 'पासवर्ड बनाएं',
    'minimum8CharactersRequired': 'न्यूनतम 8 अक्षर आवश्यक हैं',
    'weVerifyEveryBusiness': 'बाज़ार को विश्वसनीय बनाए रखने के लिए हम प्रत्येक व्यवसाय को मैन्युअल रूप से सत्यापित करते हैं।',
    'submitForReview': 'समीक्षा हेतु सबमिट करें',
    'alreadyVerifiedSignIn': 'पहले से ही सत्यापित? दाखिल करना',
    'forgotPassword': 'पासवर्ड भूल गए?',
    'welcomeBack': 'वापसी पर स्वागत है',
    'signInToReach': 'अपने नजदीकी अनुमोदित थोक विक्रेताओं तक पहुंचने के लिए साइन इन करें।',
    'createKioskOrWholesalerAccount': 'एक कियोस्क या थोक विक्रेता खाता बनाएँ',
    'accountSubmittedForApproval': 'खाता अनुमोदन हेतु प्रस्तुत किया गया. स्वीकृत होते ही डैशबोर्ड अनलॉक हो जाएगा।',
    'dashboardWillUnlock': 'स्वीकृत होते ही डैशबोर्ड अनलॉक हो जाएगा।',
    'pleaseLoginToPlaceOrder': 'कृपया ऑर्डर देने के लिए लॉग इन करें',
    // ============================================
    // Legal / Compliance (T&C + GDPR)
    // ============================================
    'legalComplianceTitle': 'कानूनी एवं अनुपालन',
    'termsAndConditionsFullText': 'एक खाता बनाकर आप प्लेटफ़ॉर्म ऑपरेटर के साथ व्यावसायिक संबंध में प्रवेश करते हैं और प्लेटफ़ॉर्म के नियमों और शर्तों (एजीबी) से सहमत होते हैं। ये शर्तें नियंत्रित करती हैं कि आप बाज़ार का उपयोग कैसे कर सकते हैं, सौदे और ऑर्डर कैसे प्रबंधित किए जाते हैं, और खरीदारों और थोक विक्रेताओं पर कौन से दायित्व लागू होते हैं। आप पुष्टि करते हैं कि आपके द्वारा प्रदान की गई सभी जानकारी सटीक है और आप केवल वैध व्यावसायिक उद्देश्यों के लिए मंच का उपयोग करेंगे। आप इस बात से भी सहमत हैं कि थोक विक्रेता द्वारा पुष्टि किए जाने पर या सौदे का लक्ष्य पूरा हो जाने पर सौदे और ऑर्डर बाध्यकारी हो सकते हैं। आपके अधिकार क्षेत्र के आधार पर अतिरिक्त देश-विशिष्ट नियम लागू हो सकते हैं। कृपया जारी रखने से पहले ऑपरेटर द्वारा साझा किए गए पूर्ण नियम और शर्तों की समीक्षा करें।',
    'scrollToAcceptTerms': 'स्वीकृति चेकबॉक्स को अनलॉक करने के लिए नियम और शर्तों के अंत तक स्क्रॉल करें।',
    'scrollToBottom': 'नीचे स्क्रॉल करें',
    'acceptTermsLabel': 'मैंने नियम एवं शर्तें (एजीबी) पढ़ ली हैं और उन्हें स्वीकार करता हूं।',
    'termsScrollHint': 'कृपया स्वीकार करने से पहले नियम एवं शर्तों को पढ़ लें।',
    'acceptPrivacyLabel': 'मैंने डेटा गोपनीयता/जीडीपीआर नीति को पढ़ लिया है और स्वीकार कर लिया है।',
    'privacySummaryText': 'आपका डेटा हमारी गोपनीयता नीति के अनुरूप खाता प्रबंधन, ऑर्डर, विश्लेषण और सुरक्षा के लिए संसाधित किया जाएगा।',
    'mustAcceptAllLegalDocuments': 'कृपया सभी कानूनी दस्तावेज़ स्वीकार करें और फ़्रेमवर्क अनुबंध की पुष्टि करें।',
    'mustAcceptTermsAndPrivacy': 'जारी रखने के लिए कृपया नियम एवं शर्तें और डेटा गोपनीयता/जीडीपीआर स्वीकार करें।',
    // ============================================
    // Account Approval / Waiting Screen Related
    // ============================================
    'accountApproval': 'खाता अनुमोदन',
    'accountApproved': 'खाता स्वीकृत!',
    'redirecting': 'पुनर्निर्देशन...',
    'pendingReview': 'समीक्षा लंबित है',
    'needMoreInfo': 'अधिक जानकारी चाहिए',
    'wholesalerVerificationMessage': 'धन्यवाद! अपने थोक विक्रेता खाते को सक्रिय करने के लिए, कृपया अपने व्यवसाय सत्यापन दस्तावेज़ जमा करें। हमारा व्यवस्थापक आपके खाते की समीक्षा करेगा और उसे स्वीकृत करेगा।',
    'buyerVerificationMessage': 'धन्यवाद! अपने खरीदार खाते को सक्रिय करने के लिए, कृपया अपने पहचान सत्यापन दस्तावेज़ जमा करें। हमारा व्यवस्थापक आपके खाते की समीक्षा करेगा और उसे स्वीकृत करेगा।',
    'generalVerificationMessage': 'धन्यवाद! अपना खाता सक्रिय करने के लिए, कृपया सत्यापन दस्तावेज़ जमा करें। हमारा व्यवस्थापक आपके खाते की समीक्षा करेगा और उसे स्वीकृत करेगा।',
    'adminNote': 'व्यवस्थापक नोट',
    'uploadVerificationDocument': 'सत्यापन दस्तावेज़ अपलोड करें',
    'acceptedDocumentTypes': 'स्वीकृत दस्तावेज़ प्रकार',
    'wholesalerDocumentTypes': 'व्यवसाय लाइसेंस, टैक्स आईडी, कंपनी पंजीकरण दस्तावेज़ (पीएनजी, जेपीजी, पीडीएफ)',
    'buyerDocumentTypes': 'पहचान पत्र, ड्राइवर का लाइसेंस, या कोई सरकार द्वारा जारी आईडी (पीएनजी, जेपीजी, पीडीएफ)',
    'generalDocumentTypes': 'व्यवसाय लाइसेंस, चालक लाइसेंस, पहचान पत्र (पीएनजी, जेपीजी, पीडीएफ)',
    'selectedDocuments': 'चयनित दस्तावेज़',
    'addDocuments': 'दस्तावेज़ जोड़ें',
    'uploading': 'अपलोड हो रहा है...',
    'uploaded': 'अपलोड किए गए',
    'selectFirst': 'प्रथम का चयन करें',
    'documentsUploadedSuccessfully': 'दस्तावेज़ सफलतापूर्वक अपलोड हो गए। हमारा व्यवस्थापक आपके खाते की स्थिति की समीक्षा करेगा और उसे अपडेट करेगा।',
    'documentUploadedSuccessfully': 'दस्तावेज़ सफलतापूर्वक अपलोड हो गया. हमारा व्यवस्थापक आपके खाते की स्थिति की समीक्षा करेगा और उसे अपडेट करेगा।',
    'failedToPickDocuments': 'दस्तावेज़ लेने में विफल',
    'passport': 'पासपोर्ट',
    'passportDescription': 'पहचान सत्यापन के लिए अपना पासपोर्ट अपलोड करें',
    'passportAlternative': 'यदि आपके पास पासपोर्ट नहीं है, तो आप पते के साथ सरकार द्वारा अनुमोदित आईडी कार्ड अपलोड कर सकते हैं (उदाहरण के लिए, भारत में आधार, राष्ट्रीय आईडी, आदि)',
    'gewerbeschein': 'Gewerbeschein',
    'idCard': 'आईडी कार्ड',
    'taxId': 'टैक्स आईडी',
    'companyRegistration': 'कंपनी पंजीकरण',
    'document': 'दस्तावेज़',
    'gewerbescheinDescription': 'व्यवसाय सत्यापन के लिए अपना Gewerbeschein (व्यापार लाइसेंस) अपलोड करें',
    'gewerbescheinAlternative': 'अधिकारियों द्वारा जारी अपना आधिकारिक व्यापार लाइसेंस दस्तावेज़ अपलोड करें',
    'businessLicense': 'बिजनेस लाइसेंस / ग्वेर्बेशिन',
    'businessLicenseDescription': 'व्यवसाय सत्यापन के लिए अपना व्यवसाय लाइसेंस या Gewerbeschein अपलोड करें',
    'businessLicenseAlternative': 'यदि आपके पास व्यवसाय लाइसेंस नहीं है, तो आप कंपनी पंजीकरण दस्तावेज़, टैक्स आईडी, या कोई आधिकारिक व्यवसाय सत्यापन दस्तावेज़ अपलोड कर सकते हैं',
    'selectDocument': 'दस्तावेज़ चुनें',
    'changeDocument': 'दस्तावेज़ बदलें',
    'pleaseSelectAtLeastOneDocument': 'कृपया अपलोड करने के लिए कम से कम एक दस्तावेज़ चुनें।',
    'sendByEmail': 'ईमेल से भेजें',
    'emailOptionDescription': 'वैकल्पिक रूप से, आप अपने सत्यापन दस्तावेज़ सीधे ईमेल के माध्यम से भेज सकते हैं। हमारा व्यवस्थापक दस्तावेज़ों का सत्यापन करेगा और तदनुसार आपके खाते की स्थिति अपडेट करेगा।',
    'openEmailToAdmin': 'व्यवस्थापक को ईमेल खोलें',
    'emailDraftOpened': 'ईमेल ड्राफ्ट खोला गया. कृपया इसे पूरा सबमिशन करने के लिए भेजें। हमारा व्यवस्थापक आपके दस्तावेज़ों का सत्यापन करेगा और आपके खाते की स्थिति अपडेट करेगा।',
    'couldNotOpenEmailApp': 'ईमेल ऐप नहीं खुल सका. कृपया एक ईमेल भेजें',
    'manually': 'मैन्युअल',
    'failedToOpenEmail': 'ईमेल खोलने में विफल',
    'loadingAccountStatus': 'खाता स्थिति लोड हो रही है...',
    'errorLoadingStatus': 'स्थिति लोड करने में त्रुटि',
    'pleaseReviewAndResubmit': 'कृपया अपने दस्तावेज़ों की समीक्षा करें और पुनः सबमिट करें।',
    'useDifferentAccount': 'अलग खाता उपयोग करें',
    'useDifferentAccountConfirm':
        'किसी अलग खाते से लॉग इन या रजिस्टर करने के लिए साइन आउट करें?',
    'failedToUpdateStatus': 'कानूनी सेटिंग अपडेट करने में विफल. कृपया पुन: प्रयास करें।',
    // ============================================
    // Profile Related
    // ============================================
    'editProfile': 'प्रोफ़ाइल संपादित करें',
    'profileUpdated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई',
    'failedToUpdateProfile': 'प्रोफ़ाइल अपडेट करने में विफल',
    'profileImageUpdated': 'प्रोफ़ाइल छवि अपडेट की गई',
    'failedToUploadImage': 'छवि अपलोड करने में विफल',
    'tagline': 'TAGLINE',
    'locations': 'स्थानों',
    'addLocation': 'स्थान जोड़ना',
    'editLocation': 'स्थान संपादित करें',
    'deleteLocation': 'स्थान हटाएँ',
    'latitude': 'अक्षांश',
    'longitude': 'देशान्तर',
    'nameIsRequired': 'नाम आवश्यक है',
    'businessNameOptional': 'व्यवसाय का नाम (वैकल्पिक)',
    'phoneOptional': 'दूरवाणी वैकल्पिक)',
    'addresses': 'पतों',
    'addAddress': 'पता जोड़ें',
    'noAddressesAdded': 'कोई पता नहीं जोड़ा गया',
    'addYourFirstAddress': 'आरंभ करने के लिए अपना पहला पता जोड़ें',
    'editAddress': 'पता संपादित करें',
    'removeAddress': 'पता हटाएँ',
    'editAddressTitle': 'पता संपादित करें',
    'addAddressTitle': 'पता जोड़ें',
    'saveChanges': 'परिवर्तनों को सुरक्षित करें',
    'labelExample': 'लेबल (जैसे घर, कार्यालय, मुख्य आउटलेट)',
    'streetAreaOptional': 'सड़क/क्षेत्र (वैकल्पिक)',
    'countryOptional': 'देश (वैकल्पिक)',
    'cityOptional': 'शहर (वैकल्पिक)',
    'locationNotUpdating': 'स्थान अपडेट नहीं हो रहा है',
    'locationNotUpdatingSolution': 'प्रोफ़ाइल > पते पर जाएँ और सुनिश्चित करें कि आपके स्थान निर्देशांक सही हैं',
    // ============================================
    // Deals Related
    // ============================================
    'deals': 'सौदा',
    'activeDeals': 'सक्रिय सौदे',
    'allDeals': 'सभी सौदे',
    'myDeals': 'मेरे सौदे',
    'manageDeals': 'सौदे प्रबंधित करें',
    'noDealsFound': 'कोई डील नहीं मिली',
    'selectDeal': 'डील चुनें',
    'unableToLoadDeals': 'सौदे लोड करने में असमर्थ',
    'noDealsAvailable': 'कोई डील उपलब्ध नहीं है',
    'noDealsYet': 'अभी तक कोई डील नहीं',
    'checkBackLaterForNewDeals': 'नए सौदों के लिए बाद में दोबारा जाँचें',
    'noActiveDeals': 'कोई सक्रिय डील नहीं',
    'filterDeals': 'डील फ़िल्टर करें',
    'progress': 'प्रगति',
    'dealClosed': 'डील बंद',
    'ends': 'समाप्त होता है',
    'variant': 'प्रकार',
    'min': 'न्यूनतम:',
    'max': 'अधिकतम:',
    'perUnit': '/इकाई',
    'perUnitLabel': 'प्रति {unit}',
    'inStock': 'स्टॉक में',
    'similarProducts': 'समान उत्पाद',
    'noActiveDealsForProduct': 'इस उत्पाद के लिए कोई सक्रिय डील नहीं',
    'activeDealsForProduct': 'इस उत्पाद के लिए सक्रिय सौदे',
    'moreFromWholesaler': '{name} से अधिक',
    'dealsFromWholesaler': '{name} से डील',
    'productsFromWholesaler': '{name} से उत्पाद',
    'searchProductsFromWholesaler': '{name} से उत्पाद खोजें...',
    'onlyKioskCanPurchase': 'केवल कियोस्क/शॉप खाते ही उत्पाद खरीद सकते हैं',
    'canOnlyReviewFromDelivered': 'आप केवल वितरित ऑर्डर के उत्पादों की समीक्षा कर सकते हैं',
    'alreadyReviewedThisProduct': 'आप इस ऑर्डर से पहले ही इस उत्पाद की समीक्षा कर चुके हैं',
    'selectOrderToReview': 'समीक्षा करने के लिए आदेश का चयन करें',
    'orderN': 'आदेश #{id}',
    'viewDeals': 'सौदे देखें',
    'locationInfoNotAvailable': 'स्थान की जानकारी उपलब्ध नहीं है',
    'location': 'जगह',
    'kfProductDealTagline': 'केएफ उत्पाद डील, आपको सर्वोत्तम सौदे ढूंढने में मदद करता है',
    'errorSearchingProducts': 'उत्पाद खोजने में त्रुटि',
    'myDealOrders': 'मेरा डील ऑर्डर',
    'noDealOrdersYet': 'अभी तक कोई डील ऑर्डर नहीं',
    'browseDealsPlaceFirstOrder': 'सक्रिय सौदे ब्राउज़ करें और अपना पहला ऑर्डर दें।',
    'statusLabel': 'स्थिति',
    'noProductsFoundForWholesaler': 'चयनित थोक विक्रेता के लिए कोई उत्पाद नहीं मिला',
    'noApprovedWholesalersAvailable': 'कोई अनुमोदित थोक विक्रेता उपलब्ध नहीं है',
    'searchByNameBusinessEmail': 'नाम, व्यवसाय नाम, ईमेल द्वारा खोजें...',
    'selectWholesaler': 'थोक विक्रेता का चयन करें',
    'selectProduct': 'उत्पाद का चयन करें',
    'pageNOfM': 'पेज {current} / {total}',
    'priceLabel': 'कीमत',
    'pleaseSelectImageOrVideo': 'कृपया कोई छवि या वीडियो चुनें',
    'onlyWholesalersCreateStories': 'केवल थोक विक्रेता ही कहानियाँ बना सकते हैं',
    'storyCreatedSuccessfully': 'कहानी सफलतापूर्वक बनाई गई! 🎉',
    'uploadingMedia': 'मीडिया अपलोड हो रहा है...',
    'creatingStory': 'कहानी बनाई जा रही है...',
    'storyMedia': 'स्टोरी मीडिया',
    'videoSelected': 'वीडियो चयनित',
    'activeShopsSuffix': 'सक्रिय दुकानें',
    'storiesCountSuffix': 'कहानियां',
    'create': 'बनाएं',
    'off': 'बंद',
    'minOrder': 'मिनीमम ऑर्डर',
    'target': 'लक्ष्य',
    'units': 'इकाइयां',
    'dealCreatedSuccessfully': 'डील सफलतापूर्वक संपन्न हुई',
    'createDeal': 'डील बनाएं',
    'editDeal': 'डील संपादित करें',
    'closeDeal': 'डील बंद करें',
    'closeDealConfirmMessage': 'क्या आप वाकई यह सौदा बंद करना चाहते हैं? इस एक्शन को वापस नहीं किया जा सकता।',
    'closeDealGoalReached': 'लक्ष्य प्राप्त हुआ',
    'closeDealGoalReachedHint': 'यदि जाँच की गई: सभी लंबित ऑर्डर स्वतः-पुष्टि कर दिए जाएंगे (सौदा सफलतापूर्वक भरा गया)। यदि अनियंत्रित है: सौदा बंद हो जाएगा लेकिन आप बाद में मैन्युअल रूप से ऑर्डर की पुष्टि कर सकते हैं।',
    'createYourFirstDeal': 'अपनी पहली डील बनाएं',
    'dealTitle': 'डील का शीर्षक',
    'pleaseEnterDealTitle': 'कृपया डील का शीर्षक दर्ज करें',
    'dealType': 'डील का प्रकार',
    'dealPrice': 'सौदे की कीमत',
    'startDate': 'आरंभ करने की तिथि',
    'endDate': 'अंतिम तिथि',
    'pleaseEnterDealPrice': 'कृपया डील मूल्य दर्ज करें',
    'originalPrice': 'असली कीमत',
    'targetQuantity': 'लक्ष्य मात्रा',
    'pleaseEnterTargetQuantity': 'कृपया लक्ष्य मात्रा दर्ज करें',
    'targetQuantityMin': 'लक्ष्य मात्रा कम से कम 1 होनी चाहिए',
    'minOrderQty': 'न्यूनतम आदेश मात्रा',
    'pleaseEnterMinOrderQty': 'कृपया न्यूनतम ऑर्डर मात्रा दर्ज करें',
    'minOrderQtyMin': 'न्यूनतम ऑर्डर मात्रा कम से कम 1 होनी चाहिए',
    'maxOrderQuantityOptional': 'अधिकतम ऑर्डर मात्रा (वैकल्पिक)',
    'endDateMustBeAfterStartDate': 'समाप्ति तिथि आरंभ तिथि के बाद की होनी चाहिए',
    'pleaseSelectWholesalerFirst': 'कृपया पहले एक थोक विक्रेता का चयन करें',
    'auction': 'नीलामी',
    'priceDrop': 'कीमत में गिरावट',
    'limitedStock': 'सीमित स्टॉक',
    'scheduled': 'अनुसूचित',
    'live': 'रहना',
    'highlightedDeal': 'हाइलाइट डील',
    'canOnlyViewDeals': 'केवल सौदे देख सकते हैं। केवल कियोस्क/शॉप खाते ही ऑर्डर दे सकते हैं।',
    'dealProgressNotUpdating': 'डील की प्रगति अपडेट नहीं हो रही है',
    'dealProgressNotUpdatingSolution': 'डील की प्रगति स्वचालित रूप से अपडेट होती है। यदि यह अटका हुआ लगता है, तो पृष्ठ को ताज़ा करें',
    'dealProgress': 'सौदे की प्रगति',
    'unableToLoadProgress': 'प्रगति लोड करने में असमर्थ: {detail}',
    'noOrdersPlacedYet': 'इस डील पर अभी तक कोई ऑर्डर नहीं दिया गया है.',
    'orderPlacedSuffix': 'आदेश रखा',
    'ordersPlacedSuffix': 'आदेश दिए गए',
    'closed': 'बंद किया हुआ',
    // ============================================
    // Products Related
    // ============================================
    'product': 'उत्पाद',
    'products': 'उत्पादों',
    'productsSection': 'उत्पादों',
    'allProducts': 'सभी प्रोडक्ट',
    'myProducts': 'मेरे उत्पाद',
    'noProductsAvailable': 'कोई उत्पाद उपलब्ध नहीं',
    'noProductsYet': 'अभी तक कोई उत्पाद नहीं',
    'addYourFirstProduct': 'अपना पहला उत्पाद जोड़ें',
    'addFirstProduct': 'अपना पहला उत्पाद जोड़ें',
    'addProduct': 'उत्पाद जोड़ें',
    'editProduct': 'उत्पाद संपादित करें',
    'deleteProduct': 'उत्पाद हटाएँ',
    'deletingProduct': 'उत्पाद हटाया जा रहा है...',
    'deleteProductConfirmGeneric': 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं? इस एक्शन को वापस नहीं किया जा सकता।',
    'productUpdatedSuccessfully': 'उत्पाद सफलतापूर्वक अपडेट किया गया',
    'productCreatedSuccessfully': 'उत्पाद सफलतापूर्वक बनाया गया',
    'productDeletedSuccessfully': 'उत्पाद सफलतापूर्वक हटा दिया गया',
    'changeProductStatus': 'उत्पाद स्थिति बदलें',
    'changeStatus': 'स्थिति बदलें',
    'updatingStatus': 'स्थिति अपडेट हो रही है...',
    'statusUpdatedToPending': 'स्थिति को लंबित में अद्यतन किया गया',
    'statusUpdatedToApproved': 'स्थिति को स्वीकृत में अद्यतन किया गया',
    'statusUpdatedToRejected': 'स्थिति को अस्वीकृत में अद्यतन किया गया',
    'productsWillAppearHere': 'उत्पाद जुड़ते ही यहां दिखाई देंगे',
    'noProductsFound': 'कोई उत्पाद नहीं मिला',
    'youveReachedEnd': 'आप अंत तक पहुंच गए हैं',
    'errorLoadingProducts': 'उत्पाद लोड करने में त्रुटि',
    'featuredCatalog': 'विशेष सूची',
    'viewAll': 'सभी को देखें',
    'outOfStock': 'स्टॉक ख़त्म',
    'onlyLeft': 'केवल',
    'left': 'बाएं',
    'timeRemainingDay': '{count} दिन बाकी',
    'timeRemainingDays': '{count} दिन बाकी',
    'timeRemainingHour': '{count} घंटा बाकी',
    'timeRemainingHours': '{count} घंटे बाकी',
    'timeRemainingMinute': '{count} मिनट बाकी',
    'timeRemainingMinutes': '{count} मिनट बाकी',
    'pleaseSelectProduct': 'कृपया एक उत्पाद चुनें',
    'tapToSelectProduct': 'किसी उत्पाद का चयन करने के लिए टैप करें',
    'unknownProduct': 'अज्ञात उत्पाद',
    'searchProductsHint': 'नाम, SKU से उत्पाद खोजें...',
    'loadingMoreProducts': 'अधिक उत्पाद लोड हो रहे हैं...',
    'reachedEnd': 'आप अंत तक पहुंच गए हैं',
    'productsCountSuffix': 'उत्पादों',
    'price': 'कीमत',
    'kilogram': 'किलोग्राम',
    'gram': 'ग्राम',
    'liter': 'लीटर',
    'milliliter': 'मिलीलीटर',
    'piece': 'टुकड़ा',
    'box': 'डिब्बा',
    'pack': 'सामान बाँधना',
    'kmAway': 'किमी दूर',
    'viewAllProducts': 'सभी उत्पाद देखें',
    // ============================================
    // Product Management Related
    // ============================================
    'productTitle': 'उत्पाद शीर्षक',
    'productTitleRequired': 'कृपया उत्पाद शीर्षक दर्ज करें',
    'titleMinLength': 'शीर्षक कम से कम 3 अक्षर का होना चाहिए',
    'description': 'विवरण',
    'category': 'वर्ग',
    'wholesaler': 'थोक विक्रेता',
    'selectCategory': 'श्रेणी चुनना',
    'selectCategories': 'श्रेणियाँ चुनें',
    'pleaseSelectCategory': 'कृपया एक कैटेगरी चयनित करें',
    'tapToSelectCategory': 'किसी श्रेणी का चयन करने के लिए टैप करें',
    'pleaseSelectWholesaler': 'कृपया एक थोक विक्रेता का चयन करें',
    'tapToSelectWholesaler': 'थोक विक्रेता का चयन करने के लिए टैप करें',
    'unknownCategory': 'अज्ञात श्रेणी',
    'yourAccount': 'आपका खाता',
    'currentUser': 'तात्कालिक प्रयोगकर्ता',
    'variants': 'वेरिएंट',
    'useVariants': 'वेरिएंट का प्रयोग करें',
    'addVariant': 'वैरिएंट जोड़ें',
    'addAttribute': 'विशेषता जोड़ें',
    'variantSkuRequired': 'SKU आवश्यक है',
    'addAtLeastOneVariant': 'कृपया कम से कम एक प्रकार जोड़ें',
    'selectVariant': 'वैरिएंट चुनें',
    'selectVariantHelper': 'इस सौदे के लिए एक प्रकार चुनें',
    'noVariantsMessage': 'इस उत्पाद का कोई प्रकार नहीं है. सीधे प्रोडक्ट पर बनेगी डील.',
    'unableToLoadVariantsMessage': 'वेरिएंट लोड करने में असमर्थ. प्रोडक्ट पर डील बनेगी.',
    'featuredProduct': 'विशेष उत्पाद',
    'default': 'गलती करना',
    'updateProduct': 'उत्पाद अद्यतन करें',
    'createProduct': 'उत्पाद बनाएं',
    'globalAttributes': 'वैश्विक गुण',
    'globalAttributesDescription': 'सभी प्रकारों पर लागू करने के लिए रंग, आकार जैसी विशेषताओं को परिभाषित करें।',
    'attributeName': 'गुण नाम (जैसे रंग)',
    'attributeNameHint': 'रंग, आकार, सामग्री...',
    'imageUrl': 'छवि यूआरएल',
    'productImages': 'उत्पाद छवियाँ',
    'firstImagePrimary': 'पहली छवि प्राथमिक है',
    'addImageUrl': 'यूआरएल जोड़ें',
    'pasteImageUrlHint': 'छवि URL चिपकाएँ',
    'costPrice': 'लागत मूल्य',
    'stock': 'भंडार',
    'stockRequired': 'कृपया स्टॉक दर्ज करें',
    'stockNegative': 'स्टॉक नकारात्मक नहीं हो सकता',
    'priceRequired': 'कृपया कीमत दर्ज करें',
    'pricePositive': 'कीमत 0 से अधिक होनी चाहिए',
    'validationError': 'सत्यापन त्रुटि',
    'checkAllFields': 'कृपया सभी फ़ील्ड जांचें',
    'pending': 'लंबित',
    'approved': 'अनुमत',
    'rejected': 'अस्वीकार कर दिया',
    'draft': 'मसौदा',
    'failedToCreateDeal': 'सौदा बनाने में विफल',
    'invalidDateTimeFormat': 'अमान्य दिनांक/समय प्रारूप. कृपया अपनी तिथियां जांचें.',
    // ============================================
    // Categories Related
    // ============================================
    'noCategoriesFound': 'कोई श्रेणियां नहीं मिलीं',
    'noCategoriesAvailable': 'कोई श्रेणियां उपलब्ध नहीं',
    'allCategories': 'सभी श्रेणियाँ',
    'searchCategories': 'श्रेणियां खोजें...',
    'noCategoriesMatchSearch': 'कोई भी श्रेणियां आपकी खोज से मेल नहीं खातीं',
    'categoriesWillAppearHere': 'श्रेणियाँ जुड़ते ही यहाँ दिखाई देंगी',
    'tryDifferentSearchTerm': 'कोई भिन्न खोज शब्द आज़माएँ',
    'errorLoadingCategories': 'श्रेणियां लोड करने में त्रुटि',
    'unableToLoadCategory': 'श्रेणी लोड करने में असमर्थ',
    'productsCount': '{n} उत्पाद',
    'categoryName': 'श्रेणी नाम',
    'categoryDescription': 'विवरण',
    'categoryImageUrl': 'छवि यूआरएल',
    'createCategory': 'श्रेणी बनाएं',
    'editCategory': 'श्रेणी संपादित करें',
    'deleteCategory': 'श्रेणी हटाएँ',
    'deleteCategoryConfirm': 'क्या आप वाकई "{name}" को हटाना चाहते हैं? इस एक्शन को वापस नहीं किया जा सकता।',
    'categoryCreatedSuccessfully': 'श्रेणी सफलतापूर्वक बनाई गई',
    'enterCategoryDescriptionToGenerate': 'स्वचालित रूप से सामग्री उत्पन्न करने के लिए एक श्रेणी विवरण दर्ज करें।',
    'categoryDescriptionHint': 'जैसे, जैविक सब्जियाँ...',
    'contentGeneratedSuccessfullyEnglish': 'सामग्री सफलतापूर्वक उत्पन्न हुई! (अंग्रेज़ी)',
    'generationFailedWithError': 'जनरेशन विफल: {error}',
    'categoryUpdatedSuccessfully': 'श्रेणी सफलतापूर्वक अपडेट की गई',
    'categoryDeletedSuccessfully': 'श्रेणी सफलतापूर्वक हटा दी गई',
    'categoryCreationImportMessage': 'श्रेणी निर्माण वर्तमान में आयात के माध्यम से किया जाता है। कृपया व्यवस्थापक से संपर्क करें.',
    'pleaseEnterCategoryName': 'कृपया एक श्रेणी का नाम दर्ज करें',
    // ============================================
    // Reviews Related
    // ============================================
    'reviewed': 'समीक्षित',
    'youHaveAlreadyReviewed': 'आप इस ऑर्डर से पहले ही इस उत्पाद की समीक्षा कर चुके हैं',
    'reviewUpdatedSuccessfully': 'समीक्षा सफलतापूर्वक अपडेट की गई',
    'reviewSubmittedSuccessfully': 'समीक्षा सफलतापूर्वक सबमिट की गई',
    'pleaseSelectRating': 'कृपया एक रेटिंग चुनें',
    'maximum5ImagesAllowed': 'अधिकतम 5 छवियों की अनुमति है',
    'failedToPickImage': 'छवि चुनने में विफल',
    'failedToUploadImages': 'छवियाँ अपलोड करने में विफल',
    'uploadImages': 'छवियाँ अपलोड करें',
    'pickImage': 'छवि चुनें',
    'pickVideo': 'वीडियो चुनें',
    'uploadFailed': 'अपलोड विफल रहा',
    'upload': 'अपलोड करें',
    'invalidImageUrl': 'अमान्य छवि URL',
    // ============================================
    // Banners Related
    // ============================================
    'viewProduct': 'उत्पाद देखें',
    'viewDeal': 'डील देखें',
    'openLink': 'खुला लिंक',
    'discoverGreatDealsNearby': 'आस-पास बढ़िया सौदे खोजें',
    'stayTunedForOffers': 'सत्यापित थोक विक्रेताओं के नए ऑफ़र और कहानियों के लिए बने रहें।',
    'manageBanners': 'बैनर प्रबंधित करें',
    'myBanners': 'मेरे बैनर',
    'noBannersFound': 'कोई बैनर नहीं मिला. एक तैयार करें!',
    'bannerDetails': 'बैनर विवरण',
    'bannerNotFound': 'बैनर नहीं मिला',
    'views': 'दृश्यों',
    'clicks': 'संवादों',
    'bannerRequestSubmitted': 'बैनर अनुरोध सबमिट किया गया!',
    'failedToSubmitRequest': 'अनुरोध सबमिट करने में विफल',
    'deleteBanner': 'बैनर हटाएँ',
    'deleteBannerConfirm': 'क्या आप वाकई इस बैनर को हटाना चाहते हैं?',
    'bannerDeleted': 'बैनर हटा दिया गया',
    'failedToDeleteBanner': 'बैनर हटाने में विफल',
    'targetId': 'लक्ष्य आईडी',
    'url': 'यूआरएल',
    'createNewBanner': 'नया बैनर बनाएं',
    'bannerTitle': 'बैनर शीर्षक',
    'enterBannerTitle': 'बैनर शीर्षक दर्ज करें',
    'bannerImage': 'बैनर छवि',
    'webBannerImage': 'वेब छवि',
    'webBannerImageHint': 'वेब के लिए लैंडस्केप',
    'mobileBannerImage': 'मोबाइल छवि',
    'mobileBannerImageHint': 'मोबाइल के लिए पोर्ट्रेट/वर्ग',
    'mobilePreview': 'मोबाइल पूर्वावलोकन',
    'preview': 'पूर्वावलोकन',
    'previewMobile': 'मोबाइल पूर्वावलोकन',
    'previewWillAppearHere': 'पूर्वावलोकन यहां दिखेगा',
    'pasteImageUrlHere': 'छवि यूआरएल यहां चिपकाएं',
    'pleaseEnterImageUrlOrSwitch': 'कृपया एक छवि यूआरएल दर्ज करें या अपलोड पर स्विच करें और एक छवि चुनें।',
    'pleaseTapChooseImage': 'कृपया बैनर छवि अपलोड करने के लिए "छवि चुनें" पर टैप करें, या यूआरएल पर स्विच करें और एक छवि लिंक पेस्ट करें।',
    'tapToUploadWebImage': 'वेब छवि अपलोड करने के लिए टैप करें',
    'tapToUploadMobileImage': 'मोबाइल छवि अपलोड करने के लिए टैप करें',
    'chooseImage': 'छवि चुनें',
    'replaceImage': 'छवि बदलें',
    // ============================================
    // Stories Related
    // ============================================
    'createStory': 'कहानी बनाएं',
    'storiesFromVerifiedWholesalers': 'सत्यापित थोक विक्रेताओं की कहानियाँ',
    'storiesWillAppearHere': 'कहानियाँ जुड़ते ही यहाँ दिखाई देंगी',
    'selectImageOrVideoForStory': 'अपनी कहानी के लिए एक छवि या वीडियो चुनें',
    'post': 'डाक',
    'expiresAt': 'पर समाप्त होता है',
    // ============================================
    // Shipment / Tracking Related
    // ============================================
    'trackingNumber': 'ट्रैकिंग नंबर',
    'carrier': 'वाहक',
    'trackingUrl': 'ट्रैकिंग यूआरएल',
    'openTrackingLink': 'ट्रैकिंग लिंक खोलें',
    'statusTimeline': 'स्थिति समयरेखा',
    // ============================================
    // Account Deletion Related
    // ============================================
    'submitDeletionRequest': 'हटाने का अनुरोध सबमिट करें',
    'submitRequest': 'अनुरोध सबमिट करें',
    'reviewProcess': 'समीक्षा प्रक्रिया',
    'accountDeleted': 'खाता हटा दिया गया',
    'whatHappensNext': 'आगे क्या होता है?',
    'submitRequestDescription': 'खाता हटाने का अनुरोध करने के लिए अपना ईमेल पता दर्ज करें',
    'reviewProcessDescription': 'हमारी टीम 24-48 घंटों के भीतर आपके अनुरोध की समीक्षा करेगी। आपका अनुरोध संसाधित हो जाने पर आपको एक पुष्टिकरण ईमेल प्राप्त होगा।',
    'accountDeletedDescription': 'आपका खाता और सभी संबद्ध डेटा स्थायी रूप से हटा दिए जाएंगे। इस एक्शन को वापस नहीं किया जा सकता।',
    'ourTeamReviewsYourRequest': 'हमारी टीम आपके अनुरोध की समीक्षा करती है',
    'reviewDetails': 'विवरण की समीक्षा करें',
    'reviewDetailsDescription': 'हम आपके खाते को सत्यापित करते हैं और सुनिश्चित करते हैं कि हटाने की प्रक्रिया से पहले सभी लंबित ऑर्डर या लेनदेन पूरे हो गए हैं।',
    'yourAccountIsPermanentlyRemoved': 'आपका खाता स्थायी रूप से हटा दिया गया है',
    'finalStep': 'अंतिम चरण',
    'finalStepDescription': 'एक बार स्वीकृत हो जाने पर, आपका खाता डेटा हमारे सिस्टम से स्थायी रूप से हटा दिया जाएगा। इस एक्शन को वापस नहीं किया जा सकता।',
    'importantInformation': 'महत्वपूर्ण सूचना',
    'accountDeletionIsPermanent': 'खाता विलोपन स्थायी है और इसे उलटा नहीं किया जा सकता',
    'allDataWillBeRemoved': 'आपका सारा डेटा, ऑर्डर और इतिहास स्थायी रूप से हटा दिया जाएगा',
    'pendingOrdersMustBeCompleted': 'विलोपन आगे बढ़ने से पहले लंबित आदेशों को पूरा किया जाना चाहिए',
    'youllReceiveEmailConfirmation': 'प्रक्रिया पूरी होने पर आपको एक ईमेल पुष्टिकरण प्राप्त होगा',
    'confirmActionPermanent': 'कृपया पुष्टि करें कि आप समझते हैं कि यह कार्रवाई स्थायी है',
    'requestSubmitted': 'अनुरोध सबमिट किया गया',
    'deletionRequestSubmittedMessage': 'आपका खाता हटाने का अनुरोध सफलतापूर्वक सबमिट कर दिया गया है। हमारी टीम 24-48 घंटों के भीतर इसकी समीक्षा करेगी। आपका अनुरोध संसाधित हो जाने पर आपको एक पुष्टिकरण ईमेल प्राप्त होगा।',
    'ok': 'ठीक है',
    'failedToSubmitDeletionRequest': 'हटाने का अनुरोध सबमिट करने में विफल. कृपया पुन: प्रयास करें।',
    'requestAccountDeletion': 'खाता हटाने का अनुरोध करें',
    'sorryToSeeYouGo': 'हमें आपके जाते हुए देखकर दुख हुआ',
    'emailAddress': 'मेल पता',
    'enterRegisteredEmail': 'अपना पंजीकृत ईमेल पता दर्ज करें',
    'emailAddressRequired': 'ईमेल पते की ज़रुरत है',
    'pleaseEnterValidEmail': 'कृपया एक मान्य ईमेल पता प्रविष्ट करें',
    'reasonForDeletionOptional': 'हटाने का कारण (वैकल्पिक)',
    'helpUsImproveLeaving': 'आप क्यों छोड़ रहे हैं, यह साझा करके सुधार करने में हमारी सहायता करें...',
    'understandActionPermanent': 'मैं समझता हूं कि यह कार्रवाई स्थायी है और इसे पूर्ववत नहीं किया जा सकता',
    // ============================================
    // Support / Help Related
    // ============================================
    'emailSupport': 'ई - मेल समर्थन',
    'getHelpViaEmail': 'ईमेल के माध्यम से सहायता प्राप्त करें',
    'phoneSupport': 'फ़ोन सहायता',
    'callUsDuringBusinessHours': 'व्यावसायिक घंटों के दौरान हमें कॉल करें',
    'liveChat': 'सीधी बातचीत',
    'chatWithUs': 'हमारे साथ चैट करें',
    'chatWithSupportTeam': 'हमारी सहायता टीम से चैट करें',
    'commonIssues': 'सामान्य मुद्दे',
    'orderNotShowingUp': 'ऑर्डर दिखाई नहीं दे रहा है',
    'orderNotShowingUpSolution': 'डैशबोर्ड को रीफ़्रेश करें या "मेरे ऑर्डर" में अपना ऑर्डर इतिहास जांचें',
    'liveChatComingSoon': 'लाइव चैट जल्द ही आ रही है!',
    'needHelpContactSupport': 'मदद की ज़रूरत है? समर्थन से संपर्क करें',
    'contactSupportAt': 'यहां सहायता से संपर्क करें',
    'getInTouch': 'संपर्क में रहो',
    'wereHereToHelp': 'हम आपकी मदद के लिए यहां हैं',
    'businessEmail': 'बिजनेस ईमेल',
    'contactUsOnWhatsApp': 'व्हाट्सएप पर हमसे संपर्क करें',
    'helloNeedAssistance': 'नमस्ते! मुझे सहायता चाहिए.',
    'myDetails': 'मेरे विवरण:',
    'nameLabel': 'नाम:',
    'phoneLabel': 'फ़ोन:',
    'emailLabel': 'ईमेल:',
    'businessLabel': 'व्यापार:',
    'howCanYouHelpMe': 'आप किस तरह मेरी सहायता कर सकते हैं?',
    'unableToOpenWhatsApp': 'व्हाट्सएप खोलने में असमर्थ. कृपया पुन: प्रयास करें।',
    'hello': 'नमस्ते',
    // ============================================
    // Common Validation Related
    // ============================================
    'required': 'यह फ़ील्ड आवश्यक है',
    'invalidEmail': 'अमान्य ईमेल',
    'passwordTooShort': 'पासवर्ड कम से कम 6 अंकों का होना चाहिए',
    'passwordsDoNotMatch': 'सांकेतिक शब्द मेल नहीं खाते',
    // ============================================
    // Manager / Admin Related
    // ============================================
    'admin': 'व्यवस्थापक',
    'role': 'भूमिका',
    'created': 'बनाया था',
    'subAdmin': 'उप-प्रशासन',
    'accessDenied': 'पहुंच अस्वीकृत',
    'managersSectionOnly': 'यह अनुभाग केवल प्रबंधकों के लिए उपलब्ध है',
    'totalRevenue': 'कुल मुनाफा',
    'myRevenue': 'मेरा राजस्व',
    'activeShops': 'सक्रिय थोक विक्रेता',
    'activeMembers': 'सक्रिय दुकानें/कोइस्क',
    'inactiveMembers': 'निष्क्रिय दुकानें',
    'activeShopsSubtitle': 'प्लेटफ़ॉर्म पर सत्यापित थोक विक्रेता',
    'activeMembersSubtitle': 'दुकानें जिन्होंने हाल ही में ऑर्डर किया है',
    'inactiveMembersSubtitle': '60+ दिनों में कोई ऑर्डर नहीं',
    'lastOrder': 'अंतिम आदेश',
    'lastActive': 'अंतिम सक्रिय',
    'lastLogin': 'आखरी लॉगइन',
    'joined': 'सम्मिलित हुए',
    'selectToNotify': 'अधिसूचना भेजने के लिए चयन करें',
    'deselect': 'अचयनित',
    'recipients': 'प्राप्तकर्ता',
    'notificationSent': 'अधिसूचना भेजी गई',
    'notifyDealParticipantsTitle': 'डील प्रतिभागियों को सूचित करें',
    'notifyDealParticipantsAudienceWarning':
        'यह संदेश केवल उन्हीं उपयोगकर्ताओं को भेजा जाएगा जिन्होंने इस डील के लिए ऑर्डर किया है।',
    'notifyDealParticipantsSendUpdateTooltip': 'अपडेट भेजें',
    'notifyDealParticipantsSending': 'भेजना...',
    'notifyDealParticipantsNoParticipantsError':
        'भेजना संभव नहीं: अभी तक कोई उपयोगकर्ता इस डील में शामिल नहीं हुआ है।',
    'notifyDealParticipantsFailedToSend':
        'सूचना भेजने में विफल: {error}',
    'noInactiveMembers': 'कोई निष्क्रिय सदस्य नहीं',
    'selectAll': 'सबका चयन करें',
    'sendNotification': 'अधिसूचना भेजें',
    'title': 'शीर्षक',
    'body': 'संदेश',
    'send': 'भेजना',
    'generateWithAI': 'एआई के साथ उत्पन्न करें',
    'generateNotificationPrompt': 'शीर्षक और संदेश उत्पन्न करने के लिए अधिसूचना का वर्णन करें (उदाहरण के लिए पुनः जुड़ाव, फ्लैश बिक्री, नए उत्पाद)।',
    'weMissYou': 'हमें आपकी याद आती है!',
    'reEngagementDefaultBody': 'आपने कुछ समय से कोई ऑर्डर नहीं दिया है. हमारे नवीनतम सौदे और उत्पाद ब्राउज़ करें।',
    'notificationRemindHint': 'उदाहरण के लिए, निष्क्रिय दुकानों को हमारी शीतकालीन बिक्री के बारे में याद दिलाएँ',
    'searchByNameEmail': 'नाम, ईमेल से खोजें...',
    'generate': 'उत्पन्न',
    'page': 'पेज',
    'never': 'कभी नहीं',
    'quickActions': 'त्वरित कार्रवाई',
    'recentOrders': 'हालिया आदेश',
    'noRecentOrders': 'कोई हालिया आदेश नहीं',
    'analyticsComingSoon': 'एनालिटिक्स - जल्द ही आ रहा है',
    'importCsv': 'सीएसवी से आयात करें',
    'importFromCsv': 'सीएसवी से आयात करें',
    'importProductsFromCsv': 'सीएसवी से उत्पाद आयात करें',
    'importProducts': 'उत्पाद आयात करें',
    'importing': 'आयात किया जा रहा है...',
    'downloadCsvTemplate': 'सीएसवी टेम्पलेट डाउनलोड करें',
    'getSampleCsvWithColumns': 'सभी आवश्यक कॉलमों के साथ एक नमूना CSV फ़ाइल प्राप्त करें',
    'selectCsvFile': 'सीएसवी फ़ाइल चुनें',
    'chooseFile': 'फाइलें चुनें',
    'tapToSelectWholesalerForImport': 'आयातित उत्पादों के लिए थोक विक्रेता का चयन करने के लिए टैप करें',
    'importComplete': 'आयात पूर्ण',
    'inserted': 'सम्मिलित किया गया',
    'updated': 'अद्यतन',
    'skipped': 'छोड़ा गया',
    'fileLabel': 'फ़ाइल: {name}',
    'wholesalerRequired': 'थोक विक्रेता *',
    'wholesalerLabel': 'थोक विक्रेता {id}',
    'csvPreviewRows': 'सीएसवी पूर्वावलोकन ({n} पंक्तियाँ)',
    'multipleRowsSameProductVariant': 'एक ही उत्पाद नाम वाली एकाधिक पंक्तियाँ = एकाधिक प्रकार',
    'errorsCount': 'त्रुटियाँ ({n})',
    'andMoreErrors': '... और {n} और त्रुटियाँ',
    'failedToReadFileBytes': 'फ़ाइल बाइट्स पढ़ने में विफल',
    'failedToGetFilePath': 'फ़ाइल पथ प्राप्त करने में विफल',
    'errorPickingFile': 'फ़ाइल चुनने में त्रुटि: {error}',
    'csvFileEmpty': 'सीएसवी फ़ाइल खाली है',
    'errorParsingCsv': 'CSV को पार्स करने में त्रुटि: {error}',
    'templateSavedSuccessfully': 'टेम्प्लेट सफलतापूर्वक सहेजा गया',
    'templateDownloadCancelled': 'टेम्प्लेट डाउनलोड रद्द किया गया',
    'errorGeneratingTemplate': 'टेम्पलेट जनरेट करने में त्रुटि',
    'errors': 'त्रुटियाँ',
    'viewWholesaler': 'थोक विक्रेता देखें',
    'cropImage': 'छवि सुधारें # क्रॉप इमेज फोटो एडिटर',
    'change': 'परिवर्तन',
    'navigationError': 'नेविगेशन त्रुटि',
    // ============================================
    // Time Related
    // ============================================
    'hours': 'घंटे',
    'minutes': 'मिनट',
    'seconds': 'सेकंड',
    'twentyFourHours': '24 घंटे',
    'twelveHours': '12 घंटे',
    'sixHours': '6 घंटे',
    // ============================================
    // Navigation / Route Errors
    // ============================================
    'noStoryDataProvided': 'कोई कहानी डेटा उपलब्ध नहीं कराया गया.',
    'missingWholesalerId': 'थोक विक्रेता की आईडी गायब है।',
    'missingProductId': 'गुम उत्पाद आईडी.',
    'missingCategorySlug': 'गुम श्रेणी स्लग.',
    'missingDealId': 'डील आईडी गुम है.',
    'missingOrderId': 'ऑर्डर आईडी गुम है.',
    'featuredProducts': 'विशेष रुप से प्रदर्शित प्रोडक्टस',
    // ============================================
    // Order Update / Quantity Change Result
    // ============================================
    'orderUpdate': 'आदेश अपडेट',
    'viewMyOrders': 'मेरे ऑर्डर देखें',
    'goToHome': 'घर जाओ',
    'quantityChangeAccepted': 'मात्रा परिवर्तन स्वीकार किया गया',
    'quantityChangeDeclined': 'मात्रा परिवर्तन में गिरावट आई',
    'somethingWentWrong': 'कुछ गलत हो गया',
    'orderUpdatedMessage': 'आपका ऑर्डर अपडेट कर दिया गया है.',
    'orderRevertedMessage': 'आपका ऑर्डर पिछली मात्रा पर वापस कर दिया गया है।',
    'pleaseTryAgainLater': 'कृपया बाद में पुन: प्रयास करें।',
    // ============================================
    // Deal Detail / Deal Errors
    // ============================================
    'unableToLoadDeal': 'डील लोड करने में असमर्थ',
    'regularPrice': 'नियमित रूप से मूल्य',
    'stockLabel': 'भंडार',
    'dealNotStarted': 'यह डील अभी शुरू नहीं हुई है',
    'adminWholesalerManageHint': 'एक व्यवस्थापक या थोक विक्रेता के रूप में, आप इस सौदे का प्रबंधन कर सकते हैं लेकिन ऑर्डर नहीं दे सकते। इस सौदे को संपादित करने या बंद करने के लिए ऐप बार में मेनू बटन (⋮) का उपयोग करें।',
    'adminDealOnlyOwnerCanBid': 'केवल व्यवस्थापक (डील स्वामी) ही व्यवस्थापक सौदों पर बोलियाँ जोड़ सकता है। कियोस्क उपयोगकर्ता इस सौदे पर ऑर्डर नहीं दे सकते।',
    'kioskOnlyPlaceOrders': 'केवल कियोस्क/शॉप खाते ही इस डील पर ऑर्डर दे सकते हैं।',
    'managementView': 'प्रबंधन दृश्य',
    'ordering': 'आदेश',
    'failedToLoadDealData': 'डील डेटा लोड करने में विफल',
    'dealClosedSuccess': 'सौदा सफलतापूर्वक संपन्न हुआ',
    'failedToCloseDeal': 'सौदा बंद करने में विफल',
    'onlyAdminCanAddBidsOnAdminDeals': 'केवल व्यवस्थापक (डील स्वामी) ही व्यवस्थापक सौदों पर बोलियाँ जोड़ सकता है।',
    // ============================================
    // Product Search / Detail
    // ============================================
    'searchProducts': 'उत्पादों को खोजना',
    'youCanOnlyReviewFromDeliveredOrders': 'आप केवल वितरित ऑर्डर के उत्पादों की समीक्षा कर सकते हैं',
    'allImages': 'सभी छवियाँ',
    'contentGeneratedSuccessfully': 'सामग्री सफलतापूर्वक उत्पन्न हुई! श्रेणी और अन्य फ़ील्ड जांचें.',
    'generationFailed': 'पीढ़ी विफल रही',
    'userIdRequired': 'उपयोगकर्ता आईडी आवश्यक है',
    // ============================================
    // Admin Banner Management
    // ============================================
    'adminBannerManagement': 'व्यवस्थापक बैनर प्रबंधन',
    'requests': 'अनुरोध',
    'active': 'सक्रिय',
    'noBannersFoundShort': 'कोई बैनर नहीं मिला.',
    'failedToUpdateBanner': 'बैनर अपडेट करने में विफल',
    'bannerSubmittedSuccessfully': 'बैनर सफलतापूर्वक सबमिट किया गया',
    'failedToCreateBanner': 'बैनर बनाने में विफल',
    'failedToSubmitBannerRequest': 'बैनर अनुरोध सबमिट करने में विफल',
    // ============================================
    // User Management / Admin
    // ============================================
    'administratorsOnlySection': 'यह अनुभाग केवल व्यवस्थापकों के लिए उपलब्ध है',
    'allRoles': 'सभी भूमिकाएँ',
    'allStatuses': 'सभी क़ानून',
    'suspended': 'निलंबित',
    'noUsersFound': 'कोई उपयोगकर्ता नहीं मिला',
    'pageOf': 'पेज',
    'ofLabel': 'का',
    'noDocumentsAvailable': 'कोई दस्तावेज़ उपलब्ध नहीं है',
    'userUpdatedSuccessfully': 'उपयोगकर्ता सफलतापूर्वक अपडेट किया गया',
    'userCreatedSuccessfully': 'उपयोगकर्ता सफलतापूर्वक बनाया गया',
    'userDeletedSuccessfully': 'उपयोगकर्ता सफलतापूर्वक हटा दिया गया',
    'deleteUser': 'उपयोगकर्ता हटाएँ',
    'deleteUserConfirm': 'क्या आप वाकई {name} को हटाना चाहते हैं? इस एक्शन को वापस नहीं किया जा सकता।',
    'verificationDocuments': 'सत्यापन दस्तावेज़',
    'noVerificationDocumentsYet': 'अभी तक कोई सत्यापन दस्तावेज़ अपलोड नहीं किया गया है.',
    'rejectionReason': 'अस्वीकृति का कारण:',
    'createUser': 'उपयोगकर्ता बनाएं',
    'editUser': 'यूजर को संपादित करो',
    'updateUser': 'उपयोगकर्ता को अद्यतन करें',
    'roleRequired': 'भूमिका आवश्यक है',
    'statusRequired': 'स्थिति आवश्यक है',
    'newPasswordLeaveEmpty': 'नया पासवर्ड (वर्तमान रखने के लिए खाली छोड़ें)',
    'passwordRequired': 'पासवर्ड आवश्यक है',
    'passwordMinLength': 'पासवर्ड कम से कम 6 अंकों का होना चाहिए',
    'needInfo': 'जानकारी चाहिए',
    'business': 'व्यापार',
    'searchByNameEmailPhone': 'नाम, ईमेल, फ़ोन द्वारा खोजें...',
    'daysAgo': 'दिन पहले',
    'activeDaysLast14': 'सक्रिय दिन (पिछले 14)',
    'docsCount': '{count} दस्तावेज़',
    'noPassportDocuments': 'कोई पासपोर्ट दस्तावेज नहीं',
    'noGewerbescheinDocuments': 'कोई ग्वेर्बेशिन दस्तावेज़ नहीं',
    'noBusinessLicenseDocuments': 'कोई व्यवसाय लाइसेंस दस्तावेज़ नहीं',
    'documentN': 'दस्तावेज़ {n}',
    'openInBrowser': 'ब्राउज़र में खोलें',
    'pdfDocument': 'पीडीएफ दस्तावेज़',
    'kiosk': 'कीओस्क',
    // ============================================
    // Order Management (Deal Orders)
    // ============================================
    'errorLoadingOrders': 'ऑर्डर लोड करने में त्रुटि',
    'errorLoadingDeals': 'सौदे लोड करने में त्रुटि',
    'orderManagement': 'प्रबंधन को आदेश दें',
    'orderCountSuffix': 'आदेश',
    'confirmOrder': 'आदेश की पुष्टि',
    'confirmOrderMessage': 'क्या आप वाकई इस आदेश की पुष्टि करना चाहते हैं?',
    'confirm': 'पुष्टि करना',
    'markAsDelivered': 'वितरित के रूप में चिह्नित करें',
    'markDelivered': 'मार्क डिलीवर',
    'cancelOrder': 'आदेश रद्द',
    'cancelOrderConfirm': 'क्या आप वाकई यह ऑर्डर रद्द करना चाहते हैं?',
    'no': 'नहीं',
    'reduceQuantity': 'मात्रा कम करें',
    'orderConfirmedSuccess': 'ऑर्डर की सफलतापूर्वक पुष्टि हो गई',
    'orderMarkedDelivered': 'ऑर्डर को वितरित के रूप में चिह्नित किया गया',
    'failedToConfirmOrder': 'आदेश की पुष्टि करने में विफल',
    'failedToMarkDelivered': 'वितरित के रूप में चिह्नित करने में विफल',
    'orderCancelled': 'आदेश रद्द किया गया',
    'failedToCancelOrder': 'ऑर्डर रद्द करने में विफल',
    'orderMarkedPaid': 'आदेश को भुगतान के रूप में चिह्नित किया गया',
    'failedToMarkOrderPaid': 'आदेश को भुगतान के रूप में चिह्नित करने में विफल रहा',
    'quantityUpdatedSuccess': 'मात्रा सफलतापूर्वक अपडेट की गई',
    'failedToUpdateQuantity': 'मात्रा अद्यतन करने में विफल',
    'deliveryNotesOptional': 'डिलिवरी नोट्स (वैकल्पिक)',
    'newQuantity': 'नई मात्रा',
    'reduceQuantityHint': 'नई मात्रा दर्ज करें. न्यूनतम 1 है (या सौदे की न्यूनतम ऑर्डर मात्रा)। इस ऑर्डर को रद्द करने के लिए 0 का उपयोग करें।',
    'quantityUpdatedTo': 'मात्रा को अद्यतन किया गया',
    // ============================================
    // Deal Order Form
    // ============================================
    'enterQuantity': 'मात्रा दर्ज करें',
    'pleaseEnterQuantity': 'कृपया मात्रा दर्ज करें',
    'invalidQuantity': 'अमान्य मात्रा',
    'minimumOrderIs': 'न्यूनतम आदेश है',
    'maximumOrderIs': 'अधिकतम आदेश है',
    'addSpecialInstructions': 'कोई विशेष निर्देश जोड़ें...',
    'minQuantityLabel': 'मिन',
    'selectedLabel': 'चयनित',
    'maxQuantityLabel': 'अधिकतम',
    // ============================================
    // Shipment / Carrier
    // ============================================
    'pleaseSelectCarrier': 'कृपया एक वाहक चुनें',
    'pleaseEnterCarrierNameForOther': 'कृपया "अन्य" के लिए वाहक का नाम दर्ज करें',
    'shipmentCreatedSuccess': 'शिपमेंट सफलतापूर्वक बनाया गया',
    'shipmentCreatedAndOrderShipped': 'शिपमेंट बनाया गया और ऑर्डर को शिपमेंट के रूप में चिह्नित किया गया',
    'failedToCreateShipment': 'शिपमेंट बनाने में विफल',
    // ============================================
    // Stories
    // ============================================
    'failedToPickMedia': 'मीडिया चुनने में विफल',
    'onlyWholesalersCanCreateStories': 'केवल थोक विक्रेता ही कहानियाँ बना सकते हैं',
    'storyCreatedSuccess': 'कहानी सफलतापूर्वक बनाई गई! 🎉',
    'failedToCreateStory': 'कहानी बनाने में विफल',
    // ============================================
    // Payment
    // ============================================
    'paymentCompletedSuccess': 'भुगतान सफलतापूर्वक पूरा हुआ!',
    'paymentFailed': 'भुगतान विफल रही',
    // ============================================
    // Notifications
    // ============================================
    'notifications': 'सूचनाएं',
    'markAllAsRead': 'सभी को पढ़ा हुआ मार्क करें',
    'deleteAll': 'सभी हटा दो',
    'filterNotifications': 'सूचनाएं फ़िल्टर करें',
    'unread': 'अपठित ग',
    'read': 'पढ़ना',
    'deleteAllNotificationsConfirm': 'सभी सूचनाएं हटाएं?',
    'deleteAllNotificationsMessage': 'क्या आप वाकई सभी सूचनाएं हटाना चाहते हैं? इस एक्शन को वापस नहीं किया जा सकता।',
    // ============================================
    // Deal / Product Modals
    // ============================================
    'paymentEmailTemplateGenerated': 'भुगतान ईमेल टेम्प्लेट तैयार किया गया',
    'aiGenerationFailed': 'एआई पीढ़ी विफल रही',
    'dealUpdatedSuccess': 'डील सफलतापूर्वक अपडेट हो गई',
    'allowOnlinePayment': 'ऑनलाइन भुगतान की अनुमति दें',
    'allowOnlinePaymentSubtitle': 'यदि अनियंत्रित है, तो ग्राहक केवल ऑर्डर दे सकते हैं; आदेश की पुष्टि होने के बाद भुगतान (जैसे बैंक हस्तांतरण) का अनुरोध किया जाता है।',
    'paymentAndEmail': 'भुगतान एवं ईमेल',
    'generating': 'उत्पन्न हो रहा है...',
    'enterDealDescriptionPrompt': 'स्वचालित रूप से सामग्री उत्पन्न करने के लिए अपने सौदे का स्पष्ट विवरण दर्ज करें।',
    'dealDescriptionHint': 'उदाहरण के लिए, फ्लैश सेल: सभी शीतकालीन जैकेटों पर 50% की छूट',
    'enterProductDescriptionPrompt': 'स्वचालित रूप से सामग्री उत्पन्न करने के लिए विवरण या उत्पाद विवरण दर्ज करें।',
    'productDescriptionHint': 'उदाहरण के लिए, एर्गोनोमिक डिज़ाइन वाली एक प्रीमियम चमड़े की कार्यालय कुर्सी...',
    'optionalAutoAssigned': 'वैकल्पिक - खाली होने पर स्वतः-असाइन किया जाएगा',
    'defaultYourAccount': 'डिफ़ॉल्ट: आपका खाता (बदलने के लिए टैप करें)',
    'currentUserYou': 'वर्तमान उपयोगकर्ता (आप)',
    'loadingProductDetails': 'उत्पाद विवरण लोड हो रहा है...',
    'loading': 'लोड हो रहा है...',
    'ibanBankAccount': 'आईबीएएन/बैंक खाता',
    'accountOwner': 'खाते का मालिक',
    'referenceTemplate': 'संदर्भ टेम्पलेट (उदा. DEAL-{dealCode}-{buyerId})',
    'paymentInstructions': 'भुगतान निर्देश (मुफ़्त पाठ)',
    'paymentEmailSubject': 'भुगतान ईमेल विषय',
    'paymentEmailBody': 'भुगतान ईमेल का मुख्य भाग ({dealTitle}, {amount}, {iban}, {reference}, {accountOwner} का उपयोग करें)',
    'ended': 'समाप्त',
    'dealEnded': 'डील ख़त्म',
    'dealHasEnded': 'डील ख़त्म हो गई है',
    'endingSoon': 'जल्द ही खत्म हो रहा है!',
    'endsIn1Day': '1 दिन में ख़त्म',
    'endsInDays': '{n} दिनों में समाप्त होता है',
    'endsIn1Hour': '1 घंटे में ख़त्म',
    'endsInHours': '{n} घंटे में समाप्त होता है',
    'endsSoon': 'शीघ्र ही समाप्त हो जाता है',
    'categories': 'श्रेणियाँ',
    'itemsCount': '{n} आइटम',
    // ============================================
    // Shipment Tracking
    // ============================================
    'pleaseEnterTrackingNumber': 'कृपया एक ट्रैकिंग नंबर दर्ज करें',
    'pleaseSelectAtLeastOneItemToShip': 'कृपया भेजने के लिए कम से कम एक आइटम का चयन करें',
    'pleaseEnterTrackingUrlForOther': 'कृपया "अन्य" वाहक के लिए ट्रैकिंग यूआरएल दर्ज करें',
    'selectItemsToShip': 'शिप करने के लिए आइटम चुनें',
    'noItemsAvailableForShipment': 'शिपमेंट के लिए कोई आइटम उपलब्ध नहीं है',
    'selectCarrier': 'एक वाहक चुनें',
    'selectCarrierHint': 'एक वाहक चुनें...',
    'carrierName': 'वाहक का नाम',
    'enterCarrierName': 'वाहक का नाम दर्ज करें',
    'trackingNumberRequired': 'ट्रैकिंग नंबर आवश्यक है',
    'enterTrackingNumber': 'ट्रैकिंग नंबर दर्ज करें',
    'trackingUrlAutoGenerated': 'ट्रैकिंग यूआरएल स्वतः उत्पन्न हो जाएगा',
    'trackingUrlRequiredForOther': '"अन्य" वाहक के लिए ट्रैकिंग यूआरएल आवश्यक है',
    'pleaseEnterValidUrl': 'क्रुपया मान्य यूआरएल दर्ज करें',
    'estimatedDeliveryDate': 'अनुमानित प्रसव तिथि',
    'selectDate': 'तारीख़ चुनें',
    'internalNotesShipment': 'इस शिपमेंट के बारे में आंतरिक नोट्स',
    'trackingUrlHintAuto': 'वाहक और ट्रैकिंग नंबर प्रदान किए जाने पर स्वतः उत्पन्न होता है',
    'trackShipment': 'ट्रैक शिपमेंट',
    'trackShipmentHint': 'दिए गए ट्रैकिंग नंबर का उपयोग करके अपने शिपमेंट को ट्रैक करें',
    'trackingDetails': 'ट्रैकिंग विवरण',
    'shipmentNotFound': 'शिपमेंट नहीं मिला',
    'pleaseCheckTrackingNumber': 'कृपया अपना ट्रैकिंग नंबर जांचें और पुनः प्रयास करें',
    'noNotifications': 'कोई सूचना नहीं',
    'youreAllCaughtUp': 'आप सभी यहां हैं!',
    // ============================================
    // Select Deal / Category
    // ============================================

    // Feature audit – previously hardcoded strings
    'platformMobile': 'मोबाइल',
    'platformWeb': 'वेब',
    'pleaseWait': 'कृपया प्रतीक्षा करें...',
    'defaultVariant': 'डिफ़ॉल्ट',
    'trackOnCarrierWebsite': 'कैरियर वेबसाइट पर ट्रैक करें',
    'minOrderQtyRequired': 'न्यूनतम ऑर्डर मात्रा *',
    'dealPriceRequired': 'डील की कीमत *',
    'targetQuantityRequired': 'लक्ष्य मात्रा *',
    'baseShippingCostEur': 'आधार शिपिंग लागत (€)',
    'freeShippingThresholdQuantity': 'मुफ्त शिपिंग थ्रेशोल्ड (मात्रा)',
    'perUnitShippingCostEur': 'प्रति यूनिट शिपिंग लागत (€)',
    'descriptionOptional': 'विवरण (वैकल्पिक)',
    'enterBannerDescription': 'बैनर विवरण दर्ज करें',
    'bannerType': 'बैनर प्रकार',
    'targetUrl': 'लक्ष्य URL',
    'skuRequired': 'SKU *',
    'productToPromoteHint': 'प्रचार के लिए उत्पाद',
    'selectDealToPromote': 'प्रचार के लिए डील चुनें',
    'titleOptional': 'शीर्षक (वैकल्पिक)',
    'giveReviewTitle': 'अपनी समीक्षा को शीर्षक दें',
    'yourReviewOptional': 'आपकी समीक्षा (वैकल्पिक)',
    'shareExperienceWithProduct': 'इस उत्पाद के साथ अपना अनुभव साझा करें',
    'dealUpdatedSuccessfully': 'डील सफलतापूर्वक अद्यतन',
    'dealPriceMustBeValidNumber': 'डील की कीमत एक वैध संख्या होनी चाहिए',
    'pleaseEnterMinOrderQuantity': 'कृपया न्यूनतम ऑर्डर मात्रा दर्ज करें',
    'paymentEmailPlaceholdersSubject':
        'प्लेसहोल्डर: {dealTitle}, {amount}, {reference}',
    'paymentEmailPlaceholdersBody':
        'प्लेसहोल्डर: {dealTitle}, {amount}, {accountOwner}, {iban}, '
        '{reference}, {additionalInstructions}',
    'failed': 'विफल',

    // ============================================
    // Order status (product orders – display only)
    // ============================================
    'orderStatusPendingConfirmation': 'पुष्टि लंबित',
    'orderStatusConfirmed': 'पुष्ट',
    'orderStatusPacking': 'पैक हो रहा है',
    'orderStatusDispatched': 'भेज दिया गया',
    'orderStatusOutForDelivery': 'डिलीवरी के लिए निकला',
    'orderStatusDelivered': 'डिलीवर हो गया',
    'orderStatusCancelled': 'रद्द',
    'orderStatusReturned': 'वापस किया गया',
    'orderStatusRefunded': 'रिफंड',

    // ============================================
    // Notifications (backend localization keys)
    // ============================================
    'notificationProductApprovalNeededTitle': 'नया उत्पाद अनुमोदन हेतु लंबित',
    'notificationProductApprovalNeededBody': '{0} ने एक नया उत्पाद बनाया: {1}',
    'notificationProductStatusUpdatedTitle': 'उत्पाद स्थिति अपडेट हुई',
    'notificationProductApprovedBody': 'आपका उत्पाद "{0}" स्वीकृत हो गया!',
    'notificationProductRejectedBody': 'आपका उत्पाद "{0}" अस्वीकृत हो गया।',
    'notificationProductPendingBody': 'आपका उत्पाद "{0}" अनुमोदन के लिए लंबित है।',
    'notificationProductStatusChangedBody': 'आपके उत्पाद "{0}" की स्थिति {1} में बदल गई',
    'notificationNewProductOrderTitle': 'आपके उत्पादों पर नया ऑर्डर',
    'notificationNewProductOrderBody': '{0} ने {2} के {1} यूनिट का ऑर्डर दिया',
    'notificationNewDealOrderTitle': 'आपके डील पर नया ऑर्डर',
    'notificationNewDealOrderBody': '{0} ने {1} यूनिट का ऑर्डर दिया',
    'notificationPaymentReportedTitle': 'खरीदार ने भुगतान रिपोर्ट किया',
    'notificationPaymentReportedBody': '{0} ने ऑर्डर के लिए भुगतान रिपोर्ट किया। विवरण: {1}',
    'notificationDealPaymentReportedBody': '{0} ने डील ऑर्डर के लिए भुगतान रिपोर्ट किया। विवरण: {1}',
    'notificationDealOrderStatusUpdatedTitle': 'डील ऑर्डर की स्थिति अपडेट हुई',
    'notificationDealOrderConfirmedBody': '"{0}" पर आपका ऑर्डर पुष्टि हो गया!',
    'notificationDealOrderShippedBody': '"{0}" पर आपका ऑर्डर शिप हो गया!',
    'notificationDealOrderDeliveredBody': '"{0}" पर आपका ऑर्डर डिलीवर हो गया!',
    'notificationDealOrderCancelledBody': '"{0}" पर आपका ऑर्डर रद्द कर दिया गया।',
    'notificationDealOrderRefundedBody': '"{0}" पर आपके ऑर्डर का रिफंड कर दिया गया।',
    'notificationDealOrderPendingBody': '"{0}" पर आपका ऑर्डर पुष्टि के लिए लंबित है।',
    'notificationDealOrderStatusChangedBody': '"{0}" पर आपके ऑर्डर की स्थिति {1} में बदल गई',
    'notificationOrderQuantityUpdatedTitle': 'ऑर्डर मात्रा अपडेट हुई',
    'notificationDealOrderQuantityCancelledBody': '"{0}" पर आपका ऑर्डर (पहले {1} यूनिट) विक्रेता द्वारा रद्द कर दिया गया।',
    'notificationDealOrderQuantityChangedBody': '"{0}" पर आपका ऑर्डर अपडेट हुआ: मात्रा {1} से {2} यूनिट कर दी गई (विक्रेता द्वारा)।',
    'notificationQuantityChangeDeclinedTitle': 'मात्रा परिवर्तन अस्वीकार',
    'notificationQuantityChangeDeclinedBody': '{0} ने मात्रा परिवर्तन अस्वीकार किया। ऑर्डर {1} से {2} यूनिट पर वापस कर दिया गया।',
    'notificationDealNowLiveTitle': 'नई डील लाइव है',
    'notificationDealNowLiveBody': '"{0}" अब लाइव है। डील खत्म होने से पहले ऑर्डर करें।',
    'notificationDealTarget70PercentTitle': 'डील लगभग पूरी',
    'notificationDealTarget70PercentBody': '"{0}" {1}% भर चुकी है! अन्य रिटेलर्स के साथ जुड़ें और डील मालिक को लक्ष्य तक पहुँचने में मदद करें — यह संबंध मजबूत करता है और आपकी प्रतिबद्धता दिखाता है।',
    'notificationDealEnding24hTitle': 'डील जल्द खत्म हो रही है',
    'notificationDealEnding24hBody': 'अंतिम 24 घंटे! "{0}" — इस डील को बंद करने के लिए केवल {1} ऑर्डर बाकी हैं।',
    'notificationDealEnding7dTitle': 'डील 7 दिनों में खत्म होगी',
    'notificationDealEnding7dBody': '"{0}" — इस डील को बंद करने के लिए केवल {1} ऑर्डर बाकी हैं।',
    'notificationDealSuccessTitle': 'डील सफलतापूर्वक पूरी हुई',
    'notificationDealSuccessBody': 'आपकी समूह डील "{0}" आवश्यक मात्रा तक पहुँच गई है और अब पुष्टि हो गई है। कृपया थोक विक्रेता के निर्देशों के अनुसार भुगतान और शिपिंग की तैयारी करें।',
    'notificationDealClosedTitle': 'डील बंद हो गई',
    'notificationDealClosedBody': 'डील "{0}" बंद कर दी गई है। यह अब सक्रिय डील्स में दिखाई नहीं देगी।',
    'deal_closed_title': 'डील बंद हो गई!',
    'deal_closed_body':
        'डील "{0}" आधिकारिक रूप से बंद कर दी गई है। भाग लेने के लिए धन्यवाद!',
    'notificationOrderStatusUpdatedTitle': 'ऑर्डर स्थिति अपडेट हुई',
    'notificationOrderConfirmedBody': '"{0}" के लिए आपका ऑर्डर पुष्टि हो गया!',
    'notificationOrderDispatchedBody': '"{0}" के लिए आपका ऑर्डर डिस्पैच हो गया!',
    'notificationOrderDeliveredBody': '"{0}" के लिए आपका ऑर्डर डिलीवर हो गया!',
    'notificationOrderCancelledBody': '"{0}" के लिए आपका ऑर्डर रद्द कर दिया गया।',
    'notificationOrderPackingBody': '"{0}" के लिए आपका ऑर्डर पैक किया जा रहा है!',
    'notificationOrderOutForDeliveryBody': '"{0}" के लिए आपका ऑर्डर डिलीवरी के लिए निकल गया है!',
    'notificationOrderReturnedBody': '"{0}" के लिए आपका ऑर्डर वापस कर दिया गया।',
    'notificationOrderRefundedBody': '"{0}" के लिए आपका ऑर्डर रिफंड हो गया।',
    'notificationOrderStatusChangedBody': '"{0}" के लिए आपके ऑर्डर की स्थिति {1} में बदल गई',
    'notificationOrderItemRemovedBody': 'आपका ऑर्डर आइटम "{0}" (पहले {1} यूनिट) विक्रेता द्वारा हटा दिया गया।',
    'notificationOrderItemQuantityChangedBody': 'आपका ऑर्डर आइटम "{0}" अपडेट हुआ: मात्रा {1} से {2} यूनिट कर दी गई (विक्रेता द्वारा)।',
    'notificationProductQuantityChangeDeclinedBody': '{0} ने ऑर्डर आइटम की मात्रा बदलने से इंकार किया। {1} से {2} यूनिट पर वापस कर दिया गया।',
    'notificationDailyEngagementTitle': 'आज की डील्स देखें!',
    'notificationDailyEngagementBody': 'आज: {0} बैनर, {1} डील्स, {2} फीचर्ड उत्पाद। ऑफ़र्स देखने के लिए ऐप खोलें।',
    'notificationInactiveMembersAlertTitle': 'निष्क्रिय सदस्यों का अलर्ट',
    'notificationInactiveMembersAlertBody': '{0} दुकान(ों) ने {1} दिनों में कोई ऑर्डर नहीं दिया। संपर्क करने या समीक्षा करने पर विचार करें।',
    'notificationBulkImportCompletedTitle': 'बल्क इम्पोर्ट पूरा हुआ',
    'notificationBulkImportCompletedBody': '{0} उत्पाद सफलतापूर्वक इम्पोर्ट हुए। {1} छोड़े गए।',
    'notificationBannerApprovalNeededTitle': 'नया बैनर अनुमोदन हेतु लंबित',
    'notificationBannerApprovalNeededBody': '{0} ने बैनर के लिए अनुमोदन अनुरोध किया: {1}',
    'notificationNewUserRegistrationTitle': 'नया उपयोगकर्ता पंजीकरण',
    'notificationNewUserRegistrationBody': '{0} ({1}) ने {2} के रूप में पंजीकरण किया। अनुमोदन लंबित।',
    'notificationBannerStatusChangedTitle': 'बैनर की स्थिति बदली',
    'notificationBannerApprovedBody': 'आपका बैनर "{0}" स्वीकृत हो गया और अब सक्रिय है!',
    'notificationBannerRejectedBody': 'आपका बैनर "{0}" अस्वीकृत हो गया। कृपया समीक्षा करें और आवश्यकता होने पर पुनः सबमिट करें।',
    'notificationBannerDeactivatedBody': 'आपका बैनर "{0}" निष्क्रिय कर दिया गया।',
    'notificationBannerStatusChangedBody': 'आपके बैनर "{0}" की स्थिति {1} में बदल गई',
    'notificationAdminCustomTitle': '{0}',
    'notificationAdminCustomBody': '{0}',
    'kioskShopRole': 'कियोस्क / दुकान',
  };
}