class RussianFile {
  static const Map<String, String> russianTranslations = {
    // ============================================
    // Options Screen Related
    // ============================================
    'options': 'Параметры',
    'account': 'Счет',
    'myOrders': 'Мои заказы',
    'myOrdersSubtitle': 'Просматривайте и отслеживайте свои заказы',
    'statistics': 'Статистика',
    'statisticsSubtitle': 'Просмотр статистики участия в сделках',
    'profile': 'Профиль',
    'profileSubtitle': 'Управляйте своей учетной записью',
    'management': 'Управление',
    'manageCategories': 'Управление категориями',
    'manageCategoriesSubtitle': 'Создавайте категории продуктов и управляйте ими.',
    'createNewProductSubtitle': 'Создать новый продукт',
    'createNewDealSubtitle': 'Создать новую сделку',
    'viewOrdersSubtitle': 'Просмотр и управление заказами',
    'inactiveMembersViewSubtitle': 'Просмотр магазинов, в которых нет недавних заказов',
    'manageBannersSubtitle': 'Управление баннерами приложений (администратор)',
    'myBannersSubtitle': 'Управляйте своими баннерами',
    'unableToLoadOptions': 'Не удалось загрузить параметры',
    'loggingOut': 'Выход из системы...',
    'manageUsers': 'Управление пользователями',
    'manageUsersSubtitle': 'Просмотр и управление учетными записями пользователей',
    'analytics': 'Аналитика',
    'analyticsSubtitle': 'Просматривайте свою бизнес-аналитику',
    'information': 'Информация',
    'faq': 'Часто задаваемые вопросы',
    'faqSubtitle': 'Часто задаваемые вопросы',
    'aboutUs': 'О нас',
    'aboutUsSubtitle': 'Узнайте больше о нашей платформе',
    'helpSupport': 'Помощь и поддержка',
    'helpSupportSubtitle': 'Получите помощь и свяжитесь со службой поддержки',
    'accountActions': 'Действия с учетной записью',
    'deleteAccount': 'Удалить аккаунт',
    'deleteAccountSubtitle': 'Запрос на окончательное удаление вашей учетной записи',
    'logout': 'Выход из системы',
    'logoutSubtitle': 'Выйдите из своей учетной записи',
    'confirmLogout': 'Подтвердить выход',
    'confirmLogoutMessage': 'Вы уверены, что хотите выйти из системы?',
    'cancel': 'Отмена',
    'loginAgain': 'Войти снова',
    // ============================================
    // Language Related
    // ============================================
    'language': 'Язык',
    'languageSubtitle': 'Изменить язык приложения',
    'notificationSettings': 'Настройки уведомлений',
    'notificationSettingsSubtitle':
        'Выберите, какие уведомления вы хотите получать.',
    'notificationChannels': 'Каналы',
    'pushNotifications': 'Push-уведомления',
    'pushNotificationsSubtitle':
        'Получать push-уведомления на ваше устройство',
    'emailNotifications': 'Уведомления по электронной почте',
    'emailNotificationsSubtitle': 'Получать уведомления по электронной почте',
    'notificationModules': 'По категориям',
    'notificationSettingsSaved': 'Настройки уведомлений сохранены',
    'notificationModuleProducts': 'Продукты',
    'notificationModuleProductOrders': 'Заказы продуктов',
    'notificationModuleDeals': 'Сделки',
    'notificationModuleDealOrders': 'Заказы по сделкам',
    'notificationModuleBanners': 'Баннеры',
    'notificationModuleAdmin': 'Админ',
    'notificationModuleEngagement': 'Вовлеченность',
    'notificationModulePayment': 'Оплата',
    'push': 'Push',
    'currency': 'Валюта',
    'currencySubtitle': 'Отображение валюты для цен (по умолчанию: устройство)',
    'systemDefault': 'Система по умолчанию',
    'syncFxRates': 'Синхронизировать курсы валют',
    'syncFxRatesSubtitle': 'Получите последние обменные курсы от ЕЦБ',
    'syncFxRatesSuccess': 'Курсы валют успешно обновлены',
    'syncFxRatesFailed': 'Не удалось обновить курсы валют. Использование кэшированных ставок.',
    'changingLanguage': 'Меняем язык...',
    'languageChangeFailed': 'Не удалось синхронизировать языковые настройки. Пожалуйста, попробуйте еще раз.',
    'failedToChangeLanguage': 'Не удалось изменить язык. Пожалуйста, попробуйте еще раз.',
    'english': 'Английский',
    'german': 'немецкий',
    'turkish': 'турецкий',
    'arabic': 'арабский',
    'urdu': 'урду',
    'hindi': 'хинди',
    'russian': 'Русский',
    'sourceLanguageLabel': 'Язык контента',
    'sourceLanguageHint': 'Язык вводимого текста (будет переведён на другие языки)',
    // ============================================
    // Common / General
    // ============================================
    'sessionExpired': 'Срок сеанса истек',
    'sessionExpiredMessage': 'Срок вашей сессии истек. Пожалуйста, войдите еще раз, чтобы продолжить использование приложения.',
    'comingSoon': 'Вскоре',
    'retry': 'Повторить попытку',
    'error': 'Ошибка',
    'errorWithDetail': 'Ошибка: {detail}',
    'close': 'Закрывать',
    'save': 'Сохранять',
    'done': 'Сделанный',
    'saving': 'Сохранение...',
    'update': 'Обновлять',
    'edit': 'Редактировать',
    'delete': 'Удалить',
    'add': 'Добавлять',
    'remove': 'Удалять',
    'select': 'Выбирать',
    'all': 'Все',
    'filter': 'Фильтр',
    'type': 'Тип',
    'status': 'Статус',
    'unknown': 'Неизвестный',
    // ============================================
    // About Us Related
    // ============================================
    'welcomeToProductDeal': 'Добро пожаловать в предложение по продуктам',
    'trustedMarketplace': 'Ваш надежный рынок оптовых товаров и предложений',
    'ourMission': 'Наша миссия',
    'ourMissionContent': 'Объединить оптовиков и розничных продавцов, сделав оптовые закупки доступными и эффективными для предприятий любого размера.',
    'whatWeOffer': 'Что мы предлагаем',
    'whatWeOfferContent':
        '• Доступ к проверенным оптовикам.'
        '• Эксклюзивные оптовые предложения и скидки.'
        '• Отслеживание запасов в режиме реального времени.'
        '• Безопасное управление заказами'
        '• Обнаружение продуктов на основе местоположения.',
    'forWholesalers': 'Для оптовиков',
    'forRetailers': 'Для розничной торговли',
    'forRetailersContent': 'Находите товары у ближайших оптовиков, участвуйте в оптовых сделках и эффективно управляйте своими заказами.',
    'forWholesalersContent': 'Демонстрируйте свои продукты, создавайте эксклюзивные предложения, управляйте заказами и охватывайте более широкую сеть розничных продавцов.',
    // ============================================
    // FAQ Related
    // ============================================
    'frequentlyAskedQuestions': 'Часто задаваемые вопросы',
    'commonQuestions': 'Общие вопросы',
    'faqQuestion1': 'Как мне разместить заказ?',
    'faqAnswer1': 'Просмотрите активные предложения или продукты, выберите необходимое количество и нажмите «Разместить заказ». Ваш заказ будет рассмотрен оптовиком.',
    'faqQuestion2': 'Что такое ордера на сделку?',
    'faqAnswer2': 'Заказы на сделку — это возможность оптовых закупок, когда оптовики предлагают цены со скидкой при достижении целевого количества. Вы можете разместить несколько заказов по одной и той же сделке.',
    'faqQuestion3': 'Как осуществляется доставка?',
    'faqAnswer3': 'Детали доставки согласовываются непосредственно с оптовиком после подтверждения заказа. Контактная информация будет предоставлена ​​после подтверждения заказа.',
    'faqQuestion4': 'Могу ли я отменить заказ?',
    'faqAnswer4': 'Вы можете отменить отложенные ордера. После подтверждения заказа оптовиком применяются правила отмены в соответствии с условиями оптовика.',
    'faqQuestion5': 'Как мне стать проверенным оптовиком?',
    'faqAnswer5': 'Свяжитесь с нашей службой поддержки, чтобы пройти проверку. Вам необходимо будет предоставить деловую документацию и завершить процесс проверки.',
    'faqQuestion6': 'Как сортируются товары по расстоянию?',
    'faqAnswer6': 'Товары автоматически сортируются по близости к вашему местоположению. Обязательно добавьте свое местоположение в свой профиль для точной сортировки по расстоянию.',
    'faqQuestion7': 'Какие способы оплаты принимаются?',
    'faqAnswer7': 'Способы оплаты различаются в зависимости от оптовика. Детали оплаты обсуждаются после подтверждения заказа.',
    'faqQuestion8': 'Как мне обновить свой профиль?',
    'faqAnswer8': 'Перейдите на страницу своего профиля с панели управления, обновите информацию и сохраните. Вы можете добавить несколько адресов для разных мест.',
    // ============================================
    // Wholesaler Directory Related
    // ============================================
    'couldNotLoadWholesalers': 'Мы не смогли загрузить оптовиков прямо сейчас.',
    'verifiedPartners': 'проверенные партнеры',
    'verifiedPartnersDescription': 'проверенные партнеры',
    'noWholesalersNearYou': 'Рядом с вами пока нет оптовиков. Обновите свое местоположение, чтобы разблокировать близлежащий инвентарь.',
    // ============================================
    // Dashboard Related
    // ============================================
    'dashboard': 'Панель управления',
    'nearbyWholesalers': 'Ближайшие оптовики',
    'allWholesalers': 'Все оптовики',
    'noWholesalersFound': 'Оптовиков не найдено',
    'errorLoadingWholesalers': 'Ошибка загрузки оптовиков.',
    'advertiseWithUs': 'Рекламируйтесь у нас',
    'boostYourSales': 'Увеличьте свои продажи!',
    'promoteYourProducts': 'Продвигайте здесь свою продукцию и привлекайте больше клиентов.',
    'unableToLoadDashboard': 'Не удалось загрузить панель управления',
    'unableToLoadProduct': 'Невозможно загрузить товар',
    'unableToLoadWholesaler': 'Невозможно загрузить оптовика',
    'spotlight': 'Прожектор',
    'spotlightWholesalersEmpty': 'Оптовики в центре внимания появятся здесь, как только рынок наберет обороты.',
    // ============================================
    // Orders Related
    // ============================================
    'orderId': 'Идентификатор заказа',
    'payment': 'Оплата',
    'paymentStatus': 'Статус платежа',
    'placedOn': 'Размещено на',
    'orderItems': 'Заказ товаров',
    'createShipment': 'Создать отгрузку',
    'shippingAddress': 'Адрес доставки',
    'notes': 'Примечания',
    'orderNotes': 'Примечания к заказу',
    'orderDetails': 'Детали заказа',
    'unableToLoadOrder': 'Не удалось загрузить заказ',
    'updateOrderStatus': 'Обновить статус заказа',
    'subtotal': 'Итого',
    'shipping': 'Перевозки',
    'shippingWithFreeThreshold': 'Доставка: {amount} (бесплатно для единиц {threshold}+)',
    'freeShippingForThreshold': 'Бесплатная доставка для {threshold}+ единиц',
    'shippingBaseOnly': 'Доставка: {amount}',
    'shippingWithPerUnit': 'Доставка: {base} + {perUnit} за единицу.',
    'total': 'Общий',
    'reasonOptional': 'Причина (необязательно)',
    'notesOptional': 'Примечания (необязательно)',
    'sku': 'Артикул',
    'skuN/A': 'Артикул: Н/Д',
    'trackingAvailable': 'ОТСЛЕЖИВАНИЕ ДОСТУПНО',
    'shipped': 'Отправленный',
    'shipments': 'Отгрузки',
    'shipmentId': 'Отгрузка {id}',
    'trackingLabel': 'Отслеживание: {number}',
    'track': 'Отслеживать',
    'couldNotOpenTrackingUrl': 'Не удалось открыть URL отслеживания.',
    'carrierLabel': 'Перевозчик: {name}',
    'estDelivery': 'Ориентировочная доставка: {date}',
    'shippedAt': 'Отправлено: {date}',
    'deliveredAt': 'Доставлено: {date}',
    'each': 'каждый',
    'unit': 'Единица',
    'noOrdersYet': 'Заказов пока нет',
    'noOrdersYetMessage': 'Просмотрите продукты и предложения, чтобы разместить свой первый заказ.',
    'unableToLoadOrders': 'Невозможно загрузить ваши заказы',
    'orderPlaced': 'Заказ размещен',
    'confirmed': 'Подтвержденный',
    'delivered': 'Доставленный',
    'pendingOrders': 'Отложенные ордера',
    'viewOrders': 'Просмотр заказов',
    'allOrders': 'Все заказы',
    'pendingConfirmation': 'Ожидает подтверждения',
    'packing': 'Упаковка',
    'packed': 'упакованный',
    'dispatched': 'Отправлено',
    'outForDelivery': 'Готово к доставке',
    'viewDetails': 'Посмотреть детали',
    'changeOrderStatus': 'Изменить статус заказа',
    'orderStatusUpdatedSuccessfully': 'Статус заказа успешно обновлен',
    'orderStatusUpdated': 'Статус заказа успешно обновлен',
    'itemStatusUpdatedSuccessfully': 'Статус элемента успешно обновлен',
    'itemStatusUpdated': 'Статус элемента успешно обновлен',
    'ordersCountSuffix': 'заказы',
    'order': 'заказ',
    'orderLabel': 'Заказ',
    'orders': 'заказы',
    'ordered': 'заказал',
    'dealOrder': 'Заказ на сделку',
    'productOrder': 'Заказ продукта',
    'bid': 'Делать ставку',
    'itemPlusMore': '{item} + {n} ещё',
    // ============================================
    // Cart Related
    // ============================================
    'yourCart': 'Ваша корзина',
    'cart': 'Корзина',
    'emptyCart': 'Ваша корзина пуста',
    'emptyCartMessage': 'Добавьте товары в корзину, чтобы начать.',
    'addProductsToSeeThemHere': 'Добавьте товары, чтобы увидеть их здесь.',
    'placeOrderCashOnDelivery': 'Оформить заказ (наложенным платежом)',
    'cashOnDelivery': 'Наложенным платежом',
    'paymentMethodCash': 'Наложенный платёж',
    'paymentMethodCashDesc': 'Оплата при получении заказа.',
    'paymentMethodInvoice': 'По счёту',
    'paymentMethodInvoiceDesc':
        'Мы выставляем счёт; доставка после подтверждения заказа.',
    'paymentMethodBankTransfer': 'Банковский перевод',
    'paymentMethodBankTransferDesc':
        'Сначала оплата, затем отправка. Инструкции по оплате по e-mail.',
    'paymentMode': 'Способ оплаты',
    'paymentModeSubtitle':
        'По умолчанию для ваших сделок. Вы можете изменить это позже в профиле.',
    'paymentModeSubtitleMulti':
        'Выберите все способы оплаты, которые вы принимаете. '
        'Вы можете изменить это позже в профиле.',
    'paymentSettings': 'Настройки оплаты',
    'paymentSettingsSubtitle':
        'Банковские реквизиты для заказов по счёту/переводу. '
        'Их можно обновить позже в профиле.',
    'payWithCard': 'Оплатить картой',
    'placeOrderPayNow': 'Разместить заказ и оплатить',
    'paymentAfterOrderConfirmed': 'Оплата будет запрошена после подтверждения вашего заказа (например, банковским переводом).',
    'paymentNotAvailable': 'Оплата картой невозможна. Попробуйте наложенный платеж.',
    'paymentCancelled': 'Платеж был отменен.',
    'dealSucceededPayNow': 'Сделка прошла успешно – заплатите сейчас',
    'totalToPay': 'Итого к оплате',
    'payByInvoice': 'Оплата по счету',
    'payByCard': 'Оплата картой',
    'invoiceInstructionsSent': 'Инструкции по оплате были отправлены на электронную почту.',
    'paymentInstructionsBankOnly': 'Инструкции по оплате были отправлены на электронную почту. Оплата банковским переводом. Если вы уже заплатили, владелец сделки подтвердит получение.',
    'markAsPaid': 'Отметить как оплаченное',
    'paymentNotesOptional': 'Платежные примечания (например, банковская справка)',
    'myDealStats': 'Статистика моих сделок',
    'dealsJoined': 'Сделки присоединились',
    'totalOrderedQuantity': 'Общее количество заказано',
    'totalOrders': 'Всего заказов',
    'placeOrder': 'Разместить заказ',
    'fxDisclaimer': 'Валютный курс может быть изменен. Отображаемая сумма является ориентировочной.',
    'placingOrder': 'Размещение заказа...',
    'orderPlacedSuccessfully': 'Заказ успешно оформлен!',
    'failedToPlaceOrder': 'Не удалось разместить заказ',
    'onlyKioskCanOrder': 'Размещать заказы могут только учетные записи киосков/магазинов.',
    'admins': 'Админы',
    'subAdmins': 'Субадмины',
    'wholesalers': 'Оптовики',
    'canOnlyViewProducts': 'можно только просматривать товары. Размещать заказы могут только учетные записи киосков/магазинов.',
    'addToCart': 'Добавить в корзину',
    'addedToCart': '✅Добавлен в корзину',
    'quantity': 'Количество',
    'unitPrice': 'Цена за единицу товара',
    'totalAmount': 'Общая сумма',
    'buyer': 'Покупатель',
    'items': 'предметы',
    // ============================================
    // Registration Related
    // ============================================
    'register': 'Зарегистрироваться',
    'createAccount': 'Зарегистрироваться',
    'createAccountTitle': 'Зарегистрироваться',
    'createAccountSubtitle': 'Откройте доступ к курируемым оптовикам, крупным сделкам и логистической поддержке.',
    'fullName': 'Полное имя',
    'email': 'Электронная почта',
    'workEmail': 'Рабочая электронная почта',
    'phone': 'Телефон',
    'password': 'Пароль',
    'confirmPassword': 'Подтвердите пароль',
    'confirmPasswordLabel': 'Подтвердите пароль',
    'businessName': 'Название компании',
    'country': 'Страна',
    'city': 'Город',
    'address': 'Адрес',
    'streetAddress': 'адрес улицы',
    'addressWillBeGeocoded': 'Адрес будет автоматически геокодирован для получения координат.',
    'getLocation': 'Получить местоположение',
    'selectRole': 'Выберите роль',
    'accountType': 'Тип аккаунта',
    'alreadyHaveAccount': 'У вас уже есть аккаунт?',
    'login': 'Авторизоваться',
    'signIn': 'Войти',
    'registrationReceived': 'Регистрация получена! Мы сообщим вам, как только аккаунт будет одобрен.',
    'fullNameRequired': 'Требуется полное имя',
    'emailRequired': 'Требуется электронная почта',
    'provideValidEmail': 'Укажите действительный адрес электронной почты',
    'phoneNumberOptional': 'Номер телефона (необязательно)',
    'enterValidPhoneNumber': 'Введите действительный номер телефона',
    'kioskShopNameOptional': 'Название киоска/магазина (необязательно)',
    'companyName': 'Название компании',
    'latitudeOptional': 'Широта (необязательно)',
    'longitudeOptional': 'Долгота (необязательно)',
    'locating': 'Поиск...',
    'locatingEllipsis': 'Поиск…',
    'useCurrentLocation': 'Использовать текущее местоположение',
    'enableLocationServices': 'Включите службы определения местоположения для автозаполнения координат.',
    'enableLocationPermissions': 'Включите разрешения на определение местоположения для автозаполнения координат.',
    'unableToFetchLocation': 'Не удалось получить местоположение. Пожалуйста, попробуйте еще раз.',
    'unableToFetchLocationShort': 'Не удалось получить местоположение.',
    'pleaseEnterValidLatLng': 'Пожалуйста, введите действительные широту и долготу.',
    'createPassword': 'Создать пароль',
    'minimum8CharactersRequired': 'Требуется минимум 8 символов',
    'weVerifyEveryBusiness': 'Мы проверяем каждый бизнес вручную, чтобы обеспечить доверие к рынку.',
    'submitForReview': 'Отправить на рассмотрение',
    'alreadyVerifiedSignIn': 'Уже проверено? Войти',
    'forgotPassword': 'Забыли пароль?',
    'welcomeBack': 'Добро пожаловать',
    'signInToReach': 'Войдите в систему, чтобы связаться с одобренными оптовиками рядом с вами.',
    'createKioskOrWholesalerAccount': 'Создайте учетную запись киоска или оптового продавца.',
    'accountSubmittedForApproval': 'Аккаунт отправлен на утверждение. Панель управления разблокируется после одобрения.',
    'dashboardWillUnlock': 'Панель управления разблокируется после одобрения.',
    'pleaseLoginToPlaceOrder': 'Пожалуйста, войдите, чтобы разместить заказ',
    // ============================================
    // Legal / Compliance (T&C + GDPR)
    // ============================================
    'legalComplianceTitle': 'Юридические вопросы и соблюдение требований',
    'termsAndConditionsFullText': 'Создавая учетную запись, вы вступаете в деловые отношения с оператором платформы и соглашаетесь с Условиями использования платформы (AGB). Настоящие Условия определяют, как вы можете использовать торговую площадку, как обрабатываются сделки и заказы, а также какие обязательства применяются к покупателям и оптовикам. Вы подтверждаете, что вся предоставленная вами информация является точной и что вы будете использовать платформу только в законных деловых целях. Вы также соглашаетесь с тем, что сделки и заказы могут стать обязательными после подтверждения оптовым продавцом или после достижения цели сделки. В зависимости от вашей юрисдикции могут применяться дополнительные правила, специфичные для конкретной страны. Прежде чем продолжить, ознакомьтесь с полными Условиями использования, предоставленными оператором.',
    'scrollToAcceptTerms': 'Прокрутите раздел «Правила и условия» до конца, чтобы разблокировать флажок принятия.',
    'scrollToBottom': 'Прокрутить вниз',
    'acceptTermsLabel': 'Я прочитал и принимаю Условия использования (AGB).',
    'termsScrollHint': 'Пожалуйста, пролистайте Условия использования, прежде чем принять их.',
    'acceptPrivacyLabel': 'Я прочитал и принимаю политику конфиденциальности данных/GDPR.',
    'privacySummaryText': 'Ваши данные будут обрабатываться для управления учетными записями, заказами, аналитики и безопасности в соответствии с нашей политикой конфиденциальности.',
    'mustAcceptAllLegalDocuments': 'Пожалуйста, примите все юридические документы и подтвердите рамочный договор.',
    'mustAcceptTermsAndPrivacy': 'Чтобы продолжить, примите Условия использования и Конфиденциальность данных / GDPR.',
    // ============================================
    // Account Approval / Waiting Screen Related
    // ============================================
    'accountApproval': 'Утверждение аккаунта',
    'accountApproved': 'Аккаунт одобрен!',
    'redirecting': 'Перенаправление...',
    'pendingReview': 'Ожидает рассмотрения',
    'needMoreInfo': 'Нужна дополнительная информация',
    'wholesalerVerificationMessage': 'Спасибо! Чтобы активировать учетную запись оптового продавца, отправьте документы, подтверждающие ваш бизнес. Наш администратор рассмотрит и одобрит вашу учетную запись.',
    'buyerVerificationMessage': 'Спасибо! Чтобы активировать учетную запись покупателя, предоставьте документы, подтверждающие личность. Наш администратор рассмотрит и одобрит вашу учетную запись.',
    'generalVerificationMessage': 'Спасибо! Чтобы активировать учетную запись, отправьте подтверждающие документы. Наш администратор рассмотрит и одобрит вашу учетную запись.',
    'adminNote': 'Примечание администратора',
    'uploadVerificationDocument': 'Загрузить подтверждающий документ',
    'acceptedDocumentTypes': 'Принимаемые типы документов',
    'wholesalerDocumentTypes': 'Лицензия на ведение бизнеса, ИНН, документы о регистрации компании (PNG, JPG, PDF)',
    'buyerDocumentTypes': 'Удостоверение личности, водительские права или любое удостоверение личности государственного образца (PNG, JPG, PDF)',
    'generalDocumentTypes': 'Бизнес-лицензия, Водительские права, Удостоверение личности (PNG, JPG, PDF)',
    'selectedDocuments': 'Избранные документы',
    'addDocuments': 'Добавить документы',
    'uploading': 'Загрузка...',
    'uploaded': 'Загружено',
    'selectFirst': 'Выберите сначала',
    'documentsUploadedSuccessfully': 'документ(ы) загружен(ы) успешно. Наш администратор проверит и обновит статус вашей учетной записи.',
    'documentUploadedSuccessfully': 'Документ успешно загружен. Наш администратор проверит и обновит статус вашей учетной записи.',
    'failedToPickDocuments': 'Не удалось выбрать документы',
    'passport': 'Паспорт',
    'passportDescription': 'Загрузите свой паспорт для проверки личности',
    'passportAlternative': 'Если у вас нет паспорта, вы можете загрузить утвержденное правительством удостоверение личности с адресом (например, Аадхар в Индии, национальный идентификатор и т. д.)',
    'gewerbeschein': 'Гевербешайн',
    'idCard': 'Удостоверение личности',
    'taxId': 'Налоговый идентификатор',
    'companyRegistration': 'Регистрация компании',
    'document': 'Документ',
    'gewerbescheinDescription': 'Загрузите свою Gewerbeschein (торговую лицензию) для проверки бизнеса.',
    'gewerbescheinAlternative': 'Загрузите официальную торговую лицензию, выданную властями.',
    'businessLicense': 'Бизнес-лицензия / Gewerbeschein',
    'businessLicenseDescription': 'Загрузите свою бизнес-лицензию или Gewerbeschein для проверки бизнеса.',
    'businessLicenseAlternative': 'Если у вас нет лицензии на ведение бизнеса, вы можете загрузить документы о регистрации компании, налоговый идентификатор или любой официальный документ, подтверждающий бизнес.',
    'selectDocument': 'Выберите документ',
    'changeDocument': 'Изменить документ',
    'pleaseSelectAtLeastOneDocument': 'Пожалуйста, выберите хотя бы один документ для загрузки.',
    'sendByEmail': 'Отправить по электронной почте',
    'emailOptionDescription': 'Кроме того, вы можете отправить подтверждающие документы непосредственно по электронной почте. Наш администратор проверит документы и соответствующим образом обновит статус вашей учетной записи.',
    'openEmailToAdmin': 'Открыть письмо администратору',
    'emailDraftOpened': 'Черновик письма открыт. Пожалуйста, отправьте его для завершения подачи. Наш администратор проверит ваши документы и обновит статус вашего аккаунта.',
    'couldNotOpenEmailApp': 'Не удалось открыть приложение электронной почты. Пожалуйста, отправьте электронное письмо на',
    'manually': 'вручную',
    'failedToOpenEmail': 'Не удалось открыть письмо',
    'loadingAccountStatus': 'Загрузка статуса аккаунта...',
    'errorLoadingStatus': 'Ошибка загрузки статуса',
    'pleaseReviewAndResubmit': 'Пожалуйста, проверьте и отправьте документы повторно.',
    'useDifferentAccount': 'Использовать другой аккаунт',
    'useDifferentAccountConfirm':
        'Выйти, чтобы войти или зарегистрироваться с другим аккаунтом?',
    'failedToUpdateStatus': 'Не удалось обновить юридические настройки. Пожалуйста, попробуйте еще раз.',
    // ============================================
    // Profile Related
    // ============================================
    'editProfile': 'Редактировать профиль',
    'profileUpdated': 'Профиль успешно обновлен',
    'failedToUpdateProfile': 'Не удалось обновить профиль',
    'profileImageUpdated': 'Изображение профиля обновлено',
    'failedToUploadImage': 'Не удалось загрузить изображение',
    'tagline': 'Слоган',
    'locations': 'Локации',
    'addLocation': 'Добавить местоположение',
    'editLocation': 'Изменить местоположение',
    'deleteLocation': 'Удалить местоположение',
    'latitude': 'Широта',
    'longitude': 'Долгота',
    'nameIsRequired': 'Требуется имя',
    'businessNameOptional': 'Название компании (необязательно)',
    'phoneOptional': 'Телефон (необязательно)',
    'addresses': 'Адреса',
    'addAddress': 'Добавить адрес',
    'noAddressesAdded': 'Адреса не добавлены',
    'addYourFirstAddress': 'Добавьте свой первый адрес, чтобы начать',
    'editAddress': 'Изменить адрес',
    'removeAddress': 'Удалить адрес',
    'editAddressTitle': 'Изменить адрес',
    'addAddressTitle': 'Добавить адрес',
    'saveChanges': 'Сохранить изменения',
    'labelExample': 'Этикетка (например, «Дом», «Офис», «Главная розетка»)',
    'streetAreaOptional': 'Улица/Район (необязательно)',
    'countryOptional': 'Страна (необязательно)',
    'cityOptional': 'Город (необязательно)',
    'locationNotUpdating': 'Местоположение не обновляется',
    'locationNotUpdatingSolution': 'Перейдите в «Профиль» > «Адреса» и убедитесь, что координаты вашего местоположения верны.',
    // ============================================
    // Deals Related
    // ============================================
    'deals': 'Специальные предложения',
    'activeDeals': 'Активные предложения',
    'allDeals': 'Все предложения',
    'myDeals': 'Мои предложения',
    'manageDeals': 'Управление предложениями',
    'noDealsFound': 'Сделок не найдено',
    'selectDeal': 'Выберите сделку',
    'unableToLoadDeals': 'Не удалось загрузить сделки.',
    'noDealsAvailable': 'Нет доступных предложений',
    'noDealsYet': 'Сделок пока нет',
    'checkBackLaterForNewDeals': 'Зайдите позже, чтобы узнать о новых предложениях',
    'noActiveDeals': 'Нет активных сделок',
    'filterDeals': 'Фильтровать предложения',
    'progress': 'Прогресс',
    'dealClosed': 'Сделка закрыта',
    'ends': 'Заканчивается',
    'variant': 'Вариант',
    'min': 'Мин:',
    'max': 'Макс:',
    'perUnit': '/единица',
    'perUnitLabel': 'По {unit}',
    'inStock': 'в наличии',
    'similarProducts': 'Похожие продукты',
    'noActiveDealsForProduct': 'Для этого продукта нет активных предложений.',
    'activeDealsForProduct': 'Активные предложения на этот продукт',
    'moreFromWholesaler': 'Больше от {name}',
    'dealsFromWholesaler': 'Предложения от {name}',
    'productsFromWholesaler': 'Товары из {name}',
    'searchProductsFromWholesaler': 'Поиск товаров из {name}...',
    'onlyKioskCanPurchase': 'Только учетные записи киосков/магазинов могут приобретать продукты.',
    'canOnlyReviewFromDelivered': 'Вы можете просматривать товары только из доставленных заказов.',
    'alreadyReviewedThisProduct': 'Вы уже оставили отзыв на этот товар из этого заказа',
    'selectOrderToReview': 'Выберите заказ для проверки',
    'orderN': 'Заказ №{id}',
    'viewDeals': 'Посмотреть предложения',
    'locationInfoNotAvailable': 'Информация о местонахождении недоступна',
    'location': 'Расположение',
    'kfProductDealTagline': 'Предложение по продуктам KF. Помощь в поиске лучших предложений.',
    'errorSearchingProducts': 'Ошибка поиска продуктов',
    'myDealOrders': 'Мои заказы на сделки',
    'noDealOrdersYet': 'Заказов на сделки пока нет',
    'browseDealsPlaceFirstOrder': 'Просмотрите активные предложения и разместите свой первый заказ.',
    'statusLabel': 'Статус',
    'noProductsFoundForWholesaler': 'Для выбранного оптовика товары не найдены',
    'noApprovedWholesalersAvailable': 'Нет одобренных оптовиков',
    'searchByNameBusinessEmail': 'Поиск по имени, названию компании, адресу электронной почты...',
    'selectWholesaler': 'Выберите оптовика',
    'selectProduct': 'Выберите продукт',
    'pageNOfM': 'Страница {current} из {total}',
    'priceLabel': 'Цена',
    'pleaseSelectImageOrVideo': 'Пожалуйста, выберите изображение или видео',
    'onlyWholesalersCreateStories': 'Только оптовики могут создавать истории',
    'storyCreatedSuccessfully': 'История успешно создана! 🎉',
    'uploadingMedia': 'Загрузка медиа...',
    'creatingStory': 'Создание истории...',
    'storyMedia': 'История СМИ',
    'videoSelected': 'Видео выбрано',
    'activeShopsSuffix': 'активные магазины',
    'storiesCountSuffix': 'истории',
    'create': 'Создавать',
    'off': 'ВЫКЛЮЧЕННЫЙ',
    'minOrder': 'Минимальный заказ',
    'target': 'Цель',
    'units': 'единицы',
    'dealCreatedSuccessfully': 'Сделка успешно создана',
    'createDeal': 'Создать сделку',
    'editDeal': 'Редактировать сделку',
    'closeDeal': 'Закрыть сделку',
    'closeDealConfirmMessage': 'Вы уверены, что хотите закрыть эту сделку? Это действие невозможно отменить.',
    'closeDealGoalReached': 'Цель достигнута',
    'closeDealGoalReachedHint': 'Если отмечено: все отложенные ордера будут автоматически подтверждены (сделка успешно исполнена). Если флажок снят: сделка закроется, но позже вы сможете подтвердить ордера вручную.',
    'createYourFirstDeal': 'Создайте свою первую сделку',
    'dealTitle': 'Название сделки',
    'pleaseEnterDealTitle': 'Пожалуйста, введите название сделки',
    'dealType': 'Тип сделки',
    'dealPrice': 'Цена сделки',
    'startDate': 'Дата начала',
    'endDate': 'Дата окончания',
    'pleaseEnterDealPrice': 'Пожалуйста, введите цену сделки',
    'originalPrice': 'Первоначальная цена',
    'targetQuantity': 'Целевое количество',
    'pleaseEnterTargetQuantity': 'Пожалуйста, введите целевое количество',
    'targetQuantityMin': 'Целевое количество должно быть не менее 1.',
    'minOrderQty': 'Минимальное количество заказа',
    'pleaseEnterMinOrderQty': 'Пожалуйста, введите минимальный объем заказа',
    'minOrderQtyMin': 'Минимальное количество заказа должно быть не менее 1',
    'maxOrderQuantityOptional': 'Максимальное количество заказа (опционально)',
    'endDateMustBeAfterStartDate': 'Дата окончания должна быть позже даты начала.',
    'pleaseSelectWholesalerFirst': 'Пожалуйста, сначала выберите оптовика',
    'auction': 'Аукцион',
    'priceDrop': 'Снижение цен',
    'limitedStock': 'Ограниченный запас',
    'scheduled': 'Запланировано',
    'live': 'Жить',
    'highlightedDeal': 'Выделенная сделка',
    'canOnlyViewDeals': 'может только просматривать сделки. Размещать заказы могут только учетные записи киосков/магазинов.',
    'dealProgressNotUpdating': 'Ход сделки не обновляется',
    'dealProgressNotUpdatingSolution': 'Ход сделки обновляется автоматически. Если кажется, что что-то застряло, обновите страницу.',
    'dealProgress': 'Ход сделки',
    'unableToLoadProgress': 'Невозможно загрузить прогресс: {detail}',
    'noOrdersPlacedYet': 'Заказов по данной сделке пока не поступало.',
    'orderPlacedSuffix': 'заказ размещен',
    'ordersPlacedSuffix': 'заказы размещены',
    'closed': 'закрыто',
    // ============================================
    // Products Related
    // ============================================
    'product': 'Продукт',
    'products': 'продукты',
    'productsSection': 'Продукты',
    'allProducts': 'Все продукты',
    'myProducts': 'Мои продукты',
    'noProductsAvailable': 'Нет доступных продуктов',
    'noProductsYet': 'Товаров пока нет',
    'addYourFirstProduct': 'Добавьте свой первый продукт',
    'addFirstProduct': 'Добавьте свой первый продукт',
    'addProduct': 'Добавить продукт',
    'editProduct': 'Редактировать продукт',
    'deleteProduct': 'Удалить продукт',
    'deletingProduct': 'Удаление продукта...',
    'deleteProductConfirmGeneric': 'Вы уверены, что хотите удалить этот товар? Это действие невозможно отменить.',
    'productUpdatedSuccessfully': 'Продукт успешно обновлен',
    'productCreatedSuccessfully': 'Продукт успешно создан',
    'productDeletedSuccessfully': 'Товар успешно удален',
    'changeProductStatus': 'Изменить статус продукта',
    'changeStatus': 'Изменить статус',
    'updatingStatus': 'Обновление статуса...',
    'statusUpdatedToPending': 'Статус изменен на Ожидание',
    'statusUpdatedToApproved': 'Статус изменен на «Одобрено»',
    'statusUpdatedToRejected': 'Статус изменен на «Отклонено»',
    'productsWillAppearHere': 'Товары появятся здесь после того, как они будут добавлены.',
    'noProductsFound': 'Товары не найдены',
    'youveReachedEnd': 'Вы достигли конца',
    'errorLoadingProducts': 'Ошибка загрузки товаров',
    'featuredCatalog': 'Рекомендуемый каталог',
    'viewAll': 'Посмотреть все',
    'outOfStock': 'РАСПРОДАНО',
    'onlyLeft': 'ТОЛЬКО',
    'left': 'ЛЕВЫЙ',
    'timeRemainingDay': '{count} день осталось',
    'timeRemainingDays': '{count} дней осталось',
    'timeRemainingHour': '{count} ч. осталось',
    'timeRemainingHours': '{count} ч. осталось',
    'timeRemainingMinute': '{count} мин. осталось',
    'timeRemainingMinutes': '{count} мин. осталось',
    'pleaseSelectProduct': 'Пожалуйста, выберите продукт',
    'tapToSelectProduct': 'Нажмите, чтобы выбрать продукт',
    'unknownProduct': 'Неизвестный продукт',
    'searchProductsHint': 'Поиск товаров по названию, SKU...',
    'loadingMoreProducts': 'Загрузка дополнительных товаров...',
    'reachedEnd': 'Вы достигли конца',
    'productsCountSuffix': 'продукты',
    'price': 'Цена',
    'kilogram': 'Килограмм',
    'gram': 'Грамм',
    'liter': 'Литр',
    'milliliter': 'Миллилитр',
    'piece': 'Кусок',
    'box': 'Коробка',
    'pack': 'Пакет',
    'kmAway': 'км',
    'viewAllProducts': 'Просмотреть все продукты',
    // ============================================
    // Product Management Related
    // ============================================
    'productTitle': 'Название продукта',
    'productTitleRequired': 'Пожалуйста, введите название продукта',
    'titleMinLength': 'Название должно быть не менее 3 символов.',
    'description': 'Описание',
    'category': 'Категория',
    'wholesaler': 'Оптовик',
    'selectCategory': 'Выберите категорию',
    'selectCategories': 'Выберите категории',
    'pleaseSelectCategory': 'Пожалуйста, выберите категорию',
    'tapToSelectCategory': 'Нажмите, чтобы выбрать категорию',
    'pleaseSelectWholesaler': 'Пожалуйста, выберите оптовика',
    'tapToSelectWholesaler': 'Нажмите, чтобы выбрать оптовика',
    'unknownCategory': 'Неизвестная категория',
    'yourAccount': 'Ваш аккаунт',
    'currentUser': 'Текущий пользователь',
    'variants': 'Варианты',
    'useVariants': 'Используйте варианты',
    'addVariant': 'Добавить вариант',
    'addAttribute': 'Добавить атрибут',
    'variantSkuRequired': 'Требуется артикул',
    'addAtLeastOneVariant': 'Пожалуйста, добавьте хотя бы один вариант',
    'selectVariant': 'Выберите вариант',
    'selectVariantHelper': 'Выберите вариант для этой сделки',
    'noVariantsMessage': 'У этого товара нет вариантов. Сделка будет создана непосредственно на продукте.',
    'unableToLoadVariantsMessage': 'Не удалось загрузить варианты. Сделка будет создана по товару.',
    'featuredProduct': 'Рекомендуемый продукт',
    'default': 'По умолчанию',
    'updateProduct': 'Обновить продукт',
    'createProduct': 'Создать продукт',
    'globalAttributes': 'Глобальные атрибуты',
    'globalAttributesDescription': 'Определите такие атрибуты, как Цвет и Размер, чтобы применить их ко всем вариантам.',
    'attributeName': 'Имя атрибута (например, цвет)',
    'attributeNameHint': 'Цвет, размер, материал...',
    'imageUrl': 'URL-адрес изображения',
    'productImages': 'Изображения продукта',
    'firstImagePrimary': 'Первое изображение является основным',
    'addImageUrl': 'Добавить URL',
    'pasteImageUrlHint': 'Вставить URL изображения',
    'costPrice': 'Себестоимость',
    'stock': 'Запас',
    'stockRequired': 'Пожалуйста, укажите запас',
    'stockNegative': 'Запас не может быть отрицательным',
    'priceRequired': 'Пожалуйста, введите цену',
    'pricePositive': 'Цена должна быть больше 0',
    'validationError': 'Ошибка проверки',
    'checkAllFields': 'Пожалуйста, проверьте все поля',
    'pending': 'В ожидании',
    'approved': 'Одобренный',
    'rejected': 'Отклоненный',
    'draft': 'Черновик',
    'failedToCreateDeal': 'Не удалось создать сделку.',
    'invalidDateTimeFormat': 'Неверный формат даты/времени. Пожалуйста, проверьте ваши даты.',
    // ============================================
    // Categories Related
    // ============================================
    'noCategoriesFound': 'Категории не найдены',
    'noCategoriesAvailable': 'Нет доступных категорий',
    'allCategories': 'Все категории',
    'searchCategories': 'Категории поиска...',
    'noCategoriesMatchSearch': 'Ни одна категория не соответствует вашему запросу',
    'categoriesWillAppearHere': 'Категории появятся здесь после их добавления.',
    'tryDifferentSearchTerm': 'Попробуйте другой поисковый запрос',
    'errorLoadingCategories': 'Ошибка загрузки категорий.',
    'unableToLoadCategory': 'Не удалось загрузить категорию',
    'productsCount': '{n} товаров',
    'categoryName': 'Название категории',
    'categoryDescription': 'Описание',
    'categoryImageUrl': 'URL-адрес изображения',
    'createCategory': 'Создать категорию',
    'editCategory': 'Изменить категорию',
    'deleteCategory': 'Удалить категорию',
    'deleteCategoryConfirm': 'Вы уверены, что хотите удалить «{name}»? Это действие невозможно отменить.',
    'categoryCreatedSuccessfully': 'Категория успешно создана',
    'enterCategoryDescriptionToGenerate': 'Введите описание категории, чтобы автоматически генерировать контент.',
    'categoryDescriptionHint': 'Например, органические овощи...',
    'contentGeneratedSuccessfullyEnglish': 'Контент успешно создан! (Английский)',
    'generationFailedWithError': 'Не удалось создать: {error}.',
    'categoryUpdatedSuccessfully': 'Категория успешно обновлена',
    'categoryDeletedSuccessfully': 'Категория успешно удалена',
    'categoryCreationImportMessage': 'Создание категорий в настоящее время осуществляется посредством импорта. Пожалуйста, свяжитесь с администратором.',
    'pleaseEnterCategoryName': 'Пожалуйста, введите название категории',
    // ============================================
    // Reviews Related
    // ============================================
    'reviewed': 'Рассмотрено',
    'youHaveAlreadyReviewed': 'Вы уже оставили отзыв на этот товар из этого заказа',
    'reviewUpdatedSuccessfully': 'Обзор успешно обновлен',
    'reviewSubmittedSuccessfully': 'Отзыв успешно отправлен',
    'pleaseSelectRating': 'Пожалуйста, выберите рейтинг',
    'maximum5ImagesAllowed': 'Разрешено максимум 5 изображений.',
    'failedToPickImage': 'Не удалось выбрать изображение',
    'failedToUploadImages': 'Не удалось загрузить изображения',
    'uploadImages': 'Загрузить изображения',
    'pickImage': 'Выберите изображение',
    'pickVideo': 'Выбрать видео',
    'uploadFailed': 'Загрузка не удалась',
    'upload': 'Загрузить',
    'invalidImageUrl': 'Неверный URL изображения.',
    // ============================================
    // Banners Related
    // ============================================
    'viewProduct': 'Посмотреть продукт',
    'viewDeal': 'Посмотреть сделку',
    'openLink': 'Открыть ссылку',
    'discoverGreatDealsNearby': 'Откройте для себя выгодные предложения поблизости',
    'stayTunedForOffers': 'Следите за новыми предложениями и историями от проверенных оптовиков.',
    'manageBanners': 'Управление баннерами',
    'myBanners': 'Мои баннеры',
    'noBannersFound': 'Баннеры не найдены. Создайте его!',
    'bannerDetails': 'Детали баннера',
    'bannerNotFound': 'Баннер не найден',
    'views': 'Просмотры',
    'clicks': 'Клики',
    'bannerRequestSubmitted': 'Запрос на баннер отправлен!',
    'failedToSubmitRequest': 'Не удалось отправить запрос',
    'deleteBanner': 'Удалить баннер',
    'deleteBannerConfirm': 'Вы уверены, что хотите удалить этот баннер?',
    'bannerDeleted': 'Баннер удален.',
    'failedToDeleteBanner': 'Не удалось удалить баннер.',
    'targetId': 'Идентификатор цели',
    'url': 'URL-адрес',
    'createNewBanner': 'Создать новый баннер',
    'bannerTitle': 'Название баннера',
    'enterBannerTitle': 'Введите название баннера',
    'bannerImage': 'Изображение баннера',
    'webBannerImage': 'Изображение для веба',
    'webBannerImageHint': 'Альбомная ориентация для веба',
    'mobileBannerImage': 'Мобильное изображение',
    'mobileBannerImageHint': 'Портрет/квадрат для мобильных',
    'mobilePreview': 'Мобильный предпросмотр',
    'preview': 'Предпросмотр',
    'previewMobile': 'Предпросмотр',
    'previewWillAppearHere': 'Здесь появится предпросмотр',
    'pasteImageUrlHere': 'Вставьте сюда URL изображения',
    'pleaseEnterImageUrlOrSwitch': 'Введите URL-адрес изображения или переключитесь на «Загрузить» и выберите изображение.',
    'pleaseTapChooseImage': 'Нажмите «Выбрать изображение», чтобы загрузить изображение баннера, или переключитесь на URL-адрес и вставьте ссылку на изображение.',
    'tapToUploadWebImage': 'Нажмите, чтобы загрузить веб-изображение',
    'tapToUploadMobileImage': 'Нажмите, чтобы загрузить мобильное изображение',
    'chooseImage': 'Выберите изображение',
    'replaceImage': 'Заменить изображение',
    // ============================================
    // Stories Related
    // ============================================
    'createStory': 'Создать историю',
    'storiesFromVerifiedWholesalers': 'Истории проверенных оптовиков',
    'storiesWillAppearHere': 'Истории появятся здесь, как только они будут добавлены.',
    'selectImageOrVideoForStory': 'Выберите изображение или видео для своей истории',
    'post': 'Почта',
    'expiresAt': 'Срок действия истекает в',
    // ============================================
    // Shipment / Tracking Related
    // ============================================
    'trackingNumber': 'Идентификационный номер',
    'carrier': 'Перевозчик',
    'trackingUrl': 'URL-адрес отслеживания',
    'openTrackingLink': 'Открыть ссылку для отслеживания',
    'statusTimeline': 'Status Timeline',
    // ============================================
    // Account Deletion Related
    // ============================================
    'submitDeletionRequest': 'Submit Deletion Request',
    'submitRequest': 'Отправить запрос',
    'reviewProcess': 'Процесс рассмотрения',
    'accountDeleted': 'Аккаунт удален',
    'whatHappensNext': 'Что произойдет дальше?',
    'submitRequestDescription': 'Введите свой адрес электронной почты, чтобы запросить удаление учетной записи',
    'reviewProcessDescription': 'Наша команда рассмотрит ваш запрос в течение 24-48 часов. Вы получите электронное письмо с подтверждением, как только ваш запрос будет обработан.',
    'accountDeletedDescription': 'Ваша учетная запись и все связанные с ней данные будут удалены без возможности восстановления. Это действие невозможно отменить.',
    'ourTeamReviewsYourRequest': 'Наша команда рассматривает ваш запрос',
    'reviewDetails': 'Подробности обзора',
    'reviewDetailsDescription': 'Мы проверяем вашу учетную запись и обеспечиваем выполнение всех отложенных ордеров или транзакций, прежде чем приступить к удалению.',
    'yourAccountIsPermanentlyRemoved': 'Ваш аккаунт удален навсегда',
    'finalStep': 'Последний шаг',
    'finalStepDescription': 'После одобрения данные вашей учетной записи будут навсегда удалены из нашей системы. Это действие невозможно отменить.',
    'importantInformation': 'Важная информация',
    'accountDeletionIsPermanent': 'Удаление учетной записи является окончательным и не может быть отменено.',
    'allDataWillBeRemoved': 'Все ваши данные, заказы и история будут навсегда удалены.',
    'pendingOrdersMustBeCompleted': 'Отложенные ордера должны быть завершены, прежде чем можно будет продолжить удаление.',
    'youllReceiveEmailConfirmation': 'Вы получите подтверждение по электронной почте после завершения процесса.',
    'confirmActionPermanent': 'Подтвердите, что вы понимаете, что это действие является постоянным.',
    'requestSubmitted': 'Запрос отправлен',
    'deletionRequestSubmittedMessage': 'Запрос на удаление вашей учетной записи успешно отправлен. Наша команда рассмотрит его в течение 24–48 часов. Вы получите электронное письмо с подтверждением, как только ваш запрос будет обработан.',
    'ok': 'ХОРОШО',
    'failedToSubmitDeletionRequest': 'Не удалось отправить запрос на удаление. Пожалуйста, попробуйте еще раз.',
    'requestAccountDeletion': 'Запросить удаление учетной записи',
    'sorryToSeeYouGo': 'Нам жаль, что ты уходишь',
    'emailAddress': 'Адрес электронной почты',
    'enterRegisteredEmail': 'Введите зарегистрированный адрес электронной почты',
    'emailAddressRequired': 'Требуется адрес электронной почты',
    'pleaseEnterValidEmail': 'Пожалуйста, введите действительный адрес электронной почты',
    'reasonForDeletionOptional': 'Причина удаления (необязательно)',
    'helpUsImproveLeaving': 'Помогите нам стать лучше, рассказав, почему вы уходите...',
    'understandActionPermanent': 'Я понимаю, что это действие является постоянным и не может быть отменено.',
    // ============================================
    // Support / Help Related
    // ============================================
    'emailSupport': 'Поддержка по электронной почте',
    'getHelpViaEmail': 'Получить помощь по электронной почте',
    'phoneSupport': 'Поддержка по телефону',
    'callUsDuringBusinessHours': 'Позвоните нам в рабочее время',
    'liveChat': 'Живой чат',
    'chatWithUs': 'Поговорите с нами',
    'chatWithSupportTeam': 'Поговорите с нашей службой поддержки',
    'commonIssues': 'Общие проблемы',
    'orderNotShowingUp': 'Заказ не появляется',
    'orderNotShowingUpSolution': 'Обновите панель управления или проверьте историю заказов в разделе «Мои заказы».',
    'liveChatComingSoon': 'Живой чат скоро появится!',
    'needHelpContactSupport': 'Нужна помощь? Обратиться в службу поддержки',
    'contactSupportAt': 'Свяжитесь со службой поддержки по адресу',
    'getInTouch': 'Свяжитесь с нами',
    'wereHereToHelp': 'Мы здесь, чтобы помочь вам',
    'businessEmail': 'Деловая электронная почта',
    'contactUsOnWhatsApp': 'Свяжитесь с нами по WhatsApp',
    'helloNeedAssistance': 'Привет! Мне нужна помощь.',
    'myDetails': 'Мои данные:',
    'nameLabel': 'Имя:',
    'phoneLabel': 'Телефон:',
    'emailLabel': 'Электронная почта:',
    'businessLabel': 'Бизнес:',
    'howCanYouHelpMe': 'Как вы можете мне помочь?',
    'unableToOpenWhatsApp': 'Не могу открыть WhatsApp. Пожалуйста, попробуйте еще раз.',
    'hello': 'Привет',
    // ============================================
    // Common Validation Related
    // ============================================
    'required': 'Это поле обязательно к заполнению',
    'invalidEmail': 'Неверный адрес электронной почты',
    'passwordTooShort': 'Пароль должен быть не менее 6 символов',
    'passwordsDoNotMatch': 'Пароли не совпадают',
    // ============================================
    // Manager / Admin Related
    // ============================================
    'admin': 'Админ',
    'role': 'Роль',
    'created': 'Созданный',
    'subAdmin': 'субадминистратор',
    'accessDenied': 'Доступ запрещен',
    'managersSectionOnly': 'Этот раздел доступен только менеджерам',
    'totalRevenue': 'Общий доход',
    'myRevenue': 'Мой доход',
    'activeShops': 'Активные оптовики',
    'activeMembers': 'Активные магазины/койски',
    'inactiveMembers': 'Неактивные магазины',
    'activeShopsSubtitle': 'Проверенные оптовики на платформе',
    'activeMembersSubtitle': 'Магазины, которые недавно заказали',
    'inactiveMembersSubtitle': 'Нет заказов более 60 дней',
    'lastOrder': 'Последний заказ',
    'lastActive': 'Последний активный',
    'lastLogin': 'Последний вход',
    'joined': 'Присоединился',
    'selectToNotify': 'Выберите, чтобы отправить уведомление',
    'deselect': 'Отменить выбор',
    'recipients': 'Получатели',
    'notificationSent': 'Notification sent',
    'noInactiveMembers': 'No inactive members',
    'selectAll': 'Выбрать все',
    'sendNotification': 'Send notification',
    'title': 'Заголовок',
    'body': 'Сообщение',
    'send': 'Отправлять',
    'generateWithAI': 'Генерируйте с помощью ИИ',
    'generateNotificationPrompt': 'Опишите уведомление (например, повторное вовлечение, флэш-распродажа, новые продукты), чтобы создать заголовок и сообщение.',
    'weMissYou': 'Мы скучаем по тебе!',
    'reEngagementDefaultBody': 'Вы давно не делали заказ. Просмотрите наши последние предложения и продукты.',
    'notificationRemindHint': 'например, «Напомнить неактивным магазинам о нашей зимней распродаже».',
    'searchByNameEmail': 'Поиск по имени, электронной почте...',
    'generate': 'Генерировать',
    'page': 'Страница',
    'never': 'Никогда',
    'quickActions': 'Быстрые действия',
    'recentOrders': 'Недавние заказы',
    'noRecentOrders': 'Нет недавних заказов',
    'analyticsComingSoon': 'Аналитика – Скоро',
    'importCsv': 'Импорт из CSV',
    'importFromCsv': 'Импорт из CSV',
    'importProductsFromCsv': 'Импортируйте товары из CSV',
    'importProducts': 'Импортировать продукты',
    'importing': 'Импорт...',
    'downloadCsvTemplate': 'Скачать CSV-шаблон',
    'getSampleCsvWithColumns': 'Получите образец CSV-файла со всеми необходимыми столбцами.',
    'selectCsvFile': 'Выберите CSV-файл',
    'chooseFile': 'Выберите файл',
    'tapToSelectWholesalerForImport': 'Нажмите, чтобы выбрать оптового продавца импортной продукции',
    'importComplete': 'Импорт завершен',
    'inserted': 'Вставлено',
    'updated': 'Обновлено',
    'skipped': 'Пропущено',
    'fileLabel': 'Файл: {name}',
    'wholesalerRequired': 'Оптовик *',
    'wholesalerLabel': 'Оптовый торговец {id}',
    'csvPreviewRows': 'Предварительный просмотр CSV ({n} строк)',
    'multipleRowsSameProductVariant': 'Несколько строк с одинаковым названием продукта = несколько вариантов.',
    'errorsCount': 'Ошибки ({n})',
    'andMoreErrors': '... и еще {n} ошибок',
    'failedToReadFileBytes': 'Не удалось прочитать байты файла',
    'failedToGetFilePath': 'Не удалось получить путь к файлу',
    'errorPickingFile': 'Ошибка выбора файла: {error}.',
    'csvFileEmpty': 'CSV-файл пуст.',
    'errorParsingCsv': 'Ошибка анализа CSV: {error}.',
    'templateSavedSuccessfully': 'Шаблон успешно сохранен.',
    'templateDownloadCancelled': 'Загрузка шаблона отменена.',
    'errorGeneratingTemplate': 'Ошибка создания шаблона.',
    'errors': 'Ошибки',
    'viewWholesaler': 'Посмотреть оптовика',
    'cropImage': 'Обрезать изображение',
    'change': 'Изменять',
    'navigationError': 'Ошибка навигации',
    // ============================================
    // Time Related
    // ============================================
    'hours': 'часы',
    'minutes': 'Минуты',
    'seconds': 'Секунды',
    'twentyFourHours': '24 часа',
    'twelveHours': '12 часов',
    'sixHours': '6 часов',
    // ============================================
    // Navigation / Route Errors
    // ============================================
    'noStoryDataProvided': 'Данные по истории не предоставлены.',
    'missingWholesalerId': 'Отсутствует идентификатор оптовика.',
    'missingProductId': 'Отсутствует идентификатор продукта.',
    'missingCategorySlug': 'Отсутствует ярлык категории.',
    'missingDealId': 'Отсутствует идентификатор сделки.',
    'missingOrderId': 'Отсутствует идентификатор заказа.',
    'featuredProducts': 'Рекомендуемые продукты',
    // ============================================
    // Order Update / Quantity Change Result
    // ============================================
    'orderUpdate': 'Обновление заказа',
    'viewMyOrders': 'Посмотреть мои заказы',
    'goToHome': 'Перейти домой',
    'quantityChangeAccepted': 'Изменение количества принято',
    'quantityChangeDeclined': 'Изменение количества отклонено',
    'somethingWentWrong': 'Что-то пошло не так',
    'orderUpdatedMessage': 'Ваш заказ обновлен.',
    'orderRevertedMessage': 'Ваш заказ был возвращен к предыдущему количеству.',
    'pleaseTryAgainLater': 'Пожалуйста, повторите попытку позже.',
    // ============================================
    // Deal Detail / Deal Errors
    // ============================================
    'unableToLoadDeal': 'Не удалось загрузить сделку.',
    'regularPrice': 'Обычная цена',
    'stockLabel': 'Запас',
    'dealNotStarted': 'Эта сделка еще не началась',
    'adminWholesalerManageHint': 'Как администратор или оптовик, вы можете управлять этой сделкой, но не можете размещать заказы. Используйте кнопку меню (⋮) на панели приложения, чтобы отредактировать или закрыть эту сделку.',
    'adminDealOnlyOwnerCanBid': 'Только администратор (владелец сделки) может добавлять ставки по сделкам администратора. Пользователи киосков не могут размещать заказы по этой сделке.',
    'kioskOnlyPlaceOrders': 'Только учетные записи киосков/магазинов могут размещать заказы по этой сделке.',
    'managementView': 'Представление управления',
    'ordering': 'Заказ',
    'failedToLoadDealData': 'Не удалось загрузить данные о сделке.',
    'dealClosedSuccess': 'Сделка успешно закрыта',
    'failedToCloseDeal': 'Не удалось закрыть сделку',
    'onlyAdminCanAddBidsOnAdminDeals': 'Только администратор (владелец сделки) может добавлять ставки по сделкам администратора.',
    // ============================================
    // Product Search / Detail
    // ============================================
    'searchProducts': 'Поиск продуктов',
    'youCanOnlyReviewFromDeliveredOrders': 'Вы можете просматривать товары только из доставленных заказов.',
    'allImages': 'Все изображения',
    'contentGeneratedSuccessfully': 'Контент успешно создан! Проверьте категорию и другие поля.',
    'generationFailed': 'Генерация не удалась',
    'userIdRequired': 'Требуется идентификатор пользователя',
    // ============================================
    // Admin Banner Management
    // ============================================
    'adminBannerManagement': 'Управление баннерами администратора',
    'requests': 'Запросы',
    'active': 'Активный',
    'noBannersFoundShort': 'Баннеры не найдены.',
    'failedToUpdateBanner': 'Не удалось обновить баннер.',
    'bannerSubmittedSuccessfully': 'Баннер успешно отправлен',
    'failedToCreateBanner': 'Не удалось создать баннер.',
    'failedToSubmitBannerRequest': 'Не удалось отправить запрос на баннер.',
    // ============================================
    // User Management / Admin
    // ============================================
    'administratorsOnlySection': 'Этот раздел доступен только администраторам',
    'allRoles': 'Все роли',
    'allStatuses': 'Все статусы',
    'suspended': 'Приостановленный',
    'noUsersFound': 'Пользователи не найдены',
    'pageOf': 'Страница',
    'ofLabel': 'из',
    'noDocumentsAvailable': 'Нет доступных документов',
    'userUpdatedSuccessfully': 'Пользователь обновлен успешно',
    'userCreatedSuccessfully': 'Пользователь успешно создан',
    'userDeletedSuccessfully': 'Пользователь успешно удален',
    'deleteUser': 'Удалить пользователя',
    'deleteUserConfirm': 'Вы уверены, что хотите удалить {name}? Это действие невозможно отменить.',
    'verificationDocuments': 'Подтверждающие документы',
    'noVerificationDocumentsYet': 'Подтверждающие документы еще не загружены.',
    'rejectionReason': 'Причина отклонения:',
    'createUser': 'Создать пользователя',
    'editUser': 'Изменить пользователя',
    'updateUser': 'Обновить пользователя',
    'roleRequired': 'Требуется роль',
    'statusRequired': 'Статус обязателен',
    'newPasswordLeaveEmpty': 'Новый пароль (оставьте пустым, чтобы сохранить актуальность)',
    'passwordRequired': 'Требуется пароль',
    'passwordMinLength': 'Пароль должен быть не менее 6 символов',
    'needInfo': 'Нужна информация',
    'business': 'Бизнес',
    'searchByNameEmailPhone': 'Поиск по имени, электронной почте, телефону...',
    'daysAgo': 'день(дней) назад',
    'activeDaysLast14': 'Активные дни (последние 14)',
    'docsCount': '{count} документы',
    'noPassportDocuments': 'Нет паспортных документов',
    'noGewerbescheinDocuments': 'Нет документов Gewerbeschein',
    'noBusinessLicenseDocuments': 'Отсутствие документов, подтверждающих лицензию на ведение бизнеса',
    'documentN': 'Документ {n}',
    'openInBrowser': 'Открыть в браузере',
    'pdfDocument': 'PDF-документ',
    'kiosk': 'Киоск',
    // ============================================
    // Order Management (Deal Orders)
    // ============================================
    'errorLoadingOrders': 'Ошибка загрузки заказов.',
    'errorLoadingDeals': 'Ошибка при загрузке сделок.',
    'orderManagement': 'Управление заказами',
    'orderCountSuffix': 'заказ',
    'confirmOrder': 'Подтвердить заказ',
    'confirmOrderMessage': 'Вы уверены, что хотите подтвердить этот заказ?',
    'confirm': 'Подтверждать',
    'markAsDelivered': 'Отметить как доставленное',
    'markDelivered': 'Отметить доставленное',
    'cancelOrder': 'Отменить заказ',
    'cancelOrderConfirm': 'Вы уверены, что хотите отменить этот заказ?',
    'no': 'Нет',
    'reduceQuantity': 'Уменьшить количество',
    'orderConfirmedSuccess': 'Заказ успешно подтвержден',
    'orderMarkedDelivered': 'Заказ помечен как доставленный',
    'failedToConfirmOrder': 'Не удалось подтвердить заказ',
    'failedToMarkDelivered': 'Не удалось отметить как доставленное',
    'orderCancelled': 'Заказ отменен',
    'failedToCancelOrder': 'Не удалось отменить заказ',
    'orderMarkedPaid': 'Заказ помечен как оплаченный',
    'failedToMarkOrderPaid': 'Не удалось отметить заказ как оплаченный',
    'quantityUpdatedSuccess': 'Количество успешно обновлено',
    'failedToUpdateQuantity': 'Не удалось обновить количество',
    'deliveryNotesOptional': 'Примечания к доставке (необязательно)',
    'newQuantity': 'Новое количество',
    'reduceQuantityHint': 'Введите новое количество. Минимум — 1 (или минимальный объем заказа по сделке). Используйте 0, чтобы отменить этот заказ.',
    'quantityUpdatedTo': 'Количество обновлено до',
    // ============================================
    // Deal Order Form
    // ============================================
    'enterQuantity': 'Введите количество',
    'pleaseEnterQuantity': 'Пожалуйста, введите количество',
    'invalidQuantity': 'Неверное количество',
    'minimumOrderIs': 'Минимальный заказ',
    'maximumOrderIs': 'Максимальный заказ',
    'addSpecialInstructions': 'Добавьте какие-либо специальные инструкции...',
    'minQuantityLabel': 'Мин',
    'selectedLabel': 'Выбрано',
    'maxQuantityLabel': 'Макс',
    // ============================================
    // Shipment / Carrier
    // ============================================
    'pleaseSelectCarrier': 'Пожалуйста, выберите оператора связи',
    'pleaseEnterCarrierNameForOther': 'Пожалуйста, введите название оператора связи в поле «Другое»',
    'shipmentCreatedSuccess': 'Отгрузка успешно создана',
    'shipmentCreatedAndOrderShipped': 'Отгрузка создана, заказ помечен как отправленный',
    'failedToCreateShipment': 'Не удалось создать отправку.',
    // ============================================
    // Stories
    // ============================================
    'failedToPickMedia': 'Не удалось выбрать носитель',
    'onlyWholesalersCanCreateStories': 'Только оптовики могут создавать истории',
    'storyCreatedSuccess': 'История успешно создана! 🎉',
    'failedToCreateStory': 'Не удалось создать историю.',
    // ============================================
    // Payment
    // ============================================
    'paymentCompletedSuccess': 'Платеж успешно завершен!',
    'paymentFailed': 'Платеж не выполнен',
    // ============================================
    // Notifications
    // ============================================
    'notifications': 'Уведомления',
    'markAllAsRead': 'Отметить все как прочитанное',
    'deleteAll': 'Удалить все',
    'filterNotifications': 'Фильтровать уведомления',
    'unread': 'Непрочитано',
    'read': 'Читать',
    'deleteAllNotificationsConfirm': 'Удалить все уведомления?',
    'deleteAllNotificationsMessage': 'Вы уверены, что хотите удалить все уведомления? Это действие невозможно отменить.',
    // ============================================
    // Deal / Product Modals
    // ============================================
    'paymentEmailTemplateGenerated': 'Шаблон электронного письма для оплаты создан.',
    'aiGenerationFailed': 'Генерация ИИ не удалась',
    'dealUpdatedSuccess': 'Сделка успешно обновлена',
    'allowOnlinePayment': 'Разрешить онлайн-платежи',
    'allowOnlinePaymentSubtitle': 'Если этот флажок снят, клиенты могут только размещать заказы; оплата (например, банковский перевод) запрашивается после подтверждения заказа.',
    'paymentAndEmail': 'Оплата и электронная почта',
    'generating': 'Создание…',
    'enterDealDescriptionPrompt': 'Введите четкое описание вашей сделки, чтобы автоматически генерировать контент.',
    'dealDescriptionHint': 'например, срочная распродажа: скидка 50 % на все зимние куртки.',
    'enterProductDescriptionPrompt': 'Введите описание или сведения о продукте, чтобы автоматически генерировать контент.',
    'productDescriptionHint': 'Например, кожаное офисное кресло премиум-класса с эргономичным дизайном...',
    'optionalAutoAssigned': 'Необязательно: будет назначено автоматически, если оно пустое.',
    'defaultYourAccount': 'По умолчанию: ваша учетная запись (нажмите, чтобы изменить)',
    'currentUserYou': 'Текущий пользователь (Вы)',
    'loadingProductDetails': 'Загрузка сведений о продукте...',
    'loading': 'Загрузка...',
    'ibanBankAccount': 'IBAN / Банковский счет',
    'accountOwner': 'Владелец аккаунта',
    'referenceTemplate': 'Справочный шаблон (например, DEAL-{dealCode}-{buyerId})',
    'paymentInstructions': 'Инструкции по оплате (свободный текст)',
    'paymentEmailSubject': 'Тема письма о платеже',
    'paymentEmailBody': 'Текст платежного письма (используйте {dealTitle}, {amount}, {iban}, {reference}, {accountOwner})',
    'ended': 'Закончено',
    'dealEnded': 'Сделка завершена',
    'dealHasEnded': 'Сделка завершена',
    'endingSoon': 'Скоро конец!',
    'endsIn1Day': 'Завершится через 1 день',
    'endsInDays': 'Завершится через {n} дн.',
    'endsIn1Hour': 'Завершится через 1 час',
    'endsInHours': 'Завершится через {n} часов',
    'endsSoon': 'Скоро заканчивается',
    'categories': 'Категории',
    'itemsCount': '{n} Предметы',
    // ============================================
    // Shipment Tracking
    // ============================================
    'pleaseEnterTrackingNumber': 'Пожалуйста, введите номер отслеживания',
    'pleaseSelectAtLeastOneItemToShip': 'Пожалуйста, выберите хотя бы один товар для отправки',
    'pleaseEnterTrackingUrlForOther': 'Введите URL отслеживания для «Другого» оператора связи.',
    'selectItemsToShip': 'Выберите товары для отправки',
    'noItemsAvailableForShipment': 'Нет товаров, доступных для отправки',
    'selectCarrier': 'Выберите оператора связи',
    'selectCarrierHint': 'Выберите оператора...',
    'carrierName': 'Имя оператора связи',
    'enterCarrierName': 'Введите название оператора связи',
    'trackingNumberRequired': 'Требуется номер отслеживания',
    'enterTrackingNumber': 'Введите номер отслеживания',
    'trackingUrlAutoGenerated': 'URL отслеживания будет сгенерирован автоматически.',
    'trackingUrlRequiredForOther': 'URL отслеживания необходим для оператора связи «Другой».',
    'pleaseEnterValidUrl': 'Пожалуйста, введите действительный URL-адрес',
    'estimatedDeliveryDate': 'Предполагаемая дата доставки',
    'selectDate': 'Выберите дату',
    'internalNotesShipment': 'Внутренние примечания об этой отправке',
    'trackingUrlHintAuto': 'Создается автоматически при указании оператора связи и номера отслеживания.',
    'trackShipment': 'Отследить доставку',
    'trackShipmentHint': 'Отслеживайте свою посылку, используя предоставленный номер отслеживания.',
    'trackingDetails': 'Детали отслеживания',
    'shipmentNotFound': 'Посылка не найдена',
    'pleaseCheckTrackingNumber': 'Пожалуйста, проверьте свой номер отслеживания и повторите попытку.',
    'noNotifications': 'Нет уведомлений',
    'youreAllCaughtUp': 'Вы все наверстали!',
    // ============================================
    // Select Deal / Category
    // ============================================

    // Feature audit – previously hardcoded strings
    'platformMobile': 'Мобильный',
    'platformWeb': 'Веб',
    'pleaseWait': 'Пожалуйста, подождите...',
    'defaultVariant': 'По умолчанию',
    'trackOnCarrierWebsite': 'Отследить на сайте перевозчика',
    'minOrderQtyRequired': 'Мин. заказ *',
    'dealPriceRequired': 'Цена сделки *',
    'targetQuantityRequired': 'Целевое количество *',
    'baseShippingCostEur': 'Базовая стоимость доставки (€)',
    'freeShippingThresholdQuantity': 'Бесплатная доставка от (кол-во)',
    'perUnitShippingCostEur': 'Стоимость доставки за единицу (€)',
    'descriptionOptional': 'Описание (необяз.)',
    'enterBannerDescription': 'Введите описание баннера',
    'bannerType': 'Тип баннера',
    'targetUrl': 'Целевой URL',
    'skuRequired': 'Артикул *',
    'productToPromoteHint': 'товар для продвижения',
    'selectDealToPromote': 'Выберите сделку для продвижения',
    'titleOptional': 'Заголовок (необяз.)',
    'giveReviewTitle': 'Дайте отзыву заголовок',
    'yourReviewOptional': 'Ваш отзыв (необяз.)',
    'shareExperienceWithProduct': 'Поделитесь опытом использования товара',
    'dealUpdatedSuccessfully': 'Сделка успешно обновлена',
    'dealPriceMustBeValidNumber': 'Цена сделки должна быть числом',
    'pleaseEnterMinOrderQuantity': 'Введите минимальное количество заказа',
    'paymentEmailPlaceholdersSubject':
        'Подстановки: {dealTitle}, {amount}, {reference}',
    'paymentEmailPlaceholdersBody':
        'Подстановки: {dealTitle}, {amount}, {accountOwner}, {iban}, '
        '{reference}, {additionalInstructions}',
    'failed': 'Ошибка',

    // ============================================
    // Order status (product orders – display only)
    // ============================================
    'orderStatusPendingConfirmation': 'Ожидает подтверждения',
    'orderStatusConfirmed': 'Подтверждён',
    'orderStatusPacking': 'Упаковывается',
    'orderStatusDispatched': 'Отправлен',
    'orderStatusOutForDelivery': 'Передан в доставку',
    'orderStatusDelivered': 'Доставлен',
    'orderStatusCancelled': 'Отменён',
    'orderStatusReturned': 'Возвращён',
    'orderStatusRefunded': 'Возмещён',

    // ============================================
    // Notifications (backend localization keys)
    // ============================================
    'notificationProductApprovalNeededTitle': 'Новый товар ожидает одобрения',
    'notificationProductApprovalNeededBody': '{0} создал(а) новый товар: {1}',
    'notificationProductStatusUpdatedTitle': 'Статус товара обновлён',
    'notificationProductApprovedBody': 'Ваш товар "{0}" одобрен!',
    'notificationProductRejectedBody': 'Ваш товар "{0}" отклонён.',
    'notificationProductPendingBody': 'Ваш товар "{0}" ожидает одобрения.',
    'notificationProductStatusChangedBody': 'Статус вашего товара "{0}" изменён на {1}',
    'notificationNewProductOrderTitle': 'Новый заказ на ваши товары',
    'notificationNewProductOrderBody': '{0} оформил(а) заказ: {1} шт. {2}',
    'notificationNewDealOrderTitle': 'Новый заказ по вашей сделке',
    'notificationNewDealOrderBody': '{0} оформил(а) заказ на {1} шт.',
    'notificationPaymentReportedTitle': 'Покупатель сообщил об оплате',
    'notificationPaymentReportedBody': '{0} сообщил(а) об оплате заказа. Детали: {1}',
    'notificationDealPaymentReportedBody': '{0} сообщил(а) об оплате заказа по сделке. Детали: {1}',
    'notificationDealOrderStatusUpdatedTitle': 'Статус заказа по сделке обновлён',
    'notificationDealOrderConfirmedBody': 'Ваш заказ по "{0}" подтверждён!',
    'notificationDealOrderShippedBody': 'Ваш заказ по "{0}" отправлен!',
    'notificationDealOrderDeliveredBody': 'Ваш заказ по "{0}" доставлен!',
    'notificationDealOrderCancelledBody': 'Ваш заказ по "{0}" отменён.',
    'notificationDealOrderRefundedBody': 'Ваш заказ по "{0}" возмещён.',
    'notificationDealOrderPendingBody': 'Ваш заказ по "{0}" ожидает подтверждения.',
    'notificationDealOrderStatusChangedBody': 'Статус вашего заказа по "{0}" изменён на {1}',
    'notificationOrderQuantityUpdatedTitle': 'Количество в заказе обновлено',
    'notificationDealOrderQuantityCancelledBody': 'Ваш заказ по "{0}" (было {1} шт.) отменён продавцом.',
    'notificationDealOrderQuantityChangedBody': 'Ваш заказ по "{0}" обновлён: количество изменено с {1} на {2} шт. продавцом.',
    'notificationQuantityChangeDeclinedTitle': 'Изменение количества отклонено',
    'notificationQuantityChangeDeclinedBody': '{0} отклонил(а) изменение количества. Заказ возвращён с {1} на {2} шт.',
    'notificationDealNowLiveTitle': 'Новая сделка доступна',
    'notificationDealNowLiveBody': '"{0}" теперь доступна. Успейте сделать заказ до окончания сделки.',
    'notificationDealTarget70PercentTitle': 'Сделка почти достигла цели',
    'notificationDealTarget70PercentBody': '"{0}" заполнена на {1}%! Присоединяйтесь и помогите владельцу сделки достичь цели — это укрепляет партнёрство и показывает вашу вовлечённость.',
    'notificationDealEnding24hTitle': 'Сделка скоро закончится',
    'notificationDealEnding24hBody': 'Последние 24 часа! "{0}" — осталось всего {1} заказ(ов), чтобы закрыть сделку.',
    'notificationDealEnding7dTitle': 'Сделка закончится через 7 дней',
    'notificationDealEnding7dBody': '"{0}" — осталось всего {1} заказ(ов), чтобы закрыть сделку.',
    'notificationDealSuccessTitle': 'Сделка успешно завершена',
    'notificationDealSuccessBody': 'Ваша групповая сделка "{0}" достигла нужного количества и теперь подтверждена. Подготовьтесь к оплате и доставке согласно инструкциям оптовика.',
    'notificationDealClosedTitle': 'Сделка закрыта',
    'notificationDealClosedBody': 'Сделка "{0}" была закрыта и больше не будет отображаться в активных сделках.',
    'notificationOrderStatusUpdatedTitle': 'Статус заказа обновлён',
    'notificationOrderConfirmedBody': 'Ваш заказ на "{0}" подтверждён!',
    'notificationOrderDispatchedBody': 'Ваш заказ на "{0}" отправлен!',
    'notificationOrderDeliveredBody': 'Ваш заказ на "{0}" доставлен!',
    'notificationOrderCancelledBody': 'Ваш заказ на "{0}" отменён.',
    'notificationOrderPackingBody': 'Ваш заказ на "{0}" упаковывается!',
    'notificationOrderOutForDeliveryBody': 'Ваш заказ на "{0}" передан в доставку!',
    'notificationOrderReturnedBody': 'Ваш заказ на "{0}" возвращён.',
    'notificationOrderRefundedBody': 'Ваш заказ на "{0}" возмещён.',
    'notificationOrderStatusChangedBody': 'Статус вашего заказа на "{0}" изменён на {1}',
    'notificationOrderItemRemovedBody': 'Позиция "{0}" в заказе (было {1} шт.) удалена продавцом.',
    'notificationOrderItemQuantityChangedBody': 'Позиция "{0}" в заказе обновлена: количество изменено с {1} на {2} шт. продавцом.',
    'notificationProductQuantityChangeDeclinedBody': '{0} отклонил(а) изменение количества позиции заказа. Возврат с {1} на {2} шт.',
    'notificationDailyEngagementTitle': 'Посмотрите предложения дня!',
    'notificationDailyEngagementBody': 'Сегодня: {0} баннер(ов), {1} сделок, {2} избранных товаров. Откройте приложение, чтобы увидеть предложения.',
    'notificationInactiveMembersAlertTitle': 'Предупреждение: неактивные участники',
    'notificationInactiveMembersAlertBody': '{0} магазин(ов) не делали заказ(ы) {1} дней. Стоит связаться или проверить.',
    'notificationBulkImportCompletedTitle': 'Пакетный импорт завершён',
    'notificationBulkImportCompletedBody': 'Успешно импортировано {0} товаров. Пропущено: {1}.',
    'notificationBannerApprovalNeededTitle': 'Новый баннер ожидает одобрения',
    'notificationBannerApprovalNeededBody': '{0} запросил(а) одобрение баннера: {1}',
    'notificationNewUserRegistrationTitle': 'Регистрация нового пользователя',
    'notificationNewUserRegistrationBody': '{0} ({1}) зарегистрировался(ась) как {2}. Ожидает одобрения.',
    'notificationBannerStatusChangedTitle': 'Статус баннера изменён',
    'notificationBannerApprovedBody': 'Ваш баннер "{0}" одобрен и теперь активен!',
    'notificationBannerRejectedBody': 'Ваш баннер "{0}" отклонён. Проверьте и при необходимости отправьте снова.',
    'notificationBannerDeactivatedBody': 'Ваш баннер "{0}" деактивирован.',
    'notificationBannerStatusChangedBody': 'Статус вашего баннера "{0}" изменён на {1}',
    'notificationAdminCustomTitle': '{0}',
    'notificationAdminCustomBody': '{0}',
  };
}