class TurkishFile {
  static const Map<String, String> turkishTranslations = {
    // ============================================
    // Options Screen Related
    // ============================================
    'options': 'Seçenekler',
    'account': 'Hesap',
    'myOrders': 'Siparişlerim',
    'myOrdersSubtitle': 'Siparişlerinizi görüntüleyin ve takip edin',
    'statistics': 'İstatistikler',
    'statisticsSubtitle': 'Anlaşma katılım istatistiklerinizi görüntüleyin',
    'profile': 'Profil',
    'profileSubtitle': 'Hesabınızı yönetin',
    'management': 'Yönetmek',
    'manageCategories': 'Kategorileri Yönet',
    'manageCategoriesSubtitle': 'Ürün kategorileri oluşturun ve yönetin',
    'createNewProductSubtitle': 'Yeni bir ürün oluştur',
    'createNewDealSubtitle': 'Yeni bir anlaşma oluştur',
    'viewOrdersSubtitle': 'Siparişleri görüntüleyin ve yönetin',
    'inactiveMembersViewSubtitle': 'Yakın zamanda sipariş verilmeyen mağazaları görüntüle',
    'manageBannersSubtitle': 'Uygulama banner\'larını yönetin (yönetici)',
    'myBannersSubtitle': 'Banner\'larınızı yönetin',
    'unableToLoadOptions': 'Seçenekler yüklenemiyor',
    'loggingOut': 'Oturum kapatılıyor...',
    'manageUsers': 'Kullanıcıları Yönet',
    'manageUsersSubtitle': 'Kullanıcı hesaplarını görüntüleyin ve yönetin',
    'analytics': 'Analitik',
    'analyticsSubtitle': 'İş analizlerinizi görüntüleyin',
    'information': 'Bilgi',
    'faq': 'SSS',
    'faqSubtitle': 'Sık sorulan sorular',
    'aboutUs': 'Hakkımızda',
    'aboutUsSubtitle': 'Platformumuz hakkında daha fazla bilgi edinin',
    'helpSupport': 'Yardım ve Destek',
    'helpSupportSubtitle': 'Yardım alın ve destek ekibiyle iletişime geçin',
    'accountActions': 'Hesap İşlemleri',
    'deleteAccount': 'Hesabı Sil',
    'deleteAccountSubtitle': 'Hesabınızı kalıcı olarak silme isteği',
    'logout': 'Oturumu kapat',
    'logoutSubtitle': 'Hesabınızdan çıkış yapın',
    'confirmLogout': 'Oturumu Kapatmayı Onaylayın',
    'confirmLogoutMessage': 'Oturumu kapatmak istediğinizden emin misiniz?',
    'cancel': 'İptal etmek',
    'loginAgain': 'Tekrar giriş yapın',
    // ============================================
    // Language Related
    // ============================================
    'language': 'Dil',
    'languageSubtitle': 'Uygulama dilini değiştir',
    'notificationSettings': 'Bildirim Ayarları',
    'notificationSettingsSubtitle':
        'Almak istediğiniz bildirimleri seçin.',
    'notificationChannels': 'Kanallar',
    'pushNotifications': 'Push Bildirimleri',
    'pushNotificationsSubtitle':
        'Cihazınızda push bildirimleri alın',
    'emailNotifications': 'E-posta Bildirimleri',
    'emailNotificationsSubtitle': 'E-posta ile bildirim alın',
    'notificationModules': 'Kategoriye Göre',
    'notificationSettingsSaved': 'Bildirim ayarları kaydedildi',
    'notificationModuleProducts': 'Ürünler',
    'notificationModuleProductOrders': 'Ürün Siparişleri',
    'notificationModuleDeals': 'Fırsatlar',
    'notificationModuleDealOrders': 'Fırsat Siparişleri',
    'notificationModuleBanners': 'Bannerlar',
    'notificationModuleAdmin': 'Yönetici',
    'notificationModuleEngagement': 'Etkileşim',
    'notificationModulePayment': 'Ödeme',
    'push': 'Push',
    'currency': 'Para birimi',
    'currencySubtitle': 'Fiyatlar için para birimini görüntüle (varsayılan: cihaz)',
    'systemDefault': 'Sistem varsayılanı',
    'syncFxRates': 'Döviz kurlarını senkronize et',
    'syncFxRatesSubtitle': 'ECB\'den en son döviz kurlarını alın',
    'syncFxRatesSuccess': 'Döviz kurları başarıyla güncellendi',
    'syncFxRatesFailed': 'Döviz kurları güncellenemedi. Önbelleğe alınmış oranları kullanma.',
    'changingLanguage': 'Dil değiştiriliyor...',
    'languageChangeFailed': 'Dil tercihi senkronize edilemedi. Lütfen tekrar deneyin.',
    'failedToChangeLanguage': 'Dil değiştirilemedi. Lütfen tekrar deneyin.',
    'english': 'İngilizce',
    'german': 'Almanca',
    'turkish': 'Türkçe',
    'arabic': 'Arapça',
    'urdu': 'Urduca',
    'hindi': 'Hintçe',
    'russian': 'Rusça',
    'sourceLanguageLabel': 'İçerik dili',
    'sourceLanguageHint': 'Girdiğiniz metnin dili (diğer dillere çevrilecektir)',
    'selectYourLanguage': 'Dilinizi seçin',
    'selectYourLanguageSubtitle':
        'Uygulama dilini seçin. Daha sonra ayarlardan değiştirebilirsiniz.',
    'continueButton': 'Devam',
    // ============================================
    // Common / General
    // ============================================
    'sessionExpired': 'Oturumun süresi doldu',
    'sessionExpiredMessage': 'Oturumunuzun süresi doldu. Uygulamayı kullanmaya devam etmek için lütfen tekrar giriş yapın.',
    'comingSoon': 'Yakında gelecek',
    'retry': 'Yeniden dene',
    'error': 'Hata',
    'errorWithDetail': 'Hata: {detail}',
    'close': 'Kapalı',
    'save': 'Kaydetmek',
    'done': 'Tamamlamak',
    'saving': 'Kaydediliyor...',
    'update': 'Güncelleme',
    'edit': 'Düzenlemek',
    'delete': 'Silmek',
    'add': 'Eklemek',
    'remove': 'Kaldırmak',
    'select': 'Seçme',
    'all': 'Tüm',
    'filter': 'Filtre',
    'type': 'Tip',
    'status': 'Durum',
    'unknown': 'Bilinmiyor',
    // ============================================
    // About Us Related
    // ============================================
    'welcomeToProductDeal': 'Ürün Anlaşmasına Hoş Geldiniz',
    'trustedMarketplace': 'Toptan ürünler ve fırsatlar için güvenilir pazar yeriniz',
    'ourMission': 'Misyonumuz',
    'ourMissionContent': 'Toptancıları ve perakendecileri birbirine bağlamak, toplu satın almayı her büyüklükteki işletme için erişilebilir ve verimli hale getirmek.',
    'whatWeOffer': 'Ne Sunuyoruz?',
    'whatWeOfferContent':
        '• Doğrulanmış toptancılara erişim'
        '• Özel toplu fırsatlar ve indirimler'
        '• Gerçek zamanlı envanter takibi'
        '• Güvenli sipariş yönetimi'
        '• Konum bazlı ürün keşfi',
    'forWholesalers': 'Toptancılar için',
    'forRetailers': 'Perakendeciler için',
    'forRetailersContent': 'Yakındaki toptancıların ürünlerini keşfedin, toplu fırsatlara katılın ve siparişlerinizi verimli bir şekilde yönetin.',
    'forWholesalersContent': 'Ürünlerinizi sergileyin, özel fırsatlar oluşturun, siparişleri yönetin ve daha geniş bir perakendeci ağına ulaşın.',
    // ============================================
    // FAQ Related
    // ============================================
    'frequentlyAskedQuestions': 'Sıkça Sorulan Sorular',
    'commonQuestions': 'Sık Sorulan Sorular',
    'faqQuestion1': 'Nasıl sipariş verebilirim?',
    'faqAnswer1': 'Aktif fırsatlara veya ürünlere göz atın, ihtiyacınız olan miktarı seçin ve "Sipariş Ver"e tıklayın. Siparişiniz toptancı tarafından incelenecektir.',
    'faqQuestion2': 'Anlaşma emirleri nedir?',
    'faqAnswer2': 'Anlaşma siparişleri, toptancıların hedef miktara ulaşıldığında indirimli fiyatlar sunduğu toplu satın alma fırsatlarıdır. Aynı fırsata birden fazla sipariş verebilirsiniz.',
    'faqQuestion3': 'Nakliye nasıl halledilir?',
    'faqAnswer3': 'Siparişiniz onaylandıktan sonra nakliye ayrıntıları doğrudan toptancıyla görüşülerek ayarlanır. İletişim bilgileri sipariş onayı sonrasında sağlanacaktır.',
    'faqQuestion4': 'Bir siparişi iptal edebilir miyim?',
    'faqAnswer4': 'Bekleyen siparişlerinizi iptal edebilirsiniz. Sipariş toptancı tarafından onaylandıktan sonra toptancının şartlarına göre iptal politikaları geçerli olur.',
    'faqQuestion5': 'Nasıl doğrulanmış bir toptancı olurum?',
    'faqAnswer5': 'Doğrulanmak için destek ekibimizle iletişime geçin. İşletme belgelerini sağlamanız ve doğrulama sürecini tamamlamanız gerekir.',
    'faqQuestion6': 'Ürünler mesafeye göre nasıl sıralanıyor?',
    'faqAnswer6': 'Ürünler bulunduğunuz yere yakınlığa göre otomatik olarak sıralanır. Mesafeye dayalı doğru sıralama için konumunuzu profilinize eklediğinizden emin olun.',
    'faqQuestion7': 'Hangi ödeme yöntemleri kabul ediliyor?',
    'faqAnswer7': 'Ödeme yöntemleri toptancıya göre değişir. Ödeme detayları sipariş onayından sonra konuşulur.',
    'faqQuestion8': 'Profilimi nasıl güncellerim?',
    'faqAnswer8': 'Kontrol panelinden profil sayfanıza gidin, bilgilerinizi güncelleyin ve kaydedin. Farklı konumlar için birden fazla adres ekleyebilirsiniz.',
    // ============================================
    // Wholesaler Directory Related
    // ============================================
    'couldNotLoadWholesalers': 'Şu anda toptancıları yükleyemiyoruz.',
    'verifiedPartners': 'doğrulanmış iş ortakları',
    'verifiedPartnersDescription': 'doğrulanmış iş ortakları',
    'noWholesalersNearYou': 'Henüz yakınınızda toptancı yok. Yakındaki envanterin kilidini açmak için konumunuzu güncelleyin.',
    // ============================================
    // Dashboard Related
    // ============================================
    'dashboard': 'Kontrol Paneli',
    'nearbyWholesalers': 'Yakındaki toptancılar',
    'allWholesalers': 'Tüm Toptancılar',
    'noWholesalersFound': 'Toptancı bulunamadı',
    'errorLoadingWholesalers': 'Toptancılar yüklenirken hata oluştu',
    'advertiseWithUs': 'Bize reklam verin',
    'boostYourSales': 'Satışlarınızı artırın!',
    'promoteYourProducts': 'Ürünlerinizi burada tanıtın ve daha fazla müşteriye ulaşın.',
    'unableToLoadDashboard': 'Kontrol paneli yüklenemiyor',
    'unableToLoadProduct': 'Ürün yüklenemiyor',
    'unableToLoadWholesaler': 'Toptancı yüklenemiyor',
    'spotlight': 'Gündem',
    'spotlightWholesalersEmpty': 'Pazar hareketlendiğinde spotlight toptancıları burada görünecek.',
    // ============================================
    // Orders Related
    // ============================================
    'orderId': 'Sipariş Kimliği',
    'payment': 'Ödeme',
    'paymentStatus': 'Ödeme Durumu',
    'placedOn': 'Yerleştirildi',
    'orderItems': 'Sipariş Öğeleri',
    'createShipment': 'Gönderi Oluştur',
    'shippingAddress': 'Gönderi Adresi',
    'notes': 'Notlar',
    'orderNotes': 'Sipariş Notları',
    'orderDetails': 'Sipariş Detayları',
    'unableToLoadOrder': 'Sipariş yüklenemiyor',
    'updateOrderStatus': 'Sipariş Durumunu Güncelle',
    'subtotal': 'Ara toplam',
    'shipping': 'Nakliye',
    'shippingWithFreeThreshold': 'Nakliye: {amount} ({threshold}+ üniteler için ücretsiz)',
    'freeShippingForThreshold': '{threshold}+ adet için ücretsiz kargo',
    'shippingBaseOnly': 'Nakliye: {amount}',
    'shippingWithPerUnit': 'Nakliye: birim başına {base} + {perUnit}',
    'total': 'Toplam',
    'reasonOptional': 'Sebep (İsteğe bağlı)',
    'notesOptional': 'Notlar (İsteğe bağlı)',
    'sku': 'Stok Kodu',
    'skuN/A': 'Stok Kodu: Yok',
    'trackingAvailable': 'TAKİP MEVCUTTUR',
    'shipped': 'Gönderildi',
    'shipments': 'Gönderiler',
    'shipmentId': 'Gönderi {id}',
    'trackingLabel': 'Takip: {number}',
    'track': 'İzlemek',
    'couldNotOpenTrackingUrl': 'İzleme URL\'si açılamadı',
    'carrierLabel': 'Taşıyıcı: {name}',
    'estDelivery': 'Tahmini teslimat: {date}',
    'shippedAt': 'Gönderim tarihi: {date}',
    'deliveredAt': 'Teslim tarihi: {date}',
    'each': 'her biri',
    'unit': 'Birim',
    'noOrdersYet': 'Henüz sipariş yok',
    'noOrdersYetMessage': 'İlk siparişinizi vermek için ürünlere ve fırsatlara göz atın.',
    'unableToLoadOrders': 'Siparişleriniz yüklenemiyor',
    'orderPlaced': 'Sipariş Verildi',
    'confirmed': 'Onaylandı',
    'delivered': 'Teslim edilmiş',
    'pendingOrders': 'Bekleyen Siparişler',
    'viewOrders': 'Siparişleri Görüntüle',
    'allOrders': 'Tüm Siparişler',
    'pendingConfirmation': 'Onay Bekleniyor',
    'packing': 'Ambalaj',
    'packed': 'Paketlenmiş',
    'dispatched': 'Sevk edilen',
    'outForDelivery': 'Teslimata Çıktı',
    'viewDetails': 'Ayrıntıları Görüntüle',
    'changeOrderStatus': 'Sipariş Durumunu Değiştir',
    'orderStatusUpdatedSuccessfully': 'Sipariş durumu başarıyla güncellendi',
    'orderStatusUpdated': 'Sipariş durumu başarıyla güncellendi',
    'itemStatusUpdatedSuccessfully': 'Öğe durumu başarıyla güncellendi',
    'itemStatusUpdated': 'Öğe durumu başarıyla güncellendi',
    'ordersCountSuffix': 'siparişler',
    'order': 'emir',
    'orderLabel': 'Emir',
    'orders': 'siparişler',
    'ordered': 'sipariş edildi',
    'dealOrder': 'Anlaşma siparişi',
    'productOrder': 'Ürün siparişi',
    'bid': 'Teklif etmek',
    'itemPlusMore': '{item} + {n} daha fazla',
    // ============================================
    // Cart Related
    // ============================================
    'yourCart': 'Sepetiniz',
    'cart': 'Sepet',
    'emptyCart': 'Sepetiniz boş',
    'emptyCartMessage': 'Başlamak için ürünleri sepetinize ekleyin.',
    'addProductsToSeeThemHere': 'Burada görmek için ürünleri ekleyin.',
    'placeOrderCashOnDelivery': 'Sipariş Ver (Kapıda Ödeme)',
    'cashOnDelivery': 'Kapıda Ödeme',
    'paymentMethodCash': 'Kapıda Ödeme',
    'paymentMethodCashDesc': 'Teslim aldığınızda ödeyin.',
    'paymentMethodInvoice': 'Fatura',
    'paymentMethodInvoiceDesc':
        'Size fatura gönderiyoruz; sipariş onayından sonra kargo başlar.',
    'paymentMethodBankTransfer': 'Havale',
    'paymentMethodBankTransferDesc':
        'Önce ödeme, sonra kargo. Ödeme talimatları e-posta ile gönderilir.',
    'paymentMode': 'Ödeme Modu',
    'paymentModeSubtitle':
        'Anlaşmalarınız için varsayılan. Bunu daha sonra profilinizden değiştirebilirsiniz.',
    'paymentModeSubtitleMulti':
        'Kabul ettiğiniz tüm ödeme yöntemlerini seçin. '
        'Bunu daha sonra profilinizden değiştirebilirsiniz.',
    'paymentSettings': 'Ödeme Ayarları',
    'paymentSettingsSubtitle':
        'Fatura/havale siparişleri için banka bilgileri. '
        'Bunları daha sonra profilinizden güncelleyebilirsiniz.',
    'payWithCard': 'Kartla Ödeme',
    'placeOrderPayNow': 'Sipariş Ver ve Ödeme Yap',
    'paymentAfterOrderConfirmed': 'Siparişiniz onaylandıktan sonra ödeme talep edilecektir (örn. banka havalesi).',
    'paymentNotAvailable': 'Kartla ödeme yapılamamaktadır. Kapıda Ödeme seçeneğini deneyin.',
    'paymentCancelled': 'Ödeme iptal edildi.',
    'dealSucceededPayNow': 'Anlaşma başarılı oldu - şimdi öde',
    'totalToPay': 'Ödenecek toplam',
    'payByInvoice': 'Faturayla ödeme',
    'payByCard': 'Kartla ödeme',
    'invoiceInstructionsSent': 'Ödeme talimatları e-postayla gönderildi.',
    'paymentInstructionsBankOnly': 'Ödeme talimatları e-postayla gönderildi. Banka havalesi ile ödeme yapın. Zaten ödeme yaptıysanız anlaşma sahibi makbuzu onaylayacaktır.',
    'markAsPaid': 'Ödendi olarak işaretle',
    'paymentNotesOptional': 'Ödeme notları (ör. banka referansı)',
    'myDealStats': 'Anlaşma istatistiklerim',
    'dealsJoined': 'Anlaşmalar birleştirildi',
    'totalOrderedQuantity': 'Sipariş edilen toplam miktar',
    'totalOrders': 'Toplam siparişler',
    'placeOrder': 'Sipariş Ver',
    'fxDisclaimer': 'Döviz kuru değişebilir. Gösterilen tutar gösterge niteliğindedir.',
    'placingOrder': 'Sipariş Veriliyor...',
    'orderPlacedSuccessfully': 'Sipariş başarıyla verildi!',
    'failedToPlaceOrder': 'Sipariş verilemedi',
    'onlyKioskCanOrder': 'Yalnızca Kiosk/Mağaza hesapları sipariş verebilir.',
    'admins': 'Yöneticiler',
    'subAdmins': 'Alt Yöneticiler',
    'wholesalers': 'Toptancılar',
    'canOnlyViewProducts': 'yalnızca ürünleri görüntüleyebilir. Yalnızca Kiosk/Mağaza hesapları sipariş verebilir.',
    'addToCart': 'Sepete ekle',
    'addedToCart': '✅Sepete eklendi',
    'quantity': 'Miktar',
    'unitPrice': 'Birim Fiyatı',
    'totalAmount': 'Toplam Tutar',
    'buyer': 'Alıcı',
    'items': 'öğeler',
    // ============================================
    // Registration Related
    // ============================================
    'register': 'Kayıt olmak',
    'createAccount': 'Hesap oluşturmak',
    'createAccountTitle': 'Hesap oluşturmak',
    'createAccountSubtitle': 'Seçilmiş toptancıların, büyük anlaşmaların ve lojistik desteğin kilidini açın.',
    'fullName': 'Ad Soyad',
    'email': 'E-posta',
    'workEmail': 'İş e-postası',
    'phone': 'Telefon',
    'password': 'Şifre',
    'confirmPassword': 'Şifreyi Onayla',
    'confirmPasswordLabel': 'Şifreyi onayla',
    'businessName': 'İşletme Adı',
    'country': 'Ülke',
    'city': 'Şehir',
    'address': 'Adres',
    'streetAddress': 'Açık adres',
    'addressWillBeGeocoded': 'Koordinatların alınması için adres otomatik olarak coğrafi kodlanacak',
    'addressSearchHint': 'Adresinizi arayın',
    'placesLookupFailed':
        'Adres ayrıntıları sunucudan yüklenemedi. Adresinizi elle yazabilir veya '
        'düzenleyebilirsiniz.',
    'placesNoAddressResults':
        'Adres bulunamadı. Farklı bir arama deneyin.',
    'placesAddressSearchConfigError':
        'Adres araması kullanılamıyor. Ağınızı kontrol edin ve uygulamanın doğru '
        'API sunucusunu (API_BASE_URL) kullandığından emin olun.',
    'placesAddressSearchRequestFailed':
        'Adres araması başarısız. Bağlantınızı kontrol edin veya daha sonra tekrar '
        'deneyin.',
    'getLocation': 'Konumu Al',
    'selectRole': 'Rol Seçin',
    'accountType': 'Hesap türü',
    'alreadyHaveAccount': 'Zaten bir hesabınız var mı?',
    'login': 'Giriş yapmak',
    'signIn': 'Oturum aç',
    'registrationReceived': 'Kayıt alındı! Hesap onaylandığında sizi bilgilendireceğiz.',
    'fullNameRequired': 'Tam ad gerekli',
    'fullNameMinLength': 'Tam ad en az 3 karakter olmalıdır',
    'emailRequired': 'E-posta gerekli',
    'provideValidEmail': 'Geçerli bir e-posta sağlayın',
    'phoneNumberOptional': 'Telefon numarası (isteğe bağlı)',
    'enterValidPhoneNumber': 'Geçerli bir telefon numarası girin',
    'kioskShopNameOptional': 'Kiosk / Mağaza adı (isteğe bağlı)',
    'companyName': 'Firma Adı',
    'latitudeOptional': 'Enlem (isteğe bağlı)',
    'longitudeOptional': 'Boylam (isteğe bağlı)',
    'locating': 'Bulunuyor...',
    'locatingEllipsis': 'Bulunuyor…',
    'useCurrentLocation': 'Mevcut konumu kullan',
    'enableLocationServices': 'Koordinatları otomatik doldurmak için konum hizmetlerini etkinleştirin.',
    'enableLocationPermissions': 'Koordinatları otomatik doldurmak için konum izinlerini etkinleştirin.',
    'unableToFetchLocation': 'Konum getirilemiyor. Lütfen tekrar deneyin.',
    'unableToFetchLocationShort': 'Konum getirilemiyor.',
    'pleaseEnterValidLatLng': 'Lütfen geçerli enlem ve boylam girin.',
    'createPassword': 'Şifre oluştur',
    'minimum8CharactersRequired': 'Minimum 8 karakter gerekli',
    'weVerifyEveryBusiness': 'Piyasanın güvenilir kalmasını sağlamak için her işletmeyi manuel olarak doğrularız.',
    'submitForReview': 'İnceleme için gönder',
    'alreadyVerifiedSignIn': 'Zaten doğrulandınız mı? Oturum aç',
    'forgotPassword': 'Parolanızı mı unuttunuz?',
    'welcomeBack': 'tekrar hoşgeldiniz',
    'signInToReach': 'Yakınınızdaki onaylı toptancılara ulaşmak için oturum açın.',
    'createKioskOrWholesalerAccount': 'Kiosk veya toptancı hesabı oluşturun',
    'accountSubmittedForApproval': 'Hesap onaya gönderildi. Onaylandıktan sonra kontrol panelinin kilidi açılacaktır.',
    'dashboardWillUnlock': 'Onaylandıktan sonra kontrol panelinin kilidi açılacaktır.',
    'pleaseLoginToPlaceOrder': 'Sipariş vermek için lütfen giriş yapın',
    // ============================================
    // Legal / Compliance (T&C + GDPR)
    // ============================================
    'legalComplianceTitle': 'Yasal ve Uyumluluk',
    'termsAndConditionsFullText': 'Bir hesap oluşturarak platform operatörüyle iş ilişkisine girersiniz ve platformun Hüküm ve Koşullarını (AGB) kabul etmiş olursunuz. Bu Şartlar, pazarı nasıl kullanabileceğinizi, anlaşmaların ve siparişlerin nasıl ele alınacağını ve alıcılar ve toptancılar için hangi yükümlülüklerin geçerli olacağını düzenler. Sağladığınız tüm bilgilerin doğru olduğunu ve platformu yalnızca meşru ticari amaçlarla kullanacağınızı onaylıyorsunuz. Ayrıca, toptancı tarafından onaylandıktan veya bir anlaşma hedefine ulaşıldığında anlaşmaların ve siparişlerin bağlayıcı hale gelebileceğini de kabul edersiniz. Yetki alanınıza bağlı olarak ülkeye özgü ek düzenlemeler geçerli olabilir. Devam etmeden önce lütfen operatör tarafından paylaşılan Şartlar ve Koşulların tamamını inceleyin.',
    'scrollToAcceptTerms': 'Kabul onay kutusunun kilidini açmak için Şartlar ve Koşullar\'ın sonuna gidin.',
    'scrollToBottom': 'Aşağıya doğru kaydır',
    'acceptTermsLabel': 'Şartlar ve Koşulları (AGB) okudum ve kabul ediyorum.',
    'termsScrollHint': 'Lütfen kabul etmeden önce Şartlar ve Koşullar\'ı inceleyin.',
    'acceptPrivacyLabel': 'Veri Gizliliği/GDPR politikasını okudum ve kabul ediyorum.',
    'privacySummaryText': 'Verileriniz, gizlilik politikamız doğrultusunda hesap yönetimi, siparişler, analizler ve güvenlik amacıyla işlenecektir.',
    'mustAcceptAllLegalDocuments': 'Lütfen tüm yasal belgeleri kabul edin ve çerçeve sözleşmesini onaylayın.',
    'mustAcceptTermsAndPrivacy': 'Devam etmek için lütfen Şartlar ve Koşullar ile Veri Gizliliği/GDPR\'yi kabul edin.',
    // ============================================
    // Account Approval / Waiting Screen Related
    // ============================================
    'accountApproval': 'Hesap Onayı',
    'accountApproved': 'Hesap onaylandı!',
    'redirecting': 'Yönlendiriliyor...',
    'pendingReview': 'İnceleme bekleniyor',
    'needMoreInfo': 'Daha fazla bilgiye ihtiyacınız var',
    'wholesalerVerificationMessage': 'Teşekkürler! Toptancı hesabınızı etkinleştirmek için lütfen işletme doğrulama belgelerinizi gönderin. Yöneticimiz hesabınızı inceleyip onaylayacaktır.',
    'buyerVerificationMessage': 'Teşekkürler! Alıcı hesabınızı etkinleştirmek için lütfen kimlik doğrulama belgelerinizi gönderin. Yöneticimiz hesabınızı inceleyip onaylayacaktır.',
    'generalVerificationMessage': 'Teşekkürler! Hesabınızı etkinleştirmek için lütfen doğrulama belgelerini gönderin. Yöneticimiz hesabınızı inceleyip onaylayacaktır.',
    'adminNote': 'Yönetici notu',
    'uploadVerificationDocument': 'Doğrulama Belgesini Yükle',
    'acceptedDocumentTypes': 'Kabul edilen belge türleri',
    'wholesalerDocumentTypes': 'İşletme ruhsatı, Vergi Numarası, Şirket kayıt belgeleri (PNG, JPG, PDF)',
    'buyerDocumentTypes': 'Kimlik kartı, sürücü belgesi veya devlet tarafından verilmiş herhangi bir kimlik (PNG, JPG, PDF)',
    'generalDocumentTypes': 'İşletme ruhsatı, Ehliyet, Kimlik kartı (PNG, JPG, PDF)',
    'selectedDocuments': 'Seçilen Belgeler',
    'addDocuments': 'Belge Ekle',
    'uploading': 'Yükleniyor...',
    'uploaded': 'Yüklendi',
    'selectFirst': 'İlkini Seç',
    'documentsUploadedSuccessfully': 'belge(ler) başarıyla yüklendi. Yöneticimiz hesap durumunuzu inceleyecek ve güncelleyecektir.',
    'documentUploadedSuccessfully': 'Belge başarıyla yüklendi. Yöneticimiz hesap durumunuzu inceleyecek ve güncelleyecektir.',
    'failedToPickDocuments': 'Dokümanlar seçilemedi',
    'passport': 'Pasaport',
    'passportDescription': 'Kimlik doğrulaması için pasaportunuzu yükleyin',
    'passportAlternative': 'Pasaportunuz yoksa devlet onaylı, adresli bir kimlik kartı (ör. Hindistan\'da Aadhar, Ulusal Kimlik vb.) yükleyebilirsiniz.',
    'gewerbeschein': 'Gewerbeschein',
    'idCard': 'Kimlik kartı',
    'taxId': 'Vergi Numarası',
    'companyRegistration': 'Şirket Kaydı',
    'document': 'Belge',
    'gewerbescheinDescription': 'İşletme doğrulaması için Gewerbeschein\'inizi (Ticaret Lisansı) yükleyin',
    'gewerbescheinAlternative': 'Yetkililer tarafından verilen resmi ticaret lisansı belgenizi yükleyin',
    'businessLicense': 'İşletme Lisansı / Gewerbeschein',
    'businessLicenseDescription': 'İşletme doğrulaması için işletme lisansınızı veya Gewerbeschein\'inizi yükleyin',
    'businessLicenseAlternative': 'İşletme lisansınız yoksa şirket tescil belgelerini, vergi kimlik numaranızı veya herhangi bir resmi işletme doğrulama belgesini yükleyebilirsiniz',
    'selectDocument': 'Belge Seç',
    'changeDocument': 'Belgeyi Değiştir',
    'pleaseSelectAtLeastOneDocument': 'Lütfen yüklemek için en az bir belge seçin.',
    'sendByEmail': 'E-postayla Gönder',
    'emailOptionDescription': 'Alternatif olarak, doğrulama belgelerinizi doğrudan e-posta yoluyla gönderebilirsiniz. Yöneticimiz belgeleri doğrulayacak ve hesap durumunuzu buna göre güncelleyecektir.',
    'openEmailToAdmin': 'Yöneticiye E-postayı Aç',
    'emailDraftOpened': 'E-posta taslağı açıldı. Lütfen gönderimi tamamlamak için gönderin. Yöneticimiz belgelerinizi doğrulayacak ve hesap durumunuzu güncelleyecektir.',
    'couldNotOpenEmailApp': 'E-posta uygulaması açılamadı. Lütfen şu adrese bir e-posta gönderin:',
    'manually': 'manuel olarak',
    'failedToOpenEmail': 'E-posta açılamadı',
    'loadingAccountStatus': 'Hesap durumu yükleniyor...',
    'errorLoadingStatus': 'Hata Yükleme Durumu',
    'pleaseReviewAndResubmit': 'Lütfen belgelerinizi inceleyip yeniden gönderin.',
    'useDifferentAccount': 'Farklı hesap kullan',
    'useDifferentAccountConfirm':
        'Farklı bir hesapla giriş yapmak veya kayıt olmak için çıkış yapılsın mı?',
    'failedToUpdateStatus': 'Yasal ayarlar güncellenemedi. Lütfen tekrar deneyin.',
    // ============================================
    // Profile Related
    // ============================================
    'editProfile': 'Profili Düzenle',
    'profileUpdated': 'Profil başarıyla güncellendi',
    'failedToUpdateProfile': 'Profil güncellenemedi',
    'profileImageUpdated': 'Profil resmi güncellendi',
    'failedToUploadImage': 'Resim yüklenemedi',
    'tagline': 'Slogan',
    'locations': 'Konumlar',
    'addLocation': 'Konum Ekle',
    'editLocation': 'Konumu Düzenle',
    'deleteLocation': 'Konumu Sil',
    'latitude': 'Enlem',
    'longitude': 'Boylam',
    'nameIsRequired': 'Ad gerekli',
    'businessNameOptional': 'İşletme adı (isteğe bağlı)',
    'phoneOptional': 'Telefon (isteğe bağlı)',
    'addresses': 'Adresler',
    'addAddress': 'Adres Ekle',
    'noAddressesAdded': 'Adres eklenmedi',
    'addYourFirstAddress': 'Başlamak için ilk adresinizi ekleyin',
    'editAddress': 'Adresi düzenle',
    'removeAddress': 'Adresi kaldır',
    'editAddressTitle': 'Adresi Düzenle',
    'addAddressTitle': 'Adres Ekle',
    'saveChanges': 'Değişiklikleri kaydet',
    'labelExample': 'Etiket (örn. Ev, Ofis, Ana Çıkış)',
    'streetAreaOptional': 'Cadde/Bölge (isteğe bağlı)',
    'countryOptional': 'Ülke (isteğe bağlı)',
    'cityOptional': 'Şehir (isteğe bağlı)',
    'locationNotUpdating': 'Konum güncellenmiyor',
    'locationNotUpdatingSolution': 'Profil > Adresler\'e gidin ve konum koordinatlarınızın doğru olduğundan emin olun',
    // ============================================
    // Deals Related
    // ============================================
    'deals': 'Fırsatlar',
    'activeDeals': 'Aktif Fırsatlar',
    'allDeals': 'Tüm Fırsatlar',
    'myDeals': 'Fırsatlarım',
    'manageDeals': 'Fırsatları Yönet',
    'noDealsFound': 'Hiçbir fırsat bulunamadı',
    'selectDeal': 'Anlaşmayı Seçin',
    'unableToLoadDeals': 'Fırsatlar yüklenemiyor',
    'noDealsAvailable': 'Hiçbir fırsat mevcut değil',
    'noDealsYet': 'Henüz anlaşma yok',
    'checkBackLaterForNewDeals': 'Yeni fırsatlar için daha sonra tekrar kontrol edin',
    'noActiveDeals': 'Aktif fırsat yok',
    'filterDeals': 'Fırsatları Filtrele',
    'progress': 'İlerlemek',
    'dealClosed': 'Anlaşma Kapandı',
    'ends': 'biter',
    'variant': 'Varyant',
    'min': 'Min:',
    'max': 'Maksimum:',
    'perUnit': '/birim',
    'perUnitLabel': '{unit} başına',
    'inStock': 'Stokta var',
    'similarProducts': 'Benzer Ürünler',
    'noActiveDealsForProduct': 'Bu ürün için aktif fırsat yok',
    'activeDealsForProduct': 'Bu ürün için aktif fırsatlar',
    'moreFromWholesaler': '{name}\'dan daha fazlası',
    'dealsFromWholesaler': '{name} fırsatları',
    'productsFromWholesaler': '{name} ürünleri',
    'searchProductsFromWholesaler': '{name} adresindeki ürünleri arayın...',
    'onlyKioskCanPurchase': 'Yalnızca Kiosk/Mağaza hesapları ürün satın alabilir',
    'canOnlyReviewFromDelivered': 'Yalnızca teslim edilen siparişlerdeki ürünleri inceleyebilirsiniz',
    'alreadyReviewedThisProduct': 'Bu ürünü bu siparişten zaten incelediniz',
    'selectOrderToReview': 'İncelenecek Siparişi Seçin',
    'orderN': 'Sipariş #{id}',
    'viewDeals': 'Fırsatları görüntüle',
    'locationInfoNotAvailable': 'Konum bilgisi mevcut değil',
    'location': 'Konum',
    'kfProductDealTagline': 'KF Ürün Fırsatı, En iyi fırsatları bulmanıza yardımcı oluyor',
    'errorSearchingProducts': 'Ürünler aranırken hata oluştu',
    'myDealOrders': 'Anlaşma emirlerim',
    'noDealOrdersYet': 'Henüz anlaşma emri yok',
    'browseDealsPlaceFirstOrder': 'Aktif fırsatlara göz atın ve ilk siparişinizi verin.',
    'statusLabel': 'Durum',
    'noProductsFoundForWholesaler': 'Seçilen toptancıya ait ürün bulunamadı',
    'noApprovedWholesalersAvailable': 'Onaylı toptancı yok',
    'searchByNameBusinessEmail': 'Ada, işletme adına, e-postaya göre arayın...',
    'selectWholesaler': 'Toptancı Seçin',
    'selectProduct': 'Ürün Seçiniz',
    'pageNOfM': '{total} sayfasının {current} sayfası',
    'priceLabel': 'Fiyat',
    'pleaseSelectImageOrVideo': 'Lütfen bir resim veya video seçin',
    'onlyWholesalersCreateStories': 'Yalnızca toptancılar hikaye oluşturabilir',
    'storyCreatedSuccessfully': 'Hikaye başarıyla oluşturuldu! 🎉',
    'uploadingMedia': 'Medya yükleniyor...',
    'creatingStory': 'Hikaye oluşturuluyor...',
    'storyMedia': 'Hikaye Medyası',
    'videoSelected': 'Seçilen video',
    'activeShopsSuffix': 'aktif mağazalar',
    'storiesCountSuffix': 'hikayeler',
    'create': 'Yaratmak',
    'off': 'KAPALI',
    'minOrder': 'Minimum Sipariş',
    'target': 'Hedef',
    'units': 'birimler',
    'dealCreatedSuccessfully': 'Anlaşma başarıyla oluşturuldu',
    'createDeal': 'Fırsat Oluştur',
    'editDeal': 'Fırsatı Düzenle',
    'closeDeal': 'Anlaşmayı Kapat',
    'closeDealConfirmMessage': 'Bu anlaşmayı kapatmak istediğinden emin misin? Bu eylem geri alınamaz.',
    'closeDealGoalReached': 'Hedefe ulaşıldı',
    'closeDealGoalReachedHint': 'İşaretlenirse: tüm bekleyen siparişler otomatik olarak onaylanacaktır (anlaşma başarıyla gerçekleştirildi). İşaretlenmezse: anlaşma kapatılır ancak siparişleri daha sonra manuel olarak onaylayabilirsiniz.',
    'createYourFirstDeal': 'İlk Anlaşmanızı Oluşturun',
    'dealTitle': 'Anlaşma Başlığı',
    'pleaseEnterDealTitle': 'Lütfen anlaşma başlığını girin',
    'dealType': 'Anlaşma Türü',
    'dealPrice': 'Fırsat Fiyatı',
    'startDate': 'Başlangıç ​​Tarihi',
    'endDate': 'Bitiş Tarihi',
    'pleaseEnterDealPrice': 'Lütfen anlaşma fiyatını girin',
    'originalPrice': 'Orijinal Fiyat',
    'targetQuantity': 'Hedef Miktar',
    'pleaseEnterTargetQuantity': 'Lütfen hedef miktarı girin',
    'targetQuantityMin': 'Hedef miktar en az 1 olmalıdır',
    'minOrderQty': 'Min. Sipariş Adeti',
    'pleaseEnterMinOrderQty': 'Lütfen minimum sipariş miktarını girin',
    'minOrderQtyMin': 'Min. sipariş miktarı en az 1 olmalıdır',
    'maxOrderQuantityOptional': 'Maksimum Sipariş Miktarı (Opsiyonel)',
    'endDateMustBeAfterStartDate': 'Bitiş tarihi başlangıç ​​tarihinden sonra olmalıdır',
    'pleaseSelectWholesalerFirst': 'Lütfen önce bir toptancı seçin',
    'auction': 'Açık artırma',
    'priceDrop': 'Fiyat Düşüşü',
    'limitedStock': 'Sınırlı Stok',
    'scheduled': 'planlanmış',
    'live': 'Canlı',
    'highlightedDeal': 'Vurgulanan Anlaşma',
    'canOnlyViewDeals': 'yalnızca fırsatları görüntüleyebilir. Yalnızca Kiosk/Mağaza hesapları sipariş verebilir.',
    'dealProgressNotUpdating': 'Anlaşma ilerleme durumu güncellenmiyor',
    'dealProgressNotUpdatingSolution': 'İlerleme güncellemelerini otomatik olarak dağıtın. Sıkışmış gibi görünüyorsa sayfayı yenileyin',
    'dealProgress': 'Anlaşma İlerlemesi',
    'unableToLoadProgress': 'İlerleme durumu yüklenemiyor: {detail}',
    'noOrdersPlacedYet': 'Bu anlaşmaya henüz sipariş verilmedi.',
    'orderPlacedSuffix': 'sipariş verildi',
    'ordersPlacedSuffix': 'verilen siparişler',
    'closed': 'kapalı',
    // ============================================
    // Products Related
    // ============================================
    'product': 'Ürün',
    'products': 'ürünler',
    'productsSection': 'Ürünler',
    'allProducts': 'Tüm Ürünler',
    'myProducts': 'Ürünlerim',
    'noProductsAvailable': 'Hiçbir ürün mevcut değil',
    'noProductsYet': 'Henüz ürün yok',
    'addYourFirstProduct': 'İlk Ürününüzü Ekleyin',
    'addFirstProduct': 'İlk Ürününüzü Ekleyin',
    'addProduct': 'Ürün Ekle',
    'editProduct': 'Ürünü Düzenle',
    'deleteProduct': 'Ürünü Sil',
    'deletingProduct': 'Ürün siliniyor...',
    'deleteProductConfirmGeneric': 'Bu ürünü silmek istediğinizden emin misiniz? Bu eylem geri alınamaz.',
    'productUpdatedSuccessfully': 'Ürün başarıyla güncellendi',
    'productCreatedSuccessfully': 'Ürün başarıyla oluşturuldu',
    'productDeletedSuccessfully': 'Ürün başarıyla silindi',
    'changeProductStatus': 'Ürün Durumunu Değiştir',
    'changeStatus': 'Durumu Değiştir',
    'updatingStatus': 'Durum güncelleniyor...',
    'statusUpdatedToPending': 'Durum Beklemede olarak güncellendi',
    'statusUpdatedToApproved': 'Durum Onaylandı olarak güncellendi',
    'statusUpdatedToRejected': 'Durum Reddedildi olarak güncellendi',
    'productsWillAppearHere': 'Ürünler eklendiklerinde burada görünecek',
    'noProductsFound': 'Ürün bulunamadı',
    'youveReachedEnd': 'Sona ulaştın',
    'errorLoadingProducts': 'Ürünler yüklenirken hata oluştu',
    'featuredCatalog': 'Öne çıkan katalog',
    'viewAll': 'Tümünü Görüntüle',
    'outOfStock': 'STOKLAR TÜKENDİ',
    'onlyLeft': 'SADECE',
    'left': 'SOL',
    'timeRemainingDay': '{count} gün kaldı',
    'timeRemainingDays': '{count} gün kaldı',
    'timeRemainingHour': '{count} saat kaldı',
    'timeRemainingHours': '{count} saat kaldı',
    'timeRemainingMinute': '{count} dakika kaldı',
    'timeRemainingMinutes': '{count} dakika kaldı',
    'pleaseSelectProduct': 'Lütfen bir ürün seçin',
    'tapToSelectProduct': 'Bir ürün seçmek için dokunun',
    'unknownProduct': 'Bilinmeyen Ürün',
    'searchProductsHint': 'Ürünleri ada, SKU\'ya göre arayın...',
    'loadingMoreProducts': 'Daha fazla ürün yükleniyor...',
    'reachedEnd': 'Sona ulaştın',
    'productsCountSuffix': 'ürünler',
    'price': 'Fiyat',
    'kilogram': 'Kilogram',
    'gram': 'Gram',
    'liter': 'Litre',
    'milliliter': 'Mililitre',
    'piece': 'Parça',
    'box': 'Kutu',
    'pack': 'Ambalaj',
    'kmAway': 'km uzakta',
    'viewAllProducts': 'Tüm Ürünleri Görüntüle',
    // ============================================
    // Product Management Related
    // ============================================
    'productTitle': 'Ürün Başlığı',
    'productTitleRequired': 'Lütfen ürün başlığını girin',
    'titleMinLength': 'Başlık en az 3 karakter olmalıdır',
    'description': 'Tanım',
    'category': 'Kategori',
    'wholesaler': 'Toptancı',
    'selectCategory': 'Kategori Seçin',
    'selectCategories': 'Kategorileri Seçin',
    'pleaseSelectCategory': 'Lütfen bir kategori seçin',
    'tapToSelectCategory': 'Bir kategori seçmek için dokunun',
    'pleaseSelectWholesaler': 'Lütfen bir toptancı seçin',
    'tapToSelectWholesaler': 'Bir toptancı seçmek için dokunun',
    'unknownCategory': 'Bilinmeyen Kategori',
    'yourAccount': 'Hesabınız',
    'currentUser': 'Mevcut Kullanıcı',
    'variants': 'Varyantlar',
    'useVariants': 'Varyantları Kullan',
    'addVariant': 'Varyant Ekle',
    'addAttribute': 'Özellik Ekle',
    'variantSkuRequired': 'SKU gerekli',
    'addAtLeastOneVariant': 'Lütfen en az bir varyant ekleyin',
    'selectVariant': 'Varyant Seç',
    'selectVariantHelper': 'Bu fırsat için bir varyant seçin',
    'noVariantsMessage': 'Bu ürünün çeşidi yoktur. Fırsat doğrudan ürün üzerinde oluşturulacaktır.',
    'unableToLoadVariantsMessage': 'Varyantlar yüklenemiyor. Ürün üzerinde fırsat oluşturulacaktır.',
    'featuredProduct': 'Öne Çıkan Ürün',
    'default': 'Varsayılan',
    'updateProduct': 'Ürünü Güncelle',
    'createProduct': 'Ürün Oluştur',
    'globalAttributes': 'Küresel Nitelikler',
    'globalAttributesDescription': 'Tüm çeşitlere uygulanacak Renk, Boyut gibi nitelikleri tanımlayın.',
    'attributeName': 'Özellik Adı (ör. Renk)',
    'attributeNameHint': 'Renk, Boyut, Malzeme...',
    'imageUrl': 'Resim URL\'si',
    'productImages': 'Ürün Görselleri',
    'firstImagePrimary': 'İlk resim birincildir',
    'addImageUrl': 'URL ekle',
    'pasteImageUrlHint': 'Resim URL\'sini yapıştır',
    'costPrice': 'Maliyet Fiyatı',
    'stock': 'Stoklamak',
    'stockRequired': 'Lütfen stok giriniz',
    'stockNegative': 'Stok negatif olamaz',
    'priceRequired': 'Lütfen fiyatı girin',
    'pricePositive': 'Fiyat 0\'dan büyük olmalıdır',
    'validationError': 'Doğrulama hatası',
    'checkAllFields': 'Lütfen tüm alanları kontrol edin',
    'pending': 'Askıda olması',
    'approved': 'Onaylı',
    'rejected': 'Reddedilmiş',
    'draft': 'Taslak',
    'failedToCreateDeal': 'Anlaşma oluşturulamadı',
    'invalidDateTimeFormat': 'Geçersiz tarih/saat biçimi. Lütfen tarihlerinizi kontrol edin.',
    // ============================================
    // Categories Related
    // ============================================
    'noCategoriesFound': 'Kategori bulunamadı',
    'noCategoriesAvailable': 'Kategori yok',
    'allCategories': 'Tüm Kategoriler',
    'searchCategories': 'Kategorileri ara...',
    'noCategoriesMatchSearch': 'Aramanızla eşleşen kategori yok',
    'categoriesWillAppearHere': 'Kategoriler eklendiklerinde burada görünecek',
    'tryDifferentSearchTerm': 'Farklı bir arama terimi deneyin',
    'errorLoadingCategories': 'Kategoriler yüklenirken hata oluştu',
    'unableToLoadCategory': 'Kategori yüklenemiyor',
    'productsCount': '{n} ürünleri',
    'categoryName': 'Kategori Adı',
    'categoryDescription': 'Tanım',
    'categoryImageUrl': 'Resim URL\'si',
    'createCategory': 'Kategori Oluştur',
    'editCategory': 'Kategoriyi Düzenle',
    'deleteCategory': 'Kategoriyi Sil',
    'deleteCategoryConfirm': '"{name}" öğesini silmek istediğinizden emin misiniz? Bu eylem geri alınamaz.',
    'categoryCreatedSuccessfully': 'Kategori başarıyla oluşturuldu',
    'enterCategoryDescriptionToGenerate': 'İçeriği otomatik olarak oluşturmak için bir kategori açıklaması girin.',
    'categoryDescriptionHint': 'Mesela Organik Sebzeler...',
    'contentGeneratedSuccessfullyEnglish': 'İçerik başarıyla oluşturuldu! (İngilizce)',
    'generationFailedWithError': 'Oluşturma başarısız oldu: {error}',
    'categoryUpdatedSuccessfully': 'Kategori başarıyla güncellendi',
    'categoryDeletedSuccessfully': 'Kategori başarıyla silindi',
    'categoryCreationImportMessage': 'Kategori oluşturma şu anda içe aktarma yoluyla yapılmaktadır. Lütfen yöneticiyle iletişime geçin.',
    'pleaseEnterCategoryName': 'Lütfen bir kategori adı girin',
    // ============================================
    // Reviews Related
    // ============================================
    'reviewed': 'İncelendi',
    'youHaveAlreadyReviewed': 'Bu ürünü bu siparişten zaten incelediniz',
    'reviewUpdatedSuccessfully': 'İnceleme başarıyla güncellendi',
    'reviewSubmittedSuccessfully': 'İnceleme başarıyla gönderildi',
    'pleaseSelectRating': 'Lütfen bir derecelendirme seçin',
    'maximum5ImagesAllowed': 'Maksimum 5 görsele izin veriliyor',
    'failedToPickImage': 'Resim seçilemedi',
    'failedToUploadImages': 'Resimler yüklenemedi',
    'uploadImages': 'Resimleri Yükle',
    'pickImage': 'Resim Seç',
    'pickVideo': 'Video Seç',
    'uploadFailed': 'Yükleme başarısız oldu',
    'upload': 'Yüklemek',
    'invalidImageUrl': 'Geçersiz resim URL\'si',
    // ============================================
    // Banners Related
    // ============================================
    'viewProduct': 'Ürünü Görüntüle',
    'viewDeal': 'Fırsatı Görüntüle',
    'openLink': 'Bağlantıyı Aç',
    'discoverGreatDealsNearby': 'Yakındaki harika fırsatları keşfedin',
    'stayTunedForOffers': 'Doğrulanmış toptancıların yeni teklifleri ve hikayeleri için bizi takip etmeye devam edin.',
    'manageBanners': 'Banner\'ları Yönet',
    'myBanners': 'Banner\'larım',
    'noBannersFound': 'Banner bulunamadı. Bir tane yaratın!',
    'bannerDetails': 'Banner Detayları',
    'bannerNotFound': 'Banner bulunamadı',
    'views': 'Görüntüleme',
    'clicks': 'Tıklama',
    'bannerRequestSubmitted': 'Banner isteği gönderildi!',
    'failedToSubmitRequest': 'İstek gönderilemedi',
    'deleteBanner': 'Banner\'ı Sil',
    'deleteBannerConfirm': 'Bu banner\'ı silmek istediğinizden emin misiniz?',
    'bannerDeleted': 'Banner silindi',
    'failedToDeleteBanner': 'Banner silinemedi',
    'targetId': 'Hedef Kimliği',
    'url': 'URL\'si',
    'createNewBanner': 'Yeni Banner Oluştur',
    'bannerTitle': 'Banner Başlığı',
    'enterBannerTitle': 'Banner başlığını girin',
    'bannerImage': 'Banner Resmi',
    'webBannerImage': 'Web Görseli',
    'webBannerImageHint': 'Web için yatay oran',
    'mobileBannerImage': 'Mobil Görsel',
    'mobileBannerImageHint': 'Mobil için dikey/kare',
    'mobilePreview': 'Mobil Önizleme',
    'preview': 'Önizle',
    'previewMobile': 'Mobil Önizle',
    'previewWillAppearHere': 'Önizleme burada görünecek',
    'pasteImageUrlHere': 'Resim URL\'sini buraya yapıştırın',
    'pleaseEnterImageUrlOrSwitch': 'Lütfen bir Resim URL\'si girin veya Yükleme\'ye geçin ve bir resim seçin.',
    'pleaseTapChooseImage': 'Bir banner görseli yüklemek için lütfen "Resim Seç"e dokunun veya URL\'ye geçin ve bir görsel bağlantısı yapıştırın.',
    'tapToUploadWebImage': 'Web görseli yüklemek için dokunun',
    'tapToUploadMobileImage': 'Mobil görsel yüklemek için dokunun',
    'chooseImage': 'Resim Seç',
    'replaceImage': 'Resmi Değiştir',
    // ============================================
    // Stories Related
    // ============================================
    'createStory': 'Hikaye Oluştur',
    'storiesFromVerifiedWholesalers': 'Doğrulanmış toptancılardan hikayeler',
    'storiesWillAppearHere': 'Hikayeler eklendiklerinde burada görünecek',
    'selectImageOrVideoForStory': 'Hikayeniz için bir resim veya video seçin',
    'post': 'Postalamak',
    'expiresAt': 'Süresi doluyor',
    // ============================================
    // Shipment / Tracking Related
    // ============================================
    'trackingNumber': 'Takip Numarası',
    'carrier': 'Taşıyıcı',
    'trackingUrl': 'İzleme URL\'si',
    'openTrackingLink': 'İzleme bağlantısını aç',
    'statusTimeline': 'Durum Zaman Çizelgesi',
    // ============================================
    // Account Deletion Related
    // ============================================
    'submitDeletionRequest': 'Silme İsteğini Gönder',
    'submitRequest': 'Talebi Gönder',
    'reviewProcess': 'İnceleme Süreci',
    'accountDeleted': 'Hesap Silindi',
    'whatHappensNext': 'Sonra ne olacak?',
    'submitRequestDescription': 'Hesabın silinmesini istemek için e-posta adresinizi girin',
    'reviewProcessDescription': 'Ekibimiz talebinizi 24-48 saat içinde inceleyecektir. İsteğiniz işleme koyulduktan sonra bir onay e-postası alacaksınız.',
    'accountDeletedDescription': 'Hesabınız ve ilişkili tüm veriler kalıcı olarak silinecektir. Bu eylem geri alınamaz.',
    'ourTeamReviewsYourRequest': 'Ekibimiz isteğinizi inceliyor',
    'reviewDetails': 'Ayrıntıları İncele',
    'reviewDetailsDescription': 'Hesabınızı doğruluyor ve silme işlemine geçmeden önce tüm bekleyen siparişlerin veya işlemlerin tamamlandığından emin oluyoruz.',
    'yourAccountIsPermanentlyRemoved': 'Hesabınız kalıcı olarak kaldırıldı',
    'finalStep': 'Son Adım',
    'finalStepDescription': 'Onaylandıktan sonra hesap verileriniz sistemimizden kalıcı olarak silinecektir. Bu eylem geri alınamaz.',
    'importantInformation': 'Önemli Bilgiler',
    'accountDeletionIsPermanent': 'Hesap silme işlemi kalıcıdır ve geri alınamaz',
    'allDataWillBeRemoved': 'Tüm verileriniz, siparişleriniz ve geçmişiniz kalıcı olarak kaldırılacak',
    'pendingOrdersMustBeCompleted': 'Silme işleminin devam edebilmesi için bekleyen siparişlerin tamamlanması gerekir',
    'youllReceiveEmailConfirmation': 'İşlem tamamlandığında bir e-posta onayı alacaksınız',
    'confirmActionPermanent': 'Lütfen bu işlemin kalıcı olduğunu anladığınızı onaylayın',
    'requestSubmitted': 'Talep Gönderildi',
    'deletionRequestSubmittedMessage': 'Hesap silme isteğiniz başarıyla gönderildi. Ekibimiz 24-48 saat içinde inceleyecektir. Talebiniz işleme alındıktan sonra bir onay e-postası alacaksınız.',
    'ok': 'TAMAM',
    'failedToSubmitDeletionRequest': 'Silme isteği gönderilemedi. Lütfen tekrar deneyin.',
    'requestAccountDeletion': 'Hesap Silme İsteği',
    'sorryToSeeYouGo': 'Gittiğinizi gördüğümüz için üzgünüz',
    'emailAddress': 'E-posta Adresi',
    'enterRegisteredEmail': 'Kayıtlı e-posta adresinizi girin',
    'emailAddressRequired': 'E-posta adresi gerekli',
    'pleaseEnterValidEmail': 'Geçerli bir e',
    'reasonForDeletionOptional': 'Silinme Nedeni (İsteğe Bağlı)',
    'helpUsImproveLeaving': 'Neden ayrıldığınızı paylaşarak gelişmemize yardımcı olun...',
    'understandActionPermanent': 'Bu işlemin kalıcı olduğunu ve geri alınamayacağını anlıyorum',
    // ============================================
    // Support / Help Related
    // ============================================
    'emailSupport': 'E-posta Desteği',
    'getHelpViaEmail': 'E-posta yoluyla yardım alın',
    'phoneSupport': 'Telefon Desteği',
    'callUsDuringBusinessHours': 'Mesai saatlerinde bizi arayın',
    'liveChat': 'Canlı Sohbet',
    'chatWithUs': 'Bizimle sohbet edin',
    'chatWithSupportTeam': 'Destek ekibimizle sohbet edin',
    'commonIssues': 'Yaygın Sorunlar',
    'orderNotShowingUp': 'Sipariş görünmüyor',
    'orderNotShowingUpSolution': 'Kontrol panelini yenileyin veya "Siparişlerim" bölümünden sipariş geçmişinizi kontrol edin',
    'liveChatComingSoon': 'Canlı sohbet çok yakında!',
    'needHelpContactSupport': 'Yardıma mı ihtiyacınız var? Destek Ekibiyle İletişime Geçin',
    'contactSupportAt': 'Destek ekibiyle şu adresten iletişime geçin:',
    'getInTouch': 'İletişime Geçin',
    'wereHereToHelp': 'Size yardım etmek için buradayız',
    'businessEmail': 'İş e-postası',
    'contactUsOnWhatsApp': 'Bize WhatsApp\'tan ulaşın',
    'helloNeedAssistance': 'Merhaba! Yardıma ihtiyacım var.',
    'myDetails': 'Detaylarım:',
    'nameLabel': 'İsim:',
    'phoneLabel': 'Telefon:',
    'emailLabel': 'E-posta:',
    'businessLabel': 'İşletme:',
    'howCanYouHelpMe': 'Bana nasıl yardım edebilirsin?',
    'unableToOpenWhatsApp': 'WhatsApp açılamıyor. Lütfen tekrar deneyin.',
    'hello': 'Merhaba',
    // ============================================
    // Common Validation Related
    // ============================================
    'required': 'Bu alan zorunludur',
    'invalidEmail': 'Geçersiz e-posta',
    'passwordTooShort': 'Şifre en az 6 karakter olmalıdır',
    'passwordsDoNotMatch': 'Şifreler eşleşmiyor',
    // ============================================
    // Manager / Admin Related
    // ============================================
    'admin': 'Yönetici',
    'role': 'Rol',
    'created': 'Oluşturuldu',
    'subAdmin': 'Alt Yönetici',
    'accessDenied': 'Erişim engellendi',
    'managersSectionOnly': 'Bu bölüm yalnızca yöneticilere açıktır',
    'totalRevenue': 'Toplam Gelir',
    'myRevenue': 'Gelirim',
    'activeShops': 'Aktif Toptancılar',
    'activeMembers': 'Aktif Mağazalar / Koiskler',
    'inactiveMembers': 'Aktif Olmayan Mağazalar',
    'activeShopsSubtitle': 'Platformdaki doğrulanmış toptancılar',
    'activeMembersSubtitle': 'Yakın zamanda sipariş verilen mağazalar',
    'inactiveMembersSubtitle': '60+ gün içinde sipariş yok',
    'lastOrder': 'Son sipariş',
    'lastActive': 'Son aktif',
    'lastLogin': 'Son giriş',
    'joined': 'Katıldı',
    'selectToNotify': 'Bildirim göndermek için seçin',
    'deselect': 'Seçimi kaldır',
    'recipients': 'Alıcılar',
    'notificationSent': 'Bildirim gönderildi',
    'notifyDealParticipantsTitle': 'İşlem katılımcılarını bilgilendir',
    'notifyDealParticipantsAudienceWarning':
        'Bu mesaj yalnızca bu anlaşma için sipariş veren kullanıcılara gönderilecektir.',
    'notifyDealParticipantsSendUpdateTooltip': 'Güncelleme gönder',
    'notifyDealParticipantsSending': 'Gönderiliyor...',
    'notifyDealParticipantsNoParticipantsError':
        'Gönderilemedi: Bu anlaşmaya henüz kimse katılmadı.',
    'notifyDealParticipantsFailedToSend':
        'Bildirim gönderilemedi: {error}',
    'noInactiveMembers': 'Aktif olmayan üye yok',
    'selectAll': 'Tümünü seç',
    'sendNotification': 'Bildirim gönder',
    'title': 'Başlık',
    'body': 'Mesaj',
    'send': 'Göndermek',
    'generateWithAI': 'Yapay zeka ile oluşturun',
    'generateNotificationPrompt': 'Başlık ve mesaj oluşturmak için bildirimi açıklayın (ör. yeniden etkileşim, hızlı indirim, yeni ürünler).',
    'weMissYou': 'Seni özledik!',
    'reEngagementDefaultBody': 'Bir süredir sipariş vermediniz. En son fırsatlarımıza ve ürünlerimize göz atın.',
    'notificationRemindHint': 'ör. Aktif olmayan mağazalara kış indirimimizi hatırlatın',
    'searchByNameEmail': 'İsme, e-postaya göre arayın...',
    'generate': 'Oluştur',
    'page': 'Sayfa',
    'never': 'Asla',
    'quickActions': 'Hızlı Eylemler',
    'recentOrders': 'Son Siparişler',
    'noRecentOrders': 'Yeni sipariş yok',
    'analyticsComingSoon': 'Analitik - Çok yakında',
    'importCsv': 'CSV\'den içe aktar',
    'importFromCsv': 'CSV\'den içe aktar',
    'importProductsFromCsv': 'Ürünleri CSV\'den İçe Aktar',
    'importProducts': 'İthalat Ürünleri',
    'importing': 'İçe aktarılıyor...',
    'downloadCsvTemplate': 'CSV Şablonunu İndirin',
    'getSampleCsvWithColumns': 'Gerekli tüm sütunları içeren örnek bir CSV dosyası edinin',
    'selectCsvFile': 'CSV Dosyasını Seçin',
    'chooseFile': 'Dosya Seç',
    'tapToSelectWholesalerForImport': 'İthal ürünler için toptancı seçmek için dokunun',
    'importComplete': 'İçe Aktarma Tamamlandı',
    'inserted': 'Eklendi',
    'updated': 'Güncellendi',
    'skipped': 'Atlandı',
    'fileLabel': 'Dosya: {name}',
    'wholesalerRequired': 'Toptancı *',
    'wholesalerLabel': 'Toptancı {id}',
    'csvPreviewRows': 'CSV Önizlemesi ({n} satırlar)',
    'multipleRowsSameProductVariant': 'Aynı ürün adına sahip birden çok satır = birden çok çeşit',
    'errorsCount': 'Hatalar ({n})',
    'andMoreErrors': '... ve {n} daha fazla hata',
    'failedToReadFileBytes': 'Dosya baytları okunamadı',
    'failedToGetFilePath': 'Dosya yolu alınamadı',
    'errorPickingFile': 'Dosya seçilirken hata oluştu: {error}',
    'csvFileEmpty': 'CSV dosyası boş',
    'errorParsingCsv': 'CSV ayrıştırılırken hata oluştu: {error}',
    'templateSavedSuccessfully': 'Şablon başarıyla kaydedildi',
    'templateDownloadCancelled': 'Şablon indirme işlemi iptal edildi',
    'errorGeneratingTemplate': 'Şablon oluşturulurken hata oluştu',
    'errors': 'Hatalar',
    'viewWholesaler': 'Toptancıyı görüntüle',
    'cropImage': 'Resmi Kırp',
    'change': 'Değiştirmek',
    'navigationError': 'Navigasyon hatası',
    // ============================================
    // Time Related
    // ============================================
    'hours': 'saat',
    'minutes': 'dakika',
    'seconds': 'Saniye',
    'twentyFourHours': '24 saat',
    'twelveHours': '12 saat',
    'sixHours': '6 saat',
    // ============================================
    // Navigation / Route Errors
    // ============================================
    'noStoryDataProvided': 'Hikaye verisi sağlanmadı.',
    'missingWholesalerId': 'Toptancı kimliği eksik.',
    'missingProductId': 'Ürün kimliği eksik.',
    'missingCategorySlug': 'Kategori bilgisi eksik.',
    'missingDealId': 'Anlaşma kimliği eksik.',
    'missingOrderId': 'Sipariş kimliği eksik.',
    'featuredProducts': 'Öne Çıkan Ürünler',
    // ============================================
    // Order Update / Quantity Change Result
    // ============================================
    'orderUpdate': 'Sipariş Güncelleme',
    'viewMyOrders': 'Siparişlerimi Görüntüle',
    'goToHome': 'Ana Sayfaya Git',
    'quantityChangeAccepted': 'Miktar değişikliği kabul edildi',
    'quantityChangeDeclined': 'Miktar değişikliği reddedildi',
    'somethingWentWrong': 'Bir şeyler ters gitti',
    'orderUpdatedMessage': 'Siparişiniz güncellendi.',
    'orderRevertedMessage': 'Siparişiniz önceki miktara döndürülmüştür.',
    'pleaseTryAgainLater': 'Lütfen daha sonra tekrar deneyin.',
    // ============================================
    // Deal Detail / Deal Errors
    // ============================================
    'unableToLoadDeal': 'Anlaşma yüklenemiyor',
    'regularPrice': 'Normal Fiyat',
    'stockLabel': 'Stoklamak',
    'dealNotStarted': 'Bu anlaşma henüz başlamadı',
    'adminWholesalerManageHint': 'Yönetici veya Toptancı olarak bu fırsatı yönetebilirsiniz ancak sipariş veremezsiniz. Bu fırsatı düzenlemek veya kapatmak için uygulama çubuğundaki menü düğmesini (⋮) kullanın.',
    'adminDealOnlyOwnerCanBid': 'Yalnızca yönetici (anlaşma sahibi) yönetici anlaşmalarına teklif ekleyebilir. Kiosk kullanıcıları bu fırsattan sipariş veremezler.',
    'kioskOnlyPlaceOrders': 'Bu fırsattan yalnızca Kiosk/Mağaza hesapları sipariş verebilir.',
    'managementView': 'Yönetim Görünümü',
    'ordering': 'Sipariş verme',
    'failedToLoadDealData': 'Anlaşma verileri yüklenemedi',
    'dealClosedSuccess': 'Anlaşma başarıyla kapatıldı',
    'failedToCloseDeal': 'Anlaşma kapatılamadı',
    'onlyAdminCanAddBidsOnAdminDeals': 'Yalnızca yönetici (anlaşma sahibi) yönetici anlaşmalarına teklif ekleyebilir.',
    // ============================================
    // Product Search / Detail
    // ============================================
    'searchProducts': 'Ürün Ara',
    'youCanOnlyReviewFromDeliveredOrders': 'Yalnızca teslim edilen siparişlerdeki ürünleri inceleyebilirsiniz',
    'allImages': 'Tüm görseller',
    'contentGeneratedSuccessfully': 'İçerik başarıyla oluşturuldu! Kategoriyi ve diğer alanları kontrol edin.',
    'generationFailed': 'Oluşturma başarısız oldu',
    'userIdRequired': 'Kullanıcı kimliği gerekli',
    // ============================================
    // Admin Banner Management
    // ============================================
    'adminBannerManagement': 'Yönetici Banner Yönetimi',
    'requests': 'İstekler',
    'active': 'Aktif',
    'noBannersFoundShort': 'Banner bulunamadı.',
    'failedToUpdateBanner': 'Banner güncellenemedi',
    'bannerSubmittedSuccessfully': 'Banner başarıyla gönderildi',
    'failedToCreateBanner': 'Banner oluşturulamadı',
    'failedToSubmitBannerRequest': 'Banner isteği gönderilemedi',
    // ============================================
    // User Management / Admin
    // ============================================
    'administratorsOnlySection': 'Bu bölüm yalnızca yöneticilere açıktır',
    'allRoles': 'Tüm Roller',
    'allStatuses': 'Tüm Durumlar',
    'suspended': 'Askıya alınmış',
    'noUsersFound': 'Kullanıcı bulunamadı',
    'pageOf': 'Sayfa',
    'ofLabel': 'ile ilgili',
    'noDocumentsAvailable': 'Belge yok',
    'userUpdatedSuccessfully': 'Kullanıcı başarıyla güncellendi',
    'userCreatedSuccessfully': 'Kullanıcı başarıyla oluşturuldu',
    'userDeletedSuccessfully': 'Kullanıcı başarıyla silindi',
    'deleteUser': 'Kullanıcıyı Sil',
    'deleteUserConfirm': '{name} öğesini silmek istediğinizden emin misiniz? Bu eylem geri alınamaz.',
    'verificationDocuments': 'Doğrulama Belgeleri',
    'noVerificationDocumentsYet': 'Henüz doğrulama belgesi yüklenmedi.',
    'rejectionReason': 'Reddedilme Nedeni:',
    'createUser': 'Kullanıcı Oluştur',
    'editUser': 'Kullanıcıyı Düzenle',
    'updateUser': 'Kullanıcıyı Güncelle',
    'roleRequired': 'Rol gerekli',
    'statusRequired': 'Durum gerekli',
    'newPasswordLeaveEmpty': 'Yeni Şifre (güncel kalması için boş bırakın)',
    'passwordRequired': 'Şifre gerekli',
    'passwordMinLength': 'Şifre en az 6 karakter olmalıdır',
    'needInfo': 'Bilgi Gerekiyor',
    'business': 'İşletme',
    'searchByNameEmailPhone': 'Ada, e-postaya, telefona göre arayın...',
    'daysAgo': 'gün önce',
    'activeDaysLast14': 'Aktif günler (son 14)',
    'docsCount': '{count} doküman(lar)',
    'noPassportDocuments': 'Pasaport belgesi yok',
    'noGewerbescheinDocuments': 'Gewerbeschein belgesi yok',
    'noBusinessLicenseDocuments': 'İşletme ruhsatı belgesi yok',
    'documentN': 'Belge {n}',
    'openInBrowser': 'Tarayıcıda Aç',
    'pdfDocument': 'PDF Belgesi',
    'kiosk': 'Köşk',
    // ============================================
    // Order Management (Deal Orders)
    // ============================================
    'errorLoadingOrders': 'Siparişler yüklenirken hata oluştu',
    'errorLoadingDeals': 'Anlaşmalar yüklenirken hata oluştu',
    'orderManagement': 'Sipariş Yönetimi',
    'orderCountSuffix': 'emir',
    'confirmOrder': 'Siparişi Onayla',
    'confirmOrderMessage': 'Bu siparişi onaylamak istediğinizden emin misiniz?',
    'confirm': 'Onaylamak',
    'markAsDelivered': 'Teslim Edildi Olarak İşaretle',
    'markDelivered': 'Teslim Edildi Olarak İşaretle',
    'cancelOrder': 'Siparişi İptal Et',
    'cancelOrderConfirm': 'Bu siparişi iptal etmek istediğinizden emin misiniz?',
    'no': 'HAYIR',
    'reduceQuantity': 'Miktarı azalt',
    'orderConfirmedSuccess': 'Sipariş başarıyla onaylandı',
    'orderMarkedDelivered': 'Sipariş teslim edildi olarak işaretlendi',
    'failedToConfirmOrder': 'Sipariş onaylanamadı',
    'failedToMarkDelivered': 'Teslim edildi olarak işaretlenemedi',
    'orderCancelled': 'Sipariş iptal edildi',
    'failedToCancelOrder': 'Sipariş iptal edilemedi',
    'orderMarkedPaid': 'Ödendi olarak işaretlenen sipariş',
    'failedToMarkOrderPaid': 'Sipariş ödendi olarak işaretlenemedi',
    'quantityUpdatedSuccess': 'Miktar başarıyla güncellendi',
    'failedToUpdateQuantity': 'Miktar güncellenemedi',
    'deliveryNotesOptional': 'Teslimat Notları (Opsiyonel)',
    'newQuantity': 'Yeni miktar',
    'reduceQuantityHint': 'Yeni miktarı girin. Minimum 1\'dir (veya anlaşmanın minimum sipariş miktarı). Bu siparişi iptal etmek için 0\'ı kullanın.',
    'quantityUpdatedTo': 'Miktar şu şekilde güncellendi:',
    // ============================================
    // Deal Order Form
    // ============================================
    'enterQuantity': 'Miktarı girin',
    'pleaseEnterQuantity': 'Lütfen miktarı girin',
    'invalidQuantity': 'Geçersiz miktar',
    'minimumOrderIs': 'Minimum sipariş:',
    'maximumOrderIs': 'Maksimum sipariş:',
    'addSpecialInstructions': 'Özel talimatlar ekleyin...',
    'minQuantityLabel': 'Min.',
    'selectedLabel': 'Seçildi',
    'maxQuantityLabel': 'Maksimum',
    // ============================================
    // Shipment / Carrier
    // ============================================
    'pleaseSelectCarrier': 'Lütfen bir operatör seçin',
    'pleaseEnterCarrierNameForOther': 'Lütfen "Diğer" için operatör adını girin',
    'shipmentCreatedSuccess': 'Gönderi başarıyla oluşturuldu',
    'shipmentCreatedAndOrderShipped': 'Gönderi oluşturuldu ve sipariş gönderildi olarak işaretlendi',
    'failedToCreateShipment': 'Gönderim oluşturulamadı',
    // ============================================
    // Stories
    // ============================================
    'failedToPickMedia': 'Medya seçilemedi',
    'onlyWholesalersCanCreateStories': 'Yalnızca toptancılar hikaye oluşturabilir',
    'storyCreatedSuccess': 'Hikaye başarıyla oluşturuldu! 🎉',
    'failedToCreateStory': 'Hikaye oluşturulamadı',
    // ============================================
    // Payment
    // ============================================
    'paymentCompletedSuccess': 'Ödeme başarıyla tamamlandı!',
    'paymentFailed': 'Ödeme başarısız oldu',
    // ============================================
    // Notifications
    // ============================================
    'notifications': 'Bildirimler',
    'markAllAsRead': 'Tümünü okundu olarak işaretle',
    'deleteAll': 'Tümünü sil',
    'filterNotifications': 'Bildirimleri Filtrele',
    'unread': 'Okunmamış',
    'read': 'Okumak',
    'deleteAllNotificationsConfirm': 'Tüm Bildirimler Silinsin mi?',
    'deleteAllNotificationsMessage': 'Tüm bildirimleri silmek istediğinizden emin misiniz? Bu eylem geri alınamaz.',
    // ============================================
    // Deal / Product Modals
    // ============================================
    'paymentEmailTemplateGenerated': 'Ödeme e-posta şablonu oluşturuldu',
    'aiGenerationFailed': 'Yapay zeka üretimi başarısız oldu',
    'dealUpdatedSuccess': 'Anlaşma başarıyla güncellendi',
    'allowOnlinePayment': 'Çevrimiçi ödemeye izin ver',
    'allowOnlinePaymentSubtitle': 'İşaretlenmezse müşteriler yalnızca sipariş verebilir; Sipariş onaylandıktan sonra ödeme (örn. banka havalesi) talep edilir.',
    'paymentAndEmail': 'Ödeme ve e-posta',
    'generating': 'Oluşturuluyor…',
    'enterDealDescriptionPrompt': 'İçeriği otomatik olarak oluşturmak için anlaşmanızın net bir açıklamasını girin.',
    'dealDescriptionHint': 'örneğin, Flaş indirim: tüm kışlık ceketlerde %50 indirim',
    'enterProductDescriptionPrompt': 'İçeriği otomatik olarak oluşturmak için bir açıklama veya ürün ayrıntıları girin.',
    'productDescriptionHint': 'Örneğin, ergonomik tasarıma sahip birinci sınıf deri ofis koltuğu...',
    'optionalAutoAssigned': 'İsteğe bağlı - boşsa otomatik olarak atanacaktır',
    'defaultYourAccount': 'Varsayılan: Hesabınız (değiştirmek için dokunun)',
    'currentUserYou': 'Mevcut Kullanıcı (Siz)',
    'loadingProductDetails': 'Ürün ayrıntıları yükleniyor...',
    'loading': 'Yükleniyor...',
    'ibanBankAccount': 'IBAN / Banka hesabı',
    'accountOwner': 'Hesap sahibi',
    'referenceTemplate': 'Referans şablonu (ör. DEAL-{dealCode}-{buyerId})',
    'paymentInstructions': 'Ödeme talimatları (serbest metin)',
    'paymentEmailSubject': 'Ödeme e-postası konusu',
    'paymentEmailBody': 'Ödeme e-postası gövdesi ({dealTitle}, {amount}, {iban}, {reference}, {accountOwner} kullanın)',
    'ended': 'Sona erdi',
    'dealEnded': 'Anlaşma Sona Erdi',
    'dealHasEnded': 'Anlaşma sona erdi',
    'endingSoon': 'Yakında Sona Eriyor!',
    'endsIn1Day': '1 günde bitiyor',
    'endsInDays': '{n} gün içinde bitiyor',
    'endsIn1Hour': '1 saat içinde bitiyor',
    'endsInHours': '{n} saat içinde bitiyor',
    'endsSoon': 'Yakında bitiyor',
    'categories': 'Kategoriler',
    'itemsCount': '{n} Öğeler',
    // ============================================
    // Shipment Tracking
    // ============================================
    'pleaseEnterTrackingNumber': 'Lütfen bir takip numarası girin',
    'pleaseSelectAtLeastOneItemToShip': 'Lütfen gönderilecek en az bir ürün seçin',
    'pleaseEnterTrackingUrlForOther': 'Lütfen "Diğer" operatör için izleme URL\'sini girin',
    'selectItemsToShip': 'Gönderilecek Ürünleri Seçin',
    'noItemsAvailableForShipment': 'Gönderim için uygun ürün yok',
    'selectCarrier': 'Bir operatör seçin',
    'selectCarrierHint': 'Bir operatör seçin...',
    'carrierName': 'Taşıyıcı Adı',
    'enterCarrierName': 'Operatör adını girin',
    'trackingNumberRequired': 'Takip numarası gerekli',
    'enterTrackingNumber': 'Takip numarasını girin',
    'trackingUrlAutoGenerated': 'İzleme URL\'si otomatik olarak oluşturulacak',
    'trackingUrlRequiredForOther': '"Diğer" operatör için takip URL\'si gerekli',
    'pleaseEnterValidUrl': 'Lütfen geçerli bir URL girin',
    'estimatedDeliveryDate': 'Tahmini Teslimat Tarihi',
    'selectDate': 'Tarih seçin',
    'internalNotesShipment': 'Bu gönderiyle ilgili dahili notlar',
    'trackingUrlHintAuto': 'Operatör ve takip numarası sağlandığında otomatik olarak oluşturulur',
    'trackShipment': 'Gönderiyi Takip Et',
    'trackShipmentHint': 'Sağlanan takip numarasını kullanarak gönderinizi takip edin',
    'trackingDetails': 'Takip Detayları',
    'shipmentNotFound': 'Gönderim bulunamadı',
    'pleaseCheckTrackingNumber': 'Lütfen takip numaranızı kontrol edip tekrar deneyin',
    'noNotifications': 'Bildirim yok',
    'youreAllCaughtUp': 'Tümünüz yapıldı!',
    // ============================================
    // Select Deal / Category
    // ============================================

    // Feature audit – previously hardcoded strings
    'platformMobile': 'Mobil',
    'platformWeb': 'Web',
    'pleaseWait': 'Lütfen bekleyin...',
    'defaultVariant': 'Varsayılan',
    'trackOnCarrierWebsite': 'Kargo sitesinde takip et',
    'minOrderQtyRequired': 'Min. sipariş miktarı *',
    'dealPriceRequired': 'Fırsat fiyatı *',
    'targetQuantityRequired': 'Hedef miktar *',
    'baseShippingCostEur': 'Temel kargo maliyeti (€)',
    'freeShippingThresholdQuantity': 'Ücretsiz kargo eşiği (miktar)',
    'perUnitShippingCostEur': 'Birim başına kargo maliyeti (€)',
    'descriptionOptional': 'Açıklama (isteğe bağlı)',
    'enterBannerDescription': 'Banner açıklaması girin',
    'bannerType': 'Banner türü',
    'targetUrl': 'Hedef URL',
    'skuRequired': 'SKU *',
    'productToPromoteHint': 'tanıtılacak ürün',
    'selectDealToPromote': 'Tanıtılacak fırsat seçin',
    'titleOptional': 'Başlık (isteğe bağlı)',
    'giveReviewTitle': 'Yorumunuza bir başlık verin',
    'yourReviewOptional': 'Yorumunuz (isteğe bağlı)',
    'shareExperienceWithProduct': 'Bu ürünle deneyiminizi paylaşın',
    'dealUpdatedSuccessfully': 'Fırsat başarıyla güncellendi',
    'dealPriceMustBeValidNumber': 'Fırsat fiyatı geçerli bir sayı olmalı',
    'pleaseEnterMinOrderQuantity': 'Lütfen min. sipariş miktarını girin',
    'paymentEmailPlaceholdersSubject':
        'Yer tutucular: {dealTitle}, {amount}, {reference}',
    'paymentEmailPlaceholdersBody':
        'Yer tutucular: {dealTitle}, {amount}, {accountOwner}, {iban}, '
        '{reference}, {additionalInstructions}',
    'failed': 'Başarısız',

    // ============================================
    // Order status (product orders – display only)
    // ============================================
    'orderStatusPendingConfirmation': 'Onay bekliyor',
    'orderStatusConfirmed': 'Onaylandı',
    'orderStatusPacking': 'Paketleniyor',
    'orderStatusDispatched': 'Gönderildi',
    'orderStatusOutForDelivery': 'Dağıtımda',
    'orderStatusDelivered': 'Teslim edildi',
    'orderStatusCancelled': 'İptal',
    'orderStatusReturned': 'İade edildi',
    'orderStatusRefunded': 'Para iadesi',

    // ============================================
    // Notifications (backend localization keys)
    // ============================================
    'notificationProductApprovalNeededTitle': 'Onay Bekleyen Yeni Ürün',
    'notificationProductApprovalNeededBody': '{0} yeni bir ürün oluşturdu: {1}',
    'notificationProductStatusUpdatedTitle': 'Ürün Durumu Güncellendi',
    'notificationProductApprovedBody': '"{0}" ürününüz onaylandı!',
    'notificationProductRejectedBody': '"{0}" ürününüz reddedildi.',
    'notificationProductPendingBody': '"{0}" ürününüz onay bekliyor.',
    'notificationProductStatusChangedBody': '"{0}" ürününüzün durumu {1} olarak değişti',
    'notificationNewProductOrderTitle': 'Ürünleriniz için Yeni Sipariş',
    'notificationNewProductOrderBody': '{0}, {2} için {1} adet sipariş verdi',
    'notificationNewDealOrderTitle': 'Fırsatınız için Yeni Sipariş',
    'notificationNewDealOrderBody': '{0}, {1} adet sipariş verdi',
    'notificationPaymentReportedTitle': 'Alıcı ödeme bildirdi',
    'notificationPaymentReportedBody': '{0}, sipariş için ödeme bildirdi. Detaylar: {1}',
    'notificationDealPaymentReportedBody': '{0}, fırsat siparişi için ödeme bildirdi. Detaylar: {1}',
    'notificationDealOrderStatusUpdatedTitle': 'Fırsat Siparişi Durumu Güncellendi',
    'notificationDealOrderConfirmedBody': '"{0}" için siparişiniz onaylandı!',
    'notificationDealOrderShippedBody': '"{0}" için siparişiniz kargoya verildi!',
    'notificationDealOrderDeliveredBody': '"{0}" için siparişiniz teslim edildi!',
    'notificationDealOrderCancelledBody': '"{0}" için siparişiniz iptal edildi.',
    'notificationDealOrderRefundedBody': '"{0}" için siparişiniz iade edildi.',
    'notificationDealOrderPendingBody': '"{0}" için siparişiniz onay bekliyor.',
    'notificationDealOrderStatusChangedBody': '"{0}" için sipariş durumunuz {1} olarak değişti',
    'notificationOrderQuantityUpdatedTitle': 'Sipariş Miktarı Güncellendi',
    'notificationDealOrderQuantityCancelledBody': '"{0}" için siparişiniz (önce {1} adet) satıcı tarafından iptal edildi.',
    'notificationDealOrderQuantityChangedBody': '"{0}" için siparişiniz güncellendi: miktar {1} adetten {2} adede değiştirildi (satıcı tarafından).',
    'notificationQuantityChangeDeclinedTitle': 'Miktar değişikliği reddedildi',
    'notificationQuantityChangeDeclinedBody': '{0} miktar değişikliğini reddetti. Sipariş {1} adetten {2} adede geri alındı.',
    'notificationDealNowLiveTitle': 'Yeni fırsat yayında',
    'notificationDealNowLiveBody': '"{0}" artık yayında. Fırsat bitmeden sipariş verin.',
    'notificationDealTarget70PercentTitle': 'Fırsat hedefe yaklaştı',
    'notificationDealTarget70PercentBody': '"{0}" %{1} dolu! Diğer perakendecilere katılın ve fırsat sahibinin hedefine ulaşmasına yardımcı olun — bu ortaklığınızı güçlendirir ve bağlılığınızı gösterir.',
    'notificationDealEnding24hTitle': 'Fırsat yakında bitiyor',
    'notificationDealEnding24hBody': 'Son 24 saat! "{0}" — bu fırsatı kapatmak için sadece {1} sipariş kaldı.',
    'notificationDealEnding7dTitle': 'Fırsat 7 gün içinde bitiyor',
    'notificationDealEnding7dBody': '"{0}" — bu fırsatı kapatmak için sadece {1} sipariş kaldı.',
    'notificationDealSuccessTitle': 'Fırsat başarıyla tamamlandı',
    'notificationDealSuccessBody': 'Grup fırsatınız "{0}" gerekli miktara ulaştı ve artık onaylandı. Lütfen toptancının talimatlarına göre ödeme ve kargoya hazırlanın.',
    'notificationDealClosedTitle': 'Fırsat kapatıldı',
    'notificationDealClosedBody': '"{0}" fırsatı kapatıldı. Artık aktif fırsatlarda görünmeyecek.',
    'deal_closed_title': 'Fırsat kapatıldı!',
    'deal_closed_body':
        '"{0}" fırsatı resmen kapatıldı. Katılımınız için teşekkürler!',
    'notificationOrderStatusUpdatedTitle': 'Sipariş Durumu Güncellendi',
    'notificationOrderConfirmedBody': '"{0}" için siparişiniz onaylandı!',
    'notificationOrderDispatchedBody': '"{0}" için siparişiniz gönderildi!',
    'notificationOrderDeliveredBody': '"{0}" için siparişiniz teslim edildi!',
    'notificationOrderCancelledBody': '"{0}" için siparişiniz iptal edildi.',
    'notificationOrderPackingBody': '"{0}" için siparişiniz hazırlanıyor!',
    'notificationOrderOutForDeliveryBody': '"{0}" için siparişiniz dağıtımda!',
    'notificationOrderReturnedBody': '"{0}" için siparişiniz iade edildi.',
    'notificationOrderRefundedBody': '"{0}" için siparişinizin ücreti iade edildi.',
    'notificationOrderStatusChangedBody': '"{0}" için sipariş durumunuz {1} olarak değişti',
    'notificationOrderItemRemovedBody': '"{0}" sipariş kaleminiz (önce {1} adet) satıcı tarafından kaldırıldı.',
    'notificationOrderItemQuantityChangedBody': '"{0}" sipariş kaleminiz güncellendi: miktar {1} adetten {2} adede değiştirildi (satıcı tarafından).',
    'notificationProductQuantityChangeDeclinedBody': '{0} sipariş kalemi miktar değişikliğini reddetti. {1} adetten {2} adede geri alındı.',
    'notificationDailyEngagementTitle': 'Bugünün fırsatlarına göz atın!',
    'notificationDailyEngagementBody': 'Bugün: {0} banner, {1} fırsat, {2} öne çıkan ürün. Teklifler için uygulamayı kontrol edin.',
    'notificationInactiveMembersAlertTitle': 'Pasif üyeler uyarısı',
    'notificationInactiveMembersAlertBody': '{0} mağaza {1} gündür sipariş vermedi. İletişime geçmeyi veya incelemeyi düşünün.',
    'notificationBulkImportCompletedTitle': 'Toplu İçe Aktarım Tamamlandı',
    'notificationBulkImportCompletedBody': '{0} ürün başarıyla içe aktarıldı. {1} atlandı.',
    'notificationBannerApprovalNeededTitle': 'Onay Bekleyen Yeni Banner',
    'notificationBannerApprovalNeededBody': '{0} banner için onay istedi: {1}',
    'notificationNewUserRegistrationTitle': 'Yeni Kullanıcı Kaydı',
    'notificationNewUserRegistrationBody': '{0} ({1}) {2} olarak kayıt oldu. Onay bekliyor.',
    'notificationBannerStatusChangedTitle': 'Banner durumu değişti',
    'notificationBannerApprovedBody': '"{0}" bannerınız onaylandı ve artık aktif!',
    'notificationBannerRejectedBody': '"{0}" bannerınız reddedildi. Lütfen gözden geçirip gerekirse yeniden gönderin.',
    'notificationBannerDeactivatedBody': '"{0}" bannerınız devre dışı bırakıldı.',
    'notificationBannerStatusChangedBody': '"{0}" bannerınızın durumu {1} olarak değişti',
    'notificationAdminCustomTitle': '{0}',
    'notificationAdminCustomBody': '{0}',
    'kioskShopRole': 'Büfe / Dükkan',
    'legalDocumentsTitle': 'Yasal Belgeler',
    'readAndAcceptAgbPrefix': 'Şu belgeyi okudum ve kabul ediyorum: ',
    'agbLinkText': 'Genel Hükümler ve Koşullar (GHK)',
    'readAndAcceptAgbSuffix': '.',
    'acceptCompliancePrefix': 'Şu belgeyi kabul ediyorum: ',
    'complianceLinkText': 'Uyumluluk Yönergeleri (Ticari Marka ve Ürün Bütünlüğü)',
    'acceptComplianceSuffix': '.',
    'agreePrivacyPrefix': 'Şu belgeyi kabul ediyorum: ',
    'privacyLinkText': 'Gizlilik Politikası',
    'agreePrivacySuffix': ' ve veri aktarımını.',
    'confirmFrameworkPrefix': 'Şu belgeyi okuduğumu onaylıyorum: ',
    'frameworkLinkText': 'Uygulama Kullanımı Çerçeve Sözleşmesi',
    'confirmFrameworkSuffix': '.',
  };
}