class UkrainianFile {
  static const Map<String, String> ukrainianTranslations = {
    // ============================================
    // Options Screen Related
    // ============================================
    'options': 'Опції',
    'account': 'Обліковий запис',
    'myOrders': 'Мої замовлення',
    'myOrdersSubtitle': 'Переглядайте та відстежуйте свої замовлення',
    'statistics': 'Статистика',
    'statisticsSubtitle': 'Перегляньте статистику участі в угоді',
    'profile': 'Профіль',
    'profileSubtitle': 'Керуйте своїм обліковим записом',
    'management': 'управління',
    'manageCategories': 'Керування категоріями',
    'manageCategoriesSubtitle': 'Створюйте категорії продуктів і керуйте ними',
    'createNewProductSubtitle': 'Створіть новий продукт',
    'createNewDealSubtitle': 'Створіть нову угоду',
    'viewOrdersSubtitle': 'Перегляд замовлень і керування ними',
    'inactiveMembersViewSubtitle': 'Перегляньте магазини, у яких немає останніх замовлень',
    'manageBannersSubtitle': 'Керування банерами програми (адміністратор)',
    'myBannersSubtitle': 'Керуйте своїми банерами',
    'unableToLoadOptions': 'Не вдалося завантажити параметри',
    'loggingOut': 'Вихід...',
    'manageUsers': 'Керувати користувачами',
    'manageUsersSubtitle': 'Перегляд облікових записів користувачів і керування ними',
    'analytics': 'Аналітика',
    'analyticsSubtitle': 'Перегляньте свою бізнес-аналітику',
    'information': 'Інформація',
    'faq': 'Часті запитання',
    'faqSubtitle': 'Часті запитання',
    'aboutUs': 'Про нас',
    'aboutUsSubtitle': 'Дізнайтеся більше про нашу платформу',
    'helpSupport': 'Допомога та підтримка',
    'helpSupportSubtitle': 'Отримайте допомогу та зверніться до служби підтримки',
    'accountActions': 'Дії облікового запису',
    'deleteAccount': 'Видалити акаунт',
    'deleteAccountSubtitle': 'Запит на остаточне видалення вашого облікового запису',
    'logout': 'Вийти',
    'logoutSubtitle': 'Вийдіть зі свого облікового запису',
    'confirmLogout': 'Підтвердити вихід',
    'confirmLogoutMessage': 'Ви впевнені, що бажаєте вийти?',
    'cancel': 'Скасувати',
    'loginAgain': 'Увійдіть знову',
    // ============================================
    // Language Related
    // ============================================
    'language': 'Мова',
    'languageSubtitle': 'Змінити мову програми',
    'notificationSettings': 'Налаштування сповіщень',
    'notificationSettingsSubtitle': 'Виберіть, які сповіщення ви хочете отримувати.',
    'notificationChannels': 'Канали',
    'pushNotifications': 'Push-сповіщення',
    'pushNotificationsSubtitle': 'Отримуйте push-повідомлення на свій пристрій',
    'emailNotifications': 'Сповіщення електронною поштою',
    'emailNotificationsSubtitle': 'Отримувати сповіщення електронною поштою',
    'notificationModules': 'За категорією',
    'notificationSettingsSaved': 'Налаштування сповіщень збережено',
    'notificationModuleProducts': 'Продукти',
    'notificationModuleProductOrders': 'Замовлення продуктів',
    'notificationModuleDeals': 'Угоди',
    'notificationModuleDealOrders': 'Замовлення угод',
    'notificationModuleBanners': 'банери',
    'notificationModuleAdmin': 'адмін',
    'notificationModuleEngagement': 'Заручини',
    'notificationModulePayment': 'Оплата',
    'push': 'Поштовх',
    'currency': 'Валюта',
    'currencySubtitle': 'Показати валюту для цін (за замовчуванням: пристрій)',
    'systemDefault': 'Система за замовчуванням',
    'syncFxRates': 'Синхронізація курсів валют',
    'syncFxRatesSubtitle': 'Отримайте останні курси валют від ЄЦБ',
    'syncFxRatesSuccess': 'Курси валют успішно оновлено',
    'syncFxRatesFailed': 'Не вдалося оновити курси валют. Використання кешованих ставок.',
    'changingLanguage': 'Зміна мови...',
    'languageChangeFailed': 'Не вдалося синхронізувати налаштування мови. Спробуйте ще раз.',
    'failedToChangeLanguage': 'Не вдалося змінити мову. Спробуйте ще раз.',
    'english': 'англійська',
    'german': 'Німецький',
    'turkish': 'турецька',
    'arabic': 'арабська',
    'urdu': 'урду',
    'hindi': 'Хінді',
    'russian': 'російська',
    'sourceLanguageLabel': 'Мова змісту',
    'sourceLanguageHint': 'Мова тексту, який ви вводите (буде перекладено іншими мовами)',
    'selectYourLanguage': 'Виберіть свою мову',
    'selectYourLanguageSubtitle': 'Виберіть мову для програми. Ви можете змінити це пізніше в налаштуваннях.',
    'continueButton': 'Продовжити',
    // ============================================
    // Common / General
    // ============================================
    'sessionExpired': 'Сеанс закінчився',
    'sessionExpiredMessage': 'Ваш сеанс закінчився. Увійдіть ще раз, щоб продовжити використання програми.',
    'comingSoon': 'Скоро буде',
    'retry': 'Повторіть спробу',
    'error': 'Помилка',
    'errorWithDetail': 'Помилка: {detail}',
    'close': 'Закрити',
    'save': 'зберегти',
    'done': 'Готово',
    'saving': 'Збереження...',
    'update': 'Оновлення',
    'edit': 'Редагувати',
    'delete': 'Видалити',
    'add': 'додати',
    'remove': 'видалити',
    'select': 'Виберіть',
    'all': 'всі',
    'filter': 'фільтр',
    'type': 'Тип',
    'status': 'Статус',
    'unknown': 'Невідомий',
    // ============================================
    // About Us Related
    // ============================================
    'welcomeToProductDeal': 'Ласкаво просимо до Product Deal',
    'trustedMarketplace': 'Ваш надійний ринок оптових товарів і угод',
    'ourMission': 'Наша місія',
    'ourMissionContent': 'З’єднати оптових і роздрібних продавців, зробити оптові закупівлі доступними та ефективними для підприємств будь-якого розміру.',
    'whatWeOffer': 'Що ми пропонуємо',
    'whatWeOfferContent':
        '• Доступ до перевірених оптовиків'
        '• Ексклюзивні оптові пропозиції та знижки'
        '• Відстеження запасів у реальному часі'
        '• Безпечне керування замовленнями'
        '• Виявлення продукту на основі місцезнаходження',
    'forWholesalers': 'Для оптовиків',
    'forRetailers': 'Для роздрібних торговців',
    'forRetailersContent': 'Знаходьте товари від найближчих оптовиків, беріть участь у оптових угодах і ефективно керуйте своїми замовленнями.',
    'forWholesalersContent': 'Демонструйте свої продукти, створюйте ексклюзивні пропозиції, керуйте замовленнями та охоплюйте ширшу мережу роздрібних продавців.',
    // ============================================
    // FAQ Related
    // ============================================
    'frequentlyAskedQuestions': 'Часті запитання',
    'commonQuestions': 'Загальні запитання',
    'faqQuestion1': 'Як зробити замовлення?',
    'faqAnswer1': 'Перегляньте активні пропозиції або продукти, виберіть необхідну кількість і натисніть «Оформити замовлення». Ваше замовлення буде розглянуто оптовиком.',
    'faqQuestion2': 'Що таке замовлення на угоду?',
    'faqAnswer2': 'Замовлення на угоду – це можливості оптових закупівель, коли оптовики пропонують знижені ціни, коли досягнуто цільової кількості. Ви можете розмістити кілька замовлень на одну угоду.',
    'faqQuestion3': 'Як здійснюється доставка?',
    'faqAnswer3': 'Деталі доставки узгоджуються безпосередньо з оптовиком після підтвердження замовлення. Контактна інформація буде надана після підтвердження замовлення.',
    'faqQuestion4': 'Чи можу я скасувати замовлення?',
    'faqAnswer4': 'Ви можете скасувати відкладені замовлення. Після підтвердження замовлення оптовиком застосовуються правила скасування згідно з умовами оптового продавця.',
    'faqQuestion5': 'Як мені стати перевіреним оптовиком?',
    'faqAnswer5': 'Зверніться до нашої служби підтримки, щоб отримати підтвердження. Вам потрібно буде надати ділову документацію та завершити процес підтвердження.',
    'faqQuestion6': 'Як товари сортуються за відстанню?',
    'faqAnswer6': 'Товари автоматично сортуються за віддаленістю від вашого місцезнаходження. Обов’язково додайте своє місцезнаходження у своєму профілі для точного сортування на основі відстані.',
    'faqQuestion7': 'Які способи оплати приймаються?',
    'faqAnswer7': 'Способи оплати залежать від оптовика. Деталі оплати обговорюються після підтвердження замовлення.',
    'faqQuestion8': 'Як оновити профіль?',
    'faqAnswer8': 'Перейдіть на сторінку свого профілю з інформаційної панелі, оновіть інформацію та збережіть. Ви можете додати кілька адрес для різних місць.',
    // ============================================
    // Wholesaler Directory Related
    // ============================================
    'couldNotLoadWholesalers': 'Нам зараз не вдалося завантажити оптовиків.',
    'verifiedPartners': 'перевірені партнери',
    'verifiedPartnersDescription': 'перевірені партнери',
    'noWholesalersNearYou': 'Поблизу ще немає оптовиків. Оновіть своє місцезнаходження, щоб розблокувати асортимент поблизу.',
    // ============================================
    // Dashboard Related
    // ============================================
    'dashboard': 'Приладова панель',
    'nearbyWholesalers': 'Поруч оптовики',
    'allWholesalers': 'Всі оптовики',
    'noWholesalersFound': 'Оптовиків не знайдено',
    'errorLoadingWholesalers': 'Помилка завантаження оптовиків',
    'advertiseWithUs': 'Рекламуйте з нами',
    'boostYourSales': 'Збільште продажі!',
    'promoteYourProducts': 'Рекламуйте свої продукти тут і охоплюйте більше клієнтів.',
    'unableToLoadDashboard': 'Не вдалося завантажити інформаційну панель',
    'unableToLoadProduct': 'Не вдалося завантажити продукт',
    'unableToLoadWholesaler': 'Не вдається завантажити оптовика',
    'spotlight': 'Прожектор',
    'spotlightWholesalersEmpty': 'Центральні оптові торговці з’являться тут, коли ринок загуде.',
    // ============================================
    // Orders Related
    // ============================================
    'orderId': 'ID замовлення',
    'payment': 'Оплата',
    'paymentStatus': 'Статус платежу',
    'placedOn': 'Розміщено на',
    'orderItems': 'Товари замовлення',
    'createShipment': 'Створити відправлення',
    'shippingAddress': 'Адреса доставки',
    'notes': 'Примітки',
    'orderNotes': 'Примітки до замовлення',
    'orderDetails': 'Деталі замовлення',
    'unableToLoadOrder': 'Не вдалося завантажити замовлення',
    'updateOrderStatus': 'Оновити статус замовлення',
    'subtotal': 'Проміжний підсумок',
    'shipping': 'Доставка',
    'shippingWithFreeThreshold': 'Доставка: {amount} (безкоштовно за {threshold}+ одиниць)',
    'freeShippingForThreshold': 'Безкоштовна доставка за {threshold}+ одиниць',
    'shippingBaseOnly': 'Доставка: {{сума}}',
    'shippingWithPerUnit': 'Доставка: {base} + {perUnit} за одиницю',
    'total': 'Всього',
    'reasonOptional': 'Причина (необов\'язково)',
    'notesOptional': 'Примітки (необов\'язково)',
    'sku': 'Артикул',
    'skuN/A': 'Артикул: Н/Д',
    'trackingAvailable': 'ДОСТУПНИЙ ОТСЛЕЖЕННЯ',
    'shipped': 'Відправлено',
    'shipments': 'Відвантаження',
    'shipmentId': 'Відвантаження {id}',
    'trackingLabel': 'Відстеження: {{число}}',
    'track': 'Трек',
    'couldNotOpenTrackingUrl': 'Не вдалося відкрити URL-адресу відстеження',
    'carrierLabel': 'Перевізник: {name}',
    'estDelivery': 'Приблизно доставка: {{дата}}',
    'shippedAt': 'Відправлено: {date}',
    'deliveredAt': 'Доставлено: {date}',
    'each': 'кожен',
    'unit': 'одиниця',
    'noOrdersYet': 'Замовлень ще немає',
    'noOrdersYetMessage': 'Перегляньте продукти та пропозиції, щоб зробити своє перше замовлення.',
    'unableToLoadOrders': 'Не вдалося завантажити ваші замовлення',
    'orderPlaced': 'Замовлення розміщено',
    'confirmed': 'Підтверджено',
    'delivered': 'Доставлено',
    'pendingOrders': 'Відкладені замовлення',
    'viewOrders': 'Переглянути замовлення',
    'allOrders': 'Всі замовлення',
    'pendingConfirmation': 'Очікує на підтвердження',
    'packing': 'Упаковка',
    'packed': 'Упакований',
    'dispatched': 'Відправлено',
    'outForDelivery': 'На доставку',
    'viewDetails': 'Переглянути деталі',
    'changeOrderStatus': 'Змінити статус замовлення',
    'orderStatusUpdatedSuccessfully': 'Статус замовлення успішно оновлено',
    'orderStatusUpdated': 'Статус замовлення успішно оновлено',
    'itemStatusUpdatedSuccessfully': 'Статус елемента успішно оновлено',
    'itemStatusUpdated': 'Статус елемента успішно оновлено',
    'ordersCountSuffix': 'замовлення',
    'order': 'порядок',
    'orderLabel': 'порядок',
    'orders': 'замовлення',
    'ordered': 'замовив',
    'dealOrder': 'Порядок угоди',
    'productOrder': 'Замовлення товару',
    'bid': 'Ставка',
    'itemPlusMore': '{item} + ще {n}',
    // ============================================
    // Cart Related
    // ============================================
    'yourCart': 'Ваш кошик',
    'cart': 'кошик',
    'emptyCart': 'Ваш кошик порожній',
    'emptyCartMessage': 'Щоб почати, додайте продукти в кошик.',
    'addProductsToSeeThemHere': 'Додайте продукти, щоб побачити їх тут.',
    'placeOrderCashOnDelivery': 'Оформити замовлення (готівкою при доставці)',
    'cashOnDelivery': 'Накладений платіж',
    'paymentMethodCash': 'Накладений платіж',
    'paymentMethodCashDesc': 'Оплатіть при отриманні доставки.',
    'paymentMethodInvoice': 'рахунок-фактура',
    'paymentMethodInvoiceDesc': 'Ми надсилаємо вам рахунок; Відвантаження починається незабаром після підтвердження замовлення.',
    'paymentMethodBankTransfer': 'Банківський переказ',
    'paymentMethodBankTransferDesc': 'Спочатку оплата, потім відправка. Інструкції щодо оплати надіслані електронною поштою.',
    'sendPaymentInstructions': 'Надіслати платіжні інструкції',
    'paymentMode': 'Режим оплати',
    'paymentModeSubtitle': 'За умовчанням для ваших угод. Ви можете змінити це пізніше у своєму профілі.',
    'paymentModeSubtitleMulti': 'Виберіть усі прийнятні способи оплати. Ви можете змінити це пізніше у своєму профілі.',
    'paymentSettings': 'Налаштування оплати',
    'paymentSettingsSubtitle': 'Банківські реквізити для рахунків/замовлень на банківський переказ. Ви можете оновити їх пізніше у своєму профілі.',
    'payWithCard': 'Оплата карткою',
    'placeOrderPayNow': 'Розмістіть замовлення та сплатіть',
    'paymentAfterOrderConfirmed': 'Оплату буде запропоновано після підтвердження замовлення (наприклад, банківським переказом).',
    'paymentNotAvailable': 'Оплата карткою недоступна. Спробуйте готівкою при доставці.',
    'paymentCancelled': 'Платіж скасовано.',
    'dealSucceededPayNow': 'Угода виконана – платіть зараз',
    'totalToPay': 'Всього до оплати',
    'payByInvoice': 'Оплата за рахунком',
    'payByCard': 'Оплата карткою',
    'invoiceInstructionsSent': 'Інструкції щодо оплати були надіслані електронною поштою.',
    'reportPayment': '',
    'buyerReportedPayment': '',
    'reportedAt': 'Повідомлено на',
    'reportPaymentSubtitle': 'Поділіться своїми платіжними даними, щоб ми могли перевірити',
    'reportPaymentSuccess': 'Платіжні реквізити надіслано. Продавець перевірить і оновить замовлення.',
    'referenceNumber': 'Довідковий номер',
    'transactionId': 'ID транзакції',
    'bankName': 'Назва банку',
    'paymentDetailsNotes': 'Додаткові примітки (необов\'язково)',
    'paymentInstructionsBankOnly': 'Інструкції щодо оплати були надіслані електронною поштою. Оплата банківським переказом. Якщо ви вже заплатили, власник угоди підтвердить отримання.',
    'markAsPaid': 'Позначити як оплачений',
    'paymentNotesOptional': 'Платіжні квитанції (наприклад, банківська довідка)',
    'myDealStats': 'Моя статистика угод',
    'dealsJoined': 'Угоди приєдналися',
    'totalOrderedQuantity': 'Загальна кількість замовлень',
    'totalOrders': 'Всього замовлень',
    'placeOrder': 'Розмістити замовлення',
    'fxDisclaimer': 'Курс валют може змінюватися. Відображена сума є орієнтовною.',
    'placingOrder': 'Розміщення замовлення...',
    'orderPlacedSuccessfully': 'Замовлення виконано!',
    'failedToPlaceOrder': 'Не вдалося розмістити замовлення',
    'onlyKioskCanOrder': 'Лише облікові записи кіоску/магазину можуть розміщувати замовлення.',
    'admins': 'Адміністратори',
    'subAdmins': 'Суб-адміністратори',
    'wholesalers': 'Оптовики',
    'canOnlyViewProducts': 'можна лише переглядати товари. Лише облікові записи кіоску/магазину можуть розміщувати замовлення.',
    'addToCart': 'Додати в кошик',
    'addedToCart': '✅ Додано в кошик',
    'quantity': 'Кількість',
    'unitPrice': 'Ціна за одиницю',
    'totalAmount': 'Загальна сума',
    'buyer': 'Покупець',
    'items': 'елементи',
    // ============================================
    // Registration Related
    // ============================================
    'register': 'зареєструватися',
    'createAccount': 'Створити акаунт',
    'createAccountTitle': 'Створити акаунт',
    'createAccountSubtitle': 'Розблокуйте підібраних оптовиків, великі угоди та логістичну підтримку.',
    'fullName': 'ПІБ',
    'email': 'Електронна пошта',
    'workEmail': 'Робоча електронна пошта',
    'phone': 'Телефон',
    'password': 'Пароль',
    'confirmPassword': 'Підтвердьте пароль',
    'confirmPasswordLabel': 'Підтвердьте пароль',
    'businessName': 'Назва компанії',
    'country': 'Країна',
    'city': 'Місто',
    'address': 'Адреса',
    'streetAddress': 'Вулиця',
    'addressWillBeGeocoded': 'Адреса буде автоматично геокодована для отримання координат',
    'addressSearchHint': 'Знайдіть свою адресу',
    'placesLookupFailed': 'Не вдалося завантажити деталі адреси з сервера. Ви можете ввести або змінити свою адресу вручну.',
    'placesNoAddressResults': 'Адреси не знайдено. Спробуйте інший пошук.',
    'placesAddressSearchConfigError': 'Пошук за адресою недоступний. Перевірте свою мережу та перевірте, чи ця програма використовує правильний сервер API (API_BASE_URL).',
    'placesAddressSearchRequestFailed': 'Помилка пошуку адреси. Перевірте підключення або повторіть спробу пізніше.',
    'getLocation': 'Отримати місцезнаходження',
    'selectRole': 'Виберіть роль',
    'accountType': 'Тип рахунку',
    'alreadyHaveAccount': 'Вже маєте акаунт?',
    'login': 'Логін',
    'signIn': 'Увійдіть',
    'registrationReceived': 'Реєстрацію отримано! Ми повідомимо вас, коли обліковий запис буде схвалено.',
    'fullNameRequired': 'Введіть повне ім’я',
    'fullNameMinLength': 'Повне ім’я має містити щонайменше 3 символи',
    'emailRequired': 'Необхідно вказати адресу електронної пошти',
    'provideValidEmail': 'Укажіть дійсну електронну адресу',
    'phoneNumberOptional': 'номер телефону (необов\'язково)',
    'enterValidPhoneNumber': 'Введіть дійсний номер телефону',
    'kioskShopNameOptional': 'Назва кіоску/магазину (необов’язково)',
    'companyName': 'Назва компанії',
    'latitudeOptional': 'Широта (необов\'язково)',
    'longitudeOptional': 'Довгота (необов\'язково)',
    'locating': 'Розташування...',
    'locatingEllipsis': 'Пошук...',
    'useCurrentLocation': 'Використовувати поточне місцезнаходження',
    'enableLocationServices': 'Увімкніть служби визначення місцезнаходження для автоматичного заповнення координат.',
    'enableLocationPermissions': 'Увімкніть доступ до місцезнаходження для автоматичного заповнення координат.',
    'unableToFetchLocation': 'Не вдалося отримати місцезнаходження. Спробуйте ще раз.',
    'unableToFetchLocationShort': 'Не вдалося отримати місцезнаходження.',
    'pleaseEnterValidLatLng': 'Введіть дійсну широту та довготу.',
    'createPassword': 'Створіть пароль',
    'minimum8CharactersRequired': 'Потрібно мінімум 8 символів',
    'weVerifyEveryBusiness': 'Ми перевіряємо кожен бізнес вручну, щоб зберегти довіру на ринку.',
    'submitForReview': 'Надіслати на перевірку',
    'alreadyVerifiedSignIn': 'Вже перевірено? Увійдіть',
    'forgotPassword': 'Забули пароль?',
    'welcomeBack': 'Ласкаво просимо назад',
    'signInToReach': 'Увійдіть, щоб отримати доступ до затверджених оптовиків поблизу вас.',
    'createKioskOrWholesalerAccount': 'Створіть обліковий запис кіоску або оптовика',
    'accountSubmittedForApproval': 'Обліковий запис надіслано на затвердження. Інформаційна панель буде розблокована після схвалення.',
    'dashboardWillUnlock': 'Інформаційна панель буде розблокована після схвалення.',
    'pleaseLoginToPlaceOrder': 'Увійдіть, щоб зробити замовлення',
    // ============================================
    // Legal / Compliance (T&C + GDPR)
    // ============================================
    'legalComplianceTitle': 'Юридичні та відповідність',
    'termsAndConditionsFullText': 'Створюючи обліковий запис, ви вступаєте в ділові відносини з оператором платформи та погоджуєтеся з положеннями та умовами платформи (AGB). Ці Умови визначають, як ви можете використовувати ринок, як обробляються угоди та замовлення та які зобов’язання застосовуються до покупців і оптовиків. Ви підтверджуєте, що вся надана вами інформація є точною і що ви використовуватимете платформу лише для законних бізнес-цілей. Крім того, ви погоджуєтесь, що угоди та замовлення можуть стати обов’язковими після підтвердження оптовиком або після досягнення мети угоди. Залежно від вашої юрисдикції можуть застосовуватися додаткові правила, що стосуються окремих країн. Перш ніж продовжити, ознайомтеся з усіма Умовами та положеннями, наданими оператором.',
    'scrollToAcceptTerms': 'Прокрутіть до кінця Загальних положень та умов, щоб розблокувати прапорець для прийняття.',
    'scrollToBottom': 'Прокрутіть вниз',
    'acceptTermsLabel': 'Я прочитав і приймаю Загальні положення та умови (AGB).',
    'termsScrollHint': 'Будь ласка, прокрутіть Загальні положення та умови, перш ніж прийняти.',
    'acceptPrivacyLabel': 'Я прочитав і приймаю політику конфіденційності даних / GDPR.',
    'privacySummaryText': 'Ваші дані оброблятимуться для керування обліковим записом, замовлень, аналітики та безпеки відповідно до нашої політики конфіденційності.',
    'mustAcceptAllLegalDocuments': 'Будь ласка, прийміть усі юридичні документи та підтвердіть рамковий договір.',
    'mustAcceptTermsAndPrivacy': 'Щоб продовжити, прийміть Загальні положення та умови та Конфіденційність даних / GDPR.',
    // ============================================
    // Account Approval / Waiting Screen Related
    // ============================================
    'accountApproval': 'Затвердження облікового запису',
    'accountApproved': 'Обліковий запис схвалено!',
    'redirecting': 'Перенаправлення...',
    'pendingReview': 'Очікує на розгляд',
    'needMoreInfo': 'Потрібно більше інформації',
    'wholesalerVerificationMessage': 'дякую Щоб активувати обліковий запис оптового продавця, надішліть документи для підтвердження свого бізнесу. Наш адміністратор перегляне та затвердить ваш обліковий запис.',
    'buyerVerificationMessage': 'дякую Щоб активувати обліковий запис покупця, надішліть документи, що підтверджують особу. Наш адміністратор перегляне та затвердить ваш обліковий запис.',
    'generalVerificationMessage': 'дякую Щоб активувати обліковий запис, надішліть підтверджуючі документи. Наш адміністратор перегляне та затвердить ваш обліковий запис.',
    'adminNote': 'Примітка адміністратора',
    'uploadVerificationDocument': 'Завантажте документ підтвердження',
    'acceptedDocumentTypes': 'Прийнятні типи документів',
    'wholesalerDocumentTypes': 'Ліцензія на підприємницьку діяльність, податковий номер, реєстраційні документи компанії (PNG, JPG, PDF)',
    'buyerDocumentTypes': 'Посвідчення особи, посвідчення водія або будь-яке посвідчення особи державного зразка (PNG, JPG, PDF)',
    'generalDocumentTypes': 'Посвідчення особи, посвідчення водія, посвідчення особи (PNG, JPG, PDF)',
    'selectedDocuments': 'Вибрані документи',
    'addDocuments': 'Додати документи',
    'uploading': 'Завантаження...',
    'uploaded': 'Завантажено',
    'selectFirst': 'Виберіть Перший',
    'documentsUploadedSuccessfully': 'документ(и) успішно завантажено. Наш адміністратор перегляне та оновить статус вашого облікового запису.',
    'documentUploadedSuccessfully': 'Документ успішно завантажено. Наш адміністратор перегляне та оновить статус вашого облікового запису.',
    'failedToPickDocuments': 'Не вдалося вибрати документи',
    'passport': 'Паспорт',
    'passportDescription': 'Завантажте свій паспорт для підтвердження особи',
    'passportAlternative': 'Якщо у вас немає паспорта, ви можете завантажити затверджене урядом посвідчення особи з адресою (наприклад, Aadhar в Індії, національне посвідчення особи тощо)',
    'gewerbeschein': 'Gewerbeschein',
    'idCard': 'ID-картка',
    'taxId': 'Індивідуальний податковий номер',
    'companyRegistration': 'Реєстрація компанії',
    'document': 'документ',
    'gewerbescheinDescription': 'Завантажте свою Gewerbeschein (торгову ліцензію) для підтвердження бізнесу',
    'gewerbescheinAlternative': 'Завантажте свій офіційний документ про торгівлю, виданий державними органами',
    'businessLicense': 'Ділова ліцензія / Gewerbeschein',
    'businessLicenseDescription': 'Завантажте свою бізнес-ліцензію або Gewerbeschein для підтвердження бізнесу',
    'businessLicenseAlternative': 'Якщо у вас немає бізнес-ліцензії, ви можете завантажити реєстраційні документи компанії, податковий номер або будь-який офіційний документ для підтвердження бізнесу',
    'selectDocument': 'Виберіть Документ',
    'changeDocument': 'Змінити документ',
    'pleaseSelectAtLeastOneDocument': 'Виберіть принаймні один документ для завантаження.',
    'sendByEmail': 'Надіслати електронною поштою',
    'emailOptionDescription': 'Крім того, ви можете надіслати документи для підтвердження безпосередньо електронною поштою. Наш адміністратор перевірить документи та відповідно оновить статус вашого облікового запису.',
    'openEmailToAdmin': 'Відкрийте Email to Admin',
    'emailDraftOpened': 'Чернетку електронного листа відкрито. Будь ласка, надішліть його для завершення подання. Наш адміністратор перевірить ваші документи та оновить статус вашого облікового запису.',
    'couldNotOpenEmailApp': 'Не вдалося відкрити програму електронної пошти. Надішліть електронний лист на адресу',
    'manually': 'вручну',
    'failedToOpenEmail': 'Не вдалося відкрити електронну пошту',
    'loadingAccountStatus': 'Завантаження статусу облікового запису...',
    'errorLoadingStatus': 'Помилка завантаження статусу',
    'pleaseReviewAndResubmit': 'Перегляньте та надішліть документи повторно.',
    'useDifferentAccount': 'Використовуйте інший обліковий запис',
    'useDifferentAccountConfirm': 'Вийти, щоб увійти, чи зареєструватися під іншим обліковим записом?',
    'failedToUpdateStatus': 'Не вдалося оновити юридичні налаштування. Спробуйте ще раз.',
    // ============================================
    // Profile Related
    // ============================================
    'editProfile': 'Редагувати профіль',
    'profileUpdated': 'Профіль успішно оновлено',
    'failedToUpdateProfile': 'Не вдалося оновити профіль',
    'profileImageUpdated': 'Зображення профілю оновлено',
    'failedToUploadImage': 'Не вдалося завантажити зображення',
    'tagline': 'Слоган',
    'locations': 'Розташування',
    'addLocation': 'Додати місцезнаходження',
    'editLocation': 'Редагувати місцезнаходження',
    'deleteLocation': 'Видалити місцезнаходження',
    'latitude': 'Широта',
    'longitude': 'Довгота',
    'nameIsRequired': 'Необхідно вказати ім\'я',
    'businessNameOptional': 'Назва компанії (необов\'язково)',
    'phoneOptional': 'Телефон (необов\'язково)',
    'addresses': 'Адреси',
    'addAddress': 'Додати адресу',
    'noAddressesAdded': 'Адреси не додано',
    'addYourFirstAddress': 'Щоб почати, додайте свою першу адресу',
    'editAddress': 'Редагувати адресу',
    'removeAddress': 'Видалити адресу',
    'editAddressTitle': 'Редагувати адресу',
    'addAddressTitle': 'Додати адресу',
    'saveChanges': 'Зберегти зміни',
    'labelExample': 'Мітка (наприклад, дім, офіс, головна торгова точка)',
    'streetAreaOptional': 'Вулиця / район (необов\'язково)',
    'countryOptional': 'Країна (необов\'язково)',
    'cityOptional': 'місто (необов\'язково)',
    'locationNotUpdating': 'Розташування не оновлюється',
    'locationNotUpdatingSolution': 'Перейдіть до «Профіль» > «Адреси» та переконайтеся, що координати вашого місцезнаходження правильні',
    // ============================================
    // Deals Related
    // ============================================
    'deals': 'Угоди',
    'activeDeals': 'Активні пропозиції',
    'allDeals': 'Усі пропозиції',
    'myDeals': 'Мої пропозиції',
    'manageDeals': 'Керуйте угодами',
    'noDealsFound': 'Угод не знайдено',
    'selectDeal': 'Виберіть Угода',
    'unableToLoadDeals': 'Не вдалося завантажити пропозиції',
    'noDealsAvailable': 'Немає доступних угод',
    'noDealsYet': 'Угод ще немає',
    'checkBackLaterForNewDeals': 'Перевірте пізніше, щоб отримати нові пропозиції',
    'noActiveDeals': 'Немає активних угод',
    'filterDeals': 'Фільтрувати пропозиції',
    'progress': 'Прогрес',
    'dealClosed': 'Угода закрита',
    'ends': 'Закінчується',
    'variant': 'Варіант',
    'min': 'Хв:',
    'max': 'Макс.',
    'perUnit': '/од',
    'perUnitLabel': 'За {{одиницю}}',
    'inStock': 'в наявності',
    'similarProducts': 'Подібні продукти',
    'noActiveDealsForProduct': 'Немає активних пропозицій для цього товару',
    'activeDealsForProduct': 'Активні пропозиції на цей товар',
    'moreFromWholesaler': 'Більше від {name}',
    'dealsFromWholesaler': 'Пропозиції від {name}',
    'productsFromWholesaler': 'Продукти від {name}',
    'searchProductsFromWholesaler': 'Пошук продуктів від {name}...',
    'onlyKioskCanPurchase': 'Тільки облікові записи кіоску/магазину можуть купувати продукти',
    'canOnlyReviewFromDelivered': 'Ви можете переглянути лише товари з доставлених замовлень',
    'alreadyReviewedThisProduct': 'Ви вже переглянули цей продукт із цього замовлення',
    'selectOrderToReview': 'Виберіть Замовлення для перегляду',
    'orderN': 'Замовлення №{id}',
    'viewDeals': 'Переглянути пропозиції',
    'locationInfoNotAvailable': 'Інформація про місцезнаходження недоступна',
    'location': 'Розташування',
    'kfProductDealTagline': 'KF Product Deal, допомога в пошуку найкращих пропозицій',
    'errorSearchingProducts': 'Помилка пошуку продуктів',
    'myDealOrders': 'Мої розпорядження',
    'noDealOrdersYet': 'Замовлень на угоду ще немає',
    'browseDealsPlaceFirstOrder': 'Перегляньте активні пропозиції та зробіть своє перше замовлення.',
    'statusLabel': 'Статус',
    'noProductsFoundForWholesaler': 'Для вибраного оптовика не знайдено продуктів',
    'noApprovedWholesalersAvailable': 'Немає затверджених оптовиків',
    'searchByNameBusinessEmail': 'Пошук за назвою, назвою компанії, електронною поштою...',
    'selectWholesaler': 'Виберіть Оптовик',
    'selectProduct': 'Виберіть продукт',
    'pageNOfM': 'Сторінка {current} із {total}',
    'priceLabel': 'Ціна',
    'pleaseSelectImageOrVideo': 'Виберіть зображення або відео',
    'onlyWholesalersCreateStories': 'Тільки оптовики можуть створювати історії',
    'storyCreatedSuccessfully': 'Історія успішно створена! 🎉',
    'uploadingMedia': 'Завантаження медіа...',
    'creatingStory': 'Створення історії...',
    'storyMedia': 'Медіа історії',
    'videoSelected': 'Вибрано відео',
    'activeShopsSuffix': 'діючі магазини',
    'storiesCountSuffix': 'історії',
    'create': 'Створити',
    'off': 'ВИМКНЕНО',
    'minOrder': 'Мінімальне замовлення',
    'target': 'Цільова',
    'units': 'одиниць',
    'dealCreatedSuccessfully': 'Угоду успішно створено',
    'createDeal': 'Створити угоду',
    'editDeal': 'Редагувати угоду',
    'closeDeal': 'Закрити угоду',
    'closeDealConfirmMessage': 'Ви впевнені, що хочете закрити цю угоду? Цю дію не можна скасувати.',
    'closeDealGoalReached': 'Мета досягнута',
    'closeDealGoalReachedHint': 'Якщо позначено: усі незавершені замовлення будуть автоматично підтверджені (угода успішно виконана). Якщо не позначено: угоду буде закрито, але ви зможете підтвердити замовлення вручну пізніше.',
    'createYourFirstDeal': 'Створіть свою першу угоду',
    'dealTitle': 'Назва угоди',
    'pleaseEnterDealTitle': 'Введіть назву угоди',
    'dealType': 'Тип угоди',
    'dealPrice': 'Ціна угоди',
    'startDate': 'Дата початку',
    'endDate': 'Дата закінчення',
    'pleaseEnterDealPrice': 'Будь ласка, введіть ціну угоди',
    'originalPrice': 'Оригінальна ціна',
    'targetQuantity': 'Цільова кількість',
    'pleaseEnterTargetQuantity': 'Будь ласка, введіть цільову кількість',
    'targetQuantityMin': 'Цільова кількість має бути принаймні 1',
    'minOrderQty': 'Мінімальна кількість замовлення',
    'pleaseEnterMinOrderQty': 'Будь ласка, введіть мінімальну кількість замовлення',
    'minOrderQtyMin': 'Мінімальна кількість замовлення має бути принаймні 1',
    'maxOrderQuantityOptional': 'Максимальна кількість замовлення (необов\'язково)',
    'endDateMustBeAfterStartDate': 'Дата завершення має бути після дати початку',
    'pleaseSelectWholesalerFirst': 'Спочатку виберіть оптового продавця',
    'auction': 'Аукціон',
    'priceDrop': 'Падіння ціни',
    'limitedStock': 'Обмежений запас',
    'scheduled': 'За розкладом',
    'live': 'Жити',
    'highlightedDeal': 'Виділена угода',
    'canOnlyViewDeals': 'можна лише переглядати пропозиції. Лише облікові записи кіоску/магазину можуть розміщувати замовлення.',
    'dealProgressNotUpdating': 'Перебіг угоди не оновлюється',
    'dealProgressNotUpdatingSolution': 'Перебіг угоди оновлюється автоматично. Якщо здається, що він застряг, оновіть сторінку',
    'dealProgress': 'Хід угоди',
    'unableToLoadProgress': 'Не вдалося завантажити прогрес: {detail}',
    'noOrdersPlacedYet': 'За цією угодою ще не розміщено жодного замовлення.',
    'orderPlacedSuffix': 'оформлено замовлення',
    'ordersPlacedSuffix': 'розміщені замовлення',
    'closed': 'ЗАЧИНЕНО',
    // ============================================
    // Products Related
    // ============================================
    'product': 'Продукт',
    'products': 'продуктів',
    'productsSection': 'Продукти',
    'allProducts': 'Всі продукти',
    'myProducts': 'Мої продукти',
    'noProductsAvailable': 'Немає доступних продуктів',
    'noProductsYet': 'Продуктів ще немає',
    'addYourFirstProduct': 'Додайте свій перший продукт',
    'addFirstProduct': 'Додайте свій перший продукт',
    'addProduct': 'Додати продукт',
    'editProduct': 'Редагувати товар',
    'deleteProduct': 'Видалити продукт',
    'deletingProduct': 'Видалення продукту...',
    'deleteProductConfirmGeneric': 'Ви впевнені, що хочете видалити цей продукт? Цю дію не можна скасувати.',
    'productUpdatedSuccessfully': 'Продукт успішно оновлено',
    'productCreatedSuccessfully': 'Продукт створено успішно',
    'productDeletedSuccessfully': 'Продукт успішно видалено',
    'changeProductStatus': 'Змінити статус продукту',
    'changeStatus': 'Змінити статус',
    'updatingStatus': 'Оновлення статусу...',
    'statusUpdatedToPending': 'Статус оновлено до Очікує',
    'statusUpdatedToApproved': 'Статус оновлено до Approved',
    'statusUpdatedToRejected': 'Статус змінено на Відхилено',
    'productsWillAppearHere': 'Продукти з’являться тут, коли їх буде додано',
    'noProductsFound': 'Продукти не знайдено',
    'youveReachedEnd': '',
    'errorLoadingProducts': 'Помилка завантаження продуктів',
    'featuredCatalog': 'Популярний каталог',
    'viewAll': 'Переглянути всі',
    'outOfStock': 'НЕМАЄ В ​​НАЯВНОСТІ',
    'onlyLeft': 'ТІЛЬКИ',
    'left': 'ВЛІВО',
    'timeRemainingDay': 'Залишився {count} день',
    'timeRemainingDays': 'Залишилося {count} днів',
    'timeRemainingHour': 'Залишилося {count} год',
    'timeRemainingHours': 'Залишилося {count} год',
    'timeRemainingMinute': 'Залишилося {count} м',
    'timeRemainingMinutes': 'Залишилося {count} м',
    'pleaseSelectProduct': 'Виберіть продукт',
    'tapToSelectProduct': 'Торкніться, щоб вибрати продукт',
    'unknownProduct': 'Невідомий продукт',
    'searchProductsHint': 'Пошук продуктів за назвою, SKU...',
    'loadingMoreProducts': 'Завантаження інших продуктів...',
    'reachedEnd': 'Ви дійшли до кінця',
    'productsCountSuffix': 'продуктів',
    'price': 'Ціна',
    'kilogram': 'кілограм',
    'gram': 'грам',
    'liter': 'літр',
    'milliliter': 'мілілітр',
    'piece': 'Шматок',
    'box': 'Коробка',
    'pack': 'упаковка',
    'kmAway': 'км',
    'viewAllProducts': 'Переглянути всі продукти',
    // ============================================
    // Product Management Related
    // ============================================
    'productTitle': 'Назва продукту',
    'productTitleRequired': 'Введіть назву продукту',
    'titleMinLength': 'Заголовок має містити не менше 3 символів',
    'description': 'опис',
    'category': 'Категорія',
    'wholesaler': 'Оптовик',
    'selectCategory': 'Виберіть категорію',
    'selectCategories': 'Виберіть Категорії',
    'pleaseSelectCategory': 'Виберіть категорію',
    'tapToSelectCategory': 'Натисніть, щоб вибрати категорію',
    'pleaseSelectWholesaler': 'Виберіть оптового продавця',
    'tapToSelectWholesaler': 'Натисніть, щоб вибрати оптовика',
    'unknownCategory': 'Невідома категорія',
    'yourAccount': 'Ваш рахунок',
    'currentUser': 'Поточний користувач',
    'variants': 'Варіанти',
    'useVariants': 'Використовуйте варіанти',
    'addVariant': 'Додати варіант',
    'addAttribute': 'Додати атрибут',
    'variantSkuRequired': 'Потрібно вказати SKU',
    'addAtLeastOneVariant': 'Будь ласка, додайте хоча б один варіант',
    'selectVariant': 'Виберіть Варіант',
    'selectVariantHelper': 'Виберіть варіант цієї угоди',
    'noVariantsMessage': 'Цей товар не має варіантів. Угода буде створена безпосередньо для продукту.',
    'unableToLoadVariantsMessage': 'Не вдалося завантажити варіанти. Угода буде створена на продукт.',
    'featuredProduct': 'Рекомендований продукт',
    'default': 'За замовчуванням',
    'updateProduct': 'Оновити продукт',
    'createProduct': 'Створити продукт',
    'globalAttributes': 'Глобальні атрибути',
    'globalAttributesDescription': 'Визначте такі атрибути, як «Колір», «Розмір», щоб застосувати їх до всіх варіантів.',
    'attributeName': 'Назва атрибута (наприклад, колір)',
    'attributeNameHint': 'Колір, розмір, матеріал...',
    'imageUrl': 'URL зображення',
    'productImages': 'Зображення продукту',
    'firstImagePrimary': 'Перше зображення є основним',
    'addImageUrl': 'Додати URL',
    'pasteImageUrlHint': 'Вставте URL зображення',
    'costPrice': 'Собівартість',
    'stock': 'Запас',
    'stockRequired': 'Введіть запас',
    'stockNegative': 'Запас не може бути від’ємним',
    'priceRequired': 'Будь ласка, введіть ціну',
    'pricePositive': 'Ціна має бути більше 0',
    'validationError': 'Помилка підтвердження',
    'checkAllFields': 'Перевірте всі поля',
    'pending': 'В очікуванні',
    'approved': 'Затверджено',
    'rejected': 'Відхилено',
    'draft': 'Чернетка',
    'failedToCreateDeal': 'Не вдалося створити угоду',
    'dealNotification24hLabel': 'Цілодобове сповіщення',
    'dealNotification24hHint': 'Додатково. Використовуйте {dealTitle} і {remainingQuantity} як заповнювачі. Залиште пустим, щоб використовувати значення за умовчанням.',
    'dealNotification7dLabel': 'Сповіщення за 7 днів',
    'dealNotification7dHint': 'Додатково. Використовуйте {dealTitle} і {remainingQuantity} як заповнювачі. Залиште пустим, щоб використовувати значення за умовчанням.',
    'notificationTemplatePlaceholdersError': 'Шаблон не повинен використовувати заповнювачі або містити {dealTitle} і {remainingQuantity}.',
    'invalidDateTimeFormat': 'Недійсний формат дати/часу. Будь ласка, перевірте свої дати.',
    // ============================================
    // Categories Related
    // ============================================
    'noCategoriesFound': 'Категорії не знайдено',
    'noCategoriesAvailable': 'Категорії відсутні',
    'allCategories': 'Всі Категорії',
    'searchCategories': 'Пошук категорій...',
    'noCategoriesMatchSearch': 'Жодна категорія не відповідає вашому пошуку',
    'categoriesWillAppearHere': 'Категорії з’являться тут, коли їх буде додано',
    'tryDifferentSearchTerm': 'Спробуйте інший термін пошуку',
    'errorLoadingCategories': 'Помилка завантаження категорій',
    'unableToLoadCategory': 'Не вдалося завантажити категорію',
    'productsCount': '{n} продуктів',
    'categoryName': 'Назва категорії',
    'categoryDescription': 'опис',
    'categoryImageUrl': 'URL зображення',
    'createCategory': 'Створити категорію',
    'editCategory': 'Редагувати категорію',
    'deleteCategory': 'Видалити категорію',
    'deleteCategoryConfirm': 'Ви впевнені, що хочете видалити "{name}"? Цю дію не можна скасувати.',
    'categoryCreatedSuccessfully': 'Категорію успішно створено',
    'enterCategoryDescriptionToGenerate': 'Введіть опис категорії для автоматичного створення вмісту.',
    'categoryDescriptionHint': 'Наприклад, органічні овочі...',
    'contentGeneratedSuccessfullyEnglish': 'Контент створено успішно! (англійська)',
    'generationFailedWithError': 'Помилка створення: {{помилка}}',
    'categoryUpdatedSuccessfully': 'Категорію успішно оновлено',
    'categoryDeletedSuccessfully': 'Категорію успішно видалено',
    'categoryCreationImportMessage': 'Створення категорій наразі здійснюється через імпорт. Будь ласка, зв\'яжіться з адміном.',
    'pleaseEnterCategoryName': 'Введіть назву категорії',
    // ============================================
    // Reviews Related
    // ============================================
    'reviewed': 'Переглянуто',
    'youHaveAlreadyReviewed': 'Ви вже переглянули цей продукт із цього замовлення',
    'reviewUpdatedSuccessfully': 'Відгук успішно оновлено',
    'reviewSubmittedSuccessfully': 'Відгук успішно надіслано',
    'pleaseSelectRating': 'Будь ласка, виберіть оцінку',
    'maximum5ImagesAllowed': 'Дозволено максимум 5 зображень',
    'failedToPickImage': 'Не вдалося вибрати зображення',
    'failedToUploadImages': 'Не вдалося завантажити зображення',
    'uploadImages': 'Завантажте зображення',
    'pickImage': 'Виберіть зображення',
    'pickVideo': 'Виберіть відео',
    'uploadFailed': 'Помилка завантаження',
    'upload': 'Завантажити',
    'invalidImageUrl': 'Недійсна URL-адреса зображення',
    // ============================================
    // Banners Related
    // ============================================
    'viewProduct': 'Переглянути продукт',
    'viewDeal': 'Переглянути угоду',
    'openLink': 'Відкрити посилання',
    'discoverGreatDealsNearby': 'Відкрийте для себе вигідні пропозиції поблизу',
    'stayTunedForOffers': 'Слідкуйте за новими пропозиціями та історіями від перевірених оптовиків.',
    'manageBanners': 'Керування банерами',
    'myBanners': 'Мої банери',
    'noBannersFound': 'Банерів не знайдено. Створіть один!',
    'bannerDetails': 'Деталі банера',
    'bannerNotFound': 'Банер не знайдено',
    'views': 'Перегляди',
    'clicks': 'кліки',
    'bannerRequestSubmitted': 'Запит на банер подано!',
    'failedToSubmitRequest': 'Не вдалося надіслати запит',
    'deleteBanner': 'Видалити банер',
    'deleteBannerConfirm': 'Ви впевнені, що хочете видалити цей банер?',
    'bannerDeleted': 'Банер видалено',
    'bannerUpdated': 'Банер оновлено.',
    'bannerEditSubmittedForApproval': 'Банер оновлено. Зміни будуть розглянуті адміністратором.',
    'failedToDeleteBanner': 'Не вдалося видалити банер',
    'targetId': 'Цільовий ідентифікатор',
    'url': 'URL',
    'createNewBanner': 'Створити новий банер',
    'bannerTitle': 'Заголовок банера',
    'enterBannerTitle': 'Введіть назву банера',
    'bannerImage': 'Зображення банера',
    'webBannerImage': 'Веб-зображення',
    'webBannerImageHint': 'Альбомне/широке співвідношення сторін для Інтернету',
    'mobileBannerImage': 'Мобільний образ',
    'mobileBannerImageHint': 'Портрет/квадрат для попереднього перегляду на мобільному пристрої',
    'mobilePreview': 'Мобільний попередній перегляд',
    'preview': 'Попередній перегляд',
    'previewMobile': 'Попередній перегляд мобільного',
    'previewWillAppearHere': 'Тут з’явиться попередній перегляд',
    'pasteImageUrlHere': 'Вставте тут URL-адресу зображення',
    'pleaseEnterImageUrlOrSwitch': 'Введіть URL-адресу зображення або перейдіть до Завантажити та виберіть зображення.',
    'pleaseTapChooseImage': 'Натисніть «Вибрати зображення», щоб завантажити зображення банера, або перейдіть на URL-адресу та вставте посилання на зображення.',
    'tapToUploadWebImage': 'Натисніть, щоб завантажити веб-зображення',
    'tapToUploadMobileImage': 'Торкніться, щоб завантажити мобільне зображення',
    'chooseImage': 'Виберіть Зображення',
    'replaceImage': 'Замінити зображення',
    // ============================================
    // Stories Related
    // ============================================
    'createStory': 'Створити історію',
    'storiesFromVerifiedWholesalers': 'Розповіді від перевірених оптовиків',
    'storiesWillAppearHere': 'Історії з’являться тут, коли їх буде додано',
    'selectImageOrVideoForStory': 'Виберіть зображення або відео для своєї історії',
    'post': 'Опублікувати',
    'expiresAt': 'Термін дії закінчується о',
    // ============================================
    // Shipment / Tracking Related
    // ============================================
    'trackingNumber': 'Номер відстеження',
    'carrier': 'Перевізник',
    'trackingUrl': 'URL відстеження',
    'openTrackingLink': 'Відкрити посилання для відстеження',
    'statusTimeline': 'Часова шкала стану',
    // ============================================
    // Account Deletion Related
    // ============================================
    'submitDeletionRequest': 'Надіслати запит на видалення',
    'submitRequest': 'Надіслати запит',
    'reviewProcess': 'Процес огляду',
    'accountDeleted': 'Обліковий запис видалено',
    'whatHappensNext': 'Що буде далі?',
    'submitRequestDescription': 'Введіть адресу електронної пошти, щоб подати запит на видалення облікового запису',
    'reviewProcessDescription': 'Наша команда розгляне ваш запит протягом 24-48 годин. Ви отримаєте електронний лист із підтвердженням, щойно ваш запит буде оброблено.',
    'accountDeletedDescription': 'Ваш обліковий запис і всі пов’язані з ним дані буде остаточно видалено. Цю дію не можна скасувати.',
    'ourTeamReviewsYourRequest': 'Наша команда розглядає ваш запит',
    'reviewDetails': 'Деталі огляду',
    'reviewDetailsDescription': 'Ми перевіряємо ваш обліковий запис і гарантуємо, що всі незавершені замовлення або транзакції завершені, перш ніж продовжити видалення.',
    'yourAccountIsPermanentlyRemoved': 'Ваш обліковий запис видалено назавжди',
    'finalStep': 'Заключний крок',
    'finalStepDescription': 'Після схвалення дані вашого облікового запису буде остаточно видалено з нашої системи. Цю дію не можна скасувати.',
    'importantInformation': 'Важлива інформація',
    'accountDeletionIsPermanent': 'Видалення облікового запису є остаточним і не може бути скасовано',
    'allDataWillBeRemoved': 'Усі ваші дані, замовлення та історія буде видалено назавжди',
    'pendingOrdersMustBeCompleted': 'Замовлення, що очікують на розгляд, мають бути завершені, перш ніж можна буде продовжити видалення',
    'youllReceiveEmailConfirmation': 'Після завершення процесу ви отримаєте електронний лист із підтвердженням',
    'confirmActionPermanent': 'Підтвердьте, що ви розумієте, що ця дія є постійною',
    'requestSubmitted': 'Запит надіслано',
    'deletionRequestSubmittedMessage': 'Ваш запит на видалення облікового запису успішно надіслано. Наша команда розгляне його протягом 24-48 годин. Ви отримаєте електронний лист із підтвердженням, коли ваш запит буде оброблено.',
    'ok': 'добре',
    'failedToSubmitDeletionRequest': 'Не вдалося надіслати запит на видалення. Спробуйте ще раз.',
    'requestAccountDeletion': 'Запит на видалення облікового запису',
    'sorryToSeeYouGo': 'Нам шкода, що ви йдете',
    'emailAddress': 'Адреса електронної пошти',
    'enterRegisteredEmail': 'Введіть зареєстровану електронну адресу',
    'emailAddressRequired': 'Необхідно вказати адресу електронної пошти',
    'pleaseEnterValidEmail': 'Введіть дійсну електронну адресу',
    'reasonForDeletionOptional': 'Причина видалення (необов’язково)',
    'helpUsImproveLeaving': 'Допоможіть нам покращитися, поділившись, чому ви йдете...',
    'understandActionPermanent': 'Я розумію, що ця дія є постійною та не може бути скасована',
    // ============================================
    // Support / Help Related
    // ============================================
    'emailSupport': 'Підтримка електронною поштою',
    'getHelpViaEmail': 'Отримати допомогу електронною поштою',
    'phoneSupport': 'Підтримка по телефону',
    'callUsDuringBusinessHours': 'Телефонуйте нам в робочий час',
    'liveChat': 'Живий чат',
    'chatWithUs': 'Спілкуйтеся з нами',
    'chatWithSupportTeam': 'Поспілкуйтеся з нашою командою підтримки',
    'commonIssues': 'Загальні питання',
    'orderNotShowingUp': 'Замовлення не відображається',
    'orderNotShowingUpSolution': 'Оновіть інформаційну панель або перевірте історію замовлень у «Моїх замовленнях»',
    'liveChatComingSoon': 'Чат у прямому ефірі незабаром!',
    'needHelpContactSupport': 'Потрібна допомога? Зверніться до служби підтримки',
    'contactSupportAt': 'Зверніться до служби підтримки за адресою',
    'getInTouch': 'Зв\'яжіться з нами',
    'wereHereToHelp': 'Ми тут, щоб допомогти вам',
    'businessEmail': 'Ділова електронна пошта',
    'contactUsOnWhatsApp': 'Зв\'яжіться з нами через WhatsApp',
    'helloNeedAssistance': 'Привіт! Мені потрібна допомога.',
    'myDetails': 'Мої дані:',
    'nameLabel': 'Ім\'я:',
    'phoneLabel': 'телефон:',
    'emailLabel': 'Електронна пошта:',
    'businessLabel': 'Бізнес:',
    'howCanYouHelpMe': 'Чим ви можете мені допомогти?',
    'unableToOpenWhatsApp': 'Неможливо відкрити WhatsApp. Спробуйте ще раз.',
    'hello': 'Привіт',
    // ============================================
    // Common Validation Related
    // ============================================
    'required': 'Це поле є обов\'язковим для заповнення',
    'invalidEmail': 'Недійсна електронна адреса',
    'passwordTooShort': 'Пароль має бути не менше 6 символів',
    'passwordsDoNotMatch': 'Паролі не збігаються',
    // ============================================
    // Manager / Admin Related
    // ============================================
    'admin': 'адмін',
    'role': 'роль',
    'created': 'Створено',
    'subAdmin': 'Суб-адміністратор',
    'accessDenied': 'Доступ заборонено',
    'managersSectionOnly': 'Цей розділ доступний тільки для менеджерів',
    'totalRevenue': 'Загальний дохід',
    'myRevenue': 'Мій дохід',
    'revenueDetail': 'Відомості про дохід',
    'myRevenueDetail': 'Деталі мого доходу',
    'howCalculated': 'Як розраховується дохід?',
    'productOrdersRevenue': 'Замовлення продуктів (доставлено)',
    'dealOrdersRevenue': 'Замовлення на угоду (доставлено)',
    'totalGrossRevenue': 'Загальний валовий дохід',
    'platformCut': 'Виріз на платформі ({percent}%)',
    'platformCutDescription': 'Ваша частка як адміністратора платформи (1% комісії)',
    'revenueFromDeliveredOrders': 'Дохід від поставлених продуктів і замовлень угоди.',
    'revenueDetailAdminInfo': 'Як адміністратор ви отримуєте 1% комісії з усіх доставлених замовлень (продукт + угода). Власники продукту отримують решту 99%.',
    'revenueDetailOwnerInfo': 'Ваш повний дохід від доставлених замовлень продуктів і замовлень угоди, де ви є власником угоди.',
    'revenueOrdersList': 'Замовлення, що сприяють доходу',
    'noRevenueOrdersYet': 'Ще немає доставлених замовлень',
    'errorLoading': 'Помилка завантаження',
    'activeShops': 'Активні оптовики',
    'activeMembers': 'Активні Магазини / Кіоск',
    'inactiveMembers': 'Неактивні магазини',
    'activeShopsSubtitle': 'Перевірені оптовики на платформі',
    'activeMembersSubtitle': 'Магазини, які нещодавно замовляли',
    'inactiveMembersSubtitle': 'Без замовлення протягом 60+ днів',
    'lastOrder': 'Останнє замовлення',
    'lastActive': 'Останній активний',
    'lastLogin': 'Останній вхід',
    'joined': 'Приєднався',
    'selectToNotify': 'Виберіть, щоб надіслати сповіщення',
    'deselect': 'Зняти вибір',
    'recipients': 'Одержувачі',
    'notificationSent': 'Сповіщення надіслано',
    'notifyDealParticipantsTitle': 'Повідомити учасників угоди',
    'notifyDealParticipantsAudienceWarning':
        'Це повідомлення буде надіслано лише тим користувачам, які розмістили замовлення за цією угодою.',
    'notifyDealParticipantsSendUpdateTooltip': 'Надіслати оновлення',
    'notifyDealParticipantsSending': 'Надсилання...',
    'notifyDealParticipantsNoParticipantsError':
        'Неможливо надіслати: до цієї угоди ще ніхто не приєднався.',
    'notifyDealParticipantsFailedToSend':
        'Не вдалося надіслати повідомлення: {error}',
    'noInactiveMembers': 'Немає неактивних учасників',
    'selectAll': 'Вибрати все',
    'sendNotification': 'Надіслати сповіщення',
    'title': 'Назва',
    'body': 'повідомлення',
    'send': 'Надіслати',
    'generateWithAI': 'Генерувати за допомогою ШІ',
    'generateNotificationPrompt': 'Опишіть сповіщення (наприклад, повторне залучення, швидкий розпродаж, нові продукти), щоб створити назву та повідомлення.',
    'weMissYou': 'ми сумуємо за тобою!',
    'reEngagementDefaultBody': 'Ви давно не робили замовлення. Перегляньте наші останні пропозиції та продукти.',
    'notificationRemindHint': 'наприклад, нагадати неактивним магазинам про наш зимовий розпродаж',
    'searchByNameEmail': 'Пошук за іменем, електронною поштою...',
    'generate': 'Генерувати',
    'page': 'Сторінка',
    'never': 'Ніколи',
    'quickActions': 'Швидкі дії',
    'recentOrders': 'Останні замовлення',
    'noRecentOrders': 'Немає останніх замовлень',
    'analyticsComingSoon': 'Аналітика – незабаром',
    'importCsv': 'Імпортувати з CSV',
    'importFromCsv': 'Імпортувати з CSV',
    'importProductsFromCsv': 'Імпорт продуктів із CSV',
    'importProducts': 'Імпортні продукти',
    'importing': 'Імпорт...',
    'downloadCsvTemplate': 'Завантажити шаблон CSV',
    'getSampleCsvWithColumns': 'Отримайте зразок файлу CSV з усіма необхідними стовпцями',
    'selectCsvFile': 'Виберіть Файл CSV',
    'chooseFile': 'Виберіть Файл',
    'tapToSelectWholesalerForImport': 'Торкніться, щоб вибрати оптового продавця імпортних товарів',
    'importComplete': 'Імпорт завершено',
    'inserted': 'Вставлено',
    'updated': 'Оновлено',
    'skipped': 'Пропущено',
    'fileLabel': 'Файл: {name}',
    'wholesalerRequired': 'Оптовик *',
    'wholesalerLabel': 'Оптовик {id}',
    'csvPreviewRows': 'Попередній перегляд CSV ({n} рядків)',
    'multipleRowsSameProductVariant': 'Кілька рядків з однаковою назвою продукту = кілька варіантів',
    'errorsCount': 'Помилки ({n})',
    'andMoreErrors': '... і ще {n} помилок',
    'failedToReadFileBytes': 'Не вдалося прочитати байти файлу',
    'failedToGetFilePath': 'Не вдалося отримати шлях до файлу',
    'errorPickingFile': 'Помилка вибору файлу: {error}',
    'csvFileEmpty': 'Файл CSV порожній',
    'errorParsingCsv': 'Помилка аналізу CSV: {error}',
    'templateSavedSuccessfully': 'Шаблон успішно збережено',
    'templateDownloadCancelled': 'Завантаження шаблону скасовано',
    'errorGeneratingTemplate': 'Помилка створення шаблону',
    'errors': 'Помилки',
    'viewWholesaler': 'Переглянути оптовик',
    'cropImage': 'Обрізати зображення',
    'change': 'Зміна',
    'navigationError': 'Помилка навігації',
    // ============================================
    // Time Related
    // ============================================
    'hours': 'години',
    'minutes': 'хвилин',
    'seconds': 'секунд',
    'twentyFourHours': '24 години',
    'twelveHours': '12 годин',
    'sixHours': '6 годин',
    // ============================================
    // Navigation / Route Errors
    // ============================================
    'noStoryDataProvided': 'Дані історії не надано.',
    'missingWholesalerId': 'Відсутній ідентифікатор оптовика.',
    'missingProductId': 'Відсутній ідентифікатор товару.',
    'missingCategorySlug': 'Відсутня категорія.',
    'missingDealId': 'Відсутній ідентифікатор угоди.',
    'missingOrderId': 'Відсутній ідентифікатор замовлення.',
    'featuredProducts': 'Рекомендовані продукти',
    // ============================================
    // Order Update / Quantity Change Result
    // ============================================
    'orderUpdate': 'Оновлення замовлення',
    'viewMyOrders': 'Переглянути мої замовлення',
    'goToHome': 'Перейдіть на головну сторінку',
    'quantityChangeAccepted': 'Зміна кількості прийнята',
    'quantityChangeDeclined': 'Зміну кількості відхилено',
    'somethingWentWrong': 'Щось пішло не так',
    'orderUpdatedMessage': 'Ваше замовлення оновлено.',
    'orderRevertedMessage': 'Ваше замовлення повернено до попередньої кількості.',
    'pleaseTryAgainLater': 'Спробуйте пізніше.',
    // ============================================
    // Deal Detail / Deal Errors
    // ============================================
    'unableToLoadDeal': 'Не вдалося завантажити угоду',
    'regularPrice': 'Звичайна ціна',
    'stockLabel': 'Запас',
    'dealNotStarted': 'Ця угода ще не розпочалася',
    'adminWholesalerManageHint': 'Як адміністратор або оптовик ви можете керувати цією угодою, але не можете розміщувати замовлення. Використовуйте кнопку меню (⋮) на панелі програми, щоб редагувати або закрити цю угоду.',
    'adminDealOnlyOwnerCanBid': 'Лише адміністратор (власник угоди) може додавати ставки до угод адміністратора. Kiosk users cannot place orders on this deal.',
    'kioskOnlyPlaceOrders': 'Лише облікові записи кіоску/магазину можуть розміщувати замовлення за цією угодою.',
    'managementView': 'Перегляд керування',
    'ordering': 'Замовлення',
    'failedToLoadDealData': 'Не вдалося завантажити дані угоди',
    'dealClosedSuccess': 'Угода успішно закрита',
    'failedToCloseDeal': 'Не вдалося закрити угоду',
    'onlyAdminCanAddBidsOnAdminDeals': 'Лише адміністратор (власник угоди) може додавати ставки до угод адміністратора.',
    // ============================================
    // Product Search / Detail
    // ============================================
    'searchProducts': 'Пошук продуктів',
    'youCanOnlyReviewFromDeliveredOrders': 'Ви можете переглянути лише товари з доставлених замовлень',
    'allImages': 'Всі зображення',
    'contentGeneratedSuccessfully': 'Контент створено успішно! Перевірте категорію та інші поля.',
    'generationFailed': 'Помилка генерації',
    'userIdRequired': 'Необхідний ідентифікатор користувача',
    // ============================================
    // Admin Banner Management
    // ============================================
    'adminBannerManagement': 'Керування банерами адміністратора',
    'requests': 'Запити',
    'active': 'Активний',
    'noBannersFoundShort': 'Банерів не знайдено.',
    'failedToUpdateBanner': 'Не вдалося оновити банер',
    'bannerSubmittedSuccessfully': 'Банер успішно надіслано',
    'failedToCreateBanner': 'Не вдалося створити банер',
    'failedToSubmitBannerRequest': 'Не вдалося надіслати запит на банер',
    // ============================================
    // User Management / Admin
    // ============================================
    'administratorsOnlySection': 'Цей розділ доступний лише для адміністраторів',
    'allRoles': 'Усі ролі',
    'allStatuses': 'Всі статуси',
    'suspended': 'Підвішено',
    'noUsersFound': 'Користувачів не знайдено',
    'pageOf': 'Сторінка',
    'ofLabel': 'з',
    'noDocumentsAvailable': 'Немає документів',
    'userUpdatedSuccessfully': 'Користувача успішно оновлено',
    'userCreatedSuccessfully': 'Користувача створено успішно',
    'userDeletedSuccessfully': 'Користувача успішно видалено',
    'deleteUser': 'Видалити користувача',
    'deleteUserConfirm': 'Ви впевнені, що хочете видалити {name}? Цю дію не можна скасувати.',
    'verificationDocuments': 'Перевірка документів',
    'noVerificationDocumentsYet': 'Документів підтвердження ще не завантажено.',
    'rejectionReason': 'Причина відмови:',
    'createUser': 'Створити користувача',
    'editUser': 'Редагувати користувача',
    'updateUser': 'Оновити користувача',
    'roleRequired': 'Потрібна роль',
    'statusRequired': 'Необхідний статус',
    'newPasswordLeaveEmpty': 'Новий пароль (залиште порожнім, щоб зберегти поточний)',
    'passwordRequired': 'Необхідно ввести пароль',
    'passwordMinLength': 'Пароль має бути не менше 6 символів',
    'needInfo': 'Потрібна інформація',
    'business': 'Бізнес',
    'searchByNameEmailPhone': 'Пошук за іменем, електронною поштою, телефоном...',
    'daysAgo': 'день (днів) тому',
    'activeDaysLast14': 'Активні дні (останні 14)',
    'docsCount': '{count} документів',
    'noPassportDocuments': 'Без паспортних документів',
    'noGewerbescheinDocuments': 'Немає документів Gewerbeschein',
    'noBusinessLicenseDocuments': 'Немає ліцензійних документів на підприємницьку діяльність',
    'documentN': 'Документ {n}',
    'openInBrowser': 'Відкрити в браузері',
    'pdfDocument': 'PDF-документ',
    'kiosk': 'Кіоск',
    // ============================================
    // Order Management (Deal Orders)
    // ============================================
    'errorLoadingOrders': 'Помилка завантаження замовлень',
    'errorLoadingDeals': 'Помилка завантаження угод',
    'orderManagement': 'Управління замовленнями',
    'orderCountSuffix': 'порядок',
    'confirmOrder': 'Підтвердити замовлення',
    'confirmOrderMessage': 'Ви впевнені, що хочете підтвердити це замовлення?',
    'confirm': 'Підтвердити',
    'markAsDelivered': 'Позначити як доставлене',
    'markDelivered': 'Позначте як доставлено',
    'cancelOrder': 'Скасувати замовлення',
    'cancelOrderConfirm': 'Ви впевнені, що бажаєте скасувати це замовлення?',
    'no': 'немає',
    'reduceQuantity': 'Зменшіть кількість',
    'orderConfirmedSuccess': 'Замовлення успішно підтверджено',
    'orderMarkedDelivered': 'Замовлення позначено як доставлене',
    'failedToConfirmOrder': 'Не вдалося підтвердити замовлення',
    'failedToMarkDelivered': 'Не вдалося позначити як доставлене',
    'orderCancelled': 'Замовлення скасовано',
    'failedToCancelOrder': 'Не вдалося скасувати замовлення',
    'orderMarkedPaid': 'Замовлення позначено як оплачене',
    'failedToMarkOrderPaid': 'Не вдалося позначити замовлення як оплачене',
    'quantityUpdatedSuccess': 'Кількість успішно оновлено',
    'failedToUpdateQuantity': 'Не вдалося оновити кількість',
    'deliveryNotesOptional': 'Накладні на доставку (необов\'язково)',
    'newQuantity': 'Нова кількість',
    'reduceQuantityHint': 'Введіть нову кількість. Мінімум – 1 (або мінімальна кількість замовлення в угоді). Використовуйте 0, щоб скасувати це замовлення.',
    'quantityUpdatedTo': 'Кількість оновлено до',
    // ============================================
    // Deal Order Form
    // ============================================
    'enterQuantity': 'Введіть кількість',
    'pleaseEnterQuantity': 'Будь ласка, введіть кількість',
    'invalidQuantity': 'Недійсна кількість',
    'minimumOrderIs': 'Мінімальне замовлення становить',
    'maximumOrderIs': 'Максимальне замовлення становить',
    'addSpecialInstructions': 'Додайте спеціальні інструкції...',
    'minQuantityLabel': 'Хв',
    'selectedLabel': 'Вибране',
    'maxQuantityLabel': 'Макс',
    // ============================================
    // Shipment / Carrier
    // ============================================
    'pleaseSelectCarrier': 'Виберіть оператора',
    'pleaseEnterCarrierNameForOther': 'Будь ласка, введіть назву оператора для "Інше"',
    'shipmentCreatedSuccess': 'Відправлення створено успішно',
    'shipmentCreatedAndOrderShipped': 'Відправлення створено, а замовлення позначено як відправлене',
    'failedToCreateShipment': 'Не вдалося створити відправлення',
    // ============================================
    // Stories
    // ============================================
    'failedToPickMedia': 'Не вдалося вибрати медіа',
    'onlyWholesalersCanCreateStories': 'Тільки оптовики можуть створювати історії',
    'storyCreatedSuccess': 'Історія успішно створена! 🎉',
    'failedToCreateStory': 'Не вдалося створити історію',
    // ============================================
    // Payment
    // ============================================
    'paymentCompletedSuccess': 'Оплата успішно завершена!',
    'paymentFailed': 'Платіж не вдалося',
    // ============================================
    // Notifications
    // ============================================
    'notifications': 'Сповіщення',
    'markAllAsRead': 'Позначити все як прочитане',
    'deleteAll': 'Видалити все',
    'filterNotifications': 'Фільтр сповіщень',
    'unread': 'Непрочитаний',
    'read': 'Прочитайте',
    'deleteAllNotificationsConfirm': 'Видалити всі сповіщення?',
    'deleteAllNotificationsMessage': 'Ви впевнені, що хочете видалити всі сповіщення? Цю дію не можна скасувати.',
    'deleteAllNotificationsSuccess': 'Усі сповіщення видалено',
    'markedAllAsRead': 'Усі позначено як прочитані',
    // ============================================
    // Deal / Product Modals
    // ============================================
    'paymentEmailTemplateGenerated': 'Створено платіжний електронний лист',
    'aiGenerationFailed': 'Генерація ШІ не вдалася',
    'dealUpdatedSuccess': 'Угоду успішно оновлено',
    'allowOnlinePayment': 'Дозволити оплату онлайн',
    'allowOnlinePaymentSubtitle': 'Якщо не позначено, клієнти можуть лише розміщувати замовлення; оплата (наприклад, банківський переказ) запитується після підтвердження замовлення.',
    'paymentAndEmail': 'Оплата та електронна пошта',
    'generating': 'Створення…',
    'enterDealDescriptionPrompt': 'Введіть чіткий опис вашої угоди, щоб автоматично створювати вміст.',
    'dealDescriptionHint': 'наприклад, швидкий розпродаж: знижка 50% на всі зимові куртки',
    'enterProductDescriptionPrompt': 'Введіть опис або деталі продукту, щоб автоматично створити вміст.',
    'productDescriptionHint': 'Наприклад, шкіряне офісне крісло преміум-класу з ергономічним дизайном...',
    'optionalAutoAssigned': 'Необов’язково – буде автоматично призначено, якщо пусте',
    'defaultYourAccount': 'За умовчанням: ваш обліковий запис (натисніть, щоб змінити)',
    'currentUserYou': 'Поточний користувач (Ви)',
    'loadingProductDetails': 'Завантаження деталей продукту...',
    'loading': 'Завантаження...',
    'ibanBankAccount': 'IBAN / банківський рахунок',
    'accountOwner': 'Власник облікового запису',
    'referenceTemplate': 'Довідковий шаблон (наприклад, DEAL-{dealCode}-{buyerId})',
    'paymentInstructions': 'Платіжні інструкції (вільний текст)',
    'paymentEmailSubject': 'Тема платіжного листа',
    'paymentEmailBody': 'Тіло платіжної електронної пошти (заповнювачі: {dealTitle}, {amount}, {accountOwner}, {iban}, {reference}, {additionalInstructions})',
    'ended': 'Завершено',
    'dealEnded': 'Угода завершена',
    'dealHasEnded': 'Угода закінчилася',
    'endingSoon': 'Скоро кінець!',
    'endsIn1Day': 'Закінчується через 1 день',
    'endsInDays': 'Закінчується через {n} днів',
    'endsIn1Hour': 'Закінчується через 1 годину',
    'endsInHours': 'Закінчується через {n} год',
    'endsSoon': 'Скоро закінчиться',
    'categories': 'Категорії',
    'itemsCount': '{n} предметів',
    // ============================================
    // Shipment Tracking
    // ============================================
    'pleaseEnterTrackingNumber': 'Будь ласка, введіть номер відстеження',
    'pleaseSelectAtLeastOneItemToShip': 'Виберіть принаймні один товар для відправки',
    'pleaseEnterTrackingUrlForOther': 'Введіть URL-адресу відстеження для "Іншого" оператора',
    'selectItemsToShip': 'Виберіть Товари для доставки',
    'noItemsAvailableForShipment': 'Немає товарів, доступних для відправки',
    'selectCarrier': 'Виберіть перевізника',
    'selectCarrierHint': 'Виберіть оператора...',
    'carrierName': 'Назва оператора',
    'enterCarrierName': 'Введіть назву оператора',
    'trackingNumberRequired': 'Потрібно ввести номер відстеження',
    'enterTrackingNumber': 'Введіть номер відстеження',
    'trackingUrlAutoGenerated': 'URL відстеження буде створено автоматично',
    'trackingUrlRequiredForOther': 'URL-адреса відстеження необхідна для "Іншого" оператора',
    'pleaseEnterValidUrl': 'Введіть дійсну URL-адресу',
    'estimatedDeliveryDate': 'Орієнтовна дата доставки',
    'selectDate': 'Виберіть дату',
    'internalNotesShipment': 'Внутрішні примітки щодо цього відправлення',
    'trackingUrlHintAuto': 'Автоматично генерується, коли надається оператор і номер відстеження',
    'trackShipment': 'Відстежити відправлення',
    'trackShipmentHint': 'Відстежуйте своє відправлення за допомогою наданого номера відстеження',
    'trackingDetails': 'Деталі відстеження',
    'shipmentNotFound': 'Відправлення не знайдено',
    'pleaseCheckTrackingNumber': 'Перевірте номер відстеження та повторіть спробу',
    'noNotifications': 'Немає повідомлень',
    'youreAllCaughtUp': '',
    // ============================================
    // Select Deal / Category
    // ============================================
    // ============================================
    // Feature audit – previously hardcoded strings
    // ============================================
    'platformMobile': 'Мобільний',
    'platformWeb': 'Інтернет',
    'pleaseWait': 'Будь ласка, зачекайте...',
    'defaultVariant': 'За замовчуванням',
    'trackOnCarrierWebsite': 'Відстежуйте на веб-сайті перевізника',
    'minOrderQtyRequired': 'Мінімальна кількість замовлення *',
    'dealPriceRequired': 'Ціна угоди *',
    'targetQuantityRequired': 'Цільова кількість *',
    'baseShippingCostEur': 'Базова вартість доставки (€)',
    'freeShippingThresholdQuantity': 'Поріг безкоштовної доставки (кількість)',
    'perUnitShippingCostEur': 'Вартість доставки за одиницю (€)',
    'descriptionOptional': 'Опис (необов\'язково)',
    'enterBannerDescription': 'Введіть опис банера',
    'bannerType': 'Тип банера',
    'targetUrl': 'Цільова URL-адреса',
    'skuRequired': 'Артикул *',
    'productToPromoteHint': 'продукт для просування',
    'selectDealToPromote': 'Виберіть угоду для просування',
    'titleOptional': 'Назва (необов\'язково)',
    'giveReviewTitle': 'Дайте своєму відгуку назву',
    'yourReviewOptional': 'Ваш відгук (необов\'язково)',
    'shareExperienceWithProduct': 'Поділіться своїм досвідом використання цього продукту',
    'dealUpdatedSuccessfully': 'Угоду успішно оновлено',
    'dealPriceMustBeValidNumber': 'Ціна угоди має бути дійсним числом',
    'pleaseEnterMinOrderQuantity': 'Будь ласка, введіть мінімальну кількість замовлення',
    'paymentEmailPlaceholdersSubject': 'Заповнювачі: {dealTitle}, {amount}, {reference}',
    'paymentEmailPlaceholdersBody': 'Заповнювачі: {dealTitle}, {amount}, {accountOwner}, {iban}, {reference}, {additionalInstructions}',
    'failed': 'Не вдалося',
    // ============================================
    // Order status (product orders – display only)
    // ============================================
    'orderStatusPendingConfirmation': 'Очікує підтвердження',
    'orderStatusConfirmed': 'Підтверджено',
    'orderStatusPacking': 'Упаковка',
    'orderStatusDispatched': 'Відправлено',
    'orderStatusOutForDelivery': 'На доставку',
    'orderStatusDelivered': 'Доставлено',
    'orderStatusCancelled': 'Скасовано',
    'orderStatusReturned': 'Повернувся',
    'orderStatusRefunded': 'Повернено',
    // ============================================
    // Notifications (backend localization keys)
    // ============================================
    'notificationProductApprovalNeededTitle': 'Новий продукт очікує на затвердження',
    'notificationProductApprovalNeededBody': '{0} створив новий продукт: {1}',
    'notificationProductStatusUpdatedTitle': 'Статус продукту оновлено',
    'notificationProductApprovedBody': 'Ваш продукт "{0}" схвалено!',
    'notificationProductRejectedBody': 'Ваш продукт "{0}" відхилено.',
    'notificationProductPendingBody': 'Ваш продукт "{0}" очікує на затвердження.',
    'notificationProductStatusChangedBody': 'Статус вашого продукту "{0}" змінено на {1}',
    'notificationNewProductOrderTitle': 'Нове замовлення на ваші продукти',
    'notificationNewProductOrderBody': '{0} розмістив замовлення на {1} одиницю(ів) із {2}',
    'notificationNewDealOrderTitle': 'Нове замовлення на вашу угоду',
    'notificationNewDealOrderBody': '{0} розмістив замовлення на {1} одиниць',
    'notificationPaymentReportedTitle': 'Покупець повідомив про оплату',
    'notificationPaymentReportedBody': '{0} повідомив про оплату замовлення. Подробиці: {1}',
    'notificationDealPaymentReportedBody': '{0} повідомив про оплату замовлення угоди. Подробиці: {1}',
    'notificationDealOrderStatusUpdatedTitle': 'Статус замовлення на угоду оновлено',
    'notificationDealOrderConfirmedBody': 'Ваше замовлення на "{0}" підтверджено!',
    'notificationDealOrderShippedBody': 'Ваше замовлення на "{0}" відправлено!',
    'notificationDealOrderDeliveredBody': 'Ваше замовлення на "{0}" доставлено!',
    'notificationDealOrderCancelledBody': 'Ваше замовлення на "{0}" скасовано.',
    'notificationDealOrderRefundedBody': 'Ваше замовлення на "{0}" було відшкодовано.',
    'notificationDealOrderPendingBody': 'Ваше замовлення на "{0}" очікує на підтвердження.',
    'notificationDealOrderStatusChangedBody': 'Статус вашого замовлення на "{0}" змінено на {1}',
    'notificationOrderQuantityUpdatedTitle': 'Кількість замовлення оновлено',
    'notificationDealOrderQuantityCancelledBody': 'Ваше замовлення на "{0}" (було {1} одиниць) було скасовано продавцем.',
    'notificationDealOrderQuantityChangedBody': 'Ваше замовлення на "{0}" було оновлено: продавець змінив кількість одиниць з {1} на {2}.',
    'notificationQuantityChangeDeclinedTitle': 'Зміну кількості відхилено',
    'notificationQuantityChangeDeclinedBody': '{0} відхилив зміну кількості. Порядок повернуто з {1} до {2} одиниць.',
    'notificationDealNowLiveTitle': 'Нова угода доступна',
    'notificationDealNowLiveBody': '"{0}" зараз доступний. Розмістіть замовлення до завершення угоди.',
    'notificationDealTarget70PercentTitle': 'Майже справа',
    'notificationDealTarget70PercentBody': '"{0}" заповнено на {1}%! Приєднуйтесь до інших роздрібних торговців і допоможіть власнику угоди досягти своєї мети – це зміцнить ваші стосунки та продемонструє вашу відданість партнерству.',
    'notificationDealEnding24hTitle': 'Угода скоро закінчується',
    'notificationDealEnding24hBody': 'Останні 24 години! "{0}" – для закриття цієї угоди залишилося лише {1} замовлень.',
    'notificationDealEnding7dTitle': 'Угода закінчується через 7 днів',
    'notificationDealEnding7dBody': '"{0}" – для закриття цієї угоди залишилося лише {1} замовлень.',
    'notificationDealSuccessTitle': 'Угода успішно виконана',
    'notificationDealSuccessBody': 'Ваша групова угода "{0}" досягла необхідної кількості та тепер підтверджена. Будь ласка, підготуйтеся до оплати та відправлення відповідно до інструкцій від оптовика.',
    'notificationDealClosedTitle': 'Угоду закрито',
    'notificationDealClosedBody': 'Угоду "{0}" закрито. Він більше не відображатиметься в активних угодах.',
    'deal_closed_title': 'Угоду закрито!',
    'deal_closed_body':
        'Угоду «{0}» офіційно закрито. Дякуємо за участь!',
    'notificationOrderStatusUpdatedTitle': 'Статус замовлення оновлено',
    'notificationOrderConfirmedBody': 'Ваше замовлення на "{0}" підтверджено!',
    'notificationOrderDispatchedBody': 'Ваше замовлення на "{0}" відправлено!',
    'notificationOrderDeliveredBody': 'Ваше замовлення на "{0}" доставлено!',
    'notificationOrderCancelledBody': 'Ваше замовлення на "{0}" скасовано.',
    'notificationOrderPackingBody': 'Ваше замовлення на "{0}" упаковується!',
    'notificationOrderOutForDeliveryBody': 'Ваше замовлення на "{0}" готове до доставки!',
    'notificationOrderReturnedBody': 'Ваше замовлення на "{0}" повернуто.',
    'notificationOrderRefundedBody': 'Ваше замовлення на "{0}" було відшкодовано.',
    'notificationOrderStatusChangedBody': 'Статус вашого замовлення для "{0}" змінено на {1}',
    'notificationOrderItemRemovedBody': 'Товар вашого замовлення "{0}" (було {1} одиниць) був видалений продавцем.',
    'notificationOrderItemQuantityChangedBody': 'Позицію вашого замовлення "{0}" було оновлено: продавець змінив кількість одиниць з {1} на {2}.',
    'notificationProductQuantityChangeDeclinedBody': '{0} відхилив зміну кількості позиції замовлення. Повернуто з {1} до {2} одиниць.',
    'notificationDailyEngagementTitle': '',
    'notificationDailyEngagementBody': 'Сьогодні: {0} банерів, {1} угод, {2} рекомендованих продуктів. Перевірте додаток на наявність пропозицій.',
    'notificationInactiveMembersAlertTitle': 'Сповіщення про неактивних учасників',
    'notificationInactiveMembersAlertBody': '',
    'notificationBulkImportCompletedTitle': 'Масове імпортування завершено',
    'notificationBulkImportCompletedBody': 'Успішно імпортовано {0} продуктів. {1} пропущено.',
    'notificationBannerApprovalNeededTitle': 'Новий банер очікує на затвердження',
    'notificationBannerApprovalNeededBody': '{0} подав запит на схвалення банера: {1}',
    'notificationNewUserRegistrationTitle': 'Реєстрація нового користувача',
    'notificationNewUserRegistrationBody': '{0} ({1}) зареєстровано як {2}. Очікує затвердження.',
    'notificationBannerStatusChangedTitle': 'Статус банера змінено',
    'notificationBannerApprovedBody': 'Ваш банер "{0}" схвалено та тепер активний!',
    'notificationBannerRejectedBody': 'Ваш банер "{0}" відхилено. Будь ласка, перегляньте та надішліть повторно, якщо потрібно.',
    'notificationBannerDeactivatedBody': 'Ваш банер "{0}" дезактивовано.',
    'notificationBannerStatusChangedBody': 'Статус вашого банера "{0}" змінено на {1}',
    'notificationAdminCustomTitle': '{0}',
    'notificationAdminCustomBody': '{0}',
    'kioskShopRole': 'Кіоск / Магазин',
  };
}