class UrduFile {
  static const Map<String, String> urduTranslations = {
    // ============================================
    // Options Screen Related
    // ============================================
    'options': 'اختیارات',
    'account': 'اکاؤنٹ',
    'myOrders': 'میرے احکامات',
    'myOrdersSubtitle': 'اپنے آرڈرز کو دیکھیں اور ٹریک کریں۔',
    'statistics': 'شماریات',
    'statisticsSubtitle': 'اپنے معاہدے میں شرکت کے اعدادوشمار دیکھیں',
    'profile': 'پروفائل',
    'profileSubtitle': 'اپنے اکاؤنٹ کا نظم کریں۔',
    'management': 'انتظام',
    'manageCategories': 'زمرہ جات کا نظم کریں۔',
    'manageCategoriesSubtitle': 'مصنوعات کے زمرے بنائیں اور ان کا نظم کریں۔',
    'createNewProductSubtitle': 'ایک نیا پروڈکٹ بنائیں',
    'createNewDealSubtitle': 'ایک نیا معاہدہ بنائیں',
    'viewOrdersSubtitle': 'آرڈرز دیکھیں اور ان کا نظم کریں۔',
    'inactiveMembersViewSubtitle': 'حالیہ آرڈرز کے بغیر دکانیں دیکھیں',
    'manageBannersSubtitle': 'ایپ بینرز کا نظم کریں (ایڈمن)',
    'myBannersSubtitle': 'اپنے بینرز کا نظم کریں۔',
    'unableToLoadOptions': 'اختیارات لوڈ کرنے سے قاصر',
    'loggingOut': 'لاگ آؤٹ ہو رہا ہے...',
    'manageUsers': 'صارفین کا نظم کریں۔',
    'manageUsersSubtitle': 'صارف اکاؤنٹس دیکھیں اور ان کا نظم کریں۔',
    'analytics': 'تجزیات',
    'analyticsSubtitle': 'اپنے کاروباری تجزیات دیکھیں',
    'information': 'معلومات',
    'faq': 'اکثر پوچھے گئے سوالات',
    'faqSubtitle': 'اکثر پوچھے گئے سوالات',
    'aboutUs': 'ہمارے بارے میں',
    'aboutUsSubtitle': 'ہمارے پلیٹ فارم کے بارے میں مزید جانیں۔',
    'helpSupport': 'مدد اور تعاون',
    'helpSupportSubtitle': 'مدد حاصل کریں اور مدد سے رابطہ کریں۔',
    'accountActions': 'اکاؤنٹ کے اعمال',
    'deleteAccount': 'اکاؤنٹ حذف کریں۔',
    'deleteAccountSubtitle': 'اپنے اکاؤنٹ کو مستقل طور پر حذف کرنے کی درخواست کریں۔',
    'logout': 'لاگ آؤٹ',
    'logoutSubtitle': 'اپنے اکاؤنٹ سے سائن آؤٹ کریں۔',
    'confirmLogout': 'لاگ آؤٹ کی تصدیق کریں۔',
    'confirmLogoutMessage': 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
    'cancel': 'منسوخ کریں۔',
    'loginAgain': 'دوبارہ لاگ ان کریں۔',
    // ============================================
    // Language Related
    // ============================================
    'language': 'زبان',
    'languageSubtitle': 'ایپ کی زبان تبدیل کریں۔',
    'notificationSettings': 'اطلاعات کی ترتیبات',
    'notificationSettingsSubtitle':
        'منتخب کریں کہ آپ کون سی اطلاعات موصول کرنا چاہتے ہیں۔',
    'notificationChannels': 'چینلز',
    'pushNotifications': 'پش اطلاعات',
    'pushNotificationsSubtitle':
        'اپنے ڈیوائس پر پش اطلاعات موصول کریں۔',
    'emailNotifications': 'ای میل اطلاعات',
    'emailNotificationsSubtitle': 'ای میل کے ذریعے اطلاعات موصول کریں۔',
    'notificationModules': 'زمرے کے لحاظ سے',
    'notificationSettingsSaved': 'اطلاعات کی ترتیبات محفوظ ہو گئیں۔',
    'notificationModuleProducts': 'مصنوعات',
    'notificationModuleProductOrders': 'مصنوعات کے آرڈرز',
    'notificationModuleDeals': 'معاہدے',
    'notificationModuleDealOrders': 'معاہدے کے آرڈرز',
    'notificationModuleBanners': 'بینرز',
    'notificationModuleAdmin': 'ایڈمن',
    'notificationModuleEngagement': 'مشغولیت',
    'notificationModulePayment': 'ادائیگی',
    'push': 'پش',
    'currency': 'کرنسی',
    'currencySubtitle': 'قیمتوں کے لیے کرنسی دکھائیں (ڈیفالٹ: ڈیوائس)',
    'systemDefault': 'سسٹم ڈیفالٹ',
    'syncFxRates': 'FX ریٹس کو سنک کریں۔',
    'syncFxRatesSubtitle': 'ECB سے تازہ ترین شرح مبادلہ حاصل کریں۔',
    'syncFxRatesSuccess': 'FX کی شرحیں کامیابی کے ساتھ اپ ڈیٹ ہو گئیں۔',
    'syncFxRatesFailed': 'FX کی شرحوں کو اپ ڈیٹ نہیں کیا جا سکا۔ کیش شدہ نرخوں کا استعمال۔',
    'changingLanguage': 'زبان بدل رہی ہے...',
    'languageChangeFailed': 'زبان کی ترجیح کی مطابقت پذیری میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
    'failedToChangeLanguage': 'زبان تبدیل کرنے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
    'english': 'انگریزی',
    'german': 'جرمن',
    'turkish': 'ترکی',
    'arabic': 'عربی',
    'urdu': 'اردو',
    'hindi': 'ہندی',
    'russian': 'روسی',
    'sourceLanguageLabel': 'مواد کی زبان',
    'sourceLanguageHint': 'آپ کے داخل کردہ متن کی زبان (دوسری زبانوں میں ترجمہ کی جائے گی)',
    'selectYourLanguage': 'اپنی زبان منتخب کریں',
    'selectYourLanguageSubtitle':
        'ایپ کے لیے زبان منتخب کریں۔ آپ بعد میں ترتیبات میں اسے بدل سکتے ہیں۔',
    'continueButton': 'جاری رکھیں',
    // ============================================
    // Common / General
    // ============================================
    'sessionExpired': 'سیشن ختم ہو گیا۔',
    'sessionExpiredMessage': 'آپ کا سیشن ختم ہو گیا ہے۔ ایپ کا استعمال جاری رکھنے کے لیے براہ کرم دوبارہ لاگ ان کریں۔',
    'comingSoon': 'جلد آرہا ہے۔',
    'retry': 'دوبارہ کوشش کریں۔',
    'error': 'خرابی',
    'errorWithDetail': 'خرابی: {detail}',
    'close': 'بند',
    'save': 'محفوظ کریں۔',
    'done': 'ہو گیا',
    'saving': 'محفوظ کر رہا ہے...',
    'update': 'اپڈیٹ کریں۔',
    'edit': 'ترمیم کریں۔',
    'delete': 'حذف کریں۔',
    'add': 'شامل کریں۔',
    'remove': 'ہٹا دیں۔',
    'select': 'منتخب کریں۔',
    'all': 'تمام',
    'filter': 'فلٹر',
    'type': 'قسم',
    'status': 'حیثیت',
    'unknown': 'نامعلوم',
    // ============================================
    // About Us Related
    // ============================================
    'welcomeToProductDeal': 'پروڈکٹ ڈیل میں خوش آمدید',
    'trustedMarketplace': 'تھوک مصنوعات اور سودوں کے لیے آپ کا بھروسہ مند بازار',
    'ourMission': 'ہمارا مشن',
    'ourMissionContent': 'تھوک فروشوں اور خوردہ فروشوں کو مربوط کرنے کے لیے، ہر سائز کے کاروبار کے لیے بلک خریداری کو قابل رسائی اور موثر بنانا۔',
    'whatWeOffer': 'ہم کیا پیش کرتے ہیں',
    'whatWeOfferContent':
        '• تصدیق شدہ تھوک فروشوں تک رسائی'
        '• خصوصی بلک سودے اور چھوٹ'
        '• ریئل ٹائم انوینٹری ٹریکنگ'
        '• محفوظ آرڈر مینجمنٹ'
        '• مقام کی بنیاد پر مصنوعات کی دریافت',
    'forWholesalers': 'تھوک فروشوں کے لیے',
    'forRetailers': 'خوردہ فروشوں کے لیے',
    'forRetailersContent': 'قریبی تھوک فروشوں سے پروڈکٹس دریافت کریں، بلک ڈیلز میں حصہ لیں، اور اپنے آرڈرز کا مؤثر طریقے سے انتظام کریں۔',
    'forWholesalersContent': 'اپنی مصنوعات کی نمائش کریں، خصوصی سودے بنائیں، آرڈرز کا نظم کریں، اور خوردہ فروشوں کے وسیع نیٹ ورک تک پہنچیں۔',
    // ============================================
    // FAQ Related
    // ============================================
    'frequentlyAskedQuestions': 'اکثر پوچھے گئے سوالات',
    'commonQuestions': 'عام سوالات',
    'faqQuestion1': 'میں آرڈر کیسے کر سکتا ہوں؟',
    'faqAnswer1': 'فعال سودوں یا مصنوعات کو براؤز کریں، اپنی مطلوبہ مقدار کو منتخب کریں، اور "پلیس آرڈر" پر کلک کریں۔ آپ کے آرڈر کا تھوک فروش کے ذریعہ جائزہ لیا جائے گا۔',
    'faqQuestion2': 'ڈیل آرڈرز کیا ہیں؟',
    'faqAnswer2': 'ڈیل آرڈرز بڑی تعداد میں خریداری کے مواقع ہیں جہاں تھوک فروش ہدف کی مقدار تک پہنچنے پر رعایتی قیمتیں پیش کرتے ہیں۔ آپ ایک ہی ڈیل پر متعدد آرڈر دے سکتے ہیں۔',
    'faqQuestion3': 'شپنگ کا انتظام کیسے کیا جاتا ہے؟',
    'faqAnswer3': 'آپ کے آرڈر کی تصدیق کے بعد شپنگ کی تفصیلات براہ راست تھوک فروش کے ساتھ ترتیب دی جاتی ہیں۔ آرڈر کی تصدیق پر رابطہ کی معلومات فراہم کی جائیں گی۔',
    'faqQuestion4': 'کیا میں آرڈر منسوخ کر سکتا ہوں؟',
    'faqAnswer4': 'آپ زیر التواء آرڈرز منسوخ کر سکتے ہیں۔ تھوک فروش کے ذریعہ آرڈر کی تصدیق ہونے کے بعد، تھوک فروش کی شرائط کے مطابق منسوخی کی پالیسیاں لاگو ہوتی ہیں۔',
    'faqQuestion5': 'میں تصدیق شدہ تھوک فروش کیسے بن سکتا ہوں؟',
    'faqAnswer5': 'تصدیق کے لیے ہماری سپورٹ ٹیم سے رابطہ کریں۔ آپ کو کاروباری دستاویزات فراہم کرنے اور تصدیقی عمل کو مکمل کرنے کی ضرورت ہوگی۔',
    'faqQuestion6': 'مصنوعات کو فاصلے کے لحاظ سے کس طرح ترتیب دیا جاتا ہے؟',
    'faqAnswer6': 'مصنوعات آپ کے مقام کی قربت کے لحاظ سے خود بخود ترتیب دی جاتی ہیں۔ درست فاصلے پر مبنی چھانٹی کے لیے اپنے پروفائل میں اپنا مقام شامل کرنا یقینی بنائیں۔',
    'faqQuestion7': 'ادائیگی کے کون سے طریقے قبول کیے جاتے ہیں؟',
    'faqAnswer7': 'ادائیگی کے طریقے تھوک فروش کے لحاظ سے مختلف ہوتے ہیں۔ آرڈر کی تصدیق کے بعد ادائیگی کی تفصیلات پر تبادلہ خیال کیا جاتا ہے۔',
    'faqQuestion8': 'میں اپنا پروفائل کیسے اپ ڈیٹ کروں؟',
    'faqAnswer8': 'ڈیش بورڈ سے اپنے پروفائل پیج پر جائیں، اپنی معلومات کو اپ ڈیٹ کریں، اور محفوظ کریں۔ آپ مختلف مقامات کے لیے متعدد پتے شامل کر سکتے ہیں۔',
    // ============================================
    // Wholesaler Directory Related
    // ============================================
    'couldNotLoadWholesalers': 'ہم ابھی تھوک فروشوں کو لوڈ نہیں کر سکے۔',
    'verifiedPartners': 'تصدیق شدہ شراکت دار',
    'verifiedPartnersDescription': 'تصدیق شدہ شراکت دار',
    'noWholesalersNearYou': 'ابھی تک آپ کے قریب کوئی تھوک فروش نہیں۔ قریبی انوینٹری کو غیر مقفل کرنے کے لیے اپنا مقام اپ ڈیٹ کریں۔',
    // ============================================
    // Dashboard Related
    // ============================================
    'dashboard': 'ڈیش بورڈ',
    'nearbyWholesalers': 'قریبی تھوک فروش',
    'allWholesalers': 'تمام تھوک فروش',
    'noWholesalersFound': 'کوئی تھوک فروش نہیں ملا',
    'errorLoadingWholesalers': 'تھوک فروشوں کو لوڈ کرنے میں خرابی۔',
    'advertiseWithUs': 'ہمارے ساتھ اشتہار دیں۔',
    'boostYourSales': 'اپنی فروخت کو فروغ دیں!',
    'promoteYourProducts': 'یہاں اپنی مصنوعات کی تشہیر کریں اور مزید صارفین تک پہنچیں۔',
    'unableToLoadDashboard': 'ڈیش بورڈ لوڈ کرنے سے قاصر',
    'unableToLoadProduct': 'پروڈکٹ لوڈ کرنے سے قاصر',
    'unableToLoadWholesaler': 'تھوک فروش لوڈ کرنے سے قاصر ہے۔',
    'spotlight': 'اسپاٹ لائٹ',
    'spotlightWholesalersEmpty': 'اسپاٹ لائٹ تھوک فروش یہاں ایک بار دکھائی دیں گے جب بازار میں ہنگامہ آرائی ہوگی۔',
    // ============================================
    // Orders Related
    // ============================================
    'orderId': 'آرڈر کی شناخت',
    'payment': 'ادائیگی',
    'paymentStatus': 'ادائیگی کی حیثیت',
    'placedOn': 'پر رکھا',
    'orderItems': 'آرڈر آئٹمز',
    'createShipment': 'شپمنٹ بنائیں',
    'shippingAddress': 'شپنگ ایڈریس',
    'notes': 'نوٹس',
    'orderNotes': 'آرڈر نوٹس',
    'orderDetails': 'آرڈر کی تفصیلات',
    'unableToLoadOrder': 'آرڈر لوڈ کرنے سے قاصر',
    'updateOrderStatus': 'آرڈر کی حیثیت کو اپ ڈیٹ کریں۔',
    'subtotal': 'ذیلی کل',
    'shipping': 'شپنگ',
    'shippingWithFreeThreshold': 'ترسیل: {amount} ({threshold}+ یونٹس کے لئے مفت)',
    'freeShippingForThreshold': '{threshold}+ یونٹس کے لیے مفت ترسیل',
    'shippingBaseOnly': 'ترسیل: {amount}',
    'shippingWithPerUnit': 'ترسیل: {base} + {perUnit} فی یونٹ',
    'total': 'کل',
    'reasonOptional': 'وجہ (اختیاری)',
    'notesOptional': 'نوٹس (اختیاری)',
    'sku': 'SKU',
    'skuN/A': 'SKU: N/A',
    'trackingAvailable': 'ٹریکنگ دستیاب ہے۔',
    'shipped': 'بھیج دیا گیا۔',
    'shipments': 'شپمنٹس',
    'shipmentId': 'کھیپ {id}',
    'trackingLabel': 'ٹریکنگ: {number}',
    'track': 'ٹریک',
    'couldNotOpenTrackingUrl': 'ٹریکنگ URL نہیں کھول سکا',
    'carrierLabel': 'کیریئر: {name}',
    'estDelivery': 'تخمینہ ترسیل: {date}',
    'shippedAt': 'بھیج دیا گیا: {date}',
    'deliveredAt': 'ڈیلیور کیا گیا: {date}',
    'each': 'ہر ایک',
    'unit': 'یونٹ',
    'noOrdersYet': 'ابھی تک کوئی آرڈر نہیں ہے۔',
    'noOrdersYetMessage': 'اپنا پہلا آرڈر دینے کے لیے پروڈکٹس اور ڈیلز کو براؤز کریں۔',
    'unableToLoadOrders': 'آپ کے آرڈرز لوڈ کرنے سے قاصر',
    'orderPlaced': 'آرڈر دیا گیا۔',
    'confirmed': 'تصدیق شدہ',
    'delivered': 'پہنچایا',
    'pendingOrders': 'زیر التواء احکامات',
    'viewOrders': 'آرڈرز دیکھیں',
    'allOrders': 'تمام احکامات',
    'pendingConfirmation': 'زیر التوا تصدیق',
    'packing': 'پیکنگ',
    'packed': 'پیک',
    'dispatched': 'روانہ کر دیا گیا۔',
    'outForDelivery': 'ڈیلیوری کے لیے باہر',
    'viewDetails': 'تفصیلات دیکھیں',
    'changeOrderStatus': 'آرڈر کی حیثیت کو تبدیل کریں۔',
    'orderStatusUpdatedSuccessfully': 'آرڈر کی حیثیت کامیابی کے ساتھ اپ ڈیٹ ہو گئی۔',
    'orderStatusUpdated': 'آرڈر کی حیثیت کامیابی کے ساتھ اپ ڈیٹ ہو گئی۔',
    'itemStatusUpdatedSuccessfully': 'آئٹم کی حیثیت کامیابی کے ساتھ اپ ڈیٹ ہو گئی۔',
    'itemStatusUpdated': 'آئٹم کی حیثیت کامیابی کے ساتھ اپ ڈیٹ ہو گئی۔',
    'ordersCountSuffix': 'احکامات',
    'order': 'حکم',
    'orderLabel': 'آرڈر',
    'orders': 'احکامات',
    'ordered': 'حکم دیا',
    'dealOrder': 'ڈیل آرڈر',
    'productOrder': 'پروڈکٹ آرڈر',
    'bid': 'بولی۔',
    'itemPlusMore': '{item} + {n} مزید',
    // ============================================
    // Cart Related
    // ============================================
    'yourCart': 'آپ کی ٹوکری',
    'cart': 'ٹوکری',
    'emptyCart': 'آپ کی ٹوکری خالی ہے۔',
    'emptyCartMessage': 'شروع کرنے کے لیے اپنی کارٹ میں پروڈکٹس شامل کریں۔',
    'addProductsToSeeThemHere': 'مصنوعات کو یہاں دیکھنے کے لیے شامل کریں۔',
    'placeOrderCashOnDelivery': 'آرڈر کریں (کیش آن ڈیلیوری)',
    'cashOnDelivery': 'کیش آن ڈیلیوری',
    'paymentMethodCash': 'ڈیلیوری پر ادائیگی',
    'paymentMethodCashDesc': 'ڈیلیوری ملنے پر ادا کریں۔',
    'paymentMethodInvoice': 'انوائس',
    'paymentMethodInvoiceDesc':
        'ہم انوائس بھیجتے ہیں؛ آرڈر کی تصدیق کے بعد شپمنٹ شروع۔',
    'paymentMethodBankTransfer': 'بینک ٹرانسفر',
    'paymentMethodBankTransferDesc':
        'پہلے ادائیگی، پھر شپمنٹ۔ ادائیگی کی ہدایات ای میل سے بھیجی جاتی ہیں۔',
    'paymentMode': 'ادائیگی کا طریقہ',
    'paymentModeSubtitle':
        'آپ کے سودوں کے لیے ڈیفالٹ۔ آپ بعد میں اپنے پروفائل میں اسے تبدیل کر سکتے ہیں۔',
    'paymentModeSubtitleMulti':
        'وہ تمام ادائیگی کے طریقے منتخب کریں جو آپ قبول کرتے ہیں۔ '
        'آپ بعد میں اپنے پروفائل میں اسے تبدیل کر سکتے ہیں۔',
    'paymentSettings': 'ادائیگی کی ترتیبات',
    'paymentSettingsSubtitle':
        'انوائس/بینک ٹرانسفر آرڈرز کے لیے بینک کی تفصیلات۔ '
        'آپ انہیں بعد میں اپنے پروفائل میں اپ ڈیٹ کر سکتے ہیں۔',
    'payWithCard': 'کارڈ سے ادائیگی کریں۔',
    'placeOrderPayNow': 'آرڈر کریں اور ادائیگی کریں۔',
    'paymentAfterOrderConfirmed': 'آپ کے آرڈر کی تصدیق ہونے کے بعد ادائیگی کی درخواست کی جائے گی (جیسے بینک ٹرانسفر)۔',
    'paymentNotAvailable': 'کارڈ کی ادائیگی دستیاب نہیں ہے۔ کیش آن ڈیلیوری آزمائیں۔',
    'paymentCancelled': 'ادائیگی منسوخ کر دی گئی۔',
    'dealSucceededPayNow': 'ڈیل کامیاب ہو گئی - ابھی ادائیگی کریں۔',
    'totalToPay': 'ادا کرنے کے لیے کل',
    'payByInvoice': 'انوائس کے ذریعے ادائیگی کریں۔',
    'payByCard': 'کارڈ کے ذریعے ادائیگی کریں۔',
    'invoiceInstructionsSent': 'ادائیگی کی ہدایات بذریعہ ای میل بھیجی گئیں۔',
    'paymentInstructionsBankOnly': 'ادائیگی کی ہدایات بذریعہ ای میل بھیجی گئیں۔ بینک ٹرانسفر کے ذریعے ادائیگی کریں۔ اگر آپ پہلے ہی ادائیگی کر چکے ہیں، تو ڈیل کا مالک رسید کی تصدیق کرے گا۔',
    'markAsPaid': 'بطور ادا شدہ نشان زد کریں۔',
    'paymentNotesOptional': 'ادائیگی کے نوٹس (جیسے بینک حوالہ)',
    'myDealStats': 'میرے سودے کے اعدادوشمار',
    'dealsJoined': 'سودے شامل ہو گئے۔',
    'totalOrderedQuantity': 'کل مقدار کا حکم دیا',
    'totalOrders': 'کل آرڈرز',
    'placeOrder': 'آرڈر کریں۔',
    'fxDisclaimer': 'FX کی شرح تبدیلی سے مشروط ہے۔ ظاہر کی گئی رقم اشارہ ہے۔',
    'placingOrder': 'آرڈر دے رہا ہے...',
    'orderPlacedSuccessfully': 'آرڈر کامیابی کے ساتھ رکھا گیا!',
    'failedToPlaceOrder': 'آرڈر دینے میں ناکام',
    'onlyKioskCanOrder': 'صرف Kiosk/Shop اکاؤنٹ ہی آرڈر دے سکتے ہیں۔',
    'admins': 'ایڈمنز',
    'subAdmins': 'سب ایڈمنز',
    'wholesalers': 'تھوک فروش',
    'canOnlyViewProducts': 'صرف مصنوعات دیکھ سکتے ہیں۔ صرف Kiosk/Shop اکاؤنٹ ہی آرڈر دے سکتے ہیں۔',
    'addToCart': 'ٹوکری میں شامل کریں۔',
    'addedToCart': '✅ کارٹ میں شامل کر دیا گیا۔',
    'quantity': 'مقدار',
    'unitPrice': 'یونٹ کی قیمت',
    'totalAmount': 'کل رقم',
    'buyer': 'خریدار',
    'items': 'اشیاء',
    // ============================================
    // Registration Related
    // ============================================
    'register': 'رجسٹر کریں۔',
    'createAccount': 'اکاؤنٹ بنائیں',
    'createAccountTitle': 'اکاؤنٹ بنائیں',
    'createAccountSubtitle': 'کیوریٹڈ ہول سیلرز، بڑے سودے اور لاجسٹک سپورٹ کو غیر مقفل کریں۔',
    'fullName': 'پورا نام',
    'email': 'ای میل',
    'workEmail': 'کام کا ای میل',
    'phone': 'فون',
    'password': 'پاس ورڈ',
    'confirmPassword': 'پاس ورڈ کی تصدیق کریں۔',
    'confirmPasswordLabel': 'پاس ورڈ کی تصدیق کریں۔',
    'businessName': 'کاروبار کا نام',
    'country': 'ملک',
    'city': 'شہر',
    'address': 'پتہ',
    'streetAddress': 'گلی کا پتہ',
    'addressWillBeGeocoded': 'کوآرڈینیٹ حاصل کرنے کے لیے پتہ خود بخود جیو کوڈ ہو جائے گا۔',
    'addressSearchHint': 'اپنا پتہ تلاش کریں',
    'placesLookupFailed':
        'سرور سے پتے کی تفصیلات لوڈ نہیں ہو سکیں۔ آپ اپنا پتہ دستی طور پر ٹائپ یا '
        'ترمیم کر سکتے ہیں۔',
    'placesNoAddressResults':
        'کوئی پتہ نہیں ملا۔ کوئی اور تلاش آزمائیں۔',
    'placesAddressSearchConfigError':
        'پتے کی تلاش دستیاب نہیں۔ اپنا نیٹ ورک چیک کریں اور یقینی بنائیں کہ ایپ '
        'صحیح API سرور (API_BASE_URL) استعمال کر رہی ہے۔',
    'placesAddressSearchRequestFailed':
        'پتے کی تلاش ناکام۔ اپنا کنکشن چیک کریں یا بعد میں دوبارہ کوشش کریں۔',
    'getLocation': 'مقام حاصل کریں۔',
    'selectRole': 'کردار منتخب کریں۔',
    'accountType': 'اکاؤنٹ کی قسم',
    'alreadyHaveAccount': 'پہلے سے ہی اکاؤنٹ ہے؟',
    'login': 'لاگ ان',
    'signIn': 'سائن ان کریں۔',
    'registrationReceived': 'رجسٹریشن موصول! اکاؤنٹ کی منظوری کے بعد ہم آپ کو مطلع کریں گے۔',
    'fullNameRequired': 'پورا نام درکار ہے۔',
    'fullNameMinLength': 'مکمل نام کم از کم 3 حروف کا ہونا چاہیے',
    'emailRequired': 'ای میل درکار ہے۔',
    'provideValidEmail': 'ایک درست ای میل فراہم کریں۔',
    'phoneNumberOptional': 'فون نمبر (اختیاری)',
    'enterValidPhoneNumber': 'ایک درست فون نمبر درج کریں۔',
    'kioskShopNameOptional': 'کیوسک / دکان کا نام (اختیاری)',
    'companyName': 'کمپنی کا نام',
    'latitudeOptional': 'عرض البلد (اختیاری)',
    'longitudeOptional': 'طول البلد (اختیاری)',
    'locating': 'تلاش کر رہا ہے...',
    'locatingEllipsis': 'تلاش کر رہا ہے…',
    'useCurrentLocation': 'موجودہ مقام کا استعمال کریں۔',
    'enableLocationServices': 'کوآرڈینیٹس کو آٹو فل کرنے کے لیے لوکیشن سروسز کو فعال کریں۔',
    'enableLocationPermissions': 'کوآرڈینیٹس کو آٹو فل کرنے کے لیے مقام کی اجازتوں کو فعال کریں۔',
    'unableToFetchLocation': 'مقام حاصل کرنے سے قاصر۔ براہ کرم دوبارہ کوشش کریں۔',
    'unableToFetchLocationShort': 'مقام حاصل کرنے سے قاصر۔',
    'pleaseEnterValidLatLng': 'براہ کرم درست عرض البلد اور طول البلد درج کریں۔',
    'createPassword': 'پاس ورڈ بنائیں',
    'minimum8CharactersRequired': 'کم از کم 8 حروف درکار ہیں۔',
    'weVerifyEveryBusiness': 'ہم بازار کو بھروسہ رکھنے کے لیے ہر کاروبار کی دستی طور پر تصدیق کرتے ہیں۔',
    'submitForReview': 'جائزہ لینے کے لیے جمع کرائیں۔',
    'alreadyVerifiedSignIn': 'پہلے سے تصدیق شدہ؟ سائن ان کریں۔',
    'forgotPassword': 'پاس ورڈ بھول گئے؟',
    'welcomeBack': 'دوبارہ خوش آمدید',
    'signInToReach': 'اپنے قریب کے منظور شدہ تھوک فروشوں تک پہنچنے کے لیے سائن ان کریں۔',
    'createKioskOrWholesalerAccount': 'ایک کیوسک یا تھوک فروش اکاؤنٹ بنائیں',
    'accountSubmittedForApproval': 'اکاؤنٹ منظوری کے لیے جمع کرایا گیا۔ منظور ہونے کے بعد ڈیش بورڈ انلاک ہو جائے گا۔',
    'dashboardWillUnlock': 'منظور ہونے کے بعد ڈیش بورڈ انلاک ہو جائے گا۔',
    'pleaseLoginToPlaceOrder': 'براہ کرم آرڈر دینے کے لیے لاگ ان کریں۔',
    // ============================================
    // Legal / Compliance (T&C + GDPR)
    // ============================================
    'legalComplianceTitle': 'قانونی اور تعمیل',
    'termsAndConditionsFullText': 'ایک اکاؤنٹ بنا کر آپ پلیٹ فارم آپریٹر کے ساتھ کاروباری تعلقات میں داخل ہوتے ہیں اور پلیٹ فارم کی شرائط و ضوابط (AGB) سے اتفاق کرتے ہیں۔ یہ شرائط اس بات پر حکومت کرتی ہیں کہ آپ بازار کو کس طرح استعمال کر سکتے ہیں، ڈیلز اور آرڈرز کو کیسے ہینڈل کیا جاتا ہے، اور خریداروں اور تھوک فروشوں پر کون سی ذمہ داریاں لاگو ہوتی ہیں۔ آپ تصدیق کرتے ہیں کہ آپ کی فراہم کردہ تمام معلومات درست ہیں اور یہ کہ آپ پلیٹ فارم کو صرف جائز کاروباری مقاصد کے لیے استعمال کریں گے۔ آپ مزید اس بات سے اتفاق کرتے ہیں کہ تھوک فروش کی طرف سے تصدیق ہو جانے کے بعد یا ڈیل کا ہدف پورا ہونے کے بعد ڈیلز اور آرڈرز پابند ہو سکتے ہیں۔ آپ کے دائرہ اختیار کے لحاظ سے اضافی ملک کے مخصوص ضابطے لاگو ہو سکتے ہیں۔ براہ کرم جاری رکھنے سے پہلے آپریٹر کے اشتراک کردہ مکمل شرائط و ضوابط کا جائزہ لیں۔',
    'scrollToAcceptTerms': 'قبولیت کے چیک باکس کو غیر مقفل کرنے کے لیے شرائط و ضوابط کے آخر تک سکرول کریں۔',
    'scrollToBottom': 'نیچے تک سکرول کریں۔',
    'acceptTermsLabel': 'میں نے شرائط و ضوابط (AGB) کو پڑھ لیا ہے اور قبول کر لیا ہے۔',
    'termsScrollHint': 'قبول کرنے سے پہلے براہ کرم شرائط و ضوابط کے ذریعے سکرول کریں۔',
    'acceptPrivacyLabel': 'میں نے ڈیٹا پرائیویسی / جی ڈی پی آر پالیسی پڑھ لی ہے اور قبول کر لی ہے۔',
    'privacySummaryText': 'آپ کے ڈیٹا پر ہماری پرائیویسی پالیسی کے مطابق اکاؤنٹ مینجمنٹ، آرڈرز، اینالیٹکس اور سیکیورٹی کے لیے کارروائی کی جائے گی۔',
    'mustAcceptAllLegalDocuments': 'براہ کرم تمام قانونی دستاویزات کو قبول کریں اور فریم ورک کنٹریکٹ کی تصدیق کریں۔',
    'mustAcceptTermsAndPrivacy': 'جاری رکھنے کے لیے براہ کرم شرائط و ضوابط اور ڈیٹا کی رازداری / GDPR قبول کریں۔',
    // ============================================
    // Account Approval / Waiting Screen Related
    // ============================================
    'accountApproval': 'اکاؤنٹ کی منظوری',
    'accountApproved': 'اکاؤنٹ منظور ہو گیا!',
    'redirecting': 'ری ڈائریکٹ ہو رہا ہے...',
    'pendingReview': 'زیر التواء جائزہ',
    'needMoreInfo': 'مزید معلومات کی ضرورت ہے۔',
    'wholesalerVerificationMessage': 'شکریہ! اپنے تھوک فروش اکاؤنٹ کو چالو کرنے کے لیے، براہ کرم اپنے کاروباری تصدیقی دستاویزات جمع کرائیں۔ ہمارا منتظم آپ کے اکاؤنٹ کا جائزہ لے گا اور اسے منظور کرے گا۔',
    'buyerVerificationMessage': 'شکریہ! اپنے خریدار اکاؤنٹ کو چالو کرنے کے لیے، براہ کرم اپنے شناختی تصدیقی دستاویزات جمع کروائیں۔ ہمارا منتظم آپ کے اکاؤنٹ کا جائزہ لے گا اور اسے منظور کرے گا۔',
    'generalVerificationMessage': 'شکریہ! اپنے اکاؤنٹ کو چالو کرنے کے لیے، براہ کرم تصدیقی دستاویزات جمع کرائیں۔ ہمارا منتظم آپ کے اکاؤنٹ کا جائزہ لے گا اور اسے منظور کرے گا۔',
    'adminNote': 'ایڈمن نوٹ',
    'uploadVerificationDocument': 'تصدیقی دستاویز اپ لوڈ کریں۔',
    'acceptedDocumentTypes': 'قبول شدہ دستاویز کی اقسام',
    'wholesalerDocumentTypes': 'کاروباری لائسنس، ٹیکس ID، کمپنی کے رجسٹریشن کے دستاویزات (PNG، JPG، PDF)',
    'buyerDocumentTypes': 'شناختی کارڈ، ڈرائیور کا لائسنس، یا حکومت کی طرف سے جاری کردہ کوئی ID (PNG، JPG، PDF)',
    'generalDocumentTypes': 'کاروباری لائسنس، ڈرائیور کا لائسنس، شناختی کارڈ (PNG، JPG، PDF)',
    'selectedDocuments': 'منتخب دستاویزات',
    'addDocuments': 'دستاویزات شامل کریں۔',
    'uploading': 'اپ لوڈ ہو رہا ہے...',
    'uploaded': 'اپ لوڈ کیا گیا',
    'selectFirst': 'پہلے منتخب کریں۔',
    'documentsUploadedSuccessfully': 'دستاویز (دستاویزیں) کامیابی سے اپ لوڈ ہو گئیں۔ ہمارا منتظم آپ کے اکاؤنٹ کی حیثیت کا جائزہ لے گا اور اسے اپ ڈیٹ کرے گا۔',
    'documentUploadedSuccessfully': 'دستاویز کامیابی کے ساتھ اپ لوڈ ہو گئی۔ ہمارا منتظم آپ کے اکاؤنٹ کی حیثیت کا جائزہ لے گا اور اسے اپ ڈیٹ کرے گا۔',
    'failedToPickDocuments': 'دستاویزات لینے میں ناکام',
    'passport': 'پاسپورٹ',
    'passportDescription': 'شناخت کی تصدیق کے لیے اپنا پاسپورٹ اپ لوڈ کریں۔',
    'passportAlternative': 'اگر آپ کے پاس پاسپورٹ نہیں ہے، تو آپ ایڈریس کے ساتھ حکومت سے منظور شدہ شناختی کارڈ اپ لوڈ کر سکتے ہیں (جیسے، ہندوستان میں آدھار، قومی شناخت، وغیرہ)',
    'gewerbeschein': 'Gewerbeschein',
    'idCard': 'شناختی کارڈ',
    'taxId': 'ٹیکس ID',
    'companyRegistration': 'کمپنی کی رجسٹریشن',
    'document': 'دستاویز',
    'gewerbescheinDescription': 'کاروباری تصدیق کے لیے اپنا Gewerbeschein (تجارتی لائسنس) اپ لوڈ کریں۔',
    'gewerbescheinAlternative': 'حکام کی طرف سے جاری کردہ اپنی سرکاری تجارتی لائسنس کی دستاویز اپ لوڈ کریں۔',
    'businessLicense': 'کاروباری لائسنس / Gewerbeschein',
    'businessLicenseDescription': 'کاروباری تصدیق کے لیے اپنا کاروباری لائسنس یا Gewerbeschein اپ لوڈ کریں۔',
    'businessLicenseAlternative': 'اگر آپ کے پاس کاروباری لائسنس نہیں ہے، تو آپ کمپنی کے رجسٹریشن کے دستاویزات، ٹیکس ID، یا کوئی بھی سرکاری کاروباری تصدیقی دستاویز اپ لوڈ کر سکتے ہیں۔',
    'selectDocument': 'دستاویز کو منتخب کریں۔',
    'changeDocument': 'دستاویز تبدیل کریں۔',
    'pleaseSelectAtLeastOneDocument': 'براہ کرم اپ لوڈ کرنے کے لیے کم از کم ایک دستاویز منتخب کریں۔',
    'sendByEmail': 'ای میل کے ذریعے بھیجیں۔',
    'emailOptionDescription': 'متبادل طور پر، آپ اپنے تصدیقی دستاویزات براہ راست ای میل کے ذریعے بھیج سکتے ہیں۔ ہمارا منتظم دستاویزات کی تصدیق کرے گا اور اس کے مطابق آپ کے اکاؤنٹ کی حیثیت کو اپ ڈیٹ کرے گا۔',
    'openEmailToAdmin': 'ایڈمن کو ای میل کھولیں۔',
    'emailDraftOpened': 'ای میل ڈرافٹ کھل گیا۔ براہ کرم اسے مکمل جمع کرانے کے لیے بھیجیں۔ ہمارا منتظم آپ کے دستاویزات کی تصدیق کرے گا اور آپ کے اکاؤنٹ کی حیثیت کو اپ ڈیٹ کرے گا۔',
    'couldNotOpenEmailApp': 'ای میل ایپ نہیں کھول سکی۔ براہ کرم ایک ای میل بھیجیں۔',
    'manually': 'دستی طور پر',
    'failedToOpenEmail': 'ای میل کھولنے میں ناکام',
    'loadingAccountStatus': 'اکاؤنٹ کی صورتحال لوڈ ہو رہی ہے...',
    'errorLoadingStatus': 'صورتحال لوڈ کرنے میں خرابی۔',
    'pleaseReviewAndResubmit': 'براہ کرم اپنے دستاویزات کا جائزہ لیں اور دوبارہ جمع کرائیں۔',
    'useDifferentAccount': 'مختلف اکاؤنٹ استعمال کریں',
    'useDifferentAccountConfirm':
        'کسی مختلف اکاؤنٹ سے لاگ ان یا رجسٹر کرنے کے لیے سائن آؤٹ کریں؟',
    'failedToUpdateStatus': 'قانونی ترتیبات کو اپ ڈیٹ کرنے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
    // ============================================
    // Profile Related
    // ============================================
    'editProfile': 'پروفائل میں ترمیم کریں۔',
    'profileUpdated': 'پروفائل کامیابی کے ساتھ اپ ڈیٹ ہو گیا۔',
    'failedToUpdateProfile': 'پروفائل اپ ڈیٹ کرنے میں ناکام',
    'profileImageUpdated': 'پروفائل تصویر اپ ڈیٹ کر دی گئی۔',
    'failedToUploadImage': 'تصویر اپ لوڈ کرنے میں ناکام',
    'tagline': 'ٹیگ لائن',
    'locations': 'مقامات',
    'addLocation': 'مقام شامل کریں۔',
    'editLocation': 'مقام میں ترمیم کریں۔',
    'deleteLocation': 'مقام حذف کریں۔',
    'latitude': 'عرض بلد',
    'longitude': 'طول البلد',
    'nameIsRequired': 'نام درکار ہے۔',
    'businessNameOptional': 'کاروباری نام (اختیاری)',
    'phoneOptional': 'فون (اختیاری)',
    'addresses': 'پتے',
    'addAddress': 'ایڈریس شامل کریں۔',
    'noAddressesAdded': 'کوئی پتے شامل نہیں کیے گئے۔',
    'addYourFirstAddress': 'شروع کرنے کے لیے اپنا پہلا پتہ شامل کریں۔',
    'editAddress': 'ایڈریس میں ترمیم کریں۔',
    'removeAddress': 'پتہ ہٹا دیں۔',
    'editAddressTitle': 'ایڈریس میں ترمیم کریں۔',
    'addAddressTitle': 'ایڈریس شامل کریں۔',
    'saveChanges': 'تبدیلیاں محفوظ کریں۔',
    'labelExample': 'لیبل (جیسے گھر، دفتر، مین آؤٹ لیٹ)',
    'streetAreaOptional': 'گلی / علاقہ (اختیاری)',
    'countryOptional': 'ملک (اختیاری)',
    'cityOptional': 'شہر (اختیاری)',
    'locationNotUpdating': 'مقام اپ ڈیٹ نہیں ہو رہا ہے۔',
    'locationNotUpdatingSolution': 'پروفائل > پتے پر جائیں اور یقینی بنائیں کہ آپ کے مقام کے نقاط درست ہیں۔',
    // ============================================
    // Deals Related
    // ============================================
    'deals': 'سودے',
    'activeDeals': 'ایکٹو ڈیلز',
    'allDeals': 'تمام سودے',
    'myDeals': 'میری ڈیلز',
    'manageDeals': 'ڈیلز کا نظم کریں۔',
    'noDealsFound': 'کوئی سودے نہیں ملے',
    'selectDeal': 'ڈیل کو منتخب کریں۔',
    'unableToLoadDeals': 'سودے لوڈ کرنے سے قاصر',
    'noDealsAvailable': 'کوئی سودے دستیاب نہیں ہیں۔',
    'noDealsYet': 'ابھی تک کوئی سودے نہیں۔',
    'checkBackLaterForNewDeals': 'نئے سودوں کے لیے بعد میں دوبارہ چیک کریں۔',
    'noActiveDeals': 'کوئی فعال سودے نہیں۔',
    'filterDeals': 'فلٹر ڈیلز',
    'progress': 'پیش رفت',
    'dealClosed': 'ڈیل بند',
    'ends': 'ختم ہوتا ہے۔',
    'variant': 'متغیر',
    'min': 'کم از کم:',
    'max': 'زیادہ سے زیادہ:',
    'perUnit': '/یونٹ',
    'perUnitLabel': 'فی {unit}',
    'inStock': 'اسٹاک میں',
    'similarProducts': 'ملتے جلتے مصنوعات',
    'noActiveDealsForProduct': 'اس پروڈکٹ کے لیے کوئی فعال ڈیلز نہیں ہیں۔',
    'activeDealsForProduct': 'اس پروڈکٹ کے لیے فعال ڈیلز',
    'moreFromWholesaler': '{name} سے مزید',
    'dealsFromWholesaler': '{name} سے ڈیلز',
    'productsFromWholesaler': '{name} سے پروڈکٹس',
    'searchProductsFromWholesaler': '{name} سے پروڈکٹس تلاش کریں...',
    'onlyKioskCanPurchase': 'صرف Kiosk/Shop اکاؤنٹ ہی مصنوعات خرید سکتے ہیں۔',
    'canOnlyReviewFromDelivered': 'آپ صرف ڈیلیور کردہ آرڈرز سے پروڈکٹس کا جائزہ لے سکتے ہیں۔',
    'alreadyReviewedThisProduct': 'آپ پہلے ہی اس آرڈر سے اس پروڈکٹ کا جائزہ لے چکے ہیں۔',
    'selectOrderToReview': 'جائزہ لینے کے لیے آرڈر کو منتخب کریں۔',
    'orderN': 'آرڈر #{id}',
    'viewDeals': 'سودے دیکھیں',
    'locationInfoNotAvailable': 'مقام کی معلومات دستیاب نہیں ہے۔',
    'location': 'مقام',
    'kfProductDealTagline': 'KF پروڈکٹ ڈیل، بہترین سودے تلاش کرنے میں آپ کی مدد کرنا',
    'errorSearchingProducts': 'مصنوعات کی تلاش میں خرابی۔',
    'myDealOrders': 'میرے ڈیل آرڈرز',
    'noDealOrdersYet': 'ابھی تک کوئی ڈیل آرڈر نہیں ہے۔',
    'browseDealsPlaceFirstOrder': 'فعال ڈیلز کو براؤز کریں اور اپنا پہلا آرڈر دیں۔',
    'statusLabel': 'حیثیت',
    'noProductsFoundForWholesaler': 'منتخب تھوک فروش کے لیے کوئی پروڈکٹس نہیں ملے',
    'noApprovedWholesalersAvailable': 'کوئی منظور شدہ تھوک فروش دستیاب نہیں ہے۔',
    'searchByNameBusinessEmail': 'نام، کاروباری نام، ای میل کے ذریعے تلاش کریں...',
    'selectWholesaler': 'تھوک فروش کو منتخب کریں۔',
    'selectProduct': 'پروڈکٹ کو منتخب کریں۔',
    'pageNOfM': 'صفحہ {current} از {total}',
    'priceLabel': 'قیمت',
    'pleaseSelectImageOrVideo': 'براہ کرم کوئی تصویر یا ویڈیو منتخب کریں۔',
    'onlyWholesalersCreateStories': 'صرف تھوک فروش کہانیاں بنا سکتے ہیں۔',
    'storyCreatedSuccessfully': 'کہانی کامیابی کے ساتھ بنائی گئی! 🎉',
    'uploadingMedia': 'میڈیا اپ لوڈ ہو رہا ہے...',
    'creatingStory': 'کہانی بنائی جا رہی ہے...',
    'storyMedia': 'کہانی میڈیا',
    'videoSelected': 'ویڈیو منتخب کی گئی۔',
    'activeShopsSuffix': 'فعال دکانیں',
    'storiesCountSuffix': 'کہانیاں',
    'create': 'بنائیں',
    'off': 'آف',
    'minOrder': 'کم از کم آرڈر',
    'target': 'ہدف',
    'units': 'یونٹس',
    'dealCreatedSuccessfully': 'ڈیل کامیابی سے بن گئی۔',
    'createDeal': 'ڈیل بنائیں',
    'editDeal': 'ڈیل میں ترمیم کریں۔',
    'closeDeal': 'ڈیل بند کریں۔',
    'closeDealConfirmMessage': 'کیا آپ واقعی اس ڈیل کو بند کرنا چاہتے ہیں؟ اس کارروائی کو کالعدم نہیں کیا جا سکتا۔',
    'closeDealGoalReached': 'منزل تک پہنچ گئی۔',
    'closeDealGoalReachedHint': 'اگر جانچ پڑتال کی گئی ہے: تمام زیر التواء آرڈرز کی خود بخود تصدیق ہو جائے گی (ڈیل کامیابی سے بھر گئی)۔ اگر چیک نہیں کیا گیا تو: ڈیل بند ہو جائے گی لیکن آپ بعد میں دستی طور پر آرڈرز کی تصدیق کر سکتے ہیں۔',
    'createYourFirstDeal': 'اپنی پہلی ڈیل بنائیں',
    'dealTitle': 'ڈیل کا عنوان',
    'pleaseEnterDealTitle': 'براہ کرم ڈیل کا عنوان درج کریں۔',
    'dealType': 'ڈیل کی قسم',
    'dealPrice': 'ڈیل کی قیمت',
    'startDate': 'آغاز کی تاریخ',
    'endDate': 'اختتامی تاریخ',
    'pleaseEnterDealPrice': 'براہ کرم سودے کی قیمت درج کریں۔',
    'originalPrice': 'اصل قیمت',
    'targetQuantity': 'ہدف کی مقدار',
    'pleaseEnterTargetQuantity': 'براہ کرم ہدف کی مقدار درج کریں۔',
    'targetQuantityMin': 'ہدف کی مقدار کم از کم 1 ہونی چاہیے۔',
    'minOrderQty': 'کم از کم آرڈر کی مقدار',
    'pleaseEnterMinOrderQty': 'براہ کرم کم از کم آرڈر کی مقدار درج کریں۔',
    'minOrderQtyMin': 'کم از کم آرڈر کی مقدار کم از کم 1 ہونی چاہیے۔',
    'maxOrderQuantityOptional': 'زیادہ سے زیادہ آرڈر کی مقدار (اختیاری)',
    'endDateMustBeAfterStartDate': 'اختتامی تاریخ شروع ہونے کی تاریخ کے بعد ہونی چاہیے۔',
    'pleaseSelectWholesalerFirst': 'براہ کرم پہلے تھوک فروش کا انتخاب کریں۔',
    'auction': 'نیلامی',
    'priceDrop': 'قیمت میں کمی',
    'limitedStock': 'محدود اسٹاک',
    'scheduled': 'طے شدہ',
    'live': 'جیو',
    'highlightedDeal': 'نمایاں ڈیل',
    'canOnlyViewDeals': 'صرف سودے دیکھ سکتے ہیں۔ صرف Kiosk/Shop اکاؤنٹ ہی آرڈر دے سکتے ہیں۔',
    'dealProgressNotUpdating': 'ڈیل کی پیشرفت اپ ڈیٹ نہیں ہو رہی ہے۔',
    'dealProgressNotUpdatingSolution': 'ڈیل پروگریس اپڈیٹس خود بخود۔ اگر ایسا لگتا ہے کہ یہ پھنس گیا ہے، تو صفحہ ریفریش کریں۔',
    'dealProgress': 'ڈیل کی پیشرفت',
    'unableToLoadProgress': 'پیش رفت لوڈ کرنے سے قاصر: {detail}',
    'noOrdersPlacedYet': 'اس معاہدے پر ابھی تک کوئی آرڈر نہیں دیا گیا ہے۔',
    'orderPlacedSuffix': 'آرڈر دیا',
    'ordersPlacedSuffix': 'احکامات دیے گئے',
    'closed': 'بند',
    // ============================================
    // Products Related
    // ============================================
    'product': 'پروڈکٹ',
    'products': 'مصنوعات',
    'productsSection': 'مصنوعات',
    'allProducts': 'تمام مصنوعات',
    'myProducts': 'میری مصنوعات',
    'noProductsAvailable': 'کوئی پروڈکٹس دستیاب نہیں ہیں۔',
    'noProductsYet': 'ابھی تک کوئی مصنوعات نہیں ہیں۔',
    'addYourFirstProduct': 'اپنا پہلا پروڈکٹ شامل کریں۔',
    'addFirstProduct': 'اپنا پہلا پروڈکٹ شامل کریں۔',
    'addProduct': 'پروڈکٹ شامل کریں۔',
    'editProduct': 'پروڈکٹ میں ترمیم کریں۔',
    'deleteProduct': 'پروڈکٹ کو حذف کریں۔',
    'deletingProduct': 'پروڈکٹ کو حذف کیا جا رہا ہے...',
    'deleteProductConfirmGeneric': 'کیا آپ واقعی اس پروڈکٹ کو حذف کرنا چاہتے ہیں؟ اس کارروائی کو کالعدم نہیں کیا جا سکتا۔',
    'productUpdatedSuccessfully': 'پروڈکٹ کو کامیابی سے اپ ڈیٹ کر دیا گیا۔',
    'productCreatedSuccessfully': 'پروڈکٹ کامیابی کے ساتھ بن گئی۔',
    'productDeletedSuccessfully': 'پروڈکٹ کو کامیابی کے ساتھ حذف کر دیا گیا۔',
    'changeProductStatus': 'مصنوعات کی حیثیت کو تبدیل کریں۔',
    'changeStatus': 'اسٹیٹس کو تبدیل کریں۔',
    'updatingStatus': 'اسٹیٹس کو اپ ڈیٹ کر رہا ہے...',
    'statusUpdatedToPending': 'اسٹیٹس کو زیر التواء میں اپ ڈیٹ کر دیا گیا۔',
    'statusUpdatedToApproved': 'اسٹیٹس کو منظور شدہ پر اپ ڈیٹ کر دیا گیا۔',
    'statusUpdatedToRejected': 'اسٹیٹس کو مسترد کر دیا گیا۔',
    'productsWillAppearHere': 'شامل ہونے کے بعد پروڈکٹس یہاں ظاہر ہوں گے۔',
    'noProductsFound': 'کوئی پروڈکٹس نہیں ملے',
    'youveReachedEnd': 'آپ اختتام کو پہنچ گئے ہیں۔',
    'errorLoadingProducts': 'پروڈکٹس لوڈ کرنے میں خرابی۔',
    'featuredCatalog': 'نمایاں کیٹلاگ',
    'viewAll': 'سبھی دیکھیں',
    'outOfStock': 'اسٹاک سے باہر',
    'onlyLeft': 'صرف',
    'left': 'بائیں',
    'timeRemainingDay': '{count} دن باقی',
    'timeRemainingDays': '{count} دن باقی',
    'timeRemainingHour': '{count} گھنٹہ باقی',
    'timeRemainingHours': '{count} گھنٹے باقی',
    'timeRemainingMinute': '{count} منٹ باقی',
    'timeRemainingMinutes': '{count} منٹ باقی',
    'pleaseSelectProduct': 'براہ کرم ایک پروڈکٹ منتخب کریں۔',
    'tapToSelectProduct': 'پروڈکٹ کو منتخب کرنے کے لیے تھپتھپائیں۔',
    'unknownProduct': 'نامعلوم پروڈکٹ',
    'searchProductsHint': 'نام سے مصنوعات تلاش کریں، SKU...',
    'loadingMoreProducts': 'مزید پروڈکٹس لوڈ ہو رہی ہیں...',
    'reachedEnd': 'آپ اختتام کو پہنچ گئے ہیں۔',
    'productsCountSuffix': 'مصنوعات',
    'price': 'قیمت',
    'kilogram': 'کلوگرام',
    'gram': 'چنے',
    'liter': 'لیٹر',
    'milliliter': 'ملی لیٹر',
    'piece': 'ٹکڑا',
    'box': 'ڈبہ',
    'pack': 'پیک',
    'kmAway': 'کلومیٹر دور',
    'viewAllProducts': 'تمام مصنوعات دیکھیں',
    // ============================================
    // Product Management Related
    // ============================================
    'productTitle': 'پروڈکٹ کا عنوان',
    'productTitleRequired': 'براہ کرم پروڈکٹ کا عنوان درج کریں۔',
    'titleMinLength': 'عنوان کم از کم 3 حروف کا ہونا چاہیے۔',
    'description': 'تفصیل',
    'category': 'زمرہ',
    'wholesaler': 'تھوک فروش',
    'selectCategory': 'زمرہ منتخب کریں۔',
    'selectCategories': 'زمرہ جات منتخب کریں۔',
    'pleaseSelectCategory': 'براہ کرم ایک زمرہ منتخب کریں۔',
    'tapToSelectCategory': 'زمرہ منتخب کرنے کے لیے تھپتھپائیں۔',
    'pleaseSelectWholesaler': 'براہ کرم ایک تھوک فروش منتخب کریں۔',
    'tapToSelectWholesaler': 'تھوک فروش کو منتخب کرنے کے لیے تھپتھپائیں۔',
    'unknownCategory': 'نامعلوم زمرہ',
    'yourAccount': 'آپ کا اکاؤنٹ',
    'currentUser': 'موجودہ صارف',
    'variants': 'متغیرات',
    'useVariants': 'متغیرات کا استعمال کریں۔',
    'addVariant': 'متغیر شامل کریں۔',
    'addAttribute': 'انتساب شامل کریں۔',
    'variantSkuRequired': 'SKU درکار ہے۔',
    'addAtLeastOneVariant': 'براہ کرم کم از کم ایک قسم شامل کریں۔',
    'selectVariant': 'متغیر کو منتخب کریں۔',
    'selectVariantHelper': 'اس ڈیل کے لیے مختلف قسم کا انتخاب کریں۔',
    'noVariantsMessage': 'اس پروڈکٹ کی کوئی قسم نہیں ہے۔ ڈیل براہ راست پروڈکٹ پر بنائی جائے گی۔',
    'unableToLoadVariantsMessage': 'متغیرات لوڈ کرنے سے قاصر۔ پروڈکٹ پر ڈیل کی جائے گی۔',
    'featuredProduct': 'نمایاں مصنوعات',
    'default': 'طے شدہ',
    'updateProduct': 'پروڈکٹ کو اپ ڈیٹ کریں۔',
    'createProduct': 'پروڈکٹ بنائیں',
    'globalAttributes': 'عالمی صفات',
    'globalAttributesDescription': 'تمام قسموں پر لاگو ہونے کے لیے رنگ، سائز جیسی صفات کی وضاحت کریں۔',
    'attributeName': 'انتساب کا نام (مثلاً رنگ)',
    'attributeNameHint': 'رنگ، سائز، مواد...',
    'imageUrl': 'تصویری URL',
    'productImages': 'مصنوعات کی تصاویر',
    'firstImagePrimary': 'پہلی تصویر بنیادی ہے۔',
    'addImageUrl': 'URL شامل کریں۔',
    'pasteImageUrlHint': 'تصویر کا URL چسپاں کریں۔',
    'costPrice': 'لاگت کی قیمت',
    'stock': 'اسٹاک',
    'stockRequired': 'براہ کرم اسٹاک درج کریں۔',
    'stockNegative': 'اسٹاک منفی نہیں ہو سکتا',
    'priceRequired': 'براہ کرم قیمت درج کریں۔',
    'pricePositive': 'قیمت 0 سے زیادہ ہونی چاہیے۔',
    'validationError': 'توثیق کی خرابی۔',
    'checkAllFields': 'براہ کرم تمام فیلڈز کو چیک کریں۔',
    'pending': 'زیر التواء',
    'approved': 'منظور شدہ',
    'rejected': 'مسترد',
    'draft': 'مسودہ',
    'failedToCreateDeal': 'ڈیل بنانے میں ناکام',
    'invalidDateTimeFormat': 'غلط تاریخ/وقت کی شکل۔ براہ کرم اپنی تاریخیں چیک کریں۔',
    // ============================================
    // Categories Related
    // ============================================
    'noCategoriesFound': 'کوئی زمرہ نہیں ملا',
    'noCategoriesAvailable': 'کوئی زمرہ جات دستیاب نہیں ہیں۔',
    'allCategories': 'تمام زمرے',
    'searchCategories': 'زمرے تلاش کریں...',
    'noCategoriesMatchSearch': 'کوئی زمرہ آپ کی تلاش سے مماثل نہیں ہے۔',
    'categoriesWillAppearHere': 'زمرے شامل ہونے کے بعد یہاں ظاہر ہوں گے۔',
    'tryDifferentSearchTerm': 'تلاش کی ایک مختلف اصطلاح آزمائیں۔',
    'errorLoadingCategories': 'زمرے لوڈ کرنے میں خرابی۔',
    'unableToLoadCategory': 'زمرہ لوڈ کرنے سے قاصر',
    'productsCount': '{n} مصنوعات',
    'categoryName': 'زمرہ کا نام',
    'categoryDescription': 'تفصیل',
    'categoryImageUrl': 'تصویری URL',
    'createCategory': 'زمرہ بنائیں',
    'editCategory': 'زمرہ میں ترمیم کریں۔',
    'deleteCategory': 'زمرہ حذف کریں۔',
    'deleteCategoryConfirm': 'کیا آپ واقعی "{name}" کو حذف کرنا چاہتے ہیں؟ اس کارروائی کو کالعدم نہیں کیا جا سکتا۔',
    'categoryCreatedSuccessfully': 'زمرہ کامیابی کے ساتھ بنایا گیا۔',
    'enterCategoryDescriptionToGenerate': 'مواد خود بخود پیدا کرنے کے لیے زمرہ کی تفصیل درج کریں۔',
    'categoryDescriptionHint': 'مثال کے طور پر، نامیاتی سبزیاں...',
    'contentGeneratedSuccessfullyEnglish': 'مواد کامیابی سے تیار ہوا! (انگریزی)',
    'generationFailedWithError': 'جنریشن ناکام ہو گئی: {error}',
    'categoryUpdatedSuccessfully': 'زمرہ کامیابی سے اپ ڈیٹ ہو گیا۔',
    'categoryDeletedSuccessfully': 'زمرہ کامیابی سے حذف ہو گیا۔',
    'categoryCreationImportMessage': 'زمرہ کی تخلیق فی الحال درآمد کے ذریعے کی جاتی ہے۔ براہ کرم ایڈمن سے رابطہ کریں۔',
    'pleaseEnterCategoryName': 'براہ کرم زمرہ کا نام درج کریں۔',
    // ============================================
    // Reviews Related
    // ============================================
    'reviewed': 'جائزہ لیا گیا۔',
    'youHaveAlreadyReviewed': 'آپ پہلے ہی اس آرڈر سے اس پروڈکٹ کا جائزہ لے چکے ہیں۔',
    'reviewUpdatedSuccessfully': 'جائزہ کامیابی کے ساتھ اپ ڈیٹ ہو گیا۔',
    'reviewSubmittedSuccessfully': 'جائزہ کامیابی کے ساتھ جمع ہو گیا۔',
    'pleaseSelectRating': 'براہ کرم ایک درجہ بندی منتخب کریں۔',
    'maximum5ImagesAllowed': 'زیادہ سے زیادہ 5 تصاویر کی اجازت ہے۔',
    'failedToPickImage': 'تصویر چننے میں ناکام',
    'failedToUploadImages': 'تصاویر اپ لوڈ کرنے میں ناکام',
    'uploadImages': 'تصاویر اپ لوڈ کریں۔',
    'pickImage': 'تصویر چنیں۔',
    'pickVideo': 'ویڈیو چنیں۔',
    'uploadFailed': 'اپ لوڈ ناکام ہو گیا۔',
    'upload': 'اپ لوڈ کریں۔',
    'invalidImageUrl': 'غلط تصویر کا URL',
    // ============================================
    // Banners Related
    // ============================================
    'viewProduct': 'پروڈکٹ دیکھیں',
    'viewDeal': 'ڈیل دیکھیں',
    'openLink': 'لنک کھولیں۔',
    'discoverGreatDealsNearby': 'آس پاس کے زبردست سودے دریافت کریں۔',
    'stayTunedForOffers': 'تصدیق شدہ تھوک فروشوں کی نئی پیشکشوں اور کہانیوں کے لیے دیکھتے رہیں۔',
    'manageBanners': 'بینرز کا نظم کریں۔',
    'myBanners': 'میرے بینرز',
    'noBannersFound': 'کوئی بینرز نہیں ملے۔ ایک بنائیں!',
    'bannerDetails': 'بینر کے تفصیلات',
    'bannerNotFound': 'بینر نہیں ملا',
    'views': 'دیکھا',
    'clicks': 'کلک کریں',
    'bannerRequestSubmitted': 'بینر کی درخواست جمع کرائی گئی!',
    'failedToSubmitRequest': 'درخواست جمع کرانے میں ناکام',
    'deleteBanner': 'بینر حذف کریں۔',
    'deleteBannerConfirm': 'کیا آپ واقعی اس بینر کو حذف کرنا چاہتے ہیں؟',
    'bannerDeleted': 'بینر حذف کر دیا گیا۔',
    'failedToDeleteBanner': 'بینر کو حذف کرنے میں ناکام',
    'targetId': 'ٹارگٹ آئی ڈی',
    'url': 'URL',
    'createNewBanner': 'نیا بینر بنائیں',
    'bannerTitle': 'بینر کا عنوان',
    'enterBannerTitle': 'بینر کا عنوان درج کریں۔',
    'bannerImage': 'بینر کی تصویر',
    'webBannerImage': 'ویب تصویر',
    'webBannerImageHint': 'ویب کے لیے لینڈ اسکیپ',
    'mobileBannerImage': 'موبائل تصویر',
    'mobileBannerImageHint': 'موبائل کے لیے پورٹریٹ/مربع',
    'mobilePreview': 'موبائل پیش نظارہ',
    'preview': 'پیش نظارہ',
    'previewMobile': 'موبائل پیش نظارہ',
    'previewWillAppearHere': 'پیش نظارہ یہاں ظاہر ہوگا',
    'pasteImageUrlHere': 'تصویر کا URL یہاں چسپاں کریں۔',
    'pleaseEnterImageUrlOrSwitch': 'براہ کرم ایک تصویری URL درج کریں یا اپ لوڈ پر سوئچ کریں اور ایک تصویر منتخب کریں۔',
    'pleaseTapChooseImage': 'براہ کرم بینر کی تصویر اپ لوڈ کرنے کے لیے "تصویر کا انتخاب کریں" کو تھپتھپائیں، یا URL پر سوئچ کریں اور تصویر کا لنک چسپاں کریں۔',
    'tapToUploadWebImage': 'ویب تصویر اپ لوڈ کرنے کے لیے ٹیپ کریں',
    'tapToUploadMobileImage': 'موبائل تصویر اپ لوڈ کرنے کے لیے ٹیپ کریں',
    'chooseImage': 'تصویر کا انتخاب کریں۔',
    'replaceImage': 'تصویر بدلیں',
    // ============================================
    // Stories Related
    // ============================================
    'createStory': 'کہانی بنائیں',
    'storiesFromVerifiedWholesalers': 'تصدیق شدہ تھوک فروشوں کی کہانیاں',
    'storiesWillAppearHere': 'کہانیاں شامل ہونے کے بعد یہاں ظاہر ہوں گی۔',
    'selectImageOrVideoForStory': 'اپنی کہانی کے لیے ایک تصویر یا ویڈیو منتخب کریں۔',
    'post': 'پوسٹ',
    'expiresAt': 'پر ختم ہو جائے گا۔',
    // ============================================
    // Shipment / Tracking Related
    // ============================================
    'trackingNumber': 'ٹریکنگ نمبر',
    'carrier': 'کیریئر',
    'trackingUrl': 'ٹریکنگ یو آر ایل',
    'openTrackingLink': 'ٹریکنگ لنک کھولیں۔',
    'statusTimeline': 'اسٹیٹس ٹائم لائن',
    // ============================================
    // Account Deletion Related
    // ============================================
    'submitDeletionRequest': 'حذف کرنے کی درخواست جمع کروائیں۔',
    'submitRequest': 'درخواست جمع کروائیں۔',
    'reviewProcess': 'عمل کا جائزہ لیں۔',
    'accountDeleted': 'اکاؤنٹ حذف کر دیا گیا۔',
    'whatHappensNext': 'آگے کیا ہوتا ہے؟',
    'submitRequestDescription': 'اکاؤنٹ حذف کرنے کی درخواست کرنے کے لیے اپنا ای میل ایڈریس درج کریں۔',
    'reviewProcessDescription': 'ہماری ٹیم 24-48 گھنٹوں کے اندر آپ کی درخواست کا جائزہ لے گی۔ آپ کی درخواست پر کارروائی ہونے کے بعد آپ کو ایک تصدیقی ای میل موصول ہوگا۔',
    'accountDeletedDescription': 'آپ کا اکاؤنٹ اور تمام متعلقہ ڈیٹا مستقل طور پر حذف کر دیا جائے گا۔ اس کارروائی کو کالعدم نہیں کیا جا سکتا۔',
    'ourTeamReviewsYourRequest': 'ہماری ٹیم آپ کی درخواست کا جائزہ لے رہی ہے۔',
    'reviewDetails': 'تفصیلات کا جائزہ لیں۔',
    'reviewDetailsDescription': 'ہم آپ کے اکاؤنٹ کی تصدیق کرتے ہیں اور اس بات کو یقینی بناتے ہیں کہ تمام زیر التواء آرڈرز یا لین دین کو حذف کرنے سے پہلے مکمل کر لیا گیا ہے۔',
    'yourAccountIsPermanentlyRemoved': 'آپ کا اکاؤنٹ مستقل طور پر ہٹا دیا گیا ہے۔',
    'finalStep': 'آخری مرحلہ',
    'finalStepDescription': 'منظوری کے بعد، آپ کے اکاؤنٹ کا ڈیٹا ہمارے سسٹم سے مستقل طور پر حذف کر دیا جائے گا۔ اس کارروائی کو کالعدم نہیں کیا جا سکتا۔',
    'importantInformation': 'اہم معلومات',
    'accountDeletionIsPermanent': 'اکاؤنٹ کو حذف کرنا مستقل ہے اور اسے واپس نہیں لیا جا سکتا',
    'allDataWillBeRemoved': 'آپ کا تمام ڈیٹا، آرڈرز اور سرگزشت مستقل طور پر ہٹا دی جائے گی۔',
    'pendingOrdersMustBeCompleted': 'زیر التواء آرڈرز کو حذف کرنے سے پہلے مکمل کرنا ضروری ہے۔',
    'youllReceiveEmailConfirmation': 'عمل مکمل ہونے کے بعد آپ کو ایک ای میل تصدیق موصول ہوگی۔',
    'confirmActionPermanent': 'براہ کرم تصدیق کریں کہ آپ سمجھتے ہیں کہ یہ عمل مستقل ہے۔',
    'requestSubmitted': 'درخواست جمع کرائی گئی۔',
    'deletionRequestSubmittedMessage': 'آپ کے اکاؤنٹ کو حذف کرنے کی درخواست کامیابی کے ساتھ جمع کر دی گئی ہے۔ ہماری ٹیم 24-48 گھنٹوں کے اندر اس کا جائزہ لے گی۔ آپ کی درخواست پر کارروائی ہونے کے بعد آپ کو ایک تصدیقی ای میل موصول ہوگا۔',
    'ok': 'ٹھیک ہے',
    'failedToSubmitDeletionRequest': 'حذف کرنے کی درخواست جمع کرانے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
    'requestAccountDeletion': 'اکاؤنٹ حذف کرنے کی درخواست کریں۔',
    'sorryToSeeYouGo': 'آپ کو جاتے دیکھ کر ہمیں افسوس ہے۔',
    'emailAddress': 'ای میل ایڈریس',
    'enterRegisteredEmail': 'اپنا رجسٹرڈ ای میل ایڈریس درج کریں۔',
    'emailAddressRequired': 'ای میل ایڈریس درکار ہے۔',
    'pleaseEnterValidEmail': 'براہ کرم ایک درست ای میل ایڈریس درج کریں۔',
    'reasonForDeletionOptional': 'حذف کرنے کی وجہ (اختیاری)',
    'helpUsImproveLeaving': 'یہ بتا کر کہ آپ کیوں جا رہے ہیں اسے بہتر بنانے میں ہماری مدد کریں...',
    'understandActionPermanent': 'میں سمجھتا ہوں کہ یہ کارروائی مستقل ہے اور اسے کالعدم نہیں کیا جا سکتا',
    // ============================================
    // Support / Help Related
    // ============================================
    'emailSupport': 'ای میل سپورٹ',
    'getHelpViaEmail': 'ای میل کے ذریعے مدد حاصل کریں۔',
    'phoneSupport': 'فون سپورٹ',
    'callUsDuringBusinessHours': 'کاروباری اوقات کے دوران ہمیں کال کریں۔',
    'liveChat': 'لائیو چیٹ',
    'chatWithUs': 'ہمارے ساتھ چیٹ کریں۔',
    'chatWithSupportTeam': 'ہماری سپورٹ ٹیم کے ساتھ چیٹ کریں۔',
    'commonIssues': 'عام مسائل',
    'orderNotShowingUp': 'آرڈر ظاہر نہیں ہو رہا ہے۔',
    'orderNotShowingUpSolution': 'ڈیش بورڈ کو ریفریش کریں یا "میرے آرڈرز" میں اپنے آرڈر کی سرگزشت چیک کریں۔',
    'liveChatComingSoon': 'لائیو چیٹ جلد آرہی ہے!',
    'needHelpContactSupport': 'مدد کی ضرورت ہے؟ سپورٹ سے رابطہ کریں۔',
    'contactSupportAt': 'سپورٹ پر رابطہ کریں۔',
    'getInTouch': 'رابطے میں رہیں',
    'wereHereToHelp': 'ہم آپ کی مدد کے لیے حاضر ہیں۔',
    'businessEmail': 'کاروباری ای میل',
    'contactUsOnWhatsApp': 'ہم سے واٹس ایپ پر رابطہ کریں۔',
    'helloNeedAssistance': 'ہیلو! مجھے مدد کی ضرورت ہے۔',
    'myDetails': 'میری تفصیلات:',
    'nameLabel': 'نام:',
    'phoneLabel': 'فون:',
    'emailLabel': 'ای میل:',
    'businessLabel': 'کاروبار:',
    'howCanYouHelpMe': 'آپ میری مدد کیسے کر سکتے ہیں؟',
    'unableToOpenWhatsApp': 'واٹس ایپ کھولنے سے قاصر۔ براہ کرم دوبارہ کوشش کریں۔',
    'hello': 'ہیلو',
    // ============================================
    // Common Validation Related
    // ============================================
    'required': 'یہ فیلڈ درکار ہے۔',
    'invalidEmail': 'غلط ای میل',
    'passwordTooShort': 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔',
    'passwordsDoNotMatch': 'پاس ورڈز مماثل نہیں ہیں۔',
    // ============================================
    // Manager / Admin Related
    // ============================================
    'admin': 'ایڈمن',
    'role': 'کردار',
    'created': 'بنایا',
    'subAdmin': 'سب ایڈمن',
    'accessDenied': 'رسائی سے انکار کر دیا گیا۔',
    'managersSectionOnly': 'یہ سیکشن صرف مینیجرز کے لیے دستیاب ہے۔',
    'totalRevenue': 'کل آمدنی',
    'myRevenue': 'میری آمدنی',
    'activeShops': 'فعال تھوک فروش',
    'activeMembers': 'فعال دکانیں/کوئسکس',
    'inactiveMembers': 'غیر فعال دکانیں۔',
    'activeShopsSubtitle': 'پلیٹ فارم پر تصدیق شدہ تھوک فروش',
    'activeMembersSubtitle': 'وہ دکانیں جنہوں نے حال ہی میں آرڈر کیا تھا۔',
    'inactiveMembersSubtitle': '60+ دنوں میں کوئی آرڈر نہیں ہے۔',
    'lastOrder': 'آخری آرڈر',
    'lastActive': 'آخری فعال',
    'lastLogin': 'آخری لاگ ان',
    'joined': 'شامل ہو گئے۔',
    'selectToNotify': 'اطلاع بھیجنے کے لیے منتخب کریں۔',
    'deselect': 'غیر منتخب کریں۔',
    'recipients': 'وصول کنندگان',
    'notificationSent': 'اطلاع بھیج دی گئی۔',
    'notifyDealParticipantsTitle': 'ڈیل کے شرکاء کو اطلاع دیں',
    'notifyDealParticipantsAudienceWarning':
        'یہ پیغام صرف اُن صارفین کو بھیجا جائے گا جنہوں نے اس ڈیل کے لیے آرڈر کیا ہے۔',
    'notifyDealParticipantsSendUpdateTooltip': 'اپ ڈیٹ بھیجیں',
    'notifyDealParticipantsSending': 'بھیجا جا رہا ہے...',
    'notifyDealParticipantsNoParticipantsError':
        'بھیجنا ممکن نہیں: ابھی تک کوئی صارف اس ڈیل میں شامل نہیں ہوا۔',
    'notifyDealParticipantsFailedToSend':
        'اطلاع بھیجنے میں ناکامی: {error}',
    'noInactiveMembers': 'کوئی غیر فعال ممبر نہیں۔',
    'selectAll': 'سبھی کو منتخب کریں۔',
    'sendNotification': 'اطلاع بھیجیں۔',
    'title': 'عنوان',
    'body': 'پیغام',
    'send': 'بھیجیں۔',
    'generateWithAI': 'AI کے ساتھ تیار کریں۔',
    'generateNotificationPrompt': 'عنوان اور پیغام تخلیق کرنے کے لیے اطلاع (مثلاً دوبارہ مشغولیت، فلیش سیل، نئی مصنوعات) کی وضاحت کریں۔',
    'weMissYou': 'ہم آپ کو یاد کرتے ہیں!',
    'reEngagementDefaultBody': 'آپ نے تھوڑی دیر سے آرڈر نہیں دیا ہے۔ ہمارے تازہ ترین سودے اور مصنوعات کو براؤز کریں۔',
    'notificationRemindHint': 'مثال کے طور پر، غیر فعال دکانوں کو ہماری موسم سرما کی فروخت کے بارے میں یاد دلائیں۔',
    'searchByNameEmail': 'نام، ای میل کے ذریعے تلاش کریں...',
    'generate': 'پیدا کریں۔',
    'page': 'صفحہ',
    'never': 'کبھی نہیں',
    'quickActions': 'فوری اقدامات',
    'recentOrders': 'حالیہ احکامات',
    'noRecentOrders': 'کوئی حالیہ آرڈرز نہیں ہیں۔',
    'analyticsComingSoon': 'تجزیات - جلد آرہا ہے۔',
    'importCsv': 'CSV سے درآمد کریں۔',
    'importFromCsv': 'CSV سے درآمد کریں۔',
    'importProductsFromCsv': 'CSV سے مصنوعات درآمد کریں۔',
    'importProducts': 'مصنوعات درآمد کریں۔',
    'importing': 'درآمد کر رہا ہے...',
    'downloadCsvTemplate': 'CSV ٹیمپلیٹ ڈاؤن لوڈ کریں۔',
    'getSampleCsvWithColumns': 'تمام مطلوبہ کالموں کے ساتھ ایک نمونہ CSV فائل حاصل کریں۔',
    'selectCsvFile': 'CSV فائل کو منتخب کریں۔',
    'chooseFile': 'فائل کا انتخاب کریں۔',
    'tapToSelectWholesalerForImport': 'درآمد شدہ مصنوعات کے لیے تھوک فروش کو منتخب کرنے کے لیے تھپتھپائیں۔',
    'importComplete': 'درآمد مکمل',
    'inserted': 'داخل کیا گیا۔',
    'updated': 'تازہ کاری',
    'skipped': 'چھوڑ دیا',
    'fileLabel': 'فائل: {name}',
    'wholesalerRequired': 'تھوک فروش *',
    'wholesalerLabel': 'تھوک فروش {id}',
    'csvPreviewRows': 'CSV پیش نظارہ ({n} قطاریں)',
    'multipleRowsSameProductVariant': 'ایک ہی پروڈکٹ کے نام کے ساتھ متعدد قطاریں = متعدد قسمیں۔',
    'errorsCount': 'خرابیاں ({n})',
    'andMoreErrors': '... اور {n} مزید خرابیاں',
    'failedToReadFileBytes': 'فائل بائٹس پڑھنے میں ناکام',
    'failedToGetFilePath': 'فائل پاتھ حاصل کرنے میں ناکام',
    'errorPickingFile': 'فائل چننے میں خرابی: {error}',
    'csvFileEmpty': 'CSV فائل خالی ہے۔',
    'errorParsingCsv': 'CSV کو پارس کرنے میں خرابی: {error}',
    'templateSavedSuccessfully': 'ٹیمپلیٹ کامیابی کے ساتھ محفوظ ہو گیا۔',
    'templateDownloadCancelled': 'ٹیمپلیٹ ڈاؤن لوڈ منسوخ کر دیا گیا۔',
    'errorGeneratingTemplate': 'ٹیمپلیٹ بنانے میں خرابی۔',
    'errors': 'غلطیاں',
    'viewWholesaler': 'تھوک فروش دیکھیں',
    'cropImage': 'تصویر کو تراشیں۔',
    'change': 'تبدیلی',
    'navigationError': 'نیویگیشن کی خرابی۔',
    // ============================================
    // Time Related
    // ============================================
    'hours': 'گھنٹے',
    'minutes': 'منٹس',
    'seconds': 'سیکنڈز',
    'twentyFourHours': '24 گھنٹے',
    'twelveHours': '12 گھنٹے',
    'sixHours': '6 گھنٹے',
    // ============================================
    // Navigation / Route Errors
    // ============================================
    'noStoryDataProvided': 'کہانی کا کوئی ڈیٹا فراہم نہیں کیا گیا۔',
    'missingWholesalerId': 'تھوک فروش کی شناخت غائب ہے۔',
    'missingProductId': 'پروڈکٹ کی شناخت غائب ہے۔',
    'missingCategorySlug': 'لاپتہ زمرہ سلگ۔',
    'missingDealId': 'ڈیل آئی ڈی غائب ہے۔',
    'missingOrderId': 'آرڈر آئی ڈی غائب ہے۔',
    'featuredProducts': 'نمایاں مصنوعات',
    // ============================================
    // Order Update / Quantity Change Result
    // ============================================
    'orderUpdate': 'آرڈر کی تازہ کاری',
    'viewMyOrders': 'میرے آرڈرز دیکھیں',
    'goToHome': 'ہوم پر جائیں۔',
    'quantityChangeAccepted': 'مقدار میں تبدیلی قبول کر لی گئی۔',
    'quantityChangeDeclined': 'مقدار کی تبدیلی میں کمی آئی',
    'somethingWentWrong': 'کچھ غلط ہو گیا۔',
    'orderUpdatedMessage': 'آپ کا آرڈر اپ ڈیٹ کر دیا گیا ہے۔',
    'orderRevertedMessage': 'آپ کا آرڈر پچھلی مقدار پر لوٹا دیا گیا ہے۔',
    'pleaseTryAgainLater': 'براہ کرم بعد میں دوبارہ کوشش کریں۔',
    // ============================================
    // Deal Detail / Deal Errors
    // ============================================
    'unableToLoadDeal': 'ڈیل لوڈ کرنے سے قاصر',
    'regularPrice': 'باقاعدہ قیمت',
    'stockLabel': 'اسٹاک',
    'dealNotStarted': 'یہ ڈیل ابھی شروع نہیں ہوئی۔',
    'adminWholesalerManageHint': 'بطور ایڈمن یا تھوک فروش، آپ اس ڈیل کا انتظام کر سکتے ہیں لیکن آرڈر نہیں دے سکتے۔ اس ڈیل میں ترمیم کرنے یا اسے بند کرنے کے لیے ایپ بار میں مینو بٹن (⋮) استعمال کریں۔',
    'adminDealOnlyOwnerCanBid': 'صرف ایڈمن (ڈیل کا مالک) ہی ایڈمن ڈیلز پر بولی لگا سکتا ہے۔ کیوسک صارفین اس ڈیل پر آرڈر نہیں دے سکتے۔',
    'kioskOnlyPlaceOrders': 'صرف Kiosk/Shop اکاؤنٹ ہی اس ڈیل پر آرڈر دے سکتے ہیں۔',
    'managementView': 'انتظامی نظارہ',
    'ordering': 'آرڈر کرنا',
    'failedToLoadDealData': 'ڈیل ڈیٹا لوڈ کرنے میں ناکام',
    'dealClosedSuccess': 'ڈیل کامیابی سے بند ہو گئی۔',
    'failedToCloseDeal': 'ڈیل بند کرنے میں ناکام',
    'onlyAdminCanAddBidsOnAdminDeals': 'صرف ایڈمن (ڈیل کا مالک) ہی ایڈمن ڈیلز پر بولی لگا سکتا ہے۔',
    // ============================================
    // Product Search / Detail
    // ============================================
    'searchProducts': 'مصنوعات تلاش کریں۔',
    'youCanOnlyReviewFromDeliveredOrders': 'آپ صرف ڈیلیور کردہ آرڈرز سے پروڈکٹس کا جائزہ لے سکتے ہیں۔',
    'allImages': 'تمام تصاویر',
    'contentGeneratedSuccessfully': 'مواد کامیابی سے تیار ہوا! زمرہ اور دیگر شعبوں کو چیک کریں۔',
    'generationFailed': 'نسل ناکام ہوگئی',
    'userIdRequired': 'یوزر آئی ڈی درکار ہے۔',
    // ============================================
    // Admin Banner Management
    // ============================================
    'adminBannerManagement': 'ایڈمن بینر مینجمنٹ',
    'requests': 'درخواستیں',
    'active': 'فعال',
    'noBannersFoundShort': 'کوئی بینرز نہیں ملے۔',
    'failedToUpdateBanner': 'بینر اپ ڈیٹ کرنے میں ناکام',
    'bannerSubmittedSuccessfully': 'بینر کامیابی کے ساتھ جمع ہو گیا۔',
    'failedToCreateBanner': 'بینر بنانے میں ناکام',
    'failedToSubmitBannerRequest': 'بینر کی درخواست جمع کرانے میں ناکام',
    // ============================================
    // User Management / Admin
    // ============================================
    'administratorsOnlySection': 'یہ سیکشن صرف منتظمین کے لیے دستیاب ہے۔',
    'allRoles': 'تمام کردار',
    'allStatuses': 'تمام سٹیٹس',
    'suspended': 'معطل',
    'noUsersFound': 'کوئی صارف نہیں ملا',
    'pageOf': 'صفحہ',
    'ofLabel': 'کی',
    'noDocumentsAvailable': 'کوئی دستاویزات دستیاب نہیں ہیں۔',
    'userUpdatedSuccessfully': 'صارف کامیابی کے ساتھ اپ ڈیٹ ہو گیا۔',
    'userCreatedSuccessfully': 'صارف کامیابی کے ساتھ بنایا گیا۔',
    'userDeletedSuccessfully': 'صارف کو کامیابی سے حذف کر دیا گیا۔',
    'deleteUser': 'صارف کو حذف کریں۔',
    'deleteUserConfirm': 'کیا آپ واقعی {name} کو حذف کرنا چاہتے ہیں؟ اس کارروائی کو کالعدم نہیں کیا جا سکتا۔',
    'verificationDocuments': 'تصدیقی دستاویزات',
    'noVerificationDocumentsYet': 'ابھی تک کوئی تصدیقی دستاویزات اپ لوڈ نہیں ہوئے۔',
    'rejectionReason': 'مسترد ہونے کی وجہ:',
    'createUser': 'صارف بنائیں',
    'editUser': 'صارف میں ترمیم کریں۔',
    'updateUser': 'صارف کو اپ ڈیٹ کریں۔',
    'roleRequired': 'کردار کی ضرورت ہے۔',
    'statusRequired': 'حیثیت درکار ہے۔',
    'newPasswordLeaveEmpty': 'نیا پاس ورڈ (موجودہ رکھنے کے لیے خالی چھوڑ دیں)',
    'passwordRequired': 'پاس ورڈ درکار ہے۔',
    'passwordMinLength': 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔',
    'needInfo': 'معلومات کی ضرورت ہے۔',
    'business': 'کاروبار',
    'searchByNameEmailPhone': 'نام، ای میل، فون کے ذریعے تلاش کریں...',
    'daysAgo': 'دن پہلے',
    'activeDaysLast14': 'فعال دن (آخری 14)',
    'docsCount': '{count} دستاویزات',
    'noPassportDocuments': 'پاسپورٹ کے کاغذات نہیں۔',
    'noGewerbescheinDocuments': 'کوئی Gewerbeschein دستاویزات نہیں ہیں۔',
    'noBusinessLicenseDocuments': 'کاروباری لائسنس کی کوئی دستاویزات نہیں ہیں۔',
    'documentN': 'دستاویز {n}',
    'openInBrowser': 'براؤزر میں کھولیں۔',
    'pdfDocument': 'پی ڈی ایف دستاویز',
    'kiosk': 'کیوسک',
    // ============================================
    // Order Management (Deal Orders)
    // ============================================
    'errorLoadingOrders': 'آرڈرز لوڈ کرنے میں خرابی۔',
    'errorLoadingDeals': 'ڈیلز لوڈ کرنے میں خرابی۔',
    'orderManagement': 'آرڈر مینجمنٹ',
    'orderCountSuffix': 'حکم',
    'confirmOrder': 'آرڈر کی تصدیق کریں۔',
    'confirmOrderMessage': 'کیا آپ واقعی اس آرڈر کی تصدیق کرنا چاہتے ہیں؟',
    'confirm': 'تصدیق کریں۔',
    'markAsDelivered': 'ڈیلیور کے بطور نشان زد کریں۔',
    'markDelivered': 'مارک ڈیلیور کر دیا گیا۔',
    'cancelOrder': 'آرڈر منسوخ کریں۔',
    'cancelOrderConfirm': 'کیا آپ واقعی اس آرڈر کو منسوخ کرنا چاہتے ہیں؟',
    'no': 'نہیں',
    'reduceQuantity': 'مقدار کو کم کریں۔',
    'orderConfirmedSuccess': 'آرڈر کی کامیابی سے تصدیق ہو گئی۔',
    'orderMarkedDelivered': 'آرڈر کو ڈیلیور کے بطور نشان زد کیا گیا ہے۔',
    'failedToConfirmOrder': 'آرڈر کی تصدیق کرنے میں ناکام',
    'failedToMarkDelivered': 'ڈیلیور کے بطور نشان زد کرنے میں ناکام',
    'orderCancelled': 'آرڈر منسوخ کر دیا گیا۔',
    'failedToCancelOrder': 'آرڈر منسوخ کرنے میں ناکام',
    'orderMarkedPaid': 'آرڈر کو بطور ادا شدہ نشان زد کیا گیا ہے۔',
    'failedToMarkOrderPaid': 'آرڈر کو بطور ادا شدہ نشان زد کرنے میں ناکام',
    'quantityUpdatedSuccess': 'مقدار کامیابی کے ساتھ اپ ڈیٹ ہو گئی۔',
    'failedToUpdateQuantity': 'مقدار کو اپ ڈیٹ کرنے میں ناکام',
    'deliveryNotesOptional': 'ڈیلیوری نوٹس (اختیاری)',
    'newQuantity': 'نئی مقدار',
    'reduceQuantityHint': 'نئی مقدار درج کریں۔ کم از کم 1 ہے (یا ڈیل کی کم از کم آرڈر کی مقدار)۔ اس آرڈر کو منسوخ کرنے کے لیے 0 استعمال کریں۔',
    'quantityUpdatedTo': 'مقدار کو اپ ڈیٹ کر دیا گیا۔',
    // ============================================
    // Deal Order Form
    // ============================================
    'enterQuantity': 'مقدار درج کریں۔',
    'pleaseEnterQuantity': 'براہ کرم مقدار درج کریں۔',
    'invalidQuantity': 'غلط مقدار',
    'minimumOrderIs': 'کم از کم آرڈر ہے۔',
    'maximumOrderIs': 'زیادہ سے زیادہ آرڈر ہے۔',
    'addSpecialInstructions': 'کوئی خاص ہدایات شامل کریں...',
    'minQuantityLabel': 'کم از کم',
    'selectedLabel': 'منتخب',
    'maxQuantityLabel': 'زیادہ سے زیادہ',
    // ============================================
    // Shipment / Carrier
    // ============================================
    'pleaseSelectCarrier': 'براہ کرم ایک کیریئر منتخب کریں۔',
    'pleaseEnterCarrierNameForOther': 'براہ کرم "دیگر" کے لیے کیریئر کا نام درج کریں',
    'shipmentCreatedSuccess': 'کھیپ کامیابی کے ساتھ بنائی گئی۔',
    'shipmentCreatedAndOrderShipped': 'کھیپ تیار کی گئی اور آرڈر کو بطور بھیج دیا گیا۔',
    'failedToCreateShipment': 'شپمنٹ بنانے میں ناکام',
    // ============================================
    // Stories
    // ============================================
    'failedToPickMedia': 'میڈیا چننے میں ناکام',
    'onlyWholesalersCanCreateStories': 'صرف تھوک فروش کہانیاں بنا سکتے ہیں۔',
    'storyCreatedSuccess': 'کہانی کامیابی کے ساتھ بنائی گئی! 🎉',
    'failedToCreateStory': 'کہانی بنانے میں ناکام',
    // ============================================
    // Payment
    // ============================================
    'paymentCompletedSuccess': 'ادائیگی کامیابی سے مکمل ہو گئی!',
    'paymentFailed': 'ادائیگی ناکام ہو گئی۔',
    // ============================================
    // Notifications
    // ============================================
    'notifications': 'اطلاعات',
    'markAllAsRead': 'سبھی کو پڑھا ہوا نشان زد کریں۔',
    'deleteAll': 'سب کو حذف کریں۔',
    'filterNotifications': 'اطلاعات کو فلٹر کریں۔',
    'unread': 'ان پڑھ',
    'read': 'پڑھیں',
    'deleteAllNotificationsConfirm': 'تمام اطلاعات کو حذف کریں؟',
    'deleteAllNotificationsMessage': 'کیا آپ واقعی تمام اطلاعات کو حذف کرنا چاہتے ہیں؟ اس کارروائی کو کالعدم نہیں کیا جا سکتا۔',
    // ============================================
    // Deal / Product Modals
    // ============================================
    'paymentEmailTemplateGenerated': 'ادائیگی کا ای میل ٹیمپلیٹ تیار ہوا۔',
    'aiGenerationFailed': 'AI نسل ناکام ہوگئی',
    'dealUpdatedSuccess': 'ڈیل کامیابی کے ساتھ اپ ڈیٹ ہو گئی۔',
    'allowOnlinePayment': 'آن لائن ادائیگی کی اجازت دیں۔',
    'allowOnlinePaymentSubtitle': 'اگر چیک نہ کیا گیا ہو، گاہک صرف آرڈر دے سکتے ہیں۔ آرڈر کی تصدیق کے بعد ادائیگی (جیسے بینک ٹرانسفر) کی درخواست کی جاتی ہے۔',
    'paymentAndEmail': 'ادائیگی اور ای میل',
    'generating': 'پیدا ہو رہا ہے…',
    'enterDealDescriptionPrompt': 'مواد خود بخود تیار کرنے کے لیے اپنی ڈیل کی واضح تفصیل درج کریں۔',
    'dealDescriptionHint': 'مثال کے طور پر، فلیش سیل: تمام موسم سرما کی جیکٹس پر %50 چھوٹ',
    'enterProductDescriptionPrompt': 'مواد خود بخود تیار کرنے کے لیے تفصیل یا مصنوعات کی تفصیلات درج کریں۔',
    'productDescriptionHint': 'مثال کے طور پر، ایرگونومک ڈیزائن کے ساتھ ایک پریمیم چمڑے کی دفتری کرسی...',
    'optionalAutoAssigned': 'اختیاری - خالی ہونے پر خود بخود تفویض کیا جائے گا۔',
    'defaultYourAccount': 'ڈیفالٹ: آپ کا اکاؤنٹ (تبدیل کرنے کے لیے تھپتھپائیں)',
    'currentUserYou': 'موجودہ صارف (آپ)',
    'loadingProductDetails': 'پروڈکٹ کی تفصیلات لوڈ ہو رہی ہیں...',
    'loading': 'لوڈ ہو رہا ہے...',
    'ibanBankAccount': 'IBAN / بینک اکاؤنٹ',
    'accountOwner': 'اکاؤنٹ کا مالک',
    'referenceTemplate': 'حوالہ تمثیل (جیسے DEAL-{dealCode}-{buyerId})',
    'paymentInstructions': 'ادائیگی کی ہدایات (مفت متن)',
    'paymentEmailSubject': 'ادائیگی ای میل کا موضوع',
    'paymentEmailBody': 'ادائیگی کے ای میل کا باڈی (استعمال کریں {dealTitle}, {amount}, {iban}, {reference}, {accountOwner})',
    'ended': 'ختم ہوا۔',
    'dealEnded': 'ڈیل ختم',
    'dealHasEnded': 'ڈیل ختم ہوگئی',
    'endingSoon': 'جلد ہی ختم ہو رہا ہے!',
    'endsIn1Day': '1 دن میں ختم ہو جائے گا۔',
    'endsInDays': '{n} دنوں میں ختم ہوتا ہے۔',
    'endsIn1Hour': '1 گھنٹے میں ختم ہوتا ہے۔',
    'endsInHours': '{n} گھنٹے میں ختم ہوتا ہے۔',
    'endsSoon': 'جلد ختم ہو جائے گا۔',
    'categories': 'زمرے',
    'itemsCount': '{n} آئٹمز',
    // ============================================
    // Shipment Tracking
    // ============================================
    'pleaseEnterTrackingNumber': 'براہ کرم ایک ٹریکنگ نمبر درج کریں۔',
    'pleaseSelectAtLeastOneItemToShip': 'براہ کرم بھیجنے کے لیے کم از کم ایک آئٹم منتخب کریں۔',
    'pleaseEnterTrackingUrlForOther': 'براہ کرم "دیگر" کیریئر کے لیے ٹریکنگ URL درج کریں۔',
    'selectItemsToShip': 'بھیجنے کے لیے آئٹمز منتخب کریں۔',
    'noItemsAvailableForShipment': 'شپمنٹ کے لیے کوئی اشیاء دستیاب نہیں ہیں۔',
    'selectCarrier': 'ایک کیریئر منتخب کریں۔',
    'selectCarrierHint': 'ایک کیریئر منتخب کریں...',
    'carrierName': 'کیریئر کا نام',
    'enterCarrierName': 'کیریئر کا نام درج کریں۔',
    'trackingNumberRequired': 'ٹریکنگ نمبر درکار ہے۔',
    'enterTrackingNumber': 'ٹریکنگ نمبر درج کریں۔',
    'trackingUrlAutoGenerated': 'ٹریکنگ یو آر ایل خود بخود تیار ہو جائے گا۔',
    'trackingUrlRequiredForOther': '"دیگر" کیریئر کے لیے ٹریکنگ URL درکار ہے۔',
    'pleaseEnterValidUrl': 'براہ کرم ایک درست URL درج کریں۔',
    'estimatedDeliveryDate': 'ڈیلیوری کی متوقع تاریخ',
    'selectDate': 'تاریخ منتخب کریں۔',
    'internalNotesShipment': 'اس کھیپ کے بارے میں اندرونی نوٹس',
    'trackingUrlHintAuto': 'جب کیریئر اور ٹریکنگ نمبر فراہم کیے جاتے ہیں تو خود کار طریقے سے تیار ہوتا ہے۔',
    'trackShipment': 'ٹریک شپمنٹ',
    'trackShipmentHint': 'فراہم کردہ ٹریکنگ نمبر کا استعمال کرتے ہوئے اپنی شپمنٹ کو ٹریک کریں۔',
    'trackingDetails': 'ٹریکنگ کی تفصیلات',
    'shipmentNotFound': 'کھیپ نہیں ملی',
    'pleaseCheckTrackingNumber': 'براہ کرم اپنا ٹریکنگ نمبر چیک کریں اور دوبارہ کوشش کریں۔',
    'noNotifications': 'کوئی اطلاع نہیں۔',
    'youreAllCaughtUp': 'آپ سب کو حل کر چکے ہیں!',
    // ============================================
    // Select Deal / Category
    // ============================================

    // Feature audit – previously hardcoded strings
    'platformMobile': 'موبائل',
    'platformWeb': 'ویب',
    'pleaseWait': 'براہ کرم انتظار کریں...',
    'defaultVariant': 'ڈیفالٹ',
    'trackOnCarrierWebsite': 'کیریئر ویب سائٹ پر ٹریک کریں',
    'minOrderQtyRequired': 'کم از کم آرڈر مقدار *',
    'dealPriceRequired': 'ڈیل کی قیمت *',
    'targetQuantityRequired': 'ہدف مقدار *',
    'baseShippingCostEur': 'بنیادی شپنگ لاگت (€)',
    'freeShippingThresholdQuantity': 'مفت شپنگ تھریشولڈ (مقدار)',
    'perUnitShippingCostEur': 'فی یونٹ شپنگ لاگت (€)',
    'descriptionOptional': 'تفصیل (اختیاری)',
    'enterBannerDescription': 'بینر کی تفصیل درج کریں',
    'bannerType': 'بینر کی قسم',
    'targetUrl': 'ہدف URL',
    'skuRequired': 'SKU *',
    'productToPromoteHint': 'تشہیر کے لیے پروڈکٹ',
    'selectDealToPromote': 'تشہیر کے لیے ڈیل منتخب کریں',
    'titleOptional': 'عنوان (اختیاری)',
    'giveReviewTitle': 'اپنی رائے کو عنوان دیں',
    'yourReviewOptional': 'آپ کی رائے (اختیاری)',
    'shareExperienceWithProduct': 'اس پروڈکٹ کے ساتھ اپنا تجربہ شیئر کریں',
    'dealUpdatedSuccessfully': 'ڈیل کامیابی سے اپ ڈیٹ ہو گئی',
    'dealPriceMustBeValidNumber': 'ڈیل کی قیمت ایک درست نمبر ہونی چاہیے',
    'pleaseEnterMinOrderQuantity': 'براہ کرم کم از کم آرڈر مقدار درج کریں',
    'paymentEmailPlaceholdersSubject':
        'پلیس ہولڈرز: {dealTitle}, {amount}, {reference}',
    'paymentEmailPlaceholdersBody':
        'پلیس ہولڈرز: {dealTitle}, {amount}, {accountOwner}, {iban}, '
        '{reference}, {additionalInstructions}',
    'failed': 'ناکام',

    // ============================================
    // Order status (product orders – display only)
    // ============================================
    'orderStatusPendingConfirmation': 'تصدیق زیرِ التوا',
    'orderStatusConfirmed': 'تصدیق شدہ',
    'orderStatusPacking': 'پیک ہو رہا ہے',
    'orderStatusDispatched': 'بھیج دیا گیا',
    'orderStatusOutForDelivery': 'ڈیلیوری کے لیے نکل گیا',
    'orderStatusDelivered': 'ڈیلیور ہوگیا',
    'orderStatusCancelled': 'منسوخ',
    'orderStatusReturned': 'واپس کیا گیا',
    'orderStatusRefunded': 'واپسی',

    // ============================================
    // Notifications (backend localization keys)
    // ============================================
    'notificationProductApprovalNeededTitle': 'نیا پروڈکٹ منظوری کے لیے زیرِ التوا',
    'notificationProductApprovalNeededBody': '{0} نے نیا پروڈکٹ بنایا: {1}',
    'notificationProductStatusUpdatedTitle': 'پروڈکٹ کی صورتحال اپ ڈیٹ ہوگئی',
    'notificationProductApprovedBody': 'آپ کا پروڈکٹ "{0}" منظور ہو گیا!',
    'notificationProductRejectedBody': 'آپ کا پروڈکٹ "{0}" مسترد کر دیا گیا۔',
    'notificationProductPendingBody': 'آپ کا پروڈکٹ "{0}" منظوری کے لیے زیرِ التوا ہے۔',
    'notificationProductStatusChangedBody': 'آپ کے پروڈکٹ "{0}" کی صورتحال {1} میں بدل گئی',
    'notificationNewProductOrderTitle': 'آپ کی مصنوعات پر نیا آرڈر',
    'notificationNewProductOrderBody': '{0} نے {2} کے {1} یونٹ آرڈر کیے',
    'notificationNewDealOrderTitle': 'آپ کی ڈیل پر نیا آرڈر',
    'notificationNewDealOrderBody': '{0} نے {1} یونٹ آرڈر کیے',
    'notificationPaymentReportedTitle': 'خریدار نے ادائیگی رپورٹ کی',
    'notificationPaymentReportedBody': '{0} نے آرڈر کی ادائیگی رپورٹ کی۔ تفصیل: {1}',
    'notificationDealPaymentReportedBody': '{0} نے ڈیل آرڈر کی ادائیگی رپورٹ کی۔ تفصیل: {1}',
    'notificationDealOrderStatusUpdatedTitle': 'ڈیل آرڈر کی صورتحال اپ ڈیٹ ہوگئی',
    'notificationDealOrderConfirmedBody': '"{0}" پر آپ کا آرڈر کنفرم ہوگیا!',
    'notificationDealOrderShippedBody': '"{0}" پر آپ کا آرڈر بھیج دیا گیا!',
    'notificationDealOrderDeliveredBody': '"{0}" پر آپ کا آرڈر ڈیلیور ہوگیا!',
    'notificationDealOrderCancelledBody': '"{0}" پر آپ کا آرڈر منسوخ کر دیا گیا۔',
    'notificationDealOrderRefundedBody': '"{0}" پر آپ کے آرڈر کی رقم واپس کر دی گئی۔',
    'notificationDealOrderPendingBody': '"{0}" پر آپ کا آرڈر کنفرم ہونے کا منتظر ہے۔',
    'notificationDealOrderStatusChangedBody': '"{0}" پر آپ کے آرڈر کی صورتحال {1} میں بدل گئی',
    'notificationOrderQuantityUpdatedTitle': 'آرڈر کی مقدار اپ ڈیٹ ہوگئی',
    'notificationDealOrderQuantityCancelledBody': '"{0}" پر آپ کا آرڈر (پہلے {1} یونٹ) بیچنے والے نے منسوخ کر دیا۔',
    'notificationDealOrderQuantityChangedBody': '"{0}" پر آپ کا آرڈر اپ ڈیٹ ہوگیا: مقدار {1} سے {2} یونٹ کردی گئی (بیچنے والے نے)۔',
    'notificationQuantityChangeDeclinedTitle': 'مقدار میں تبدیلی مسترد ہوگئی',
    'notificationQuantityChangeDeclinedBody': '{0} نے مقدار میں تبدیلی مسترد کی۔ آرڈر {1} سے {2} یونٹ پر واپس کر دیا گیا۔',
    'notificationDealNowLiveTitle': 'نئی ڈیل لائیو ہے',
    'notificationDealNowLiveBody': '"{0}" اب لائیو ہے۔ ڈیل ختم ہونے سے پہلے آرڈر کریں۔',
    'notificationDealTarget70PercentTitle': 'ڈیل تقریباً مکمل',
    'notificationDealTarget70PercentBody': '"{0}" {1}% بھر چکی ہے! دوسرے ریٹیلرز کے ساتھ شامل ہوں اور ڈیل مالک کو ہدف تک پہنچنے میں مدد کریں — یہ تعلق مضبوط کرتا ہے اور آپ کی وابستگی دکھاتا ہے۔',
    'notificationDealEnding24hTitle': 'ڈیل جلد ختم ہو رہی ہے',
    'notificationDealEnding24hBody': 'آخری 24 گھنٹے! "{0}" — اس ڈیل کو مکمل کرنے کے لیے صرف {1} آرڈر باقی ہیں۔',
    'notificationDealEnding7dTitle': 'ڈیل 7 دن میں ختم ہوگی',
    'notificationDealEnding7dBody': '"{0}" — اس ڈیل کو مکمل کرنے کے لیے صرف {1} آرڈر باقی ہیں۔',
    'notificationDealSuccessTitle': 'ڈیل کامیابی سے مکمل ہوگئی',
    'notificationDealSuccessBody': 'آپ کی گروپ ڈیل "{0}" مطلوبہ مقدار تک پہنچ گئی ہے اور اب کنفرم ہے۔ براہ کرم تھوک فروش کی ہدایات کے مطابق ادائیگی اور شپنگ کی تیاری کریں۔',
    'notificationDealClosedTitle': 'ڈیل بند ہوگئی',
    'notificationDealClosedBody': 'ڈیل "{0}" بند کر دی گئی ہے۔ یہ اب فعال ڈیلز میں نظر نہیں آئے گی۔',
    'deal_closed_title': 'ڈیل بند ہوگئی!',
    'deal_closed_body':
        'ڈیل "{0}" باضابطہ طور پر بند کر دی گئی ہے۔ شرکت کا شکریہ!',
    'notificationOrderStatusUpdatedTitle': 'آرڈر کی صورتحال اپ ڈیٹ ہوگئی',
    'notificationOrderConfirmedBody': '"{0}" کے لیے آپ کا آرڈر کنفرم ہوگیا!',
    'notificationOrderDispatchedBody': '"{0}" کے لیے آپ کا آرڈر روانہ کر دیا گیا!',
    'notificationOrderDeliveredBody': '"{0}" کے لیے آپ کا آرڈر ڈیلیور ہوگیا!',
    'notificationOrderCancelledBody': '"{0}" کے لیے آپ کا آرڈر منسوخ کر دیا گیا۔',
    'notificationOrderPackingBody': '"{0}" کے لیے آپ کا آرڈر پیک ہو رہا ہے!',
    'notificationOrderOutForDeliveryBody': '"{0}" کے لیے آپ کا آرڈر ڈیلیوری کے لیے نکل گیا ہے!',
    'notificationOrderReturnedBody': '"{0}" کے لیے آپ کا آرڈر واپس کر دیا گیا۔',
    'notificationOrderRefundedBody': '"{0}" کے لیے آپ کے آرڈر کی رقم واپس کر دی گئی۔',
    'notificationOrderStatusChangedBody': '"{0}" کے لیے آپ کے آرڈر کی صورتحال {1} میں بدل گئی',
    'notificationOrderItemRemovedBody': 'آپ کے آرڈر آئٹم "{0}" (پہلے {1} یونٹ) بیچنے والے نے ہٹا دیا۔',
    'notificationOrderItemQuantityChangedBody': 'آپ کے آرڈر آئٹم "{0}" اپ ڈیٹ ہوگیا: مقدار {1} سے {2} یونٹ کردی گئی (بیچنے والے نے)۔',
    'notificationProductQuantityChangeDeclinedBody': '{0} نے آرڈر آئٹم کی مقدار بدلنے سے انکار کیا۔ {1} سے {2} یونٹ پر واپس کر دیا گیا۔',
    'notificationDailyEngagementTitle': 'آج کی ڈیلز دیکھیں!',
    'notificationDailyEngagementBody': 'آج: {0} بینر، {1} ڈیلز، {2} نمایاں پروڈکٹس۔ آفرز دیکھنے کے لیے ایپ کھولیں۔',
    'notificationInactiveMembersAlertTitle': 'غیر فعال ممبران کا الرٹ',
    'notificationInactiveMembersAlertBody': '{0} دکان(یں) نے {1} دنوں میں کوئی آرڈر نہیں دیا۔ رابطہ کرنے یا جائزہ لینے پر غور کریں۔',
    'notificationBulkImportCompletedTitle': 'بلک امپورٹ مکمل ہوگیا',
    'notificationBulkImportCompletedBody': '{0} پروڈکٹس کامیابی سے امپورٹ ہوئیں۔ {1} چھوڑ دی گئیں۔',
    'notificationBannerApprovalNeededTitle': 'نیا بینر منظوری کے لیے زیرِ التوا',
    'notificationBannerApprovalNeededBody': '{0} نے بینر کی منظوری کی درخواست دی: {1}',
    'notificationNewUserRegistrationTitle': 'نیا صارف رجسٹریشن',
    'notificationNewUserRegistrationBody': '{0} ({1}) نے {2} کے طور پر رجسٹر کیا۔ منظوری زیرِ التوا۔',
    'notificationBannerStatusChangedTitle': 'بینر کی صورتحال بدلی',
    'notificationBannerApprovedBody': 'آپ کا بینر "{0}" منظور ہوگیا اور اب فعال ہے!',
    'notificationBannerRejectedBody': 'آپ کا بینر "{0}" مسترد کر دیا گیا۔ براہ کرم جائزہ لیں اور ضرورت ہو تو دوبارہ جمع کریں۔',
    'notificationBannerDeactivatedBody': 'آپ کا بینر "{0}" غیر فعال کر دیا گیا۔',
    'notificationBannerStatusChangedBody': 'آپ کے بینر "{0}" کی صورتحال {1} میں بدل گئی',
    'notificationAdminCustomTitle': '{0}',
    'notificationAdminCustomBody': '{0}',
    'kioskShopRole': 'کھوکھا / دکان',
  };
}